lang/java/avro/src/main/java/org/apache/avro/util/RandomData.java
lang/java/ipc/src/test/java/org/apache/avro/DataFileInteropTest.java
lang/perl/share/interop-data-generate
lang/perl/xt/interop.t
lang/rust/examples/generate_interop_data.rs
lang/rust/examples/test_interop_data.rs
lang/rust/src/error.rs
lang/rust/src/reader.rs
lang/rust/src/writer.rs

- https://issues.apache.org/jira/browse/AVRO-3405
- All the public functions and the classes in the PR contain Rustdoc that explain what it does

AVRO-3405: Add API to write/read user metadata in .avro file

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java

- https://issues.apache.org/jira/browse/AVRO-3382
added a unit test for the new input validation

AVRO-3382 (java) - require Schema argument be != null when creating a Schema.Field

---

lang/csharp/src/apache/test/Interop/InteropDataGenerator.cs
lang/csharp/src/apache/test/Interop/InteropDataTests.cs

- https://issues.apache.org/jira/browse/AVRO-3407

AVRO-3407: Add user_metadats interop tests in C#

---

.devcontainer/devcontainer.json
.gitattributes
BUILD.md

- https://issues.apache.org/jira/browse/AVRO-3411

AVRO-3411: Support VSCode devcontainer

---

doc/content/en/docs/next/Specification/_index.md

It looks like there were a few changes to the spec since the migration (which surprised me, I thought we were up to date).
I only migrated the text changes, and fixed a few `code` blocks that were changing "pretty quotes" that are inside json objects and arrays.
- https://issues.apache.org/jira/browse/AVRO-3414
- All the public …

AVRO-3414: Ensure word-for-word accuracy with existing spec

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/codeql-java-analysis.yml
.github/workflows/codeql-js-analysis.yml
.github/workflows/codeql-py-analysis.yml
.github/workflows/java-publish-snapshot.yml
.github/workflows/rat.yml
.github/workflows/spotless.yml
.github/workflows/test-lang-c++.yml
.github/workflows/test-lang-c.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java.yml
.github/workflows/test-lang-js.yml
.github/workflows/test-lang-perl.yml
.github/workflows/test-lang-php.yml
.github/workflows/test-lang-py.yml
.github/workflows/test-lang-ruby.yml
.github/workflows/test-lang-rust-audit.yml
.github/workflows/test-lang-rust-ci.yml
.github/workflows/test-lang-rust-clippy.yml
.github/workflows/test-lang-rust-miri.yml

- https://issues.apache.org/jira/browse/AVRO-3431
- 

AVRO-3431: CI: Cancel in-progress workflows if there are new commits in PR

---

lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java

The bug was fixed with AVRO-1646.
This PR just adds the test case from the patch attached to AVRO-1945
- https://issues.apache.org/jira/browse/AVRO-1965

AVRO-1965: Add the unit test from the patch attached to AVRO-1965

---

lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

Do not resolve Schema::Ref when printing as JSON.
The Java SDK complains that a type is redefined if it is not a Ref the
second time
- https://issues.apache.org/jira/browse/AVRO-3433
- 

AVRO-3433: Rust: The canonical form should preserve schema references

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/schema.rs

The branch this PR is based on introduces a fix that breaks other functionality. By correctly replacing fully defined schemas with `Schema::Ref`s it exposed a bug in the resolve flow where the resolve does not recursive add in Schemas to the named_schemas map as it finds them. This leads to unresolved schema errors where the ref looks up the name from the map that has not been updated. Fixed via recursively passing the map through the flow and using Name as the key. 
My pr adds to the Branch working to reolve
https://issues.apache.org/jira/browse/AVRO-3433
Tests added that are …

[AVRO-3433][rust] Adding in Resolve Fixes and Tests

---

lang/java/avro/src/main/java/org/apache/avro/Protocol.java
lang/java/avro/src/test/java/org/apache/avro/TestProtocol.java

- https://issues.apache.org/jira/browse/AVRO-3440
- ~In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).~
`org.apache.avro.TestProtocol#testCopyMessage`

AVRO-3440: Fix bug in Protocol.createMessage

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/util.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/schema.rs

In the Encoding and Decoding recursive flows, the schema definitions are being added to a map ad hoc. This means for input values that do not recurse to the schema definition needed by a later schema ref, there is an encoding error when both the input schema and input Value/bytes are valid. 
Ex: The following schema fails to encode/decode when a is the first union variant (null)
```json
{
"type":"record",
"name":"TestStruct",
"fields": [
{
"name":"a",
"type":[ "null", {
"type":"record",
"name": "Inner",
"fields": [ {
"name":"z",
"type":"int"
}]
}]
},
{
"name":"b",
"type":"Inner"
}
]
}
```
In the parsing, encoding, and decoding recursive workflow, the enclosing namespace needed to globally uniquely define a named schema type is not being passed recursively to help fully qualify a schema's …

[AVRO-3448][rust] Rust name/namespace spec adherence work

---

.travis.yml
lang/csharp/src/apache/codegen/AvroGen.cs
lang/csharp/src/apache/main/CodeGen/CodeGenUtil.cs
lang/csharp/src/apache/test/Avro.test.csproj
lang/csharp/src/apache/test/AvroGen/AvroGenHelper.cs
lang/csharp/src/apache/test/AvroGen/AvroGenTests.cs
lang/csharp/src/apache/test/AvroGen/AvroGenToolTests.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs
lang/csharp/versions.props

- https://issues.apache.org/jira/browse/AVRO-3446

AVRO-3446: Add avrogen unit tests

---

doc/content/en/blog/releases/_index.md
doc/content/en/community/_index.md
doc/content/en/project/Credits/_index.md
doc/content/en/project/Donate/_index.md
doc/content/en/project/_index.md
doc/layouts/project/list.html

Remapped some of the old links into their new locations in the website, using aliases.
- https://issues.apache.org/jira/browse/AVRO-3378

AVRO-3378: Map old links to new website

---

lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/DummyLogicalTypeFactory.java
lang/java/avro/src/test/java/org/apache/avro/TestLogicalType.java
lang/java/avro/src/test/resources/META-INF/services/org.apache.avro.LogicalTypes$LogicalTypeFactory

Automatically register LogicalTypeFactory classes using the Java 6
service loader upon startup. This works for any LogicalTypeFactory that
does not need constructor parameters.
- https://issues.apache.org/jira/browse/AVRO-3441
`org.apache.avro.TestLogicalType#testRegisterLogicalTypeFactoryByServiceLoader`
1. Body explains "what" and …

AVRO-3441: ServiceLoader for LogicalTypeFactory

---

lang/rust/avro/src/encode.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/writer.rs

A reuse of the resolved schema struct to help improve performance when possible. Currently every write/append into a writer would use the same schema and resolve it to index all the named schemas for every object being written. Because a writer has a consistent schema it is trivial to reuse the same resolved schema for every write. This improvement was brought up in collaboration with @travisbrown 
What made the implementation less straightforward were the following design constraints:
- absolutely no API breaking changes
- Want to keep Resolved Schema crate private for simplicity
As a result there is some complexity to how the resolved schema is initialized within the writer but I believe it is handled.
Using the example/benchmark.rs to get a csv output. I ran data for pre 1602 code …

AVRO-3451: Reuse Resolved Schemas

---

lang/rust/avro/examples/benchmark.rs

Old:
```
10000,1,Small,0.007364553,0.031123657
10000,1,Big,0.035918282,0.070638095
1,100000,Small,2.581216969,12.182083002
100,1000,Small,0.104473121,0.429455526
10000,10,Small,0.083368471,0.312625975
1,100000,Big,5.799714721,44.469941304
100,1000,Big,0.421531543,1.295618375
10000,10,Big,0.572024442,1.554042001
```
New:
```
Count		Runs		Big/Small	Total write secs	Total read secs
10000		1		Small		0.0072546		0.030194991
10000		1		Big		0.03440565		0.072913845
1		100000		Small		2.562500111		11.847315748
100		1000		Small		0.106402492		0.409962211
10000		10		Small		0.076109698		0.289378503
1		100000		Big		5.566392901		43.606074983
100		1000		Big		0.39528024		1.203362874
10000		10		Big		0.356784052		0.72371213
```
- https://issues.apache.org/jira/browse/AVRO-3464
1. Subject is separated from …

AVRO-3464: Print a header and use tabs as separators

---

lang/rust/avro/examples/generate_interop_data.rs
lang/rust/avro/src/types.rs

- https://issues.apache.org/jira/browse/AVRO-3460
- 

AVRO-3460: [rust] Value::validate does not validate against Schema Refs

---

lang/csharp/src/apache/main/Util/TimeMicrosecond.cs
lang/csharp/src/apache/main/Util/TimeMillisecond.cs
lang/csharp/src/apache/main/Util/TimestampMicrosecond.cs
lang/csharp/src/apache/test/Generic/GenericTests.cs
lang/csharp/src/apache/test/Util/LogicalTypeTests.cs

- https://issues.apache.org/jira/browse/AVRO-3471

AVRO-3471: Fix microsecond logical types resolution

---

lang/csharp/src/apache/main/Generic/GenericReader.cs

- https://issues.apache.org/jira/browse/AVRO-3474
- https://issues.apache.org/jira/browse/AVRO-1438

AVRO-3474: Move CanRead to constructor

---

lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

Reuses the namesRef from the writer in the same way the encoder does
- All unit tests pass 
nothing new

[AVRO-3460] [rust] Follow up: reusing NameRef

---

lang/rust/avro/Cargo.toml
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

Running `cargo test validate -- --nocapture` produces 
```
running 4 tests
[2022-04-08T21:50:28Z ERROR apache_avro::types] Invalid value: Int(42) for schema: Boolean. Reason: Unsupported value-schema combination
[2022-04-08T21:50:28Z ERROR apache_avro::types] Invalid value: Null for schema: Double. Reason: Unsupported value-schema combination
[2022-04-08T21:50:28Z ERROR apache_avro::types] Invalid value: Boolean(true) for schema: Long. Reason: Unsupported value-schema combination
[2022-04-08T21:50:28Z ERROR apache_avro::types] Invalid value: Fixed(5, [0, 0, 0, 0, 0]) for schema: Fixed { name: Name { name: "some_fixed", namespace: None }, aliases: None, doc: None, size: 4 }. Reason: The value's size (5) is different than the schema's size (4)
[2022-04-08T21:50:28Z ERROR apache_avro::types] …
```

AVRO-3483: [Rust] Log error messages with a reason when the validation fails

---

lang/java/avro/src/main/java/org/apache/avro/Protocol.java
lang/java/compiler/src/test/idl/output/reservedwords.avpr
lang/java/compiler/src/test/idl/output/unicode.avpr

This change fixes this cosmetic bug.
- https://issues.apache.org/jira/browse/AVRO-265
`reservedwords.avpr` and `unicode.avpr` (removed null namespaces from the expected output)

AVRO-265: Protocol.toJson writes null namespace

---

lang/java/archetypes/avro-service-archetype/src/main/pom/pom.xml
lang/java/pom.xml

- https://issues.apache.org/jira/browse/AVRO-3487

AVRO-3487: Update Jackson to 2.12.6.1

---

lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

Uses Darling's 'multiple' attribute feature - https://github.com/TedDriggs/darling/blob/master/tests/multiple.rs.
- https://issues.apache.org/jira/browse/AVRO-3492
- 

AVRO-3492: Add support for deriving Schema::Record aliases

---

lang/rust/avro/tests/schema.rs

- https://issues.apache.org/jira/browse/AVRO-3494

AVRO-3494: Uncomment a test for recursive types

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/test/AvroGen/AvroGenTests.cs

- https://issues.apache.org/jira/browse/AVRO-3003
- Add a new test case to the Avro.Test.AvroGen.GenerateSchemaCheckFields unit test

AVRO-3003: Fully qualify enum default value in C# code gen

---

lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/schema.rs
lang/rust/avro_derive/src/lib.rs

Fixes https://github.com/flavray/avro-rs/issues/47.
Until now it was expected that both the schema fields and the input values are sorted the same way.
Use BTreeMap instead of HashMap for the lookup table because otherwise the assertion on the validation error messages is impossible due to random printing of the map's entries
- https://issues.apache.org/jira/browse/AVRO-3495

AVRO-3495: Rust: Fields order should not matter

---

lang/rust/avro/src/de.rs

- https://issues.apache.org/jira/browse/AVRO-3496

AVRO-3496: Rust: Use visitor.visit_borrowed_str() when possible

---

lang/rust/avro_derive/Cargo.toml
lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

- https://issues.apache.org/jira/browse/AVRO-3484

AVRO-3484: Add support for deriving a default value for a record field

---

lang/csharp/src/apache/main/Generic/GenericEnum.cs
lang/csharp/src/apache/test/Generic/GenericEnumTests.cs

- https://issues.apache.org/jira/browse/AVRO-3497
- Parent Issue: https://issues.apache.org/jira/browse/AVRO-3383

AVRO-3497 Simplify conditional expression

---

lang/rust/avro/tests/schema.rs
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_derive/tests/derive.rs

- https://issues.apache.org/jira/browse/AVRO-3500

AVRO-3500: Use property-based testing for the IT tests in avro_derive module

---

lang/rust/avro_derive/src/lib.rs

Checking the json before using in the macro with dummy command.

AVRO-3484: Followup Check default json parsing at compile time for derive macro 

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader12.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java

DataFileReader reads magic information twice. seek(0) is invoked
twice due to this. In cloud object stores, seeking back to 0 will
cause it to fall back to "random IO policy". Example of this is
S3A connector for s3. This causes suboptimal reads in object stores.
Refactoring in the patch addresses this case by reusing MAGIC.
https://issues.apache.org/jira/browse/AVRO-3482
- Existing test cases cover this refactoring.
N/A

AVRO-3482: Reuse MAGIC in DataFileReader

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

- https://issues.apache.org/jira/browse/AVRO-3511

AVRO-3511: Fix the parsing canonical form for Decimal schema

---

lang/rust/avro/examples/test_interop_single_object_encoding.rs
lang/rust/avro/src/decode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/src/reader.rs
lang/rust/build.sh

Single object encoding readers. Both generic interfacing only with value, and Specific that takes advantage of traits to deserialize directly to the user's type. 
https://issues.apache.org/jira/browse/AVRO-3507
https://issues.apache.org/jira/browse/AVRO-3513

[AVRO-3507] Implement Single Object reader

---

lang/rust/avro/Cargo.toml
lang/rust/avro_derive/Cargo.toml

Explicitly list the features used/needed by Avro
- https://issues.apache.org/jira/browse/AVRO-3517

AVRO-3517: Do not use the default features of the dependencies

---

doc-deprecated/src/content/xdocs/spec.xml
doc/content/en/docs/next/Specification/_index.md
lang/rust/avro/src/schema.rs

- https://issues.apache.org/jira/browse/AVRO-3512

AVRO-3512: Fix the aliases' namespace when parsing named schemata

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/util.rs
lang/rust/avro_derive/tests/derive.rs

It uses Newtype pattern and wraps Name. This way it is easier to control
how it is being (de)serialized
Until now only Schema::Record serialized its aliases to JSON. Now this
is being done for all named schemata (Schema::Enum and Schema::Fixed)
- https://issues.apache.org/jira/browse/AVRO-3518

AVRO-3518: Introduce a new type 'Alias'

---

lang/rust/Cargo.toml
lang/rust/avro/Cargo.toml
lang/rust/avro/src/codec.rs
lang/rust/avro/src/de.rs
lang/rust/avro/src/decimal.rs
lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/src/rabin.rs
lang/rust/avro/src/reader.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/ser.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/util.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/io.rs
lang/rust/avro/tests/schema.rs
lang/rust/avro_test_helper/Cargo.toml
lang/rust/avro_test_helper/README.md
lang/rust/avro_test_helper/src/lib.rs
lang/rust/avro_test_helper/src/logger.rs

AVRO-3522: Better logging in tests

---

lang/rust/avro/Cargo.toml
lang/rust/avro/src/schema.rs
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_test_helper/Cargo.toml

Add 'default-features = false' consistently for all [dev-]dependencies.
Fix Rustdoc warning.

AVRO-3533: Rust: Update dependencies

---

.github/workflows/test-lang-rust-audit.yml

AVRO-3534: Rust: Use dependency-review-action only for pull_request events

---

doc/content/en/project/How to contribute/_index.md

AVRO-3523: Move contributions guidelines to website

---

lang/py/avro/io.py
lang/py/avro/schema.py
lang/py/avro/test/test_io.py
lang/py/avro/test/test_schema.py

AVRO-3521: "Scale" property from decimal object

---

doc/assets/scss/_styles_project.scss

- https://issues.apache.org/jira/browse/AVRO-3445

AVRO-3445: Disable links pointing to git repo

---

lang/rust/avro/Cargo.toml

It looks like strum_macros is at 0.24.0 as opposed to 0.24.1 on [crates.io](https://crates.io/crates/strum_macros), causing the build to fail.
Alternatively, instead of fixing the version at 0.24.0 and 0.24.1, we could just use the semver prefix of 0.24.
- https://issues.apache.org/jira/browse/AVRO-3541

AVRO-3541: Unbump strum_macros

---

lang/py/avro/schema.py

Changed string in the function: make_avsc_object (from the file "schema.py"):
scale = 0 if json_data.get("scale") is None else json_data.get("scale") -> scale = json_data.get("scale", 0)
By Python documentation:
get(self, key, default=None, /)
Return the value for key if key is in the dictionary, else default.
It is more effective and readable than previous version.
- https://issues.apache.org/jira/browse/AVRO-3542

AVRO-3542: Scale assignment optimization

---

.github/workflows/test-lang-rust-ci.yml
lang/rust/README.md
lang/rust/avro/Cargo.toml
lang/rust/avro/src/lib.rs
lang/rust/avro/src/writer.rs
lang/rust/avro_test_helper/src/lib.rs
lang/rust/avro_test_helper/src/logger.rs

At this moment, due to dependency on `getrandom` crate, the Rust library can't compile for  WebAssembly (`wasm32-unknown-unknown` target). There is a workaround for environments containing JavaScript https://docs.rs/getrandom/0.2.7/getrandom/#webassembly-support but for others, it can't be used.
This PR replaces the usage of random generating for `wasm32` with the one that supports `wasm32`.
Jira
https://issues.apache.org/jira/browse/AVRO-3543

AVRO-3543: Support wasm32 compilation target for Rust library

---

.github/workflows/test-lang-rust-ci.yml
lang/rust/avro/src/error.rs
lang/rust/avro/src/reader.rs

AVRO-3549: [rust] Return a proper error when the codec is not supported and/or enabled.

---

doc/layouts/project/list.print.html

This turns out to be the same problem also experienced in AVRO-3378, which needs to be applied to the `print` template.

AVRO-3544: Fix projects print template for website

---

lang/ruby/Gemfile

AVRO-3553: Limit changes to rubocop lint

---

doc/layouts/shortcodes/avro_version.html

Use the Go template `{{/* comment */}}` instead of HTML comments to ensure that the avro_version shortcode doesn't add additional unwanted whitespace.

 AVRO-3557: Trim whitespace from the avro_version shortcode 

---

.github/workflows/test-lang-rust-ci.yml
lang/rust/Cargo.toml
lang/rust/README.md
lang/rust/avro/src/encode.rs
lang/rust/avro/src/ser.rs
lang/rust/avro_derive/tests/derive.rs
lang/rust/wasm-demo/Cargo.toml
lang/rust/wasm-demo/README.md
lang/rust/wasm-demo/src/lib.rs
lang/rust/wasm-demo/tests/demos.rs

AVRO-3558: Rust: Add a demo crate that shows usage as WebAssembly

---

doc/content/en/_index.html

AVRO-3559: Fix links to "Getting started ..." on the home page

---

lang/java/mapred/src/main/java/org/apache/avro/mapreduce/AvroOutputFormatBase.java

In hadoop 3.x the abstract class PathOutputCommitter defines the method `getWorkPath()`, but in hadoop 2.x it only defined on FileOutputCommitter. So to be compatible with both hadoop 2.x and 3.x and support committers that only implements PathOutputComitter and not FileOutputCommitter we make the call to getWorkPath using reflection.
The implementation is based on the suggestions in https://github.com/apache/avro/pull/1431 but as that PR has no updates from the author in 3 months I create a new PR.
This fixes [AVRO-3266](https://issues.apache.org/jira/browse/AVRO-3266)
Is covered by existing tests.
No new public methods.

AVRO-3266: Work with hadoop 3.x PathOutputComitters

---

share/docker/Dockerfile

AVRO-3564: Update minimal supported Rust version in Docker to 1.54.0

---

lang/csharp/src/apache/main/Reflect/ClassCache.cs
lang/csharp/src/apache/test/Reflect/TestReflect.cs

Signed-off-by: Zike Yang <zike@apache.org>
- https://issues.apache.org/jira/browse/AVRO-3219

AVRO-3219: Add nullable enum type field support in Avro.Reflect

---

lang/java/ipc/src/main/java/org/apache/avro/ipc/stats/StatsServlet.java

Fix Velocity configuration warnings by changing to new configs since the old ones were deprecated.
- https://issues.apache.org/jira/browse/AVRO-3581
It only changes Velocity configs and all the tests pass after the changes. …

AVRO-3581: Fix Velocity configuration warnings

---

lang/c++/impl/DataFile.cc

Fix possible heap-buffer-overflow in avro::DataFileReaderBase::readDataBlock() while reading bad data.
This error was found by stress tests in ClickHouse under address sanitizer: https://github.com/ClickHouse/ClickHouse/issues/33652
Stacktrace:
```
==549==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200037c8cc at pc 0x000034e6e371 bp 0x7fc5a2e97e50 sp 0x7fc5a2e97e48
READ of size 1 at 0x60200037c8cc thread T553 (QueryPipelineEx)
#0 0x34e6e370 in avro::DataFileReaderBase::readDataBlock() obj-x86_64-linux-gnu/../contrib/avro/lang/c++/impl/DataFile.cc:418:18
#1 0x34e70485 in avro::DataFileReaderBase::hasMore() obj-x86_64-linux-gnu/../contrib/avro/lang/c++/impl/DataFile.cc:338:9
...
```
You can find an example of corrupted file here: …

Fix possible heap-buffer-overflow in avro::DataFileReaderBase::readDataBlock()

---

lang/csharp/build.sh

Add the `codec/` packages to the C# distribution.  Note that these are missing from the Avro 1.11.1 binary release but uploaded to nuget.org from the same build. 

AVRO-3592: Add the codec packages to the tar

---

lang/rust/avro/src/schema.rs

UnionSchema::new method should be public to facility programmatic schema
creation. Visibility of the method changed.

AVRO-3600: UnionSchema::new method should be public

---

lang/rust/avro/src/codec.rs
lang/rust/avro/src/duration.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

AVRO-3608: Rust: Fix clippy errors in Rust 1.63.0

---

lang/c++/api/CustomAttributes.hh
lang/c++/impl/CustomAttributes.cc
lang/c++/test/unittest.cc

Add unit tests for CustomAttributes#getAttribute(string)

AVRO-3601: CustomAttributes#getAttribute() now returns boost::optional

---

lang/c++/CMakeLists.txt
lang/c++/api/AvroTraits.hh
lang/c++/api/NodeImpl.hh
lang/c++/impl/DataFile.cc
lang/c++/impl/Resolver.cc
lang/c++/impl/ValidSchema.cc
lang/c++/impl/Validator.cc
lang/c++/test/AvrogencppTestReservedWords.cc
lang/c++/test/AvrogencppTests.cc
lang/c++/test/CodecTests.cc
lang/c++/test/CompilerTests.cc
lang/c++/test/DataFileTests.cc
lang/c++/test/JsonTests.cc
lang/c++/test/LargeSchemaTests.cc
lang/c++/test/SchemaTests.cc
lang/c++/test/SpecificTests.cc
lang/c++/test/StreamTests.cc
lang/c++/test/buffertest.cc
lang/c++/test/testgentest.cc
lang/c++/test/unittest.cc

AVRO-3616: C++ Fix compilation warnings

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectDatumReader.java

**Support Map(with non-String keys) and Set in ReflectDatumReader**
My PR addresses the following [AVRO-3602](https://issues.apache.org/jira/browse/AVRO-3602) issues 
My PR adds the following unit tests:
TestReflectDatumReader.testRead_PojoWithSet
TestReflectDatumReader.testRead_PojoWithMap

AVRO-3602 Support Map(with non-String keys) and Set in ReflectDatumReader

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

https://issues.apache.org/jira/browse/AVRO-3621
- Updated `validate_record` and added assertions that would not work previously.
- Created a new test case `resolve_to_nullable_union` that tests the changes in this PR, for upcasting record fields the corresponding union type in nullable fields.

AVRO: [Rust] Improved resolution of nullable record fields.

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro_test_helper/src/logger.rs

Follow-up on: https://github.com/apache/avro/pull/1837#discussion_r955853650
https://issues.apache.org/jira/browse/AVRO-3621
- Adds a unit test assertion based on updated behavior, to assert that each validation check is no longer producing error logs when resolving against unions.

AVRO-3621: [Rust] do not log each error while validating against union variants

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificDatumReader.java

[AVRO-3597](https://issues.apache.org/jira/browse/AVRO-3597) : recall newInstanceFromString.

AVRO-3597: Allow custom readers to override string creation

---

lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java
lang/py/avro/name.py
lang/py/avro/schema.py
lang/py/avro/test/test_compatibility.py
lang/py/avro/test/test_schema.py

Python implementation does not treat the name and namespace element as Java library.
This causes the compatibility check to fail as the name which can be fully qualified
is not splitted to name and namespace elements.
https://issues.apache.org/jira/browse/AVRO-3622
- Java: test case to `COMPATIBLE_READER_WRITER_TEST_CASES`, to demonstrate that Java library does not have the issue described.
- Python: same test case to Python lib.
1. [X] Subject is separated from body by a blank line
1. [ ] Subject is limited to 50 characters (not including Jira issue reference)
1. [X] Subject does not end with a period
1. [X] Subject uses the imperative mood ("add", not "adding")
1. [X] Body wraps at 72 characters
1. [X] Body explains "what" and "why", not "how"

AVRO-3622: Fix compatibility check for schemas having or missing namespace

---

.github/PULL_REQUEST_TEMPLATE.md

I picked the Apache Flink style to illustrate -- I like the way that most of the instructions are in the comments and only the essential text is required for the reviewer.
The original: https://github.com/apache/flink/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- https://issues.apache.org/jira/browse/AVRO-3623
- All the public …

AVRO-3623: Update the PR template

---

lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/test/java/org/apache/avro/ResolverTest.java
lang/java/avro/src/test/java/org/apache/avro/TestResolver.java

This PR add unit test on Resolver class to ensure that issue described in [AVRO-2831](https://issues.apache.org/jira/browse/AVRO-2831) found in 1.8.2 does not occurs on master (1.11.1). 
The issue is about Logical Type that are ignore by resolver (in 1.8.2)
- Added unit test on org.apache.avro.Resolver class (org.apache.avro.TestResolver)

AVRO-2831: add unit test on Avro

---

lang/java/archetypes/avro-service-archetype/src/main/pom/pom.xml
lang/java/archetypes/avro-service-archetype/src/main/resources/archetype-resources/src/test/java/integration/SimpleOrderServiceIntegrationTest.java
lang/java/maven-plugin/pom.xml
lang/java/maven-plugin/src/test/resources/unit/idl/pom-injecting-velocity-tools.xml
lang/java/maven-plugin/src/test/resources/unit/idl/pom.xml
lang/java/maven-plugin/src/test/resources/unit/protocol/pom-injecting-velocity-tools.xml
lang/java/maven-plugin/src/test/resources/unit/protocol/pom.xml
lang/java/maven-plugin/src/test/resources/unit/schema/pom.xml
lang/java/pom.xml

Use JUnit 5.x Vintage engine instead of JUnit 4.x
* Fix the execution of JUnit 4.x unit tests by using JUnit 5.x Vintage engine. Fixes AVRO-3628
Check the stdout of the Maven build and make sure that JUnit 4.x tests are executed, e.g. avro-maven-plugin module should execute 11 tests.

AVRO-3628: [Java] JUnit 4.x tests are not executed

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/DirectBinaryDecoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java

[AVRO-3618](https://issues.apache.org/jira/browse/AVRO-3618) : update unit test testBinaryDecoder to test directBinaryDecoder before moving it in JUnit5.

AVRO-3618: Test both directBinaryDecoder and binaryDecoder

---

doc/content/en/docs/++version++/Specification/_index.md
lang/py/avro/tether/tether_task.py

There are small typos in:
- doc/content/en/docs/++version++/Specification/_index.md
- lang/py/avro/tether/tether_task.py
Fixes:
- Should read `correspondence` rather than `correspondance`.
- Should read `contain` rather than `containg`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

doc/config.toml
doc/layouts/partials/footer.html
doc/layouts/partials/navbar-asf-links.html
doc/layouts/partials/navbar.html

*For [AVRO-3624](https://issues.apache.org/jira/browse/AVRO-3624) Try to complete site with Apache references to get greener note in https://whimsy.apache.org/site/.
Manual check :
on folder "doc", run hugo via command `hugo server --buildDrafts --buildFuture --bind 0.0.0.0 --navigateToChanged `
This change is only on documentation.
I tried to have somethink that look like "ASF Links" on [Apache arrow site](https://arrow.apache.org/), but i succeed only with HTML select/option code, so it's little weird.

AVRO-3624: Add apache links

---

lang/rust/avro/src/lib.rs
lang/rust/avro/src/reader.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/append_to_existing.rs

* Make it possible to pass a block marker to Writer, so that it could append to pre-existing bytes (i.e. bytes created by another Writer)
Fixes AVRO-3630
This change adds new IT tests and can be verified by `cargo test`
- If yes, how is the feature documented? Rustdoc

AVRO-3630: [Rust] Make it possible to extend pre-existing Avro bytes

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

Check the first element of the union matches the default value provided according to the [union spec](https://avro.apache.org/docs/1.11.1/specification/#unions)
This change added tests and can be verified as follows: `cargo test`
- Does this pull request introduce a new feature? NO

AVRO-3632: [Rust] Handle defaults in unions according to the spec

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs
lang/rust/avro_test_helper/Cargo.toml

[AVRO-3633](https://issues.apache.org/jira/browse/AVRO-3633) *This pull request introduces additional macro attributes 'skip' and 'rename' to the 'avro_derive' crate.*
- *Added test that validates correct behavior for skipping or renaming fields with derive macro 'AvroSchema'.*
- If yes, how is the feature documented? not documented

AVRO-3633: [Rust] Additional attributes for 'avro_derive' crate

---

lang/rust/avro/src/schema.rs
lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

* AVRO-3634: Add a test case for deriving an Avro schema for a struct with `bool`ean field
Run the unit tests

AVRO-3634: Implement AvroSchemaComponent for bool

---

lang/rust/avro/src/reader.rs

*This pull request fixes a bug in GenericSingleObjectReader::read_value for non-exhaustive reads, fixing AVRO-3642
This change adds the test reader::tests::test_avro_3507_single_object_reader_incomplete_reads
This pull request does _not_ introduce a new feature

AVRO-3642: [RUST] Fix GenericSingleObjectReader::read_value for non-exhaustive reads

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumWriter.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectDatumReader.java

Why:
Javas Optional type can not be used in any meaningful way with the reflection-based schema generation. It is for example not possible to write a generic custom encoding.
How does it help with resolving the issue:
Optional can be used to make fields null safe in their usage.
Side effects:
I think that this change should not have any side effects, because Optional fields could not have been used in the past.
Implementing AVRO-3644.
- *Added test that validates that a correct schema is generated*
- *Added test that validates that Optional fields can be serialized and deserialized*
- **This is my big question. Is the reflection serialization documented anywhere?**

AVRO-3644: [java] Support java.util.Optional in reflect package

---

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java

I was trying out Optionals and was looking at the code for the same. I've put up minor improvements. Hope it helps.
This is how it looked earlier,

Improve generated comments and compiler option description

---

lang/rust/avro/benches/serde.rs
lang/rust/avro/benches/serde_json.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/schema.rs

* Fix some minor Rust clippy errors introduced with Rust 1.65. AVRO-3661
* The Rust CI workflows should pass

AVRO-3661: [Rust] Fix new clippy errors introduced with Rust 1.65

---

doc/content/en/docs/++version++/Getting started (Python)/_index.md

* Fix the type of 'favorite_color' field in the docs, fixing AVRO-3659
This change is a trivial fix in Markdown documentation.

AVRO-3659: Typo in python example

---

lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

When using a raw identifier as field name, the `r#` prefix was used as field name for the resulting schema which results in an invalid AVRO schema. This fix removes that prefix as it would be expected.
This change added tests which can be used to verify the fix.

AVRO-3663: [Rust] Allow raw identifiers as field names

---

.github/workflows/test-lang-rust-audit.yml
.github/workflows/test-lang-rust-ci.yml
.github/workflows/test-lang-rust-clippy.yml
lang/rust/avro/src/ser.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/serde_enum.rs
lang/rust/avro/tests/serde_enum_with_duplicates.rs

This pull request adds two integration tests to assess the changes of #1921:
- (De)serialization of an enum with mixed variants (Null, new type, tuple and struct): `serde_enum`.
- (De)serialization of an enum with mixed and duplicate variants: `serde_enum_with_duplicates`.
The two integration tests **do not pass** for multiple reasons:
- The serialized values do not validate the defined schema.
- The `type` value for the tuple variant is serialized as an `Array` of `Union` instead as an `Union` of `Array`.
- With duplicate variants, the index in the `type` union is not valid (because there is no duplicate in the union defined by the schema).

AVRO-3646: integration tests for (de)serializing of enum with mixed variants

---

.github/workflows/test-lang-py.yml
lang/py/avro/compatibility.py
lang/py/setup.cfg

AVRO-3672
* Add Python 3.11 to the test matrix 
* Github Actions build should pass

AVRO-3672: Add CI testing for Python 3.11

---

lang/ruby/test/test_logical_types.rb

AVRO-3662 
* Test `test_bytes_decimal_object_allocations_decode` is flaky on Ruby 2.6
* Tests should pass on CI 

AVRO-3662: It seems Ruby 2.6 sometimes retains '2'

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

AVRO-3674
* Fix a bug in schema resolution and validation when processing an inner schema with and without its own namespace
* New unit tests are added
New public methods are added. Documented with Rustdoc

AVRO-3674: [Rust] Pass the correct enclosing namespace when validating and resolving

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

In addition to https://github.com/apache/avro/pull/1204, this pull request wraps UUIDs in quotes to produce a valid JSON.
Added test that validates UUID toString() behaviour 

AVRO-3676: Produce valid toString() for UUID JSON

---

.mvn/extensions.xml
lang/java/pom.xml
pom.xml
share/docker/Dockerfile

I was playing today with maven 4 and noticed that Avro was not building yet with it. This PR updates some dependencies so we can run it and enables the new cache plugin to speed up builds for users on Maven 4.

Bump Maven plugin versions and maven version for the docker based build

---

lang/rust/avro/src/types.rs

Originally contributed by @shaeqahmed with #1985
This pull request adds support for validating/resolving a float value against a destination schema where the corresponding field is defined as a double, fixing AVRO-3678. This makes the behavior similar to how we currently support other lossless upcasting of numeric types, such as int -> long, which should be expected behavior.
https://issues.apache.org/jira/browse/AVRO-3678
- Added tests that validates that a float value can be resolved & validated against a schema double field.

AVRO-3678: [Rust] Support writing float value to field defined as double

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml

AVRO-3679
* Enable better performance of regular expressions' evaluations
* All existing tests should pass

AVRO-3679: [Rust] Enable 'perf' feature of regex dependency

---

doc/content/en/docs/++version++/Getting started (Python)/_index.md

Fix incorrect formatting in python getting started docs
See preview of page before and after the change.
Before: 
After:

Code should go into code block

---

.github/workflows/test-lang-py.yml

Use ubuntu-20.04 runners for Python workflow.
ubuntu-latest is now ubuntu-22.04 and it does not provide Python 3.6
AVRO-3681
* Fix Python 3.6 CI on Github Actions
* CI must be green again

AVRO-3681: [Python] GitHub actions failing with python 3.6

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java.yml
lang/csharp/README.md
lang/csharp/build.sh
lang/csharp/common.props
lang/csharp/src/apache/benchmark/Avro.benchmark.csproj
lang/csharp/src/apache/benchmark/Program.cs
lang/csharp/versions.props

Add support for NET 7.0, AVRO-3670
This change just adds a new target framework, updates package versions and disables EOL SDK related warnings.

AVRO-3670: Add NET 7.0 support

---

.github/dependabot.yml
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/io.rs

No JIRA ticket!
This PR fixes minor lint warnings produced by Rust 1.66.0.
CI should pass!

Fix minor warnings from rust 1.66.0

---

lang/rust/avro/src/de.rs

This PR fixes deserializing into rust structures that use `#[serde(flatten)]`, which is a very common use case when using `serde`.
This change added the corresponding test:
```bash
cargo test -- test_avro_3692_from_value_struct_flatten
```
This is a minor enough change that it probably doesn't need to be documented - users would hope for this to work from the beginning.

AVRO-3692: [rust] Make serde deserializer support serde flatten

---

doc/content/en/docs/++version++/SASL profile/_index.md

I only fixed two small typo errors in docs
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? …

docs: fix small error

---

.github/workflows/test-lang-ruby.yml
lang/ruby/build.sh

* Test against the latest Ruby release, 3.2
* bundler is already installed by the `setup-action` so skipping also installing it as a package saves some time in CI
* bundler v1.17.3 is no longer needed
* rbenv setup was previously removed from the Dockerfile: https://github.com/apache/avro/commit/cf7bfe7710febdc84e70fcc8ad21d859dbf1be1f#diff-9ad53a2cdd23436f405be61d20306403700f362287b3d86609319919176a6fb6L191-L203
This change is already covered by the existing Ruby test suite.

AVRO-3697: [ruby] Test against Ruby 3.2

---

.github/workflows/test-lang-java.yml
.github/workflows/test-lang-js.yml
.github/workflows/test-lang-py.yml
share/docker/Dockerfile

Replace tox-wheel with standard tox
Usage of third party tox-wheel package started failing since tox released version 4 with native wheel. Any usage of tox-wheel is replaced with standard tox package to fix Python tests.
This change is already covered by existing tests, and now CI pipeline should work with Python.
- Does this pull request introduce a new feature?: no

AVRO-3696: [py] Replace tox-wheel with standard tox

---

lang/py/avro/schema.py

AVRO-3229 added validation for enum default raising an exception for invalid default.  Allow disabling validation, and parsing enums with enum default not defined using existing `validate_enum_symbols` flag.
This change is already covered by existing tests, such as lang/py/avro/test/test_schema.py expanded with #1433 .
Existing inline documentation is improved to cover this type of usage.

AVRO-3229: [py] Raise on invalid enum default only if validation enabled

---

.github/workflows/test-lang-ruby.yml
BUILD.md
lang/ruby/.rubocop.yml
lang/ruby/avro.gemspec
lang/ruby/build.sh
lang/ruby/test/test_logical_types.rb

https://issues.apache.org/jira/browse/AVRO-3278
Ruby 2.6 reached EOL on March 31, 2022.
This change is already covered by the existing Ruby tests.
- Release notes for the next major release should note that Ruby 2.7 or later is required.

AVRO-3278: [ruby] Drop support for Ruby 2.6

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

Part of [AVRO-3649](https://issues.apache.org/jira/browse/AVRO-3649) for rust.
PR for [java is here](https://github.com/apache/avro/pull/1922)
This change added/updated tests and can be verified as follows:
- run schema.rs unit test.
- ./build.sh clean test (on lang/rust subfolder)
- If yes, how is the feature documented? change doc is done on [java PR](https://github.com/apache/avro/pull/1922).

AVRO-3649: default value for union type should match any type inside the union type.

---

.github/workflows/maven4.yml
pom.xml

[AVRO-3701] Add github action to validate maven 4 build compatibility

---

pom.xml

This PR aims to publish SBOM artifacts.
Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
This PR uses [CycloneDX maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin), a lightweight software bill of materials (SBOM) standard …

AVRO-3700: Publish Java SBOM artifacts with CycloneDX

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificData.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java

This pull request fixes AVRO-3698.
When makes Java Class, [SpecificCompiler](https://github.com/apache/avro/blob/master/lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java#L1129) adds "$" after reserved words like public, new, etc...
For example, if the namespace of a schema is db.public.table, then the package name of the generated Java Class, made by SpecificCompiler, is db.public$.table. (Because public is a reserved word in java)
But when deserializes an Avro Record to a SpecificRecord, SpecificData.getClassName returns db.pulic.table.Name.
So, it can't find a class by name from SpecificData.getClassName.
- Added ```@Test``` ```classNameContainingReservedWords``` on ```TestSpecificData```
- …

AVRO-3698: SpecificData.getClassName must replace reserved words

---

lang/c++/api/Reader.hh

AVRO-3712
Fix build. (I'm guessing adding 'pedantic' to build.sh broke this a while back.)
No documentation required.

AVRO-3712: Fix C++ build by initializing union

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/schema.rs
lang/rust/avro_derive/src/lib.rs

AVRO-3709
Adds support for Record field aliases
Old tests are updated.
New tests are added.
- Rustdoc is updated

AVRO-3709: [Rust] Add aliases to record fields

---

doc/content/en/docs/++version++/Specification/_index.md

Dangling commas are not permitted in JSON. This fixes that error in the Object Container Format header type definition.
n/a

doc: Fix invalid JSON in spec

---

lang/java/avro/src/main/java/org/apache/avro/reflect/FieldAccess.java
lang/java/avro/src/main/java/org/apache/avro/reflect/FieldAccessReflect.java
lang/java/avro/src/main/java/org/apache/avro/reflect/FieldAccessUnsafe.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectDatumReader.java

```
@Data
@AllArgsConstructor
@NoArgsConstructor
public static class Person {
String name;
int age;
String address;
double score;
}
@Data
@AllArgsConstructor
@NoArgsConstructor
public static class PersonV2 {
String name;
int age;
String address;
double score;
@Nullable
String country;
@Nullable
int phone;
@Nullable
double salary;
}
```
Use personV2 schema to read personV1 data; it will throw NPE.
When the basic type value is null, use the default value to populate it.

Fix NPE when basic type with Nullable annotation.

---

lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java

Revert "AVRO-3684: [Java] testAppendStream test"

---

lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java

For unknown reason the status of https://github.com/apache/avro/pull/2015 was `green` yet there was this problem.

AVRO-3690: Fix spotless problem

---

lang/java/ipc-netty/src/test/java/org/apache/avro/ipc/netty/TestNettyServer.java

https://issues.apache.org/jira/browse/AVRO-3718

AVRO-3718: [Java] Fix flaky NettyServer test

---

pom.xml

Remove a workaround that is no longer needed since we have a new enough Apache Rat.

AVRO-2404: Remove now obsolete Apache Rat workaround

---

doc/content/en/docs/++version++/Specification/_index.md

Also make data file schemas valid json (no trailing commas)
Clarify the docs for the data file format
- If yes, how is the feature documented? recursively so

[doc] Change index.md to add a schema for data blocks

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

Make GenericRecord comparison handle String vs Utf8 for MAP type
This mirrors what was already previously done for Schema.type.STRING
Adds the following new unit tests:
- org.apache.avro.generic.TestGenericData.testMapKeyEquals
- org.apache.avro.generic.TestGenericData.testMapValuesEquals
N.B.
We should also consider doing the same for Schema.type.ARRAY
https://issues.apache.org/jira/browse/AVRO-2943

AVRO-2943 improve GenericRecord MAP type comparison

---

lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

https://issues.apache.org/jira/browse/AVRO-2943

AVRO-2943: Add new GenericData String/Utf8 ARRAY comparison test

---

lang/csharp/src/apache/codegen/Avro.codegen.csproj

Add RollForward -> Major to avrogen, to make sure it will run even if the required NET SDK is not installed (AVRO-3727)*

AVRO-3727: Add RollForward option to avrogen

---

lang/csharp/versions.props
share/docker/Dockerfile

*Installing .NET 7 SDK in the docker image, fixing AVRO-3738.)*

Add NET 7 SDK to Dockerfile

---

lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectLogicalTypes.java

Currently `RecordWithTimestamps#equals` is invalid since it compares `that.localDateTime` vs `that.localDateTime`
- Does this pull request introduce a new feature? ( no)
- If yes, how is the feature documented? (not applicable )

[hotfix][java][test] RecordWithTimestamps#equals should compare its own localDateTime with that.localDateTime

---

lang/rust/avro/src/schema.rs

AVRO-3755 
Add a unit test to prevent regressions.
The bug seems to be fixed earlier and most probably there is another test test for the same but it does not harm to have a second one.
* Add a unit test to prevent regressions
* This change added tests and can be verified by executing the unit tests

AVRO-3755: [Rust] Deserialization fails for reader schema with namespace

---

lang/rust/Cargo.lock
lang/rust/avro/src/de.rs
lang/rust/avro/src/writer.rs
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

AVRO-3757
Fix compilation errors in avro_derive.
Use anyhow for test results for better error reporting.
* Update a dependency that is used by other dependencies for auto derivation (serde, strum, darling, ...)
* Run the test suite

AVRO-3757: [rust] Update syn to 2.x

---

lang/rust/avro/src/de.rs
lang/rust/avro/src/ser.rs
lang/rust/avro/src/util.rs

AVRO-3758
* Simplification and removal of `unsafe {}` block usages
*  This change is a trivial rework
* The relevant tests are updated

AVRO-3758: [Rust] use atomic types instead of static mut

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/schema.rs
lang/rust/avro_derive/src/lib.rs
lang/rust/avro_derive/tests/derive.rs

AVRO-3759
* Adds extra types for RecordSchema, EnumSchema, FixedSchema and DecimalSchema
* Existing tests are updated to the API change

AVRO-3759: Add extra types for RecordSchema, EnumSchema, FixedSchema and DecimalSchema

---

build.sh
lang/ruby/Gemfile
share/docker/Dockerfile

This pull request preinstalls the gems that the Avro Ruby SDK depends on in the ubertool docker container.
This change was manually verified by building a clean docker and building the Avro Ruby SDK.

AVRO-3736: [Ruby] Preinstall gems in ubertool docker

---

lang/rust/avro/src/lib.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/types.rs

AVRO-3772
Take into account the field's default value when resolving an enum in a reader schema
* Fix the resolution of an `enum` with a symbol which is no more available in the reader schema. Use any `default` value if available before returning an error
See https://avro.apache.org/docs/1.11.1/specification/#schema-resolution 
* An old test has been updated to the new logic

AVRO-3772: [Rust] Deserialize Errors for an Unknown Enum Symbol instead of Returning Default

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java
lang/java/avro/src/test/java/org/apache/avro/io/TestResolvingIOResolving.java
lang/java/avro/src/test/java/org/apache/avro/io/parsing/TestResolvingGrammarGenerator.java

- https://issues.apache.org/jira/browse/AVRO-3560
- TestSchema.testContentAfterAvsc()
- TestSchema.testContentAfterAvscInInputStream()

AVRO-3560: throw SchemaParseException on dangling content in avsc beyond end of schema

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_schema.rb

fixing validator for https://issues.apache.org/jira/browse/AVRO-3773
- New unit tests are added to reproduce, refer to [first Github Action](https://github.com/jychen7/avro/actions/runs/5207444823/jobs/9394998133) (Expect failure)
- Adding the fix pass all tests, including both old and new ones
- Does this pull request introduce a new feature? `no`
- If yes, how is the feature documented? `not applicable`

AVRO-3773: [ruby] fix validator for decimal default

---

lang/rust/avro/src/types.rs

Currently shows only a failing test case, described in the [JIRA issue](https://issues.apache.org/jira/browse/AVRO-3782).

[Rust]: Incorrect decimal resolving checks

---

lang/ruby/lib/avro/io.rb
lang/ruby/test/test_logical_types.rb

fix https://issues.apache.org/jira/browse/AVRO-3775
when doing schema resolution, default value is being used. However, decimal default value was returned as string/bytes, however, should be BigDecimal
- New unit tests are added to reproduce (Expect CI is Red): https://github.com/jychen7/avro/actions/runs/5227583924/jobs/9439320277
- Fix are applied to make sure CI is Green
- Does this pull request introduce a new feature? `no`
- If yes, how is the feature documented? `not applicable`

AVRO-3775: [ruby] fix decoded default value of decimal logical type

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/DirectBinaryDecoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryData.java

***NEED HELP ACCESSING JIRA ACCOUNT TO FILE ISSUE FOR THIS***
In the spec, the encoding for the bytes type is `bytes are encoded as a long followed by that many bytes of data.`. In the Java binary decoders they are read as ints this is not a correctness issue because the VLE of the long is the same as that of an equivalently valued int. The int is used (I assume) to enable easier interop with the ByteBuffer java class. But in the rare cases where validly encoded data of more than `MAX_ARRAY_SIZE` bytes is found, this change will cause an error of
```
throw new UnsupportedOperationException(
"Cannot read arrays longer than " + MAX_ARRAY_SIZE + " bytes in Java library");
```
instead of 
```
throw new InvalidNumberEncodingException("Invalid int encoding");
```
This type of checking is …

AVRO-3783: Read LONG length for bytes, only allow INT sizes

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/types.rs
lang/rust/avro_derive/src/lib.rs

AVRO-3772
* During schema resolution use the enum's `default` field instead of the field's default
* All tests should pass

AVRO-3772: [Rust] Use the enum default field instead of the field default

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml

It is based on syn 2.x
No Jira: I'd let dependabot provide the PR but since 1.11.2 could be cut any time now I open this PR myself.

[Rust]: Update Strum to 0.25.0

---

.github/workflows/test-lang-rust-ci.yml
BUILD.md
lang/rust/Cargo.toml
lang/rust/avro/Cargo.toml
lang/rust/avro/README.md
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_test_helper/Cargo.toml
lang/rust/fuzz/Cargo.toml
lang/rust/wasm-demo/Cargo.toml
share/docker/Dockerfile

AVRO-3793
Use [workspace.package] in the parent Cargo.toml to reduce duplication
* Bump the minimum supported Rust version to 1.65.0
* Run the test suite

AVRO-3793: [Rust] Bump minimum supported version of Rust to 1.65.0

---

lang/rust/avro/tests/shared.rs

AVRO-3794
* Modifies a test to not fail when the shared folder is not available
* The tests should still pass in the CI
* The test should print a warning and succeed when the shared folder is not available for any reason

AVRO-3794: [Rust] Do not fail the shared tests when the shared folder is not available

---

lang/rust/avro/src/types.rs
lang/rust/avro/tests/avro-3787.rs

AVRO-3787
Do not fail the validation if the provided enum symbol is not in the list of available ones if there schema defines a default symbol
* Improve the behavior when doing schema validation with an Enum that has a default value
* The tests from the JIRA ticket have been added to the test suite

AVRO-3787: [Rust] Deserialization fails to use default if an enum in a record in a union is given an unknown symbol

---

lang/py/tox.ini

AVRO-3797: Add Python 3.11 to tox.ini

---

lang/py/avro/ipc.py
lang/py/avro/schema.py

This change updates the Python code to consistently use the `@property` decorator for class properties, which in turn will make adding type annotations easier.
This pull request does not introduce a new feature.

AVRO-3796: Use Property Decorator

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

AVRO-3799
This PR proposes to add a feature which enables to create schemas from input streams which implement `Read` trait like `std::fs::File`.
The Java binding supports to create schemas from input streams. So, it's useful to have such a feature for the Rust binding too.
This change adds new tests to `tests/schema.rs` and `cargo test` passed.
Doc comments added.

AVRO-3799: [Rust] Enable the schema parser to read and parse from input streams for Rust binding

---

share/docker/Dockerfile

Enable all the tox environments, including Python 3.11, to work in the docker development environment.
(Also, removes the 20 second sleep when installing deprecated node.)
This pull request does not introduce a new feature.

AVRO-3806: Add Python 3.11 to Dockerfile

---

lang/py/avro/schema.py
lang/py/avro/test/test_schema.py

[AVRO-1737](https://issues.apache.org/jira/browse/AVRO-1737) : Implement Hashable for Schema. This will ensure that schema can be members of a set or keys in a dictionary. 
Also see [the python documentation](https://docs.python.org/3.11/reference/datamodel.html#object.__hash__).
Unit tests have been added to ensure schema are hashable.
- If yes, how is the feature documented? No additional documentation has been added, because this is a low-level API feature that is normal Python behavior.

AVRO-1737 Implement Hashable for Schema

---

BUILD.md
doc/content/en/docs/++version++/api-py.md
lang/py/build.sh
lang/py/docs/Makefile
lang/py/docs/make.bat
lang/py/docs/source/automodule.rst
lang/py/docs/source/conf.py
lang/py/docs/source/index.rst
lang/py/docs/source/intro.rst
lang/py/tox.ini

Use Sphinx to generate documentation in `docs/build/*.html` when `./build.sh docs` is run.
This change doesn't impact the Python Avro runtime, but provides documentation that can be uploaded to avro.apache.org, readthedocs.org and other places.
The docs generation will verify itself during checks.
- That's what it's all about.

AVRO-312 Python Sphinx Documentation

---

lang/rust/avro/src/types.rs

AVRO-3809
The `validate_internal` function is not propagating schema's sub-namespaces resulting in validation error of valid value. This PR fixes the issue checking wether a record in the schema has a `namespace` and passing it through the recursive call to `validate_internal` instead of using by default the top level namespace.
- Run `cargo test`

AVRO-3809: [Rust] Fix validate record reference with implicit namespace

---

.github/workflows/test-lang-py.yml
lang/py/setup.cfg
lang/py/tox.ini
share/docker/Dockerfile

AVRO-3808: Update the list of python versions to test against: Drop 3.6 and add more supported Pypy implementation.s
- AVRO-3808: Drop Python 3.6
- AVRO-3808 Test with Pypy 3.8-3.10
This change adds more python versions to test against.
- Does not apply

AVRO-3808: Drop Python 3.6, Update Pypy

---

lang/java/avro/src/test/java/org/apache/avro/TestReadingWritingDataInEvolvedSchemas.java

[AVRO-2284](https://issues.apache.org/jira/browse/AVRO-2284) : fix unit test
just run unit test

AVRO-2284: fix unit test code

---

lang/rust/avro/src/schema.rs

AVRO-3812
This PR fixes a issue that the Rust binding doesn't handle null namespaces for canonicalized schema representation.
Considering the following schema, which contains namespaces of "".
```
{
"namespace": "",
"name": "my_schema",
"fields": [
{
"name": "a",
"type": {
"name": "my_enum",
"namespace": "",
"symbols": ["a", "b"]
}
},  {
"name": "b",
"type": {
"type": "fixed",
"name": "my_fixed",
"namespace": "",
"size": 10
}
}
]
}
```
If we try to canonicalize this schema with the following code
```
let schema = Schema::parse_str(schema_str).unwrap().canonical_form();
println!("{schema}");
```
We get the following result.
```
{"name":".my_schema","type":"record","fields":[{"name":"a","type":{"name":".my_enum","type":"enum","symbols":["a","b"]}},{"name":"b …
```

AVRO-3812: [Rust] Handle null namespace properly for canonicalized schema representation

---

doc/content/en/docs/++version++/Specification/_index.md

AVRO-3815
At the `Records` section in the specification doc, _orders_ and _aliases_ are explained as attributes of `fields` but their indentation seems broken.
The root cause seems those items are placed below the table.
So, a simple way to fix is to place those items above the table.
Build and render the doc, and confirmed that indentation is clean.
This change fixes a doc.

AVRO-3815: [Doc] Fix broken indentation in the specification doc

---

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/compiler/src/test/java/org/apache/avro/specific/TestGeneratedCode.java
lang/java/compiler/src/test/resources/full_record_v2.avsc

[AVRO-2731](https://issues.apache.org/jira/browse/AVRO-2731) : On generated record, initialize HashMap with capacity corresponding to size and default load factor; as [it is done in guava](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Maps.java#L277-L307)
By adding a Map type to full_record_v2.avsc

AVRO-2731: [Java] initialize hashmap with good capacity

---

lang/java/avro/src/main/java/org/apache/avro/file/CodecFactory.java

AVRO-3811
This PR proposes to mention about `xz` and `zstandard` as default registered codec in JavaDoc for `CodecFactory`.
Verified the rendered JavaDoc.
This change is for JavaDoc.

AVRO-3811: [Java][Doc] Mention about xz and zstandard as default registerd codecs in JavaDoc

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaValidateDefault.java

[AVRO-2236](https://issues.apache.org/jira/browse/AVRO-2236) : Add default value for record type.
This PR allow a field is of type record to have a default value even if the record itself have field with other default values (with union type).
- new unit test TestSchemaValidateDefault

AVRO-2236: [java] default value for record type

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/tools/src/test/compiler/input/optionalgettersnullablefieldstest.avsc
lang/java/tools/src/test/compiler/output/OptionalGettersNullableFieldsTest.java

[AVRO-3788](https://issues.apache.org/jira/browse/AVRO-3788) : fix issue for generated java doc, to replace charater < by &lt; and > by &gt;
Unit test **TestSpecificCompilerTool.compileSchemaWithOptionalGettersForNullableFieldsOnly** has been augmented to add nullable array (by modifying optionalgettersnullablefieldstest.avsc file)

AVRO-3788: escape 'code extracts' in Javadoc

---

lang/rust/avro/src/schema.rs

AVRO-3818
This PR fixes an issue that with the current Rust binding, inner named types don't inherit their enclosing namespace even though they have no their own namespace.
Given we have a schema like as follows.
```
{
"namespace": "my_ns",
"aliases": ["my_alias"],
"name": "my_schema",
"fields": [
{
"name": "f1",
"type": {
"name": "enum1",
"symbols": ["a"]
}
}
]
}
```
In the canonical form of this schema, the fullname of `enum1` should be `my_ns.enum1` because it  has no their own namespace and the enclosing namespace is `my_ns`.
```
{"name":"my_ns.my_schema","type":"record","fields":[{"name":"f1","type":{"name":"my_ns.enum1","type":"enum","symbols":["a"]}}]}
```
But the current implementation makes the fullname of `enum1` as `enum1`.
``` …
```

AVRO-3818: [Rust] Let inner named types inherit their enclosing namespace if they have no their own namespace

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs

AVRO-3820
This PR fixes an issue that the current Rust binding accept invalid field name.
Given we have a schema where a field name doesn't match `[A-Za-z_][A-Za-z0-9_]*` like `f1.x`.
```
{
"name": "my_record",
"fields": [
{
"name": "f1.x",
"type": {
"name": "my_enum",
"symbols": ["a"]
}
}
]
}
```
The current Rust binding accepts such a schema but it seems illegal.
Added new test and it passed with `cargo test avro_3820`
No new feature added.

AVRO-3820: [Rust] Don't allow invalid field names

---

lang/rust/avro/src/error.rs

AVRO-3823
This PR fixes an issue that the current Rust binding doesn't show helpful error messages.
Actually, error types are implemented with helpful error messages.
This is an example.
```
#[error("No `name` field")] 
GetNameField,  
```
But those error messages are not shown.
Given we try to a invalid schema which contains no name field, we expect to get ```No `name` field``` but the actual is `GetNameFIeld`, which makes it difficult for users to resolve the problem.
The cause is that when an error is return from `main`, the error message is made by `Debug::fmt` instead of `Display::fmt`.
So, the solution is implemented `Debug` trait for errors manually.
Tested manually with the following schemas.
```
{
"fields": []
}
Error: No `name` field
```
```
{
"name": …
```

AVRO-3823: [Rust] Show helpful error messages

---

lang/rust/avro/src/encode.rs
lang/rust/avro/tests/schema.rs

AVRO-3821
When encoding Value::Record the logic should use the order of the fields in the schema instead of the order in the Value::Record
* Fix the encoding of `apache_avro::types::Value::Record` which fields are not sorted as the schema fields
* A unit test is updated to cover this case

AVRO-3821: [Rust] Encoding records should follow the schema

---

doc/README.md

AVRO-3824
How to build the website is instructed in `doc/README.md` but we cannot build even though we follow it.
The cause is that an instruction to do `git submodule update --init --recursive` is missing.
After `git submodule update --init --recursive`, I confirmed I can build the website with the instructions in `doc/README.md`.
No new features added.

AVRO-3824: [Doc] The instruction for building the website should be more precise

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_schema.rb

If an UnknownSchemaError is raised for a nested type that should inherit its parent namespace, the default_namespace information is lost when rescuing this exception.
This prevents users of the library to use the raised exception to load the missing schema that may be defined in a separate file fore readability when handling large schema files.
This is a simple addition of information when raising an exception on encountering an unknown schema reference. The existing unit test has been updated to make sure the correct information is added to the exception.
- Does this pull request introduce a new feature?: YES
- Documentation for the raised exception seems to be missing from the project. I did not create it to mention the addition I made in it.

AVRO-3790 Provide namespace on UnknownSchemaError raise

---

lang/py/build.sh

This PR fixes a minor issue that the usage of `build.sh` doesn't mention about `doc` option even though it supports the option.
Now `./build.sh` shows the usage with the `doc` option.
```
$ ./build.sh
Usage: ./build.sh {clean|dist|doc|interop-data-generate|interop-data-test|lint|test}
```
No new features added.

Minor: [Python] Usage of build.sh should mention about `doc`

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs

AVRO-3827
This PR aims to fix an issue that the current Rust binding accepts duplicate field names.
If a schema contains a record and some of its fields have the same field name, such schema should not be allowed.
```
{
"name": "my_schema",
"fields": [
{
"name": "f1",
"type": {
"name": "a",
"fields": []
}
},  {
"name": "f1",
"type": {
"name": "b",
"fields": []
}
}
]
}
```
Added new test and passed with `cargo test avro_3827`.
*(example:)*
- *Manually verified the change by building the website and checking the …

AVRO-3827: [Rust] Disallow duplicate field names

---

.github/workflows/test-lang-php.yml
.github/workflows/test-lang-rust-audit.yml
.github/workflows/test-lang-rust-ci.yml
.github/workflows/test-lang-rust-clippy.yml

AVRO-3828
Enable "RUSTFLAGS=-Dwarnings" for all Rust CI workflows, borrowed from https://github.com/serde-rs/serde/blob/master/.github/workflows/ci.yml
* Make the CI build warnings-free
* Check the CI build "**Annotations**", e.g. https://github.com/apache/avro/actions/runs/5817968858?pr=2433 has several types of warnings

AVRO-3828: [Rust] Fix CI build warnings

---

BUILD.md
doc/content/en/docs/++version++/api-py.md
lang/py/build.sh
lang/py/docs/Makefile
lang/py/docs/make.bat
lang/py/docs/source/automodule.rst
lang/py/docs/source/conf.py
lang/py/docs/source/index.rst
lang/py/docs/source/intro.rst
lang/py/tox.ini

AVRO-312 Python Sphinx Documentation
This is a backport of #2370, to 1.11.x.
Generate Documentation in docs/build/*.html when ./build.sh docs is run.
Implementation detail: Uses tox to install build-time dependencies.
* Add Tox to Python Build Requirements

AVRO-312: Python Sphinx Documentation

---

lang/rust/avro/src/schema.rs

AVRO-3830
This PR aims to fix an issue that the current Rust binding doesn't handle namespaces properly if a name starts with dot.
[The specification](https://avro.apache.org/docs/1.11.1/specification/#names) says about the name and namespace like as follows.
> The empty string may also be used as a namespace to indicate the null namespace
> If the name specified contains a dot, then it is assumed to be a fullname, and any namespace also specified is ignored
According to this specification, if a name in a name field starts with a dot, it's considered that the namespace is null and the corresponding namespace field should be ignored.
For example, given the following schema.
```
{
"name":  ".record1",
"namespace": "ns1",
"fields": []
}
```
The name and namespace should be …

AVRO-3830: [Rust] Handle namespace properly if a name starts with dot

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/avro-3786.rs

AVRO-3814
Successor-of: https://github.com/apache/avro/pull/2394
* Use `types::Value::resolve_internal()` to find the matching schema in an union

AVRO-3814: Fix schema resolution for records in union types

---

lang/java/compiler/pom.xml
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/specific/TestGeneratedCode.java
lang/java/compiler/src/test/resources/regression_error_field_in_record.avsc

Moved the isError check for the "custom codable" check to fix a
backwards compatibility issue between versions 1.8.x & 1.9.x.
- https://issues.apache.org/jira/browse/AVRO-2771
`org.apache.avro.specific.TestGeneratedCode#withErrorField` …

AVRO-2771: Refactor custom codable check

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/test/java/org/apache/avro/file/TestSeekableInputStream.java

The implementation of SeekableInputStream.skip had a longstantind issue that it did a seek to a wrong position.
This issue is rather difficult to hit in avro as it is only used in corner cases of for example the FastReader.
* Fixes AVRO-3748 a longstanding issue in SeekableInputStream.skip
This change added a test to verify the new behavior 
- Does this pull request introduce a new feature? (yes / **no**)

AVRO-3748 [java] fix SeekableInputStream.skip

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/generic/PrimitivesArrays.java
lang/java/avro/src/test/java/org/apache/avro/generic/GenericDataArrayTest.java
lang/java/avro/src/test/java/org/apache/avro/generic/PrimitivesArraysTest.java

[AVRO-2307](https://issues.apache.org/jira/browse/AVRO-2307) : sub task 1.
As described in JIRA
`Another challenge we’ve come across is that lists of primitive types (floats in our case) are always boxed into Object Floats by Avro. In our case, this resulted in millions of Objects / second getting allocated, causing pathological GC pressure.`
So, this PR aims to introduce list of primitives classes that save memory consomption when Generic data with array of boolean, int, long, float or double.
New unit test class PrimitivesArraysTest is implemented + rest of code use it via GenericData.newArray method.

AVRO-2307: [java] list of primitive

---

lang/java/avro/src/main/java/org/apache/avro/io/JsonDecoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestJsonDecoder.java

[AVRO-2885](https://issues.apache.org/jira/browse/AVRO-2885) : check non int value on JsonDecoder (accept only real int or float value as 1.0, when conversion to int doesn't modify the value.
One new unit test TestJsonDecoder.testIntWithError; to ensure that value -1.2 to read an int will throw an error.

AVRO-2885: [Java] better check int vs float value

---

build.sh
lang/py/avro/test/gen_interop_data.py
share/docker/Dockerfile

AVRO-3832
This PR fixes an issue that Python test doesn't work successfully with `./build.sh docker-test` due to some reasons.
Reason1:
```
/bin/sh: 1: BUILDARCH: parameter not set or null
```
Reason2:
```
py37: install_package> python -I -m pip install --force-reinstall --no-deps /avro/lang/py/.tox/.tmp/package/258/avro-1.12.0+snapshot.tar.gz
py37: exit 1 (0.27 seconds) /avro/lang/py> python -I -m pip install --force-reinstall --no-deps /avro/lang/py/.tox/.tmp/package/258/avro-1.12.0+snapshot.tar.gz pid=243
py37: FAIL ✖ in 0.34 seconds
```
Reason3:
```
py311: install_deps> python -I -m pip install coverage python-snappy zstandard
Collecting coverage
Obtaining dependency information for coverage from https://files.pythonhosted.org/packages/55/63/f2dcc8f7f1587ae54bf8cc1c3b08e07e442633a95353 …
```

AVRO-3832: [Python] Make Python test work with Docker

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/ipc/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

As decribe in [JIRA  AVRO-3749](https://issues.apache.org/jira/browse/AVRO-3749), SqlCompiler **can generate same method name** when field name start with undescore '_' name.
hence, a schema with fields
`"x", "X", "_x"`
generates several method getX$0(), and source can't compile.
With this PR, it will generate getX() of x, getX$0 for X and getX$1() for _x 
(but a schema that contains only field _x will generate only getX() method.)
For each field, it count number of collision with "preceding fields" to generate method. Preceding is defined with order, number of underscore (start with 0), and, for same number of underscore, start with lower case.
**This PR can also modify the generated code for a given schema.** thats why ipc TestSpecificCompiler is modify.
new Unit test on …

AVRO-3749: [Java] avoid conflict in method name for generated code

---

.github/workflows/test-lang-rust-clippy.yml
lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

Fix clippy issues with Rust 1.65.0
Run clippy also for MSRV
* Fix `clippy` errors with Rust 1.65.0 (MSRV)
* CI must fully pass

AVRO-3836: [Rust] Fix the build with Rust 1.65.0

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/codec.rs
lang/rust/avro/src/duration.rs
lang/rust/avro/src/rabin.rs

Use standard APIs for converting integers to/from byte arrays. Get rid of byteorder and zerocopy dependencies.
* Replace usage of `byteorder` and `zerocopy` dependencies with standard APIs
* All tests should still pass

AVRO-3835: [Rust] Get rid of byteorder and zerocopy dependencies

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/SystemLimitException.java
lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/DirectBinaryDecoder.java
lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java
lang/java/avro/src/test/java/org/apache/avro/TestFixed.java
lang/java/avro/src/test/java/org/apache/avro/TestSystemLimitException.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java
lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java

As described in AVRO-3819, the system properties, exception types and messages dealing with the limits when allocating strings, bytes and collections are distributed throughout the code: `BinaryDecoder`, `Utf8`, `ByteReader` all have similar logic and checks.
These have been centralised as helper methods in one  location and a new exception: `SystemLimitException` extending `AvroRuntimeException`.
In addition, these checks were applied to the collection sizes in BinaryDecoder (allocating arrays and maps), as well as applied to the `FIXED` type schema.
When dealing with untrusted or corrupt data, these checks ensure that an exception is thrown and can be gracefully handled, as opposed to an `OutOfMemoryError`.
This change added tests, especially in the `TestBinaryDecoder` covering these …

AVRO-3819: Centralize system properties that limit allocations

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs

AVRO-3837
This PR fixes an issue that `namespace` the Rust binding wrongly accept invalid namespaces in `namespace` fields, while invalid namespaces in `name` fields don't accepted.
For example, the following schema is not accepted as expected.
```
{
"name": "ns1.invalid-ns.record1",
"type": "record"
"fields": []
}
```
But the following schema is wrongly accepted.
```
{
"name": "record1",
"namespace": "ns1.invalid-ns",
"fields": []
}
```
Added new tests and all tests passed with `cargo test --workspace`.

AVRO-3837: [Rust] Disallow invalid namespaces for the Rust binding

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/schema.rs

AVRO-3838
Reduces the time for `cargo clean && cargo build --release" from 30secs to 22secs on my dev machine
* Improve the build times by around 30%
* All unit tests should still pass

AVRO-3838: [Rust] Replace "regex" with "regex-lite"

---

lang/rust/Cargo.toml
lang/rust/avro/src/reader.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/io.rs

AVRO-3844
* Fix lint errors
* The build and tests should pass with Rust stable (1.72.0)

AVRO-3844: [Rust] Fix clippy errors with Rust 1.72.0

---

lang/csharp/src/apache/main/File/DeflateCodec.cs
lang/csharp/src/apache/main/Generic/GenericReader.cs
lang/csharp/src/apache/main/Generic/PreresolvingDatumReader.cs
lang/csharp/src/apache/main/IO/BinaryDecoder.cs
lang/csharp/src/apache/main/IO/BinaryEncoder.cs
lang/csharp/src/apache/main/Specific/SpecificReader.cs
lang/csharp/src/apache/test/File/FileTests.cs

The aim of this pull request is to improve memory usage when reading Avro encoded files. Fixing AVRO-3802.
This issue was detected when using Apache.Avro C# library for compression and decompression of large Avro files. Each file is 2-3MB and decompression of 20 files is using 2.1GB memory and memory keep increasing around 200-300MB for follow up calls. 
Attached are images taken of memory profiler of three calls before fix. Each call decompress the same 20 files. First call uses 2.1GB, increase to 2.37GB and then 2.68GB. 
Call tree is showing most of the memory are used by `DeflatCodec.CopyTo` method. 
- `CopyTo` method is not using Array pool. Default Microsoft's stream `copyTo` method is much more efficient. 
- `inStream` and `outStream` memory streams are not in using statement.
- On …

AVRO-3802: [Csharp] Fix memory leak on deflate codec decompression

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/schema.rs

AVRO-3847
This PR fixes an issue that the current Rust binding doesn't support default value of pre-defined name for `Union` type field.
Given we have a schema like as follows.
```
{
"name": "record1",
"fields": [
{
"name": "f1",
"type": {
"name": "record2",
"fields": [
{
"name": "f1_1",
"type": "int"
}
]
}
},  {
"name": "f2",
"type": ["record2", "int"],
"default": {
"f1_1": 100
}
}
]
}
```
The type of the field `f2` is `union` of `record2` and `int`, and the type of the default value is `record2`, which is pre-defined.
Current Rust binding doesn't accept such schemas, raising a error message like as follows.
```
Error: One union type Ref must match the `default`'s value type Map
```
The root cause is the resolution for the type of default value doesn't …

AVRO-3847: [Rust] Support default value of pre-defined name for Union type field

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/de.rs
lang/rust/avro/src/ser.rs

AVRO-3846
This PR fixes an issue that race condition happens among serde tests named avro_3747*.
Sometimes one of tests named avro_3747* fails.
You can easily reproduce this issue frequently with cargo test like as follows.
```
$ cargo test avro_3747
```
The reason is that these tests run concurrently and save/load the same atomic variable.
So this PR introduces `serial_test` crate and make these tests run in serial.
Confirmed tests named avro_3747* don't fail.

AVRO-3846: [Rust] Fix race condition among serde tests

---

lang/rust/.cargo-rdme.toml
lang/rust/Makefile
lang/rust/avro/README.md
lang/rust/avro/src/lib.rs

AVRO-3849
This PR fixes an issue that `make readme` doesn't work.
`avro/README.md` is intended to be created from the doc comment in `avro/src/lib.rs` by `make readme`.
But it doesn't work due to some reasons.
The main reason is `cargo-readme` currently used doesn't work with workspace.
Also, `cargo-readme` is not maintained for a long time (the last commit is Apr 1, 2020).
So, I propose to use `cargo-rdme`.
https://github.com/orium/cargo-rdme
After this change, we can create `avro/README.md` from `avro/src/lib/rs` by the following instructions.
```
$ cargo install cargo-rdme
$ make readme
```
I confirmed `avro/README.md` generated by `make readme` is almost the same as it was before this change.

AVRO-3849: [Rust] Use cargo-rdme instead of cargo-readme

---

doc/content/en/docs/++version++/Specification/_index.md

This PR fixes the heading level of Single-object encoding in the doc.
Currently, `Single-object encoding` is under `JSON Encoding` but it seems wrong.
Confirmed the layout is fixed with the following command.
```
docker run --rm -v $(pwd):/src -p 1313:1313 jakejarvis/hugo-extended:latest --source doc/ server     --buildDrafts --buildFuture --bind 0.0.0.0 --navigateToChanged
```
Then, we can find `Single-object encoding` in the table of contents.

Minor: [Doc] Fix wrong heading level of Single-object encoding in the doc

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/schema.rs

AVRO-3851
This PR proposes to improve the functionality of parsing default values for record fields and enums.
Currently, default values for record fields are validated on parsing only if their types are `union`.
It's nice to apply such validation for other types.
Similarly, default values for `enum` are not also validated on parsing now.
So this PR changes parser functionality to validate default values for record fields and enums.
Added new tests.

AVRO-3851: [Rust] Validate default value for record fields and enums on parsing

---

lang/js/.gitignore

This PR adds an entry `.nyc_output` to `.gitignore` in `lang/js`.
The directory is generated when we run `npm run cover`.
Confirmed `git status` ignores `.nyc_output`.

Minor: [JavaScript] Ignore .nyc_output

---

lang/rust/avro/README.md
lang/rust/avro/src/de.rs
lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs
lang/rust/avro/tests/schema.rs

AVRO-3853
Local timestamp logical types are missing in the Rust SDK.
It's nice to support them.
Added new tests and modified existing tests.

AVRO-3853: [Rust] Support Local timestamp logical types for Rust SDK

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java
lang/java/avro/src/test/java/org/apache/avro/SchemaNameValidatorTest.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
lang/java/ipc/src/test/java/org/apache/avro/TestSchema.java

As explain in [AVRO-3704](https://issues.apache.org/jira/browse/AVRO-3704), this is to allow, in Java, to choose name validation type. Currently, there is only a choice between no validation at all or a validation that accept accent, which is not accepted by official doc.
Here, we allow user to inject its own interface of name validation ; and, in same time, proposed 3 kind of implementation : 
- No validation : accept all names, like currently when option "no validation" is chosen.
- Utf validation : reproduce current java code and accept accent.
- Strict validation : follow documentation.
Unit test SchemaNameValidatorTest is added and can be run locally (like it is run in CI)
- …

AVRO-3704: name validator interface

---

lang/java/tools/src/main/java/org/apache/avro/tool/DataFileReadTool.java
lang/java/tools/src/main/java/org/apache/avro/tool/DataFileWriteTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileRepairTool.java

When `avro-tools fromjson` parameter `--schema-file` or `--schema` is used, it is unclear whether the tool actually picked up the provided schema.
Also a couple of code style warnings are fixed.

AVRO-3845: avro-tools: Add log entry when an external schema is used

---

doc/config.toml
doc/content/en/blog/releases/avro-1.11.2-released.md

Adding the most recent release to the website.
I haven't prioritised pushing the 1.11.2 documentation to the website, but it's a good idea to keep these release notes up to date in the repo!  I'll probably try and push the 1.11.2 and 1.11.3 docs at the same time.

[website] Add 1.11.2 to the blog

---

.github/workflows/test-lang-rust-clippy.yml
lang/rust/avro/src/schema.rs

AVRO-3855
This PR fixes an issue that clippy fails with Rust 1.65.0.
You can reproduce with:
```
cargo +1.65.0 clippy --all-targets --all-features -- -Dclippy::all
```
This PR also modifies `test-lang-rust-clippy.yml` to let the CI verify.
The command shown above succeeds.

AVRO-3855: [Rust] Fix clippy error with Rust 1.65.0

---

lang/csharp/build.sh

* Make sure that `build.sh clean` removes all bin and obj folders (AVRO-3859)

AVRO-3859: build.sh clean fails to remove some C# files

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/SchemaResolver.java
lang/java/compiler/src/test/idl/input/union.avdl
lang/java/compiler/src/test/idl/output/union.avpr
lang/java/idl/src/main/java/org/apache/avro/idl/SchemaResolver.java
lang/java/idl/src/test/idl/input/union.avdl
lang/java/idl/src/test/idl/output/union.avpr

[AVRO-2254](https://issues.apache.org/jira/browse/AVRO-2254) : 
Currently, SchemaResolver.unresolvedSchema method generate always schema with same name. The idea supply Zoltan Farkas is to generate another name each time.
So, the intent of this PR is just to transformed what is proposed in PR form.
unio.avdl + union.avpr add test on this.

AVRO-2254: [java] fix unresolved schema name

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java

[AVRO-2511](https://issues.apache.org/jira/browse/AVRO-2511) : 
DataFileWriter flush well data to disk only if using constructor with File, because it use internal class SyncableFileOutputStream, and writer activate "getFD().sync" in order to "Force all system buffers to synchronize with the underlying device".
Here, the idea is to do same when the DataFileWriter is initialized with FileOutputStream instance. 
This does still not cover all cases; but at least, this one is ok.
existing unit tests are enough.

AVRO-2511: add case for sync

---

.devcontainer/devcontainer.json
README.md

Avro's devcontainers build fails, it misses the context section because of the relative path to the Dockerfile. Also the extensions section showed a warning. All should be good now.
R: @martin-g

AVRO-3411: Fix devcontainers build

---

lang/perl/xt/interop.t

This PR aims to suppress a warning in interop-data-test for Perl SDK.
When we run `./build.sh test` or `lang/perl/build.sh interop-data-test`, we get the following message.
```
Name "Avro::DataFile::ValidCodec" used only once: possible typo
```
This warning message sometimes appears in the result of CI.
https://github.com/apache/avro/actions/runs/6255050186
Confirmed the warning message is disappeared by running `lang/perl/build.sh interop-data-test`.

Minor: [Perl][Test] Suppress warning in interop-data-test for Perl SDK

---

lang/rust/avro/src/schema.rs

AVRO-3862
This PR proposes to add `fn aliases` and `fn doc` to `Schema`.
Named types (Record, Enum and Fixed) have common attributes `name`, `aliases` and `doc`.
We have already have `fn name` in Schema so it's nice to have `fn aliases` and `fn doc` too.
Add new tests.

AVRO-3862: [Rust] Add aliases and doc methods to Schema in Rust SDK

---

.github/workflows/test-lang-rust-ci.yml

AVRO-3868
This PR proposes to add a consistency check between the doc comment in `avro/src/lib.rs` and `avro/README.md`.
AVRO-3849 added cargo-rdme so it's nice if we can check the consistency between them.
Done by GitHub Actions.

AVRO-3868: [Rust][CI] Check consistency between the doc comment in lib.rs and README.md

---

lang/perl/MANIFEST
lang/perl/Makefile.PL
lang/perl/build.sh
lang/py/build.sh

AVRO-3865
AVRO-3866
This PR proposes to change the build process of Perl and Python SDK not to copying `share/VERSION.txt` when we run `lang/perl/build.sh dist` or `lang/py/build.sh doc`.
Done by CI.

AVRO-3865, AVRO-3866: [Build][Perl][Python] Refer to share/VERSION.txt rather than copy it

---

lang/csharp/common.props

*Adding README.md to nupkg. (AVRO-3872)

AVRO-3872: Add README.md to nupkg

---

lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java
lang/java/avro/src/test/java/org/apache/avro/io/TestEncoders.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestCreateRandomFileTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestToTrevniTool.java

AVRO-3863
This PR proposes to delete temporary test data generated by tests for Java SDK.
Tests for Java SDK creates some test data, which are left even after tests finish.
```
ls -1 /tmp/*.avro
/tmp/junit1533190586260098046testMappedByteBuffer.avro
/tmp/junit3099644739767498712testMappedByteBuffer.avro
/tmp/junit4466003251314064556testMappedByteBuffer.avro
/tmp/junit4974226498248565286testMappedByteBuffer.avro
/tmp/junit6473921034404349045testMappedByteBuffer.avro
/tmp/junit8662732084083941415testMappedByteBuffer.avro
/tmp/random.avro
/tmp/testIgnoreSchemaValidationOnRead275054571669736256.avro
/tmp/testIgnoreSchemaValidationOnRead4615547521362396523.avro
/tmp/testIgnoreSchemaValidationOnRead4955268403025511495.avro
/tmp/testIgnoreSchemaValidationOnRead5426593551205571746.avro …
```

AVRO-3863: [Java] Delete temporary test data after tests finish

---

lang/java/avro/src/main/java/org/apache/avro/util/RandomData.java
lang/java/avro/src/test/java/org/apache/avro/util/TestRandomData.java

Update the `RandomData` generator to use `GenericData` (or subclasses). This allows to generate `GenericRecord`, `SpecificRecord` and reflected records as random data.
Jira issue: [AVRO-3660](https://issues.apache.org/jira/browse/AVRO-3660)
This change adds a test case:
* `org.apache.avro.util.TestRandomData`
- ~If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)~

AVRO-3660: [JAVA] Use data generator with RandomData

---

doc/content/en/docs/++version++/Specification/_index.md

Update the specification to explicitly state that names must be unique (within their scope), and that aliases are names too.
Please read and verify that the change matches reasonable expectations for implementations.
- ~If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)~

AVRO-3833: [Spec] Clarify usage of names and aliases

---

lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/main/java/org/apache/avro/util/TimePeriod.java
lang/java/avro/src/test/java/org/apache/avro/TestLogicalType.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericLogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/util/TimePeriodTest.java

Add logical type and conversion for ["Duration"](https://avro.apache.org/docs/1.11.0/spec.html#Duration), in the context of [AVRO-2123](https://issues.apache.org/jira/browse/AVRO-2123)
This is an alternative implementation for PR #1263.
Core in this change is a new implementation of [`java.time.TemporalAmount`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAmount.html), which combines functionality of both `java.time.Period` and `java.time.Duration`. This is needed to cleanly implement the logical type.
This change adds tests for all changed functionality:
- `org.apache.avro.util.TimePeriodTest`
- `org.apache.avro.TestLogicalType#durationExtendsFixed12`
- `org.apache.avro.generic.TestGenericLogicalTypes#readWriteDuration`
- …

AVRO-2123: Java duration logical type

---

doc/content/en/docs/++version++/Specification/_index.md
lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/TestBigDecimalConversion.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestRecordWithLogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificToFromByteArray.java
lang/java/avro/src/test/resources/TestRecordWithLogicalTypes.avsc
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj

[AVRO-3779](https://issues.apache.org/jira/browse/AVRO-3779) propose a new feature for big decimal conversion. Current decimal conversion require to anticipate precision and scale, and so, to know in advance approximative value of it.
This conversions, added to existing, allow to deal with completly random big decimal value. Value is store in byte buffer, completly non human readable, but keep the value.
This change added tests 'TestBigDecimalConversion' and can be verified as follows:
Run junit new test, or run all unit test of java module
- If yes, how is the feature documented? not documented

AVRO-3779: [java] any big decimal conversion

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/decimal.rs
lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

[AVRO-3779](https://issues.apache.org/jira/browse/AVRO-3779) : the idea is to propose a big-decimal type where scale is stored inside value, allowing flexible big decimal field in schema (as there is no need to anticipate scale, nor precision).
This PR is related to equivalent [for Java](https://github.com/apache/avro/pull/2282).
This change added unit tests and can be verified by running it
Still need to check if serialization is same as Java (or change);

AVRO-3779: using rust bigdecimal

---

lang/rust/avro/src/writer.rs

Fix AVRO-3881
This change added test that `Writer` always write user metadata even if the body is empty.

AVRO-3881: [rust] Writer should write user metadata even if the body is empty

---

.github/workflows/test-lang-rust-ci.yml

AVRO-3870
This PR aims to make the CI for Rust faster.
In the current master, there are something wrong about actions/cache in `test-lang-rust-ci.yml`.
First, a directory `target` is tend to be cached but the path is wrong. The correct path is `lang/rust/target`, not `~/target`.
https://github.com/apache/avro/actions/runs/6277247580/job/17048599038#step:22:2
Second, as of Rust 1.70.0, Cargo changes the way to download dependencies.
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#sparse-by-default-for-cratesio
So, it's better not to share the cache for `~/.cargo`
Done by CI.

AVRO-3870: [Rust][Build] Speed up CI for Rust

---

lang/rust/avro/src/schema.rs

AVRO-3609
* The collection of the custom attributes was wrong. It should collect only attributes which names are not in the predefined list
Found the bug while reviewing the code for AVRO-3886
* The old unit tests should still pass

AVRO-3609: [Rust] Remove wrong collection of custom attributes

---

lang/rust/avro/src/schema.rs

AVRO-3886
To support custom logical type, this PR add serialize attribute in enum, fixed, record schema.
* New unit tests are added
- If yes, how is the feature documented? not documented

 AVRO-3886: [Rust] Serialize attribute in schema to support custom logical type

---

lang/java/pom.xml

Apache Commons Compress 1.22 is vulnerable to CVE-2023-42503. Fix by using version 1.24.0.

fix CVE-2023-42503 by using Apache Commons Compress 1.24.0

---

lang/java/avro/src/main/java/org/apache/avro/io/DirectBinaryDecoder.java

The PR aims at removing redundant type casts from DirectBinaryDecoder. It makes code easier to read

AVRO-3891- [Java] Removed redundant casts from DirectBinaryDecoder

---

lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/writer.rs

AVRO-3894
* Use field's aliases when resolving the types::Value while serializing
* Also don't treat field's aliases as custom attributes.
* All old and new unit tests should pass

AVRO-3894: [Rust] Record field aliases are not taken into account when serializing

---

lang/rust/avro/examples/benchmark.rs
lang/rust/avro/src/de.rs
lang/rust/avro/src/decimal.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

fixing AVRO-3892
This PR:
1. support to resolve fixed from bytes
2. support to deserialize bytes, fixed, decimal in deserialize_any
1. For resolving fixed from bytes, I have add related test.
2. For deserializing bytes, fixed, decimal in deserialize_any, seems it don't have test for deserialize_any. If it required, we can consider to add test for whole deserialize_any. And actually I have test it in https://github.com/apache/iceberg-rust/pull/82 locally.

AVRO-3892: [Rust] Support to resolve fixed from bytes and deserialize bytes in deserialize_any

---

pom.xml

AVRO-3861
This PR fixes an issue that the RAT check fails if Python API docs built are in `lang/py/docs/build`.
You can reproduce this issue by the following steps.
1. Build Python API doc by `cd lang/py && ./build.sh doc`
2. Run `./build.sh dist`
Then, you can see the following error message.
```
[WARNING] Files with unapproved licenses:
lang/py/docs/build/html/_static/pygments.css
lang/py/docs/build/html/_static/basic.css
lang/py/docs/build/html/_static/doctools.js
lang/py/docs/build/html/_static/documentation_options.js
lang/py/docs/build/html/_static/language_data.js
lang/py/docs/build/html/_static/searchtools.js
lang/py/docs/build/html/_static/sphinx_highlight.js
lang/py/docs/build/html/_static/alabaster.css
lang/py/docs/build/html/_static/custom.css …
```

AVRO-3861: [Build] Add RAT exclusions for python docs

---

build.sh

This PR fixes a minor issue that `./build.sh docker` fails with the following error message.
```
---> Running in 24cdd401ee78
/bin/sh: 1: BUILDARCH: parameter not set or null
```
`BUILDARCH` is automatically set by setting an environment variable `DOCKER_BUILDKIT` to `1`.
Confirmed `./build.sh docker` succeeded.

Minor: Fix an error in running ./build.sh docker

---

lang/rust/avro/src/schema.rs

AVRO-3897
This change aims to fix an issue that the current Rust SDK accidentally allows invalid namespace in fully qualified name with `Name::new()`.
[The specification](https://avro.apache.org/docs/1.11.1/specification/#names) says about `Names` as follows
```
The name portion of the fullname of named types, record field names, and enum symbols must:
start with [A-Za-z_]
subsequently contain only [A-Za-z0-9_]
```
```
The null namespace may not be used in a dot-separated sequence of names. So the grammar for a namespace is:
<empty> | <name>[(<dot><name>)*]
```
So the following usages of `Name:::new()` should return a kind of `Err` but actually return `Ok`.
```
Name::new("ns.0.record1");
Name::new("ns..record1");
```
The root cause is that the regex `SCHEMA_NAME_R` is not correct.
So this …

AVRO-3897: [Rust] Disallow invalid namespace in fully qualified name for Rust SDK

---

lang/rust/avro/src/schema.rs
lang/rust/avro/tests/schema.rs

AVRO-3899
Log a warning for invalid logical (decimal) schema and use the underlying (base) schema
* Fix behavior while parsing a logical schema to behave as expected by the specification
* Update the existing unit tests 

AVRO-3899: [Rust] Invalid logical types should be ignored and treatedas the underlying type

---

lang/rust/avro/src/encode.rs
lang/rust/avro/tests/union_schema.rs

Demonstrate failing serde serialization and fix for non-trivial union types
cargo test  
None added.  We're a bit short in this area...

AVRO-3901: [Rust] Unit tests and impl for better union support

---

lang/rust/avro_derive/tests/derive.rs

AVRO-3905
* Fix the build with Rust 1.74.0
* The build and tests should pass

AVRO-3905: [Rust] Fix clippy error with Rust 1.74.0

---

doc/content/en/docs/++version++/Specification/_index.md
lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/TestBigDecimalConversion.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestRecordWithLogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificToFromByteArray.java
lang/java/avro/src/test/resources/TestRecordWithLogicalTypes.avsc
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj

Report [AVRO-3779](https://issues.apache.org/jira/browse/AVRO-3779) from main to 1.11 branch. New feature for big decimal conversion.
This conversions, added to existing, allow to deal with completly random big decimal value. Value is store in byte buffer, completly non human readable, but keep the value.
Same unit test as for main branch
- If yes, how is the feature documented? (docs)

AVRO-3779: big decimal to 1.11 branch

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/schema.rs

AVRO-3779
Depend on full version and only on the `std` feature
* Dependency management. 
* Build and tests should still pass

AVRO-3779: [Rust] Fully specify the dependency to bigdecimal crate

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java.yml
lang/csharp/README.md
lang/csharp/build.sh
lang/csharp/common.props
lang/csharp/src/apache/benchmark/Program.cs
lang/csharp/src/apache/test/AvroGen/AvroGenHelper.cs
lang/csharp/versions.props
share/docker/Dockerfile

*Add .NET 8.0 support (AVRO-3906)*
This change is already covered by existing tests.

AVRO-3906: Add .NET 8.0 support

---

lang/rust/Cargo.lock
lang/rust/avro_test_helper/Cargo.toml
lang/rust/avro_test_helper/src/lib.rs

AVRO-3910
* Better stacktraces when a test fails for any reason
* The change affects only the output of a failing test. There is no way to validate the change if all the tests pass

AVRO-3910: [Rust] Replace `color-backtrace` with `better-panic` for the tests

---

lang/rust/Cargo.toml
lang/rust/avro/Cargo.toml
lang/rust/avro_derive/Cargo.toml
lang/rust/avro_test_helper/Cargo.toml

AVRO-3915
* Non functional change. Move dependencies to the parent Cargo.toml
* Build and tests should still work

AVRO-3915: [Rust] Extract dependencies used by more than one member crates into the workspace

---

doc/content/en/docs/++version++/Specification/_index.md

[AVRO-3884](https://issues.apache.org/jira/browse/AVRO-3884)
Within certain industries nano timestamps are the common practice (finance for example), therefore I would propose adding this to the Avro spec as well.
Nanosecond datetime precision is needed in various fields and applications for several reasons, particularly in scenarios where extremely precise timing is critical. Here are a few reasons why nanosecond datetime precision is essential:
1. Financial Transactions: In the world of high-frequency trading and financial markets, nanosecond precision is necessary to accurately record and timestamp transactions. Small time differentials can result in significant advantages or losses in trading, making precise timestamps crucial for maintaining fairness and integrity in financial …

AVRO-3884: Add `local-timestamp-nanos` and `timestamp-nanos`

---

lang/rust/avro/README.md
lang/rust/avro/src/de.rs
lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

AVRO-3916
* Add support for the new logical types:
- `timestamp-nanos`
- `local-timestamp-nanos`
* New unit tests are added. All old ones should pass too!
- If yes, how is the feature documented? - the specification is updated

AVRO-3916: [Rust] Add TimestampNanos types

---

.github/labeler.yml
lang/rust/README.md

* Fix the `.github/labeler.yml` after the upgrade of action/labeler to v5 (https://github.com/apache/avro/pull/2632)
* The labeler workflow should pass without error for the syntax in `.github/labeler.yml`

Fix action/labeler to work with v5

---

lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/main/java/org/apache/avro/data/TimeConversions.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtoConversions.java

[AVRO-3914](https://issues.apache.org/jira/browse/AVRO-3914)
*(or)*
*(or)*
*(example:)*

AVRO-3914: Add nanos support for the Java SDK

---

lang/rust/avro/src/schema_compatibility.rs

- Take field aliases are not taken into account when calculating schema compatibility [AVRO-3917](https://issues.apache.org/jira/browse/AVRO-3917)
This change is partially covered by existing tests, such as `avro_3894_take_aliases_into_account_when_serializing_for_schema_compatibility`,  however it does not cover all the `aliases` use cases in a proper way. With the changes that I am adding then it will fix the issue and we will covered the missing uses cases. The new test added is take_aliases_into_account_for_schema_compatibility

AVRO-3917: [Rust] take field aliases into account when calculating schema compatibilities

---

.github/workflows/test-lang-ruby.yml
lang/ruby/test/test_logical_types.rb

Verify that Avro works with the latest version of Ruby, v3.3, to resolve [AVRO-3921](https://issues.apache.org/jira/browse/AVRO-3921).
- The change adds a version to the testing matrix.
- A test that was unstable in local testing with different Ruby versions is updated to use a more stable equivalent, specifying a Date directly instead of converting from Time to a Date

AVRO-3921: [ruby] Test against Ruby 3.3

---

lang/ruby/lib/avro/logical_types.rb
lang/ruby/test/random_data.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_logical_types.rb

Add support for the `timestamp-nanos` logical type to the Avro Ruby component ([AVRO-3922](https://issues.apache.org/jira/browse/AVRO-3922)).
As part of the change, the existing implementation for `timestamp-millis` and `timestamp-micros` is updated to be clearer and more consistent.
- Added tests that the follow the pattern of existing `timestamp-*` tests.
- Added support for generating `timestamp-nanos` values as part of random data utilities.
- Ran Ruby test to verify compatibility across supported Ruby versions.
- Does this pull request introduce a new feature? **yes**
- implements the new `timestamp-nanos` feature for Ruby
- If yes, how is the feature documented? **not applicable**
- `timestamp-nanos` is already documented
- …

AVRO-3922: [ruby] add timestamp-nanos support

---

lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/IDLMojo.java
lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestIDLMojo.java
lang/java/maven-plugin/src/test/resources/unit/idl/pom-incremental-compilation.xml

This change adds an up to date check to the maven plugin when generating Java classes from avro IDL. The reason for the change is to prevent unnecessary recompilation of the java source code in projects using the plugin.
- Added tests to verify that only missing files are regenerated when processing the avro IDL files.
- Altered existing tests to ensure that files are generated and not used from previous test runs.
Not sure if there are other scenarios that may be affected by this change.
This pull request does not introduce a new feature and is not documented.

AVRO-3889: [Java][Build] Maven IDL Generation Modification Check

---

lang/rust/avro/src/schema.rs
lang/rust/avro_derive/README.md

support to serialize the custom attributes in RecordField ,fixing AVRO-3920
*(or)*
*(or)*
*(example:)*
- If yes, …

AVRO-3920: Serialize custom attribute in RecordField

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/reader.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs
lang/rust/avro_derive/src/lib.rs

AVRO-3927
This PR fix AVRO-3927. 
In iceberg-rust, the user need to contain the custom attributes in array and map type. So to support custom attributes in array and map type, it adds array and map schema to contain the custom attributes in these type.
- add unit test in schema to test serialize custom attributes in map and array type.

AVRO-3927: [Rust]support map and array schema

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

AVRO-3928
* If the JSON number is bigger than i32::MIN and smaller than i32::MAX then convert to types::Value::Int, otherwise to types::Value::Long
* Old and new tests must pass
- If yes, how is the feature documented?  not documented

AVRO-3928: [Rust] Convert serde_json::Value::Number to apache_avro::types::Value::Int when possible

---

lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java

Small PR to fix a little error in `LogicalTypes.localTimestampNanos()` method, which wrongly returns the microseconds version.

AVRO-3931 Fix nanosecond timestamps support

---

LICENSE.txt
NOTICE.txt
build.sh

Ivy is not used anymore. A long time ago it was used on the Python side
https://github.com/apache/avro/blob/4f6eb207b1df2ff438d952e383041021f0275705/lang/py/build.xml
Same goes for `pyAntTasks`.
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by …

AVRO-3936: Clean up NOTICE file

---

lang/java/mapred/src/main/java/org/apache/avro/hadoop/file/HadoopCodecFactory.java
lang/java/mapred/src/test/java/org/apache/avro/hadoop/file/TestHadoopCodecFactory.java

Mapping org.apache.hadoop.io.ZStandardCodec to zstandard in 
HadoopCodecFactory
This change added tests 
- If yes, how is the feature documented? (JavaDocs)

AVRO-3930: Mapping org.apache.hadoop.io.ZStandardCodec to zstandard

---

lang/java/maven-plugin/pom.xml
lang/java/pom.xml

Updating to the latest maven-core makes we can drop the plexus-utils dependency
(see also https://github.com/apache/avro/pull/2619 )

Bump maven-core to 3.9.6 and drop needless plexus-utils

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/schema_compatibility.rs

This pull request adds support for schema compatibility checks on logical types in the apache-avro Rust crate, fixing [AVRO-3935](https://issues.apache.org/jira/projects/AVRO/issues/AVRO-3935)
This adds compatibility support for these types:
```
(Schema::TimeMicros, Schema::Int),
(Schema::TimestampMillis, Schema::Int),
(Schema::TimestampMicros, Schema::Int),
(Schema::TimestampNanos, Schema::Int),
(Schema::LocalTimestampMillis, Schema::Int),
(Schema::LocalTimestampMicros, Schema::Int),
(Schema::LocalTimestampNanos, Schema::Int),
(Schema::Date, Schema::Long),
(Schema::TimeMillis, Schema::Long),
```
(type that gets checked, primitive type it is compatible with), of course each type also being compatible with itself
run `cargo test` in …

AVRO-3935: Add support for compatibility check logical types in Rust Avro

---

doc/content/en/docs/++version++/Specification/_index.md

The concept of the local-timestamp is each value is a recording of what can be seen on a calendar and a clock hanging on the wall, for example, "1969-07-20 16:17:39". It can be decomposed into year, month, day, hour, minute, and seconds fields, but with no time zone information available, it does not correspond to any specific point in time. It is often used in legacy systems.
The example was 12 hours off. Thanks @tjwp and @martin-g for raising this in https://github.com/apache/avro/pull/2554/files/3b9d95b046231132b77f8b7f90857f0f97f37916#r1437935439 👍 
*(or)*
This …

AVRO-3884: Update `local-timestamp` example

---

.github/workflows/test-lang-rust-audit.yml
lang/rust/deny.toml

AVRO-3937
* Use `cargo-deny` to check the licenses of the dependencies
* A new CI job is added to run `cargo deny check`

AVRO-3937: [Rust]: Use cargo-deny to check the dependencies' licenses

---

lang/c++/api/Zigzag.hh

This PR fixes an undefined behaviour in ZigZag encoding as per AVRO-2717. It supersedes #920 

AVRO-2717: Fix UB in ZigZag encoding (pre C++-20)

---

lang/c++/MainPage.dox

Doxygen doesn't have a `\ul` tag and therefore it's currently displayed as a plain text on a web page. This commit removes it.

[C++] Fix main page for Doxygen.

---

lang/c++/build.sh

Instead, use `cmake --build`. It has been mentioned at least in cmake 3.2 documentation [1] which has been released in 2015. This will make a build process more flexible to people who want to use different build systems such as Ninja.
[1]: https://cmake.org/cmake/help/v3.2/manual/cmake.1.html
This change makes the build process slightly more flexible to people who use different build systems.

[C++] do not hardcode Unix Makefiles generator

---

lang/rust/avro/src/schema_compatibility.rs

Code refactor for `schema_compatibility` module. 
- Some unnecessary `else` clause have been removed
- Improve iterations with `find_map`
- Match case grouped for  `SchemaKind::TimeMicros, SchemaKind::TimestampNanos, SchemaKind::TimestampMillis, SchemaKind::TimestampMicros, SchemaKind::LocalTimestampMillis, SchemaKind::LocalTimestampMicros, SchemaKind::LocalTimestampNanos` for `check_writer_type`
Code cleanup and refactor without any test coverage

AVRO-3904: [Rust] schema_compatibility module refactor

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java

This pull request provides a fail-fast guard against the `private final` property `Schema.Parser.validate`, implementing AVRO-3938.
This change added the test `TestSchema.testParserNullValidate`.

AVRO-3938: [Java] Add null guards for Schema.Parser

---

lang/c++/CMakeLists.txt

* Bump the minimal supported cmake version to fix the warning
*  Fix the always-true if statement in CMake

[AVRO-3944] small CMake fixes

---

lang/c++/impl/FileStream.cc

This issue has been reported by `cppcheck`:
impl/FileStream.cc:52:5: style: Struct 'FileBufferCopyIn' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
FileBufferCopyIn(const char *filename) : h_(::CreateFileA(filename, GENERIC_READ, 0, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL)) {
^
impl/FileStream.cc:235:5: style: Struct 'FileBufferCopyOut' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
FileBufferCopyOut(const char *filename) : h_(::CreateFileA(filename, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL)) {
^
impl/FileStream.cc:62:10: style: The function 'seek' overrides a function in a base class but is not marked with a 'override' specifier. [missingOverride]
void seek(size_t len) {
^ …

[AVRO-3945] Add missing `override`

---

lang/c++/api/Node.hh
lang/c++/api/NodeImpl.hh
lang/c++/impl/Compiler.cc
lang/c++/impl/Node.cc
lang/c++/impl/NodeImpl.cc
lang/c++/impl/parsing/ResolvingDecoder.cc
lang/c++/test/CodecTests.cc
lang/c++/test/unittest.cc

This adds support to the C++ library for type and field aliases. It addresses AVRO-2397 and also AVRO-1496.
It is an evolution of the old PR #522. That sought to handle support by overriding the `Name` equality operator and also using `Name` for field names too. This struck me as too broad a change (do we want that notion of equality everywhere?) and not really appropriate for field aliases (where there is no namespace).
The handling is now in two places:
1) In `ResolvingGrammarGenerator`, writer types are now matched via the new `equalOrAliasedBy()` method
2) Field aliases are handled simply by allowing them to be looked up via `nameIndex()` - i.e. aliases are added there too, as well as the original names.
This change added tests and can be verified by running the C++ unit tests, …

AVRO-2397: [c++] Add support for type and field aliases

---

lang/c++/impl/FileStream.cc
lang/c++/impl/json/JsonDom.hh

This issue is reported by `cppcheck`:
impl/json/JsonDom.hh:79:5: style: Class 'Entity' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
Entity(Bool v, size_t line = 0) : type_(EntityType::Bool), value_(v), line_(line) {}
^
impl/json/JsonDom.hh:82:5: style: Class 'Entity' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
Entity(Long v, size_t line = 0) : type_(EntityType::Long), value_(v), line_(line) {}
^
impl/json/JsonDom.hh:85:5: style: Class 'Entity' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
Entity(Double v, size_t line = 0) : type_(EntityType::Double), value_(v), line_(line) {}
^
impl/json/JsonDom.hh:88:5: style: Class 'Entity' has a constructor with 1 argument that is not explicit. …

[AVRO-3945] Added missing `explicit`

---

lang/c++/test/CodecTests.cc

This should make the test cases a bit more readable.

[AVRO-2397] Use raw string literals in the test

---

lang/rust/avro/src/schema.rs

AVRO-3946
A Union schema without any variants will log an ERROR from now on. 
A Union schema with a single variant will log a WARN suggesting to drop the union.
* Better feedback to the developer via logging
* New unit tests have been added 

AVRO-3946: [Rust] Log warning/error for strange union types

---

lang/rust/avro/src/bigdecimal.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/tests/avro-3786.rs
lang/rust/avro/tests/big_decimal.rs

AVRO-3948
* Re-export `bigdecimal::BigDecimal` as `apache_avro::BigDecimal`. This way the dependency (`bigdecimal`) could be replaced with another if needed without breaking the API 
* Use `apache_avro::BigDecimal` in a new crate, i.e. in a IT test

AVRO-3948: [Rust] Re-export bigdecimal::BigDecimal as apache_avro::BigDecimal

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/decimal.rs

AVRO-3949
* Make it possible to (de)serialize `apache_avro::Decimal`
* Add new unit test

AVRO-3949: [Rust]: Add support for serde to apache_avro::Decimal

---

lang/rust/Cargo.lock
lang/rust/avro/Cargo.toml
lang/rust/avro/src/schema_compatibility.rs

This pull request add tests for `match_schemas` in schema_compatibility `AVRO-3950`
- This change is a trivial rework / code cleanup without any test coverage.
- Added test that validates `match_schemas
- This PR also shows that some code is never called in the funcion `match_schemas` as pointed in [AVRO-3950](https://issues.apache.org/jira/browse/AVRO-3950)
- This PR also shows that `nanos` types implementation are missing in [schema parse_complex](https://github.com/apache/avro/blob/main/lang/rust/avro/src/schema.rs#L1387), which is also not documented in the [avro spec](https://avro.apache.org/docs/1.11.1/specification/#logical-types)

AVRO-3950: [Rust] tests added for match_schemas in schema_compatibility

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs

This eliminates a blocking issue where code-gen throws while generating code for this enum:
```json
{
"symbols": [
"string",
"integer",
"float",
"boolean",
"list",
"dict",
"regex"
],
"name": "type",
"namespace": "com.example"
}
```
This change is a trivial rework without any test coverage. It eliminates an apparent misunderstanding of C# syntax. The above now correctly yields 
```csharp
public enum type
{
@string,
integer,
@float,
boolean,
list,
dict,
regex,
}
```

AVRO-3953: Prefixing enum member identifiers instead of throwing

---

lang/c/docs/index.txt
lang/c/examples/quickstop.c

This fixes typos in docs and examples
No new features are added

AVRO-3957: [C] Fix typos in docs and examples

---

lang/c/src/avro/refcount.h

macOS 10.12 deprecated the OSAtomic* functions. This removes the following warnings:
```
warning: 'OSAtomicIncrement32' is deprecated: first deprecated in macOS 10.12
warning: 'OSAtomicDecrement32' is deprecated: first deprecated in macOS 10.12
```
This change is already covered by existing tests, such as `make test`
No new features are added

AVRO-3959: [C] Avoid deprecated OSX atomic ops

---

lang/java/avro/src/main/java/org/apache/avro/JsonProperties.java
lang/java/avro/src/main/java/org/apache/avro/Protocol.java

Fix of NPE in Protocol#equals.
As of documentation, `namespace` is optional in `Protocol` and thus can be `null`. `Protocol#equals` contains direct dereference of `namespace`, which causes `NullPointerException` when comparing Protocols with `null` in `namespace`.
This MR fixes that.
- Does this pull request introduce a new feature? (yes / no) - No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) - not applicable

AVRO-3956: [Java] Fix NPE in Protocol#equals

---

lang/c++/build.sh
lang/c++/impl/json/JsonIO.cc
lang/c++/test/JsonTests.cc

This PR fixes AVRO-3945.
* [C++] Sort the order of unittests and add missing tests
* Add the missing bounds check in the loop
This issue was found by cppcheck:
impl/json/JsonIO.cc:319:66: warning: Missing bounds check for extra iterator increment in loop. [StlMissingComparison]
for (string::const_iterator it = s.begin(); it != s.end(); ++it) {
^
impl/json/JsonIO.cc:350:37: note: Missing bounds check for extra iterator increment in loop.
char c = *++it;
^
impl/json/JsonIO.cc:319:66: note: Missing bounds check for extra iterator increment in loop.
for (string::const_iterator it = s.begin(); it != s.end(); ++it) {
The original implementation contained a for-loop that incremented an
iterator on each iteration **and** if a backslash was found. This caused
a situtation when a malicious string …

[AVRO-3945] Add missing bounds check in the loop

---

lang/c/src/datum.c
lang/c/src/datum_equal.c
lang/c/src/datum_size.c
lang/c/src/datum_validate.c
lang/c/src/memoize.c
lang/c/src/schema.c
lang/c/src/st.c
lang/c/src/st.h

This removes the following warning:
```
avro/lang/c/src/st.c:240:13: warning: passing arguments to a function without a prototype is deprecated in all versions of C and is not
supported in C2x [-Wdeprecated-non-prototype]
hash_val = do_hash(key, table);
```
This change is already covered by existing tests, such as `make test`
No new features are added

AVRO-3960: [C] Fix st ANYARGS warning

---

lang/rust/avro/src/decode.rs

This pull request fixes AVRO-3964, changing panic to error.
- Does this pull request introduce a new feature? - No.
- If yes, how is the feature documented? - Not applicable.

AVRO-3964: [Rust] Fix out-of-bounds panic

---

doc/content/en/docs/++version++/Specification/_index.md
lang/csharp/src/apache/main/IO/BinaryDecoder.netstandard2.0.cs
lang/csharp/src/apache/main/IO/BinaryDecoder.notnetstandard2.0.cs
lang/csharp/src/apache/main/IO/BinaryEncoder.cs
lang/py/avro/io.py
lang/ruby/lib/avro/io.rb

AVRO-3841
This PR proposes to slightly change the specification of the way to encode float/double values.
The specification says about the way to encode float/double like as follows.
```
a float is written as 4 bytes. The float is converted into a 32-bit integer using a method equivalent to Java’s floatToIntBits and then encoded in little-endian format.
a double is written as 8 bytes. The double is converted into a 64-bit integer using a method equivalent to Java’s doubleToLongBits and then encoded in little-endian format.
```
But the actual implementation in Java uses `floatToRawIntBits`/`doubleToRawLongBits` rather than `floatToIntBits`/`doubleToLongBits`.
The they are different in the way to encode `NaN`.
`floatToIntBits`/`doubleToLongBits` don't distinguish between `NaN` and `-NaN` …

AVRO-3841: [Spec] Align the specification of the way to encode NaN to the actual implementations

---

lang/csharp/src/apache/main/Specific/SpecificWriter.cs
lang/csharp/src/apache/test/IO/JsonCodecTests.cs

*Fixing AVRO-3969*
- *Extended JsonEncoder tests*

AVRO-3969: Use WriteMapStart in WriteMap

---

lang/c++/impl/parsing/JsonCodec.cc
lang/c++/impl/parsing/Symbol.hh
lang/c++/test/CodecTests.cc

This PR has the fix for the wrong behavior of Json codec when record schema has no fields as reported by AVRO-3810
- Added a couple of codec tests to catch the error and to ensure that the fix indeed works

AVRO-3860: Fix for wrong behavior of Json codec when record schema has no fields

---

lang/rust/avro/src/schema_compatibility.rs

[AVRO-3970](https://issues.apache.org/jira/browse/AVRO-3970)
- Allow for proper compatibility checks between schemas featuring the `uuid` `logicalType`
- Extended existing compatibility test with `logicalType` `uuid` pairs

AVRO-3970: [Rust] Fix compatibility checks for UUID

---

lang/py/build.sh

This PR improves the experience of using build.sh for those who have a functional python environment, but don't already have tox installed.
This PR is just for local dev convenience. It does not add any new features.

AVRO-3952: Auto-install tox

---

.github/workflows/test-lang-c++-ARM.yml
.github/workflows/test-lang-c++.yml
lang/c++/CMakeLists.txt
lang/c++/api/Exception.hh
lang/c++/api/Node.hh
lang/c++/api/NodeImpl.hh
lang/c++/api/Stream.hh
lang/c++/api/Types.hh
lang/c++/api/Validator.hh
lang/c++/impl/BinaryDecoder.cc
lang/c++/impl/Compiler.cc
lang/c++/impl/DataFile.cc
lang/c++/impl/FileStream.cc
lang/c++/impl/Generic.cc
lang/c++/impl/GenericDatum.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/impl/NodeImpl.cc
lang/c++/impl/ValidSchema.cc
lang/c++/impl/Validator.cc
lang/c++/impl/json/JsonDom.cc
lang/c++/impl/json/JsonIO.cc
lang/c++/impl/json/JsonIO.hh
lang/c++/impl/parsing/JsonCodec.cc

This reduces the binary size quite significantly and doesn't require an additional object creation during exception throwing.
This change replaces `boost::format` with `fmt` library. It increases the readability and reduces the binary size quite significantly (on my machine I noticed `avrogencpp` being 27M with `boost::format` and 14M with `fmt`.

[AVRO-3967] Replace boost::format with fmt library

---

lang/java/avro/pom.xml
lang/java/avro/src/main/java/org/apache/avro/CanonicalSchemaFormatterFactory.java
lang/java/avro/src/main/java/org/apache/avro/JsonSchemaFormatter.java
lang/java/avro/src/main/java/org/apache/avro/JsonSchemaFormatterFactory.java
lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/SchemaFormatter.java
lang/java/avro/src/main/java/org/apache/avro/SchemaFormatterFactory.java
lang/java/avro/src/main/resources/META-INF/services/org.apache.avro.SchemaFormatterFactory
lang/java/avro/src/test/java/org/apache/avro/SchemaFormatterTest.java
lang/java/idl/src/main/java/org/apache/avro/idl/IdlSchemaFormatter.java
lang/java/idl/src/main/java/org/apache/avro/idl/IdlSchemaFormatterFactory.java
lang/java/idl/src/main/java/org/apache/avro/idl/IdlSchemaParser.java
lang/java/idl/src/main/java/org/apache/avro/util/IdlUtils.java
lang/java/idl/src/main/resources/META-INF/services/org.apache.avro.SchemaFormatterFactory
lang/java/idl/src/test/java/org/apache/avro/idl/IdlSchemaFormatterFactoryTest.java
lang/java/idl/src/test/java/org/apache/avro/util/IdlUtilsTest.java
lang/java/idl/src/test/resources/org/apache/avro/util/idl_utils_test_protocol.avdl
lang/java/idl/src/test/resources/org/apache/avro/util/idl_utils_test_schema.avdl

Add a `SchemaFormatter`, complementing the recently added `SchemaParser`.
- Check the new tests
- Review the changed IDL detection in `IdlSchemaParser`
- Does this pull request introduce a new feature? (**yes** / ~no~)
- If yes, how is the feature documented? (~not applicable~ / ~docs~ / **JavaDocs** / ~not documented~)

AVRO-3677: Add SchemaFormatter

---

lang/rust/avro/src/schema.rs
lang/rust/avro/src/ser.rs

NO-JIRA: Fix clippy errors from Rust 1.78

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/encode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/schema_compatibility.rs
lang/rust/avro/src/schema_equality.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

* Return an error if the default value's length is not the same as the specified size of a Fixed schema
* Old and new unit tests should pass

AVRO-3965: [Rust] Default values for fixed can be longer than size

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java

Improve the performance by removing synchronisation calls.
Running the `ReflectRecordTest` with 8 threads on a M2 Macbook pro
before change
```
Benchmark                  Mode  Cnt        Score        Error  Units
ReflectRecordTest.decode  thrpt    3  4,157,551.230 ± 831123.819  ops/s
ReflectRecordTest.encode  thrpt    3  4,926,092.511 ± 455798.533  ops/s
```
after
```
Benchmark                  Mode  Cnt         Score         Error  Units
ReflectRecordTest.decode  thrpt    3  12,221,568.529 ± 1308392.259  ops/s
ReflectRecordTest.encode  thrpt    3  12,569,201.802 ± 1898124.234  ops/s
```
`org.apache.avo.reflect` already tests this code
- If yes, how is …

AVRO-3987 [Java] Concurrency improvement for ReflectData FieldAccessors

---

doc/examples/example.py

https://github.com/apache/avro/pull/2932 fixed one problem, but there were others:
1. The existence of a "WTF" field in the record that is not in the schema, causing the code to fail. It's not reflected in [the actual docs](https://avro.apache.org/docs/1.11.1/getting-started-python/#serializing-and-deserializing-without-code-generation).
2. The use of text mode for writing binary data. (This is also correct in the Getting Started docs.)
3. Using strings for paths instead of Path objects. This is a minor thing, but a tidy practice.
4. The possibility of a crash causing a resource leak because our example doesn't use context managers to close the file. (This is also _incorrect_ in the Getting Started docs.)

modernize example python

---

lang/c++/impl/json/JsonIO.hh
lang/c++/test/JsonTests.cc

The JSON standard permits a solidus (`/`) to be escaped in strings, but does not require that it be escaped. Most JSON serializers used by other packages/languages do not escape solidus characters, so for consistency it would be nice if Avro also did not perform this useless escape.
This change is already covered by existing json tests, I've added additional test cases to ensure full coverage.
- If yes, how is the feature documented? N/A

[C++] Do not escape solidus in JSON output

---

lang/c++/CMakeLists.txt
lang/c++/README
lang/c++/api/NodeConcepts.hh
lang/c++/api/Validator.hh
lang/c++/impl/Compiler.cc
lang/c++/impl/NodeImpl.cc
lang/c++/impl/Resolver.cc
lang/c++/impl/parsing/ValidatingCodec.cc
lang/c++/test/AvrogencppTests.cc
lang/c++/test/CodecTests.cc
lang/c++/test/CommonsSchemasTests.cc
lang/c++/test/DataFileTests.cc
lang/c++/test/buffertest.cc
lang/c++/test/unittest.cc

`-Wall` is a good start, but really not sufficient, as it doesn't turn on many compiler warnings which help catch bugs. Turning on `-Wextra` lets the compiler check more things, reducing potential bugs.
- If yes, how is the feature documented? N/A

[C++] Turn on more compiler warnings

---

BUILD.md
lang/perl/Changes
lang/perl/Makefile.PL
lang/perl/bin/avro-to-json
lang/perl/lib/Avro/Protocol.pm
lang/perl/lib/Avro/Schema.pm

The JSON::MaybeXS library serves as a compatibility layer to allow users to select the JSON backend that matches their stack, rather than forcing them to install a specific one, while still benefiting from the performance boost of XS libraries if they are available.
Ticket: https://issues.apache.org/jira/browse/AVRO-3998
> This change is already covered by existing tests
This change changes one dependency for a different one with the same interface that serves as an intermediate layer. Existing tests that exercise JSON encoding / decoding verify that this is the case.
In particular, these tests exercise the modified code:
* `t/01_schema.t`
* `t/05_protocol.t`
The only part of the code that changed that is not covered by tests is the `avro-to-json` utility under `bin`.
- Does this pull …

AVRO-3998: Switch Perl library from JSON::XS to JSON::MaybeXS

---

lang/perl/lib/Avro/BinaryDecoder.pm
lang/perl/xt/schema.t

The test suite generated several warnings which could easily be avoided. The changes in this PR make sure the test suite can complete without triggering these scenarios.
Specifically, this PR includes the following changes:
* Do not exit a sub via `next` in `xt/schema.t`
* Add a message to an error raised by Avro::BinaryDecoder which lead to a warning when trying to stringify an undefined value.
Ticket: https://issues.apache.org/jira/browse/AVRO-3999
> This change is already covered by existing tests
The change only touches the test suite, and does not change any of the tested behaviours, only the behaviour of the tests.
- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

AVRO-3999 - Avoid warnings in Perl test suite

---

lang/c++/CMakeLists.txt
lang/c++/MainPage.dox
lang/c++/README
lang/c++/api/GenericDatum.hh
lang/c++/impl/avrogencpp.cc

[AVRO-3995](https://issues.apache.org/jira/browse/AVRO-3995) Update the CMake configuration to provide a useful error message when attempting to compile with an unsupported C++ standard version, and remove code which was `#ifdef`'d to be used only with C++ targets less than C++17.
As discussed in #2431, Avro has effectively required C++17 for nearly a year now, but it wasn't obvious to consumers.
- If yes, how is the feature documented? N/A

AVRO-3995 [C++] Require C++17 to compile Avro

---

lang/rust/avro/src/util.rs
lang/rust/avro_derive/src/lib.rs

* Allow a Clippy rule in code generated by Darling library so that the project builds with Rust 1.79.0 (https://github.com/TedDriggs/darling/pull/292)
* The build and tests should pass

NO-JIRA: [Rust] Fix Clippy errors from Rust 1.79.0

---

.github/workflows/test-lang-perl-ARM.yml
.github/workflows/test-lang-perl.yml
BUILD.md
lang/perl/Changes
lang/perl/MANIFEST
lang/perl/Makefile.PL
lang/perl/lib/Avro/BinaryDecoder.pm
lang/perl/t/03_bin_decode.t

Many of the changes in this pull request were made back in 2014 by John Karp for https://issues.apache.org/jira/browse/AVRO-1514, motivated by the fact that we were no longer constrained by targetting 5.8 (since we are currently targetting 5.10).
The main motivation here was to remove some dependencies that were no longer needed (like IO::String), add some dependencies that were not properly reported (Module::Install and friends as configure dependencies, Test::Pod as a test dependency, etc), and generally clean up some of the dependencies particularly in the Github actions, which were installing many Perl dependencies twice (once with apt, once with cpanm).
This change only affects the way dependencies are reported and installed, and is already covered by existing tests, such as …

AVRO-1514: Clean up Perl dependencies

---

lang/rust/avro/src/schema.rs

AVRO-4007
Apologies for the lack of a Jira issue; I'll link an issue as soon as my account request is approved.
Writing large amounts of avro data in rust is slow because (in my case) ~40% of total run time is spent in the function `UnionSchema::is_nullable`. The issue is that the `x == Schema::Null` invokes schema canonicalization which is
apparently somewhat slow. I've modified the method to use `match` instead and see a considerable performance improvement.
This change does not change any behavior and should be covered by existing tests

AVRO-4007: [rust] Faster `is_nullable` for UnionSchema

---

lang/perl/Changes
lang/perl/lib/Avro/DataFileReader.pm
lang/perl/t/04_datafile.t

As [the specification on Object Container Files][spec] states (emphasis added):
> All metadata properties that start with "avro." are reserved. The following file metadata properties are currently used:
>
>   * **avro.schema** contains the schema of objects stored in the file, as JSON data (required).
>   * **avro.codec** the name of the compression codec used to compress blocks, as a string. Implementations are required to support the following codecs: "null" and "deflate". _If codec is absent, it is assumed to be "null"_. The codecs are described with more detail below.
This change makes it so that the Perl implementation does not die when opening a container that does not contain an explicit codec in its metadata.
This change is inspired by one originally submitted in 2016 by SK Liew …

AVRO-1830 [Perl] Support containers without codec

---

doc/content/en/project/Privacy policy/_index.md

We have not used Google Analytics or other services related to privacy policy issues, so linking to Hadoop is not appropriate. Additionally, ASF also recommends against using Google Analytics. 
By the way, we should add links to LICENSE, Privacy, and Security on our homepage(now at https://avro.apache.org/project/), but I'm not sure which method everyone prefers. Maybe we could add an ASF menu to the navigation bar, or simply use text links at the bottom?

[website]Fix incorrect privacy link

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java

This change introduces the `org.apache.avro.SERIALIZABLE_PACKAGES` system property to enforce the security aspect of using `java-class` in a schema.
This change is already covered by existing tests, using the default trusted packages. I can add an additional test specifically for non trusted packages.
- If yes, how is the feature documented? The error message already explains how to use `org.apache.avro.SERIALIZABLE_PACKAGES` system property. Happy to add additional documentation if needed.

AVRO-3985: Add trusted packages support in SpecificData

---

lang/perl/Changes
lang/perl/lib/Avro/BinaryEncoder.pm
lang/perl/t/02_bin_encode.t

The check for valid int and long values was using the absolute value of the input, but in in two's complement arithmetic types the minimum and maximum values have different absolute values, which resulted in the minimum values for both types being rejected (because their absolute values are greater than those of the corresponding maxima).
This change fixes this and expands the binary encoder tests to check the ends of the accepted ranges.
The change in this PR is based on an original submission by John Karp submitted in 2014 to https://issues.apache.org/jira/browse/AVRO-1523.
This change extended `t/02_bin_encode.t` to add tests for these scenarios, for values just in and just out of the accepted ranges, on both the lower and upper bounds.
- Does this pull request introduce a new feature? …

AVRO-1523 [Perl] Fix valid range for int and long

---

lang/c++/CMakeLists.txt
lang/c++/impl/avrogencpp.cc
lang/c++/impl/parsing/ValidatingCodec.cc
lang/c++/jsonschemas/union_empty_record
lang/c++/test/AvrogencppTests.cc

I have a schema which contains a few empty records within a union to describe operations which don't require options (other records in the union do have fields). When generating code from the avro schema for an empty record like the following:
```json
{
"name": "Empty",
"fields": []
}
```
avrogencpp creates:
```cpp
template<> struct codec_traits<empty::Empty> {
static void encode(Encoder& e, const empty::Empty& v) {
}
static void decode(Decoder& d, empty::Empty& v) {
if (avro::ResolvingDecoder *rd =
dynamic_cast<avro::ResolvingDecoder *>(&d)) {
const std::vector<size_t> fo = rd->fieldOrder();
for (std::vector<size_t>::const_iterator it = fo.begin();
it != fo.end(); ++it) {
switch (*it) {
default:
break;
}
}
} else {
}
}
};
```
In a project with compiler warnings turned …

AVRO-3992 [C++] Fix compiler warnings in code generated by schema with empty record

---

lang/perl/Changes
lang/perl/lib/Avro/Schema.pm
lang/perl/t/01_schema.t

The code to validate data against a schema made some assumptions about the state of the data before validating, which resulted in some spurious warnings being raised when validating undefined values for some data types. This change, based on one submitted by John Karp back in 2014 for https://issues.apache.org/jira/browse/AVRO-1463, resolves this issue and expands the test suite to test the validation of undefined values for all primitive data types.
This change extends `t/01_schema.t` to include a test for validating undefined values for all primitive types.
Note that these tests do not _fail_ when warnings are raised, but simply exercise the code that used to issue warnings we want to avoid. Making the code fail on warnings, particularly as a global condition, risks making the test …

AVRO-1463 [Perl] Quietly validate undefined values

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java

Fix AVRO-4006: a bug in the DataFileReader / DataStreamReader that fails to update the internal state (the previous sync marker). This is needed to quickly read to the end of an Avro file, and only decode the last block.
This change updates an existing test case and adds a new one:
* `TestDataFile.testSyncDiscovery`
* `TestDataFile.testReadLastRecord`
Additionally, it can be verified as follows: whenever `DataFileStream#blockRemaining` becomes zero (`0`), the method `blockFinished()` should be called. This was not the case on all situations.

AVRO-4006: Fix block finish while reading data files

---

lang/perl/Changes
lang/perl/lib/Avro/BinaryEncoder.pm
lang/perl/lib/Avro/Schema.pm
lang/perl/t/01_schema.t

From John Karp's original description of the original issue at https://issues.apache.org/jira/browse/AVRO-1517:
> By default in Perl, a string is a sequence of bytes, values 0-255.
> However, if a Unicode character is included that cannot be represented
> with a single byte, the string gets 'upgraded' to a non-byte-based
> Unicode string allowing ordinals outside that range. When string
> operations are done with byte and non-byte Unicode strings, the result
> is always non-byte, with the byte string first 'upgraded'. Upgrading
> consists of utf8 encoding and setting a utf8 flag on the string. ('utf8'
> is a variant of UTF-8 used by Perl)
>
> The Perl Avro API is accepting these Unicode strings as-is for the
> 'bytes' type. This is a problem because
>
>   1. values >255 are not valid as …

AVRO-1517: [Perl] Encode UTF-8 strings as bytes

---

lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestIDLProtocolMojo.java

The modification time is on a second granularity, with our crazy fast Macbooks this now runs within the second. I think it would be good to just add a sleep of 1 second in here to make sure that the release verification passes locally:

Add sleep to make sure that the `getLastModifiedTime` is different

---

lang/perl/Changes
lang/perl/lib/Avro/BinaryEncoder.pm
lang/perl/lib/Avro/Schema.pm
lang/perl/t/02_bin_encode.t

This change fixes a long-standing issue with the binary encoding of boolean values. In particular, that while several "smart" values were accepted as valid boolean values by Avro::Schema (eg. "true" and "no"), Avro::BinaryEncoder encoded them as true or false depending on their truth value for Perl. This resulted in both of those examples being encoded as true, because for Perl any non-empty string is true.
This change makes it so that those values are accepted and properly handled, and handles other values that represent boolean values like JSON::PP::Boolean references and native Perl booleans (those that would be returned by eg. builtin::true).
This also includes a small but possibly breaking bugfix for the detection of valid boolean values in Avro::Schema, which was using a …

AVRO-1521 [Perl] Fix boolean encoding errors

---

lang/rust/avro/src/reader.rs
lang/rust/avro/src/schema.rs

This is an optimization that allows to eliminate schema re-resolving on every read() by caching resolved schema in the reader instance.
The change is not breaking the API.
The documentation changes are not needed.
This improves the performance by 25% for my use case.

AVRO-4010: [Rust] Avoid re-resolving schema on every read()

---

lang/rust/avro_derive/src/lib.rs

Issue AVRO-3687 seems to have been inappropriately closed since avro supports both default values on fields and enums. Enums primarily to prevent adding enum variant being a breaking schema change.
- Added test that validates that the derive macro explicitly sets the default value.
- Does this pull request introduce a new feature? No - it really fixes an existing issue

AVRO-3687 [Rust - avro_derive]: Add support for default enum values for rust derive macros

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java

Fix bug AVRO-3635, by disallowing skipping a negative number of bytes.
This is what all other implementations of this method do, and fixes infinite loops due to malicious data.
This change is covered by an updated existing test: `TestBinaryDecoder.skipGenerated`
Also, please verify if the "no-op on non-positive skip" is indeed common in other implementations.

AVRO-3635: Disallow skipping a negative amount of bytes

---

lang/rust/avro/src/error.rs
lang/rust/avro/src/types.rs
lang/rust/avro/src/writer.rs

This pull request is intended to improve the logging of value-schema mismatch errors when appending data to a `Writer`, so that it specifies which value and schema failed validation. This changes the current error: `Value does not match schema: Reason: Unsupported value-schema combination` to specify `Value {value} does not match schema {schema}`, bringing it in line with other error reporting in some of the other structs in the Rust implementation of Avro.
This aims to make it easier to debug the issue underlying AVRO-4014 and determine what is causing it.

AVRO-4014: [Rust] Add value and schema to ValidationWithReason error class

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java

AVRO-4016: Use SecureRandom for file sync markers
Currently, sync markers are generated using an MD5 hash on a random UUID and a timestamp, but the spec simply requires a "16-byte, randomly-generated sync marker".
This change creates just that.
To verify, all existing tests must continue working.

AVRO-4016: [Java] Use SecureRandom for file sync markers

---

lang/rust/avro_derive/src/lib.rs

Introduced-with: https://github.com/apache/avro/commit/2c484c638cbad34fd1a683a7812564972af751f4
Fixed upstream with: https://github.com/TedDriggs/darling/pull/296
* Revert a temporary workaround that allows a clippy check to pass
* The build should pass without any Clippy errors

[NO-JIRA]: [Rust] Revert a temporary workaround for a problem in Darling dependency

---

lang/rust/avro/src/bytes.rs
lang/rust/avro/src/lib.rs

This is a follow up of GH-3027 and adds support for (de)serialization of optional bytes.
- New unit tests have been added
- If yes, how is the feature documented? Rustdoc

AVRO-3631: [Rust] Efficient (de)serialization for optional bytes

---

pom.xml

This will avoid an error:
```
[INFO] Reactor Summary for Apache Avro Java 1.12.0-SNAPSHOT:
[INFO]
[INFO] Apache Avro Java ................................... SUCCESS [  2.043 s]
[INFO] Apache Avro ........................................ SUCCESS [  8.623 s]
[INFO] Apache Avro Android Compatibility .................. SUCCESS [  1.571 s]
[INFO] Apache Avro IDL .................................... SUCCESS [  5.358 s]
[INFO] Apache Avro Compiler ............................... SUCCESS [  3.918 s]
[INFO] Apache Avro Maven Plugin ........................... SUCCESS [  4.313 s]
[INFO] Apache Avro IPC .................................... SUCCESS [  5.228 s]
[INFO] Apache Avro IPC Jetty .............................. SUCCESS [  2.087 s]
[INFO] Apache Avro IPC Netty .............................. …
```

Minor: Set `javadoc` to legacymode

---

lang/rust/avro/README.md
lang/rust/avro/src/lib.rs

* Fixes the build with Rust 1.80.0 
* CI must pass

[NO JIRA] [Rust] Fix rustdoc formatting issues with Rust 1.80.0

---

lang/rust/deny.toml

New https://embarkstudios.github.io/cargo-deny/index.html release emits errors if the settings match the default ones ...
See https://github.com/EmbarkStudios/cargo-deny/pull/611
* CI only: Updates `deny.toml` to fix the errors of `cargo deny check` after an update of this cargo plugin
* The CI must pass

[NO_JIRA] [Rust] Fix deny.toml values

---

lang/rust/avro/src/types.rs
lang/rust/avro/tests/io.rs

As title
[[AVRO-4024] [Rust]: Fix default value support for double and float as "NaN", "Infinity" and "-Infinity" - ASF JIRA](https://issues.apache.org/jira/browse/AVRO-4024)
CI must pass

AVRO-4024: [Rust] support nan/inf/-inf as float/double default

---

share/docker/Dockerfile

* This PR fixes the "Docker tests" CI workflow
https://github.com/apache/avro/actions/runs/10283162033/job/28456409653
```
> [ 5/22] RUN export ARCH="$(dpkg --print-architecture)";   export LIBSSL_DEB="libssl1.1_1.1.1f-1ubuntu2.22_$ARCH.deb";   wget -q "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL_DEB" ||     wget -q "http://ports.ubuntu.com/ubuntu-ports/pool/main/o/openssl/$LIBSSL_DEB";   dpkg -i "$LIBSSL_DEB";   rm "$LIBSSL_DEB":
0.570 dpkg: error: cannot access archive 'libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb': No such file or directory
0.571 rm: cannot remove 'libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb': No such file or directory
```
It got bumped from 2.22 to 2.23 ...
TODO: We need to find a repo that keeps the old versions!
* …

[NO_JIRA] [CI] Fix the version of libssl1 Ubuntu package

---

lang/java/idl/src/test/idl/input/simple.avdl
lang/java/idl/src/test/idl/output/simple.avpr
share/idl_grammar/org/apache/avro/idl/Idl.g4

The IDL grammar mistakenly did not accept empty JSON objects.

AVRO-4027: Fix bug in JSON object syntax

---

lang/rust/avro/src/decode.rs
lang/rust/avro/src/error.rs
lang/rust/avro/src/schema.rs
lang/rust/avro/src/types.rs

AVRO-4029
The PR also fixes the parsing of `[local-]timestamp-nanos`.
* Better error messages with the problematic values
* Added new tests and updated some old ones.

AVRO-4029: [Rust] Improve the error messages related to value resolving

---

lang/rust/Cargo.lock
lang/rust/Cargo.toml
lang/rust/avro/Cargo.toml

Rust SDK 0.17.0 has been released with Avro 1.12.0
* Change the crate version from 0.17.0 to 0.18.0
* The CI checks must pass

[NO-JIRA] [Rust] Bump the version to 0.18.0

---

lang/c++/CMakeLists.txt

Here is the build log on FreeBSD.
```
[ 95% 96/101] cd /wrkdirs/usr/ports/devel/avro-cpp/work/.build && /wrkdirs/usr/ports/devel/avro-cpp/work/.build/avrogencpp -p - -i /wrkdirs/usr/ports/devel/avro-cpp/work/avro-cpp-1.12.0/jsonschemas/cpp_reserved_words -o cpp_reserved_words.hh -n cppres
[ 96% 97/101] /usr/local/libexec/ccache/c++ -DAVRO_VERSION=\"1.12.0\" -DFMT_HEADER_ONLY=1 -I/wrkdirs/usr/ports/devel/avro-cpp/work/avro-cpp-1.12.0/include/avro -I/wrkdirs/usr/ports/devel/avro-cpp/work/.build -I/wrkdirs/usr/ports/devel/avro-cpp/work/avro-cpp-1.12.0/include -isystem /usr/local/include -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing   -std=c++17 -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing   -std=c++17  -DNDEBUG -std=gnu++17 -MD -MT …
```

Fix build when cpp_reserved_words_union_typedef.hh is not ready

---

lang/rust/avro/src/codec.rs
lang/rust/avro/src/lib.rs
lang/rust/avro/src/reader.rs
lang/rust/avro/src/writer.rs
lang/rust/avro/tests/codecs.rs

This PR adds support for picking a custom compression level for the `Zstandard` codec. This change does not remove the `Zstandard` codec variant in order to keep backwards compatibility and a slightly simpler interface for the default case.
Added new tests:
- Compression and decompression, analogous to other codec tests.
- A test that makes sure that the codec is converted to a string as `zstandard` (i.e. same as `Zstandard` codec) as this is still the same codec.
- Does this pull request introduce a new feature? 
Yes.
- If yes, how is the feature documented?
Simple description available in `cargo`-generated documentation. Validated it using `cargo doc --open --no-deps --all-features`.

AVRO-4032: [Rust] Make it possible to set custom compression level for all codec that support it

---

lang/rust/avro/src/writer.rs
lang/rust/avro/tests/append_to_existing.rs

This PR allows for more flexibility when creating new avro writers with the goal of appending to an existing file. Current functions are convenient wrappers but do not allow fully configuring the parameters for the new writer when it's meant for appending to an existing file.
Some more context pertaining to my particular use case: parameters such as block size become quite important when using compression so being able to append with a new writer using the same, larger-than-default block size the first writer used can make a significant difference for compression.
Added a new test.
- Does this pull request introduce a new feature?
Yes, now it is possible to create Writer for appending with any other parameter available when creating the initial writer.
- If yes, how is the feature …

AVRO-4031: [Rust]  builder header

---

.github/workflows/test-docker.yml
lang/js/package-lock.json
share/docker/Dockerfile

Fix `docker-test` for the 1.11.x branch

---

lang/c++/impl/Compiler.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/include/avro/LogicalType.hh
lang/c++/include/avro/Node.hh
lang/c++/test/SchemaTests.cc

AVRO-4037
This pull request adds support of the following logical types as defined since specification 1.10.0:
- local-timestamp-millis
- local-timestamp-micros

AVRO-4037: [C++] Add local-timestamp-millis, local-timestamp-micros logical types

---

lang/c++/CMakeLists.txt
lang/c++/impl/avrogencpp.cc
lang/c++/jsonschemas/big_union
lang/c++/test/AvrogencppTests.cc

[AVRO-3984](https://issues.apache.org/jira/browse/AVRO-3984)
This pull request should improve the code generated by avrogencpp for union types. The improvements are:
Previously the getters for a union branch returned a value:
std::map<std::string, float > get_map() const;
This lead to a complete copy of the map, which may be really expensive depending on the use case.
In this pull request the getter return a reference instead, which allows the user to choose if a copy should be done.
const std::map<std::string, float >& get_map() const;
Additionally a getter is created, that returns a mutable reference. This can be useful if a value needs to be added to a map or array.
std::map<std::string, int32_t >& get_map();
Currently the setter of a union takes a reference to the value that should be …

AVRO-3984 [C++] Improve code generated for unions

---

.github/workflows/labeler.yml
lang/c++/impl/Compiler.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/include/avro/LogicalType.hh
lang/c++/test/SchemaTests.cc

AVRO-4038
This pull request adds support of the following logical types as defined since specification 1.12.0:
- timestamp-nanos
- local-timestamp-nanos

AVRO-4038: [C++] Add local-timestamp-nanos and timestamp-nanos

---

doc/config.toml
doc/content/en/docs/++version++/IDL Language/_index.md
doc/content/en/docs/1.12.0/IDL Language/_index.md
doc/go.mod

Follow-up of https://github.com/apache/avro/pull/3092
* Fix the build of the docs: https://github.com/apache/avro/actions/runs/10488520943/job/29051171217
* The new Github Actions workflow for building the docs should pass
https://github.com/apache/avro/actions/workflows/deploy-docs.yml

[NO-JIRA] Docs build fixes

---

.github/workflows/deploy-docs.yml
lang/c/build.sh

Copy the improvements from https://github.com/apache/avro/pull/2187 to current `main`
*(or)*
*(or)*
*(example:)*
- …

Build the SDKs apidocs and copy them to the website

---

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java
lang/java/avro/src/main/java/org/apache/avro/util/internal/JacksonUtils.java

ObjectMapper is an expensive, thread-safe object. By creating just one instance, we can avoid unnecessary recalculations.
This change is already covered by existing tests, such as `TestJacksonUtils` or `TestSchemaBuilder`
- Does this pull request introduce a new feature? (yes / no) - No

AVRO-4042: [java] Precache ObjectMapper to avoid recreation

---

doc/content/en/docs/++version++/Specification/_index.md

AVRO-3155
Default values have no special purpose for maps and arrays, and are only
valid for record fields and enums.
Having it in the examples is confusing, as people might have expectations
around it behaving in a certain way.
In the Java and Rust implementation, a default value listed here
will be packed into the custom props and attributes payloads, and
do not need to be of the same type; i.e., `default: "no default"` would
be valid.
Other implementations just ignore it and won't round trip it, for example:
```js
MapType.prototype.toJSON = function () {
return {type: 'map', values: this._values};
};
```
I wrote a small test in rust to validate my understanding; unfortunately
using an assertion on Map would be confusing as the instance
for `Eq` for `MapSchema` ignores the `attributes` …

AVRO-3155: [docs] Remove 'default' from map and array examples (and add to enum).

---

doc/content/en/docs/++version++/Specification/_index.md

> Exceptions are made for typos in JavaDoc or documentation files, which need no JIRA issue.
Fixes a typo.
After the docs have been deployed, the typo should be gone from https://avro.apache.org/docs/++version++/specification/#object-container-files

docs: fix typo

---

lang/php/lib/Datum/AvroIODatumReader.php
lang/php/test/IODatumReaderTest.php

This pull request fixes the behavior that values are accidentially overwritten by default values from the reader's schema.
Detailed description: AVRO-4046
- Added test that serializes some data and ensures that the data survives deserialization.
Issues: AVRO-4046

AVRO-4046: [PHP] Handling of default values

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/main/java/org/apache/avro/util/MapUtil.java

* Make overall Avro package smaller and faster

AVRO-4050: Deprecate MapUtil computeIfAbsent

---

lang/java/avro/src/main/java/org/apache/avro/io/BufferedBinaryEncoder.java

* Remove superfluous code: make fewer calls in execution path

AVRO-4052: Inline BufferedBinaryEncoder writeZero method

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

* Improves performance of testing Strings for equality

AVRO-4049: Use JDK Arrays equal to test if two UTF8 strings are equal

---

lang/c++/impl/DataFile.cc
lang/c++/impl/Node.cc
lang/c++/impl/parsing/Symbol.hh

Example of changed code to remove error.
`int32_t checksum = crc();`
to
`auto checksum = crc();`
`error: conversion from ‘boost::crc_optimal<32, 79764919, 4294967295, 4294967295, true, true>::value_type’ {aka ‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Werror=conversion]`
Further errors not related to avro cmake but using a meson build port was missing <algorithm> header in some files such that std::find and std::find_if could not be found. Thought to include them in PR. 
These changes passed ./build.sh test
Thanks for the code!
Sorry for the informal request a bit busy but wanted to give back.

[C++] g++ (GCC) 14.2.1 20240910 fails to compile due to -Werror=conversion

---

lang/c++/test/SchemaTests.cc

[AVRO-4058](https://issues.apache.org/jira/browse/AVRO-4058) (Preparation)
Migrated the vast majority of json schema definitions to raw string literals to improve their readability. Notable exception are schemas heavily relying on escaped characters that test the json after compilation are compact
Improve readability of json schemas in SchemaTests.cc (Similar work was already done in CodecTests.cc in PR https://github.com/apache/avro/pull/2762)
I did this work in preparation of adding some new tests in the context of [AVRO-4058](https://issues.apache.org/jira/browse/AVRO-4058)
- If yes, how is the feature documented? …

[C++] Improve readability of SchemaTests 

---

lang/c++/impl/Compiler.cc
lang/c++/impl/NodeImpl.cc
lang/c++/include/avro/NodeImpl.hh
lang/c++/test/SchemaTests.cc

[AVRO-4058](https://issues.apache.org/jira/browse/AVRO-4058)
Other languages (i.e. Java) allow adding custom attributes in the schema of an array while the C++ implementation does not. The sparse spec states to allow all custom attributes ("Attributes not defined in this document are permitted as metadata, but must not affect the format of serialized data") and other projects using avro (i.e. Iceberg) depend on custom attributes in arrays.
This PR allows adding custom attributes to arrays.
Run SchemaTests, I added a single additional test case in testRoundTrip 
- Does this pull request introduce a new feature?  no

[C++] AVRO-4058: Allow custom attributes in arrays

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/io/BinaryData.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificFixed.java
lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

* This pull request improves read performance by using JDK byte compare functionality, fixing AVRO-4045.
* This change is a trivial rework / code cleanup without any test coverage.

AVRO-4045: Use JDK compare for byte arrays

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryData.java
lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java
lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java

* This pull request improves file read performance by not re-calculating hashcode for empty string, fixing AVRO-4061.
This change added unit tests.

AVRO-4061: Use Default Value of 1 For UTF8 Hash

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java

* This pull request improves simplifies the code and removes unnecessary code, fixing AVRO-4066

AVRO-4066: Use JDK isBlank Method

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/enum.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/fixed.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/protocol.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/compiler/src/test/resources/simple_record.avsc
lang/java/ipc/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

AVRO-4053: Improve doc consistency in SpecificRecord
Fixes inconsistencies in generated doc comments.
This change adds tests and can be verified as follows:
1. Verify the updates velocity templates
2. Check that the updated file `simple_record.avsc` (used by many tests) could but does not cause problems
3. Review the new test `docsAreEscaped_avro4053` in `org.apache.avro.compiler.specific.TestSpecificCompiler`

AVRO-4053: doc consistency in velocity templates

---

lang/java/avro/src/main/java/org/apache/avro/io/DatumWriter.java
lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificData.java

* This pull request improves usability by providing a convenience way to turn a datum into a byte array, fixing AVRO-4073
This change added tests.

AVRO-4073: Create Convenience toBytes Method for Datum Writer

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

* This pull request improves file read performance by not needlessly copying buffered data, fixing AVRO-4065.

AVRO-4065: Do Not Copy Array Contents when Expanding UTF-8 Arrays

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryEncoder.java

* This pull request improves file write performance by buffering ASCII String, fixing AVRO-4074.

AVRO-4074: Optimization for Serializing ASCII Strings

---

lang/java/avro/src/main/java/org/apache/avro/SystemLimitException.java
lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java

* This pull request improves file read performance by skipping needless checks, fixing AVRO-4070.

AVRO-4070: Optimize Check Max Collection Length for New Collections

---

doc/content/en/docs/++version++/Getting started (Java)/_index.md
doc/content/en/docs/++version++/Getting started (Python)/_index.md
doc/content/en/docs/++version++/IDL Language/_index.md
doc/content/en/docs/++version++/MapReduce guide/_index.md
doc/content/en/docs/++version++/SASL profile/_index.md
doc/content/en/docs/++version++/Specification/_index.md

Reported at https://github.com/apache/avro-rs/issues/22 
Discussed at https://github.com/apache/avro-rs/pull/20#issuecomment-2409096820
* Add more aliases from `++version++` to `current` in the Hugo based docs
* `cd .../avro/doc`
* Start the website locally: `hugo server --buildDrafts --buildFuture --bind 0.0.0.0`
* in a browser navigate to http://localhost:1313/docs/current/specification/#schema-resolution

chore: docs: Add more aliases for `++version++` to `current`

---

lang/csharp/src/apache/main/IO/JsonDecoder.cs
lang/csharp/src/apache/test/IO/JsonCodecTests.cs

Fixing AVRO-4075 where the JsonDecoder underlying package Newtonsoft was mixing strings with Date types when supplied with an ISO format.
Supplying an ISO format string for example: 1900-01-01T00:00:00Z in an Avro type string while reading with a JsonDecoder
- Does this pull request introduce a new feature? (yes / no) **no**
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) **not applicable**

AVRO-4075: [csharp] Fix JsonDecoder string type failing to decode ISO string date

---

.github/workflows/deploy-docs.yml
.github/workflows/test-lang-csharp-ARM.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java.yml
.github/workflows/test-lang-js.yml
share/docker/Dockerfile
share/docker/run-tests.sh

Drop more pypy3.9 usages
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / …

ci: Fix the CI builds after Github Actions moving ubuntu-latest to 24.04

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/test-lang-csharp-ARM.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java.yml
lang/csharp/README.md
lang/csharp/common.props
lang/csharp/src/apache/benchmark/Program.cs
share/docker/Dockerfile

AVRO-4079: Remove C# netcoreapp3.1 and 5.0 support

---

lang/c++/test/DataFileTests.cc

This pull request fix windows test failure, fixing AVRO-4085
This change is a trivial rework / code cleanup without that fixing test coverage.

[AVRO-4085][C++] Fix file size extraction error on windows platform

---

lang/csharp/src/apache/main/Schema/Schema.cs
lang/csharp/src/apache/test/Schema/SchemaTests.cs

Currently the C# Avro library does not have a way to parse a new schema that refers to named schemas that have been previously parsed.
The equivalent in the Java Avro library is to construct an instance of `Schema.Parser` and to use the same parser instance to parse the referenced schemas before the referring schema.
The change that is needed is to simply modify the following method in `Schema.cs` from internal to public:
```
internal static Schema Parse(string json, SchemaNames names, string encspace)
```
Without this change, tools that allow Avro schemas to reference one another, such as the [Confluent Schema Registry](https://github.com/confluentinc/schema-registry), cannot interoperate well with C# applications. …

AVRO 4091: [C#] Allow previously parsed schemas to be referenced when parsing a schema

---

lang/c++/impl/CustomAttributes.cc
lang/c++/include/avro/CustomAttributes.hh
lang/c++/test/unittest.cc

This is part of an effort to remove boost dependency as much as possible and replace it with standard library.

AVRO-4096: [C++] Replace boost::optional with std::optional

---

lang/c++/impl/json/JsonDom.cc
lang/c++/impl/json/JsonDom.hh
lang/c++/impl/parsing/Symbol.hh

This pull request reduces the usage of boost by replacing `boost::any` and `boost::tuple` with `std::any` and `std::tuple` respectively, fixing AVRO-4097
- If yes, how is the feature documented? **not applicable**

AVRO-4097: Replace boost::any with std::any; boost::tuple with std::tuple

---

lang/c++/examples/imaginary.hh
lang/c++/impl/Resolver.cc
lang/c++/impl/json/JsonIO.hh
lang/c++/impl/parsing/ValidatingCodec.cc
lang/c++/include/avro/DataFile.hh
lang/c++/include/avro/Generic.hh
lang/c++/include/avro/Layout.hh
lang/c++/include/avro/Node.hh
lang/c++/include/avro/Parser.hh
lang/c++/include/avro/Reader.hh
lang/c++/include/avro/Resolver.hh
lang/c++/include/avro/ResolverSchema.hh
lang/c++/include/avro/ResolvingReader.hh
lang/c++/include/avro/Serializer.hh
lang/c++/include/avro/Stream.hh
lang/c++/include/avro/Validator.hh
lang/c++/include/avro/Writer.hh
lang/c++/include/avro/buffer/BufferReader.hh
lang/c++/include/avro/buffer/detail/BufferDetail.hh

Remove boost::noncopyable and boost::any

AVRO-4100: [C++] Remove boost::noncopyable and boost::any

---

lang/c++/CMakeLists.txt

AVRO_BUILD_EXECUTABLES controls whether to build precompile and avrogencpp AVRO_BUILD_TESTS controls whether to build unittest
The two options default to ON conforming the original behaviour.
This is needed because for libraries like iceberg-cpp, we don't need to build the unittest and executable.

[C++] add two cmake options to make it easier to integrate avro c++

---

.github/workflows/test-lang-js.yml
lang/c++/impl/DataFile.cc
lang/c++/include/avro/DataFile.hh
lang/c++/test/CommonsSchemasTests.cc
lang/c++/test/DataFileTests.cc

On windows datafile reader does not close resource handle. It blocks file deletion, fixing AVRO-4086
This change is already covered by existing tests, such as DataFileTests and CommonSchemaTests.
I have also add tests on manipulation after closed reader.

[AVRO-4086][C++] Fix missing data file reader close handle on windows

---

doc/content/en/docs/++version++/Specification/_index.md
lang/c++/impl/Compiler.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/include/avro/LogicalType.hh
lang/c++/test/SchemaTests.cc

This pull request add support of c++ `big-decimal` logical type in Avro serializer/deserializer methods, related to AVRO-3779.
- Tests of schema serialization/deserialization with valid and invalid declarations.
- Specific validation on bad schema with precision and scale declaration.
- If yes, how is the feature documented? (update of `big-decimal` logical type specification)

[AVRO-4081][C++] Add big decimal support and update documentation

---

lang/c++/impl/json/JsonIO.hh
lang/c++/include/avro/DataFile.hh
lang/c++/include/avro/Generic.hh
lang/c++/include/avro/Specific.hh
lang/c++/include/avro/Stream.hh
lang/c++/include/avro/buffer/detail/BufferDetail.hh

Remove a set of boost includes.

AVRO-4101: [C++] Remove boost::{blank,function,shared_ptr,static_assert,utility}

---

lang/c++/include/avro/buffer/detail/BufferDetail.hh

AVRO-4102: [C++] Remove boost::shared_array

---

lang/c++/impl/avrogencpp.cc
lang/c++/jsonschemas/bigrecord

As requested by AVRO-4035, this uses the `doc` field from the avro schema when generating code.
That is, this schema:
```json
{
"doc": "Top level Doc.\nWith multiple lines",
"name": "RootRecord",
"fields": [
{
"name": "mylong",
"doc": "mylong field doc.",
"type": "long"
},
```
Generates the following when run through `avrogencpp`
```c++
// Top level Doc.
// With multiple lines
struct RootRecord {
typedef _bigrecord_Union__0__ myunion_t;
typedef _bigrecord_Union__1__ anotherunion_t;
// mylong field doc.
int64_t mylong;
```
Note: I decided to use line comments (`//`) rather than block comments (`/*` or `/**`) as they make the logic for handling escapes simpler, and make it easy to properly indent the entire comment when generating comments for record fields.
This change is …

AVRO-4035 [C++] Add doc strings to generated classes

---

lang/c++/impl/avrogencpp.cc
lang/c++/impl/json/JsonIO.hh
lang/c++/impl/parsing/JsonCodec.cc

Remove boost::lexical_cast and boost::math

AVRO-4105: [C++] Remove boost::lexical_cast and boost::math

---

lang/java/avro/src/main/java/org/apache/avro/io/DecoderFactory.java

The extra noise is from the _spotless_ plugin.

[Java] Clarify thread safety of Decoders returned by DecoderFactory.

---

lang/c++/impl/DataFile.cc
lang/c++/impl/avrogencpp.cc
lang/c++/include/avro/Specific.hh

AVRO-4106: [C++] Remove boost::random

---

lang/c++/impl/Compiler.cc
lang/c++/impl/avrogencpp.cc

AVRO-4107: [C++] Remove boost::algorithm

---

lang/c++/impl/avrogencpp.cc

AVRO-4109: [C++] Remove boost::program_options

---

.github/workflows/test-lang-c++-ARM.yml
.github/workflows/test-lang-c++.yml
lang/c++/CMakeLists.txt
lang/c++/impl/DataFile.cc
lang/c++/include/avro/DataFile.hh

The Boost header files below are used for zlib/gzip codecs.
```
boost/crc.hpp
boost/iostreams/device/file.hpp
boost/iostreams/filter/gzip.hpp
boost/iostreams/filter/zlib.hpp
boost/iostreams/filtering_stream.hpp
```
It can be replaced by the official zlib library: https://zlib.net/
This change is already covered by existing tests, such as *CodecTests.cc*.

AVRO-4111: [C++] Replace boost::iostreams with zlib library

---

lang/c++/CMakeLists.txt
lang/c++/test/DataFileTests.cc
lang/c++/test/StreamTests.cc

- Added a CMake option `AVRO_USE_BOOST` to indicate whether boost is required for non-test targets.
- Do not find Boost library when test is not required to build.
- Manually verified that Boost is not found.
- Pass CIs.

AVRO-4112: [C++][CMake] Do not find Boost when test is not built

---

lang/java/avro/src/main/java/org/apache/avro/generic/PrimitivesArrays.java
lang/java/avro/src/test/java/org/apache/avro/generic/PrimitivesArraysTest.java

Fixing [AVRO-4108](https://issues.apache.org/jira/browse/AVRO-4108)
This change added a single test which simulates the issue `testDoubleArrayPreservesPrecisionForNonFloatRepresentableValues` which creates a double value that cannot be represented by float. It adds it to the array and then verifies that it still contains the double value. 
This is a bug fix so no documentation needed. I added comments in the test to explain the issue.

AVRO-2108: [Java] DoubleArray converts double to float on array add

---

lang/c++/CMakeLists.txt
lang/c++/impl/avrogencpp.cc

AVRO-4113: [c++] Don't generate tests files if test are not requested

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java
lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java

* This pull request improves file read performance by using the JDK hashcode implementation, fixing AVRO-4060.*

AVRO-4060: Use JDK to Hash Byte Array in UTF8

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryEncoder.java

As part of my earlier work for AVRO-4074, I introduced a buffer to store strings during serialization. I chose a buffer size of 128 bytes somewhat arbitrarily: it is a power of 2. However, upon further reflection, a value of 63 is a better partition. A string is decomposed into two fields:
> a string is encoded as a long followed by that many bytes of UTF-8 encoded character data.
For the binary format of Avro:
> int and long values are written using [variable-length](https://lucene.apache.org/java/3_5_0/fileformats.html#VInt) [zig-zag](https://code.google.com/apis/protocolbuffers/docs/encoding.html#types) coding.
63 bytes is the largest ASCII string that can be written using only a single byte for the variable-length size. This makes a more sane boundary for the upper limit of this …

[Java] Reduce buffer size for ASCII string optimization to 63 bytes

---

lang/c++/impl/Compiler.cc
lang/c++/impl/json/JsonDom.cc
lang/c++/impl/json/JsonDom.hh
lang/c++/test/SchemaTests.cc

Fix a bug where Json schemas which contained non string values for unreserved keys would not work with avrocpp.
The same schema works in python, java, and c implementations so this particularly affects c++ users.
Added test cases to check different types to extra attributes.
- Does this pull request introduce a new feature? (yes / no) no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable

AVRO-4117: [c++] Allow non string values for non reserved keys in schema

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java

Prevents class with empty Java package being trusted by SpecificDatumReader.
```
"package is not here"
import java. ...
import org. ....
public class Foot {
...
}
```
For example the above class Foo used as a key or a value would be considered as trusted because in current code
`clazz.getPackage()` returns null for Foo.class, which bypassed `if (!found) then throw exception` check.
PR moves `if (!found) then throw exception` bellow `if (thePackage != null) { ... }` statement.
It complements AVRO-3985.

AVRO-3985: Prevent class with empty Java package being trusted by SpecificDatumReader

---

BUILD.md

Fixes broken links in BUILD.md due to incorrect markdown syntax.

Fix markdown links in BUILD.md

---

lang/php/lib/Datum/AvroIOBinaryDecoder.php
lang/php/lib/Datum/AvroIOBinaryEncoder.php
lang/php/test/DatumIOTest.php

This PR fixes PHP long encoding on 64bit platforms as the current implementation does not support longs bigger than `1<<61`.
I've added new tests to cover more scenarios and uncommented existing tests.
https://issues.apache.org/jira/browse/AVRO-4115

AVRO-4115: [PHP] Fix long encoding

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java

Since https://github.com/FasterXML/jackson-core/issues/919 jackson now requires to close its `JsonGenerator` to save buffer leaks - and eventually cause further big allocations due to not be able to reuse the existing one.
This can be saved by correctly closing the used `JsonGenerator`.

Close the Jackson Generator to save buffer leaks

---

lang/c++/impl/Compiler.cc
lang/c++/impl/NodeImpl.cc
lang/c++/include/avro/NodeImpl.hh
lang/c++/test/SchemaTests.cc

Allow custom attributes to be preserved for map, fixed and enum types. This commit extends the work of https://github.com/apache/avro/pull/3168.
- Added roundtrip test for fixed, map, and enum type for custom attributes.

AVRO-4120: [C++] Allow custom attributes for MAP, FIXED and ENUM types

---

lang/c++/include/avro/Node.hh
lang/c++/include/avro/NodeImpl.hh
lang/c++/test/unittest.cc

Currently we cannot get custom attribute from any Node type. This commit aims to add a public API to Node to get all attributes from a single CustomAttributes object.
- Added a test case to verify that CustomAttributes are properly populated.

AVRO-4121: [C++] Add Node::getCustomAttributes

---

.github/workflows/codeql-java-analysis.yml
.github/workflows/java-publish-snapshot.yml
.github/workflows/maven4.yml
.github/workflows/rat.yml
.github/workflows/spotless.yml
.github/workflows/test-lang-c.yml
.github/workflows/test-lang-csharp-ARM.yml
.github/workflows/test-lang-csharp.yml
.github/workflows/test-lang-java-ARM.yml
.github/workflows/test-lang-java.yml
.github/workflows/test-lang-perl-ARM.yml
.github/workflows/test-lang-perl.yml
.github/workflows/test-lang-php.yml
.github/workflows/test-lang-py.yml
.github/workflows/test-lang-ruby.yml

The use of specific Git hash (SHA1) for GitHub Actions versions is only required for external actions.
We use all actions internal to the `apache/*`, `github/*` and `actions/*` namespaces without restrictions (see https://infra.apache.org/github-actions-policy.html).
This change use version alias for GitHub Actions.

Don't use specific git hash (SHA1) for GitHub Actions

---

lang/c++/impl/Compiler.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/impl/NodeImpl.cc
lang/c++/include/avro/LogicalType.hh
lang/c++/test/SchemaTests.cc

- The Java library supports registering custom logical types: https://github.com/apache/avro/pull/885
- Apache Iceberg requires custom `map` logical type: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/avro/LogicalMap.java
- Added a test case to verify that custom `map` logical type can be respected correctly.
- If yes, how is the feature documented? added comment around the new class

AVRO-4122: [C++] Allow custom logical type

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java

* This pull request improves file read performance by optimizing the first byte of varint Longs, fixing AVRO-407
See ticket for JMH results

AVRO-4067: Optimize First Byte of Long Decode

---

lang/c++/include/avro/Node.hh
lang/c++/include/avro/NodeImpl.hh
lang/c++/test/SchemaTests.cc
lang/c++/test/unittest.cc

My previous work in https://github.com/apache/avro/pull/3325 introduces a new `Node::getCustomAttributes` API to return (consolidated) custom attributes. However, this implementation is wrong because a `Node` instance holds a separate CustomAttribute for each leaf node. This patch fixes it by replacing `Node::getCustomAttributes` with two new functions `Node::customAttributes` and `Node::customAttributesAt` to match other methods from Node for name, default value, etc.
- Added test cases to SchemaTests to verify that custom attributes from different node types are preserved and parsed correctly.

AVRO-4121: [C++] Fix get CustomAttributes from Node

---

lang/c++/impl/Compiler.cc
lang/c++/impl/CustomAttributes.cc
lang/c++/include/avro/CustomAttributes.hh
lang/c++/test/SchemaTests.cc

This PR takes a different approach than https://github.com/apache/avro/pull/3308, https://github.com/apache/avro/pull/3069, https://github.com/apache/avro/pull/3064 and https://github.com/apache/avro/pull/3266 to fix the non-string custom attributes. It extends the `CustomAttributes::addAttribute(const std::string &name, const std::string &value)` with a third parameter `bool addQuotes` with default value set to `true` to support adding non-string values explicitly and keep backward compatibility.
- Make sure that all existing test cases are passed so backward compatibility is preserved.
- Added new test case to verify that both `json->schema->json` and `schema->json->schema` round trips have preserved non-string attributes correctly. …

AVRO-4026: [C++] Allow non-string custom attributes

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java

The initial fix for AVRO-3985 applied only to one constructor in `SpecificDatumReader`. This change extend the trusted packages check in all constructors.

AVRO-3985: Apply trusted packages check on SpecificDatumReader(data) constructor

---

lang/c++/include/avro/LogicalType.hh

Fix compilation under linux && gcc
/mnt/d/vcpkg/vcpkg/buildtrees/avro-cpp/src/ase-1.12.0-9c954b550d.clean/lang/c++/include/avro/LogicalType.hh:51:5: error: 'int32_t' does not name a type
51 |     int32_t precision() const { return precision_; }
|     ^~~~~~~
/mnt/d/vcpkg/vcpkg/buildtrees/avro-cpp/src/ase-1.12.0-9c954b550d.clean/lang/c++/include/avro/LogicalType.hh:25:1: note: 'int32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
24 | #include "Config.hh"
+++ |+#include <cstdint>
25 | 
/mnt/d/vcpkg/vcpkg/buildtrees/avro-cpp/src/ase-1.12.0-9c954b550d.clean/lang/c++/include/avro/LogicalType.hh:52:19: error: 'int32_t' has not been declared
52 |     void setScale(int32_t scale);

Fix compilation under linux for int32_t 

---

.github/workflows/deploy-docs.yml

Ensure that the current jars are used to build the website.
Manually verified.
- Does this pull request introduce a new feature? *no*
- If yes, how is the feature documented? *not applicable*

AVRO-4127: Use the dist target to build website

---

lang/java/avro/src/main/java/org/apache/avro/ParseContext.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaParser.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/idl/src/main/java/org/apache/avro/idl/IdlReader.java
lang/java/mapred/pom.xml
lang/java/tools/pom.xml
lang/java/trevni/pom.xml

Fix AVRO-4123: after parsing, ParseResult#parsedNamedSchemas() is always empty.
This change altered the test case `TestSchemaParser#testParseByCustomParser` to add the omitted check. This is a reasonable place to add this, as other parsers than the core JSON parser are the most likely candidate to use this functionality.
- If yes, how is the feature documented? (not applicable ~/ docs / JavaDocs / not documented~)

AVRO-4123: Parsed named schemas always empty

---

.github/workflows/test-lang-c++-ARM.yml
.github/workflows/test-lang-c++.yml
lang/c++/CMakeLists.txt
lang/c++/impl/DataFile.cc
lang/c++/include/avro/DataFile.hh
lang/c++/test/DataFileTests.cc

Add ZSTD codec to the C++ implementation
- *Added test that validates the codec works perfectly*

AVRO-4132: [C++] Add ZSTD codec

---

lang/c++/impl/Node.cc
lang/c++/test/SchemaTests.cc

Support uuid logical type to annotate fixed type of length 16. This is required by uuid type of Apache Iceberg.
Added test cases for uuid type based on fixed[16] and verify it throws correctly for other size.
- Does this pull request introduce a new feature? technically no

AVRO-4140: [C++] Support uuid to annotate fixed[16]

---

lang/java/avro/pom.xml
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
lang/java/ipc/pom.xml

As discussed within the Parquet community, this PR is more "restrictive":
1. no serializable packages by default
2. deprecate `org.apache.avro.SERIALIZABLE_PACKAGES` property
3. instead of `SERIALIZABLE_PACKAGES`, users should use `org.apache.avro.SERIALIZABLE_CLASSES`
This is a much more "strict" security enforcement.

Remove the default serializable packages and deprecated the property to introduce org.apache.avro.SERIALIZABLE_CLASSES instead

---

lang/java/avro/src/it/pom.xml

Tests got broken after merging #3376, because in `avro/src/it/pom.xml` we forgot to set `org.apache.avro.SERIALIZABLE_CLASSES`.

fix broken test after merging #3376

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

With the introduction of the `AbstractArray` in avro 1.12, it was not possible anymore to compare arrays which contained objects which contained a Map, as the fact that we compared for equality was not propagated anymore.
This commit re-introduces this propagation.
This change added an unit test

AVRO-4139 [java] fix equality check for maps in arrays

---

lang/java/avro/src/main/java/org/apache/avro/SchemaFormatter.java

Implement AVRO-4147 by updating the javadoc for the `SchemaFormatter` interface
- If yes, how is the feature documented? (~not applicable~ / **docs** / ~JavaDocs / not documented~)

AVRO-4147: Mention ServiceLoader in SchemaFormatter javadoc

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectLogicalTypes.java
lang/java/ipc/src/test/java/org/apache/avro/TestDataFileReflect.java
lang/java/ipc/src/test/java/org/apache/avro/TestDataFileSpecific.java
share/test/schemas/fooBar.avsc

This pull request improves deserialization of data when using default `SpecificData` instance.
Why?
Often times, `SpecificDatumReader` and `ReflectDatumReader` are configured using the default `SpecificData` instance. This leads to deserialization error when reading fields with union type and inner logical type (see test-case).
Deserialization works correctly when using the custom `SpecificData` instance stored in the `MODEL$` field of the schema class that `extends SpecificRecord`. The custom `SpecificData` has the necessary conversions stored to handle fields with union and logical types. The issue has been reported multiple times, notably in [AVRO-3989](linked JIRA).
- *The added test passes when the code is present but fails when …

AVRO-3989: [java] add conversion classes to default instance of SpecificData

---

lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/main/java/org/apache/avro/util/TimePeriod.java
lang/java/avro/src/test/java/org/apache/avro/TestLogicalType.java

Support for the duration logical type was missing the final bit: recognising the logical type name in the switch statement in `LogicalTypes` (documented as bug AVRO-4159). This fixes that.
This change updated a test: `org.apache.avro.TestLogicalType#durationExtendsFixed12`

AVRO-4159 [Java]: complete support for duration

---

lang/java/gradle-plugin/src/main/java/com/github/davidmc24/gradle/plugin/avro/SchemaResolver.java

With the introduction of the new SchemaParser in 1.12 the variety of errors which can be thrown when an unresolved type is found increased significantly.
In the past unresolved type errors were tracked with a brittle regexp. In the newly proposed logic we propose to retry failed parse steps on any AvroRuntimeException.  So this works for all past and future avro library versions.
@frevib this is a small proposal for an update on #3305 so the gradle plugin support 1.12 and others.
Let me know what you think, and if I can help you improving it somehow.
*(or)*
This change can be verified as follows:
- run `SchemaResolverSpec.groovy`
- And manually verified on internal corpus.
- Does this pull request …

AVRO-3731 [java/gradle-plugin] retry on any schema parse failure

---

lang/csharp/src/apache/main/AvroDecimal.cs
lang/csharp/src/apache/test/AvroDecimalTest.cs

The conversion from the C# System.Decimal to an Avro logical type decimal is not correct. The first 12 bytes of the System.Decimal represent a positive unscaled value. This value is passed into a BigInteger constructor. However, the documentation of the [BigInteger constructor](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.-ctor?view=net-9.0#system-numerics-biginteger-ctor(system-byte())) states that the most significant bit of the last byte represents the sign of the BigInteger. The docs also explain that a 0 byte can be appended to the byte array passed to the BigInteger constructor to ensure the value is treated as positive.
Added a test that fails without the fix.

AVRO-4161: [C#] Fix System.Decimal to Avro decimal conversion

---

lang/java/avro/src/main/java/org/apache/avro/reflect/AvroEncode.java
lang/java/avro/src/main/java/org/apache/avro/reflect/FieldAccessReflect.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumWriter.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectionUtil.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestAvroEncode.java

This PR adds the ability to use the `CustomEncode` annotation directly on a class.
It required some changes to when this annotation would be scanned. Currently, it is only used on fields.
Getting this to work for the first Record written required additional changes to support the feature.
I added a new map on `ReflectData` as I feel this is cleaner from an encapsulation point of view. Alternatively, it could be added to `SpecifiedData` by changing the `classCache` map to an object that stores the class and this `CustomEncoding`. This may be slightly faster, as there would be one less map lookup. However, it would probably be negligible as this new lookup is only performed once per row, whereas other maps can be queried per field.
- …

AVRO-4165: [java] ability to specify AvroEncode on a class

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestAvroEncode.java

Fixes a bug where, if the custom encoder is specified at the top of the class, it did not drive the schema used.
This updates a test to ensure the schema used is not the same as what would be used by reflection, highlighting this issue.
extends test to make sure this case is covered.

Avro-4169: [java] custom encoder bug

---

lang/c++/CMakeLists.txt

This pull request find system installed `fmt` package first and then try the original `fetch_content` to download it from upstream. Other packages are looking for it from the system but `fmt` is not yet.

AVRO-4171: [c++] find system installed fmt first

---

lang/c++/include/avro/Node.hh
lang/c++/include/avro/Types.hh

This PR introduces compatibility with fmtlib 10+, fixing AVRO-4158.
This change is for build-time compatibility only and therefore does not introduce any new tests.
I ran the automated test suite on Arch and everything passed. I can confirm that it still compiles against fmtlib 8.1 as well, but I didn't go back any further.

AVRO-4158: [c++] Update for fmtlib 10+

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java

`SpecificDatumReader.SERIALIZABLE_PACKAGES` was used as a list of class name prefixes instead of the package names it is designed as. This change forces the provided package names to be package names.
This change is a near-trivial refactoring without any test coverage.
Tests should be added, but this is a larger undertaking than a quick fix.

java-[key-]class allowed packages must be packages

---

lang/c++/impl/DataFile.cc
lang/c++/include/avro/DataFile.hh
lang/c++/test/DataFileTests.cc

C++ `DataFileWriter` and `DataFileReader` have defined `std::map<std::string, std::vector<uint8_t>>` as internal metadata. We need to expose it via public API. Iceberg requires access to it to write and read metadata of manifest files.
- Added metadata to constructor of DataFileWriter.
- Added metadata getter to DataFileReader.
- Added roundtrip test cases in the DataFileTests.cc to write and read metadata.
- If yes, how is the feature documented? Added comment to new functions

AVRO-4174: [C++] Support read and write key-value metadata
