apache/avro

lang/c++/impl/json/JsonIO.cc

Clang reports the else statements will never be executed since stArrayN and stObjectN are always none-zero.

AVRO-1995: JSON Parser does not properly check current state

---

lang/java/pom.xml

I found a few remnants of the transition from Java 1.7 to 1.8 that can be removed.

AVRO-2043: Remove pre JDK 1.8 surefire specific configuration

---

CHANGES.txt
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/ResolvingVisitor.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/SchemaResolver.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/CloningVisitor.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/SchemaVisitor.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/SchemaVisitorAction.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/Schemas.java
pom.xml

I have combined the various actions from AVRO-2118 (licensing issues) and AVRO-2119 (Run rat always) into this set of commits.
I also updated Apache Rat to the latest version and fixed the problem that rat would not only be run at the top level (desired) but also in all subprojects (undesired and failing).

AVRO 2118+2119 Fix licensing issues

---

share/docker/Dockerfile

This is needed to generate the avro website.
Signed-off-by: Niels Basjes <nbasjes@bol.com>

AVRO-2041: Upgrade Apache Forrest in docker image to v0.9

---

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/baz.avsc
lang/java/compiler/src/test/idl/input/import.avdl
lang/java/compiler/src/test/idl/output/import.avpr

This patch is an attempt to fix [AVRO-2157](https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2157).
I tested this patch against `release-1.8.2`, and it seems to solve the problem without breaking any tests.
I also tested against `master`. There appear to be a few broken tests on `master` as of now (2018-03-09 01:31 America/New_York), but this patch appears to fix 2157 on master without breaking further tests.
I do not know why `<SCHEMA>` was not yet a part of `AnyIdentifier()`, and perhaps I'm trying to change something which ought not to be changed. If not, I hope you'll consider accepting this patch :).

jira avro 2157: add <SCHEMA> to AnyIdentifier() in idl.jj

---

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java

Add object-value attribute support to SchemaBuilder.PropBuilder:
public final S prop(String name, Object value)
JsonProperties supports object-valued attributes through its
addProp() and getObjectProps() methods.  Extend SchemaBuilder.PropBuilder
to also support object-valued attributes so that schemas with non-string
attributes can be created programmatically.

AVRO-2067: Add object-value attrs to PropBuilder

---

lang/c++/impl/json/JsonIO.hh

Proposed fix to [1191](https://issues.apache.org/jira/browse/AVRO-1191).

AVRO 1191: Fix C++ JSON Encoder to use \u escape sequence

---

lang/c++/api/AvroTraits.hh
lang/c++/api/Specific.hh
lang/c++/test/SpecificTests.cc

Fix compilation error caused due to `vector<bool>` specialization.
fixes AVRO-2081

Compilation with clang fails due to missing codec_traits specialization

---

doc/src/content/xdocs/idl.xml
lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java
lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityEnumDefaults.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/ResolvingVisitor.java
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/simple.avdl
lang/java/compiler/src/test/idl/output/simple.avpr

- Added Defaults to Enums.
- Enum Defaults are only applied to values which don't match the Reader Enum symbols.
- Enum Defaults do not override any Field Default behaviour. Field Defaults are used when a reader reads a datum that does not have the Field defined (as is current behaviour).
To see an example table of this behaviour, see Final Default & Fallback tab in:
https://docs.google.com/spreadsheets/d/1YkTBnHCBPGz2t0gQI3OioKS_xP9h9lq_a-gS2jSGFAc/edit?usp=sharing

AVRO-1340: Added Enum Defaults and unit tests.

---

lang/java/grpc/pom.xml
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroGrpcClient.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroGrpcServer.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroGrpcUtils.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroInputStream.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroRequestMarshaller.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroResponseMarshaller.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/ServiceDescriptor.java
lang/java/grpc/src/test/avro/TestService.avdl
lang/java/grpc/src/test/java/org/apache/avro/grpc/TestAvroMarshaller.java
lang/java/grpc/src/test/java/org/apache/avro/grpc/TestAvroProtocolGrpc.java
lang/java/pom.xml

To enable avro based schema and RPC IDL to be transported over gRPC.

AVRO-2172: Avro binding for gRPC (Java Implementation)

---

pom.xml

A recent commit (perhaps a11bd49e86d50f5a840ab2cdfe4f6927bedb4f93) renamed BUILD.txt to BUILD.md.  BUILD.txt was excluded from license checking in a RAT exclusion.  This pull request renames the exclusion in pom.xml so the validation phases passes.

Renamed BUILD.txt to BUILD.md in RAT-task exclusions

---

lang/c++/api/DataFile.hh
lang/c++/impl/DataFile.cc

Downstream consumers will still have to implement their own relevant
Input/Outputstream subclasses.

AVRO-2014 Add support for custom streams for the DataFile interfaces.

---

lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificLogicalTypes.java

Whe comparing Instant, DateTime, LocalTime with its Joda equivalents the tests fail since the java.time.* adds support for microseconds, and Joda only miliseconds. For example:
```
Failed tests:
TestSpecificLogicalTypes.testAbilityToReadJodaRecordWrittenAsJsr310Record:183
Expected: is "11:45:07.170331"
but: was "11:45:07.170"
TestSpecificLogicalTypes.testRecordWithJsr310LogicalTypes:115 Should match written record expected:
<{"b": true, "i32": 34, "i64": 35, "f32": 3.14, "f64": 3019.34, "s": null, "d": 2018-10-11, "t": 11:45:06.513252, "ts": 2018-10-11T11:45:06.513358Z, "dec": 123.45}>
but was:
<{"b": true, "i32": 34, "i64": 35, "f32": 3.14, "f64": 3019.34, "s": null, "d": 2018-10-11, "t": 11:45:06.513, "ts": 2018-10-11T11:45:06.513Z, "dec": 123.45}>
```

AVRO-2241. Fix Jsr310/Joda datetime tests

---

lang/java/avro/pom.xml

The classes from Guava used by Avro are shaded into the final jar, however the OSGi imports are calculated before shading, resulting in a com.google.common* dependency declared in Import-Package manifest header. As a consequence in an OSGi environment one has to install a version of Guava even though that version will not be used by Avro.
By adding !com.google.common* to the Import-Package directive of the maven-bundle-plugin the package(s) of Guava will no longer be declared on the Import-Package of the Avro OSGi bundle.

AVRO-2208 Unneeded OSGi import generated for Guava dependency

---

lang/java/ipc/src/test/java/org/apache/avro/io/Perf.java

As I continue to work on performance testing, I'm wanting to experiment with values for Perf.COUNT and Perf.CYCLES without having to recompile.  This patch allows for such experimentation.

AVRO-2251 part 2: Allow changes to COUNT and CYCLES via system properties.

---

lang/py3/avro/protocol.py
lang/py3/avro/schema.py

Per the Rejection Notice of PEP-416, use MappingProxyType instead of
creating our own implementation of ImmutableDict.

AVRO-2234 Use MappingProxyType, not ImmutableDict

---

lang/ruby/Manifest
lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/logical_types.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/random_data.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_logical_types.rb
lang/ruby/test/test_schema.rb

This is a continuation of the changes originally submitted in https://github.com/apache/avro/pull/44 for https://issues.apache.org/jira/browse/AVRO-1695.
Original description:
```
Add Ruby support for logical types
Only logical types that map directly to Ruby standard library types are supported:
* date maps to Date;
* timestamp-millis and timestamp-micros map to Time.
The remaining types are difficult to cleanly map to Ruby types, so I've refrained from doing so.   
Furthermore, there's no direct support for plugging in custom mappers – I'm unsure if this is     
needed.
```
I've tried to add address the feedback from the original PR, primarily pushing some of the implementation into `Avro::Schema.real_parse` and ensuring that the Ruby tests cover all the same cases as the Java …

AVRO-1695: Ruby support for logical types revisited

---

lang/py3/setup.py

Removes the assert statement that prevents python2 from interacting with setup.py at all. Also fixes an incompatibility and apparent brokenness with chmod in the setup.py script.
https://issues.apache.org/jira/browse/AVRO-2240

AVRO-2240 Fix py3 Setup

---

lang/java/compiler/pom.xml
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/enum.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/protocol.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/ipc/pom.xml
lang/java/pom.xml

- Remove `Slf4jLogChute` since 2.0 uses SLF4J itself: https://github.com/apache/velocity-engine#upgrading-from-velocity-17x-to-velocity-20
- Update $velocityHasNext to $foreach.hasNext because of deprecation, Update $velocityCount to $foreach.count because of deprecation: https://github.com/apache/velocity-engine#upgrading-from-velocity-16x-to-velocity-17x
- Velocity 2.0 does not depend on apache-common collections anymore which used to be an old version with known security issues:  CVE-2015-6420, CVE-2017-15708

[AVRO-2228] Bump Apache Velocity to 2.0

---

lang/java/avro/src/main/java/org/apache/avro/io/ResolvingDecoder.java

Current docs: https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/parsing/doc-files/parsing.html
Right now, this links to https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/doc-files/parsing.html
The link should actually be to https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/parsing/doc-files/parsing.html

Fix javadoc link

---

lang/py3/avro/schema.py
lang/py3/avro/tests/test_schema.py

A schema object should raise an `AttributeError` when a user attempts to access a `name` property on a schema that does not have a name. The Python 2 implementation does this correctly:
```python
>>> from avro.schema import parse
>>> s = parse('{"type": "array", "items": "int"}')
>>> s.name
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'ArraySchema' object has no attribute 'name'
```
In the Python 3 implementation, however, it raises a `KeyError`.
```python
>>> from avro.schema import Parse
>>> s=Parse('{"type":"array","items":"int"}')
>>> s.name
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/michaels/dev/avro/lang/py3/avro/schema.py", line 224, in name
return self._props['name']
KeyError: 'name'
```
This is not …

AVRO-2183 Provide name only for named schema

---

lang/java/avro/src/main/java/org/apache/avro/file/BZip2Codec.java
lang/java/avro/src/main/java/org/apache/avro/file/Codec.java
lang/java/avro/src/main/java/org/apache/avro/file/CodecFactory.java
lang/java/avro/src/main/java/org/apache/avro/file/DeflateCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/SnappyCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/XZCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardCodec.java

* Update a few things to use try-with-resources
* Updated CodecFactory to reference constants for codec names
* Fixed a small bug in Snappy and BZip2: compression/decompression were incorrect if the input ByteBuffer was a a slice(). I don't see anywhere that this would actually happen currently, but some codecs were written to account for this correctly; now they're all correct. Updated everything to compute the correct offset into the underlying array. (I can add a test for this in TestAllCodecs once #351 is merged).
I can file a matching JIRA for this if desired.

AVRO-2262 Java compression codec improvements

---

lang/java/avro/src/test/java/org/apache/avro/file/TestAllCodecs.java

This tests the changes that were merged in #352

AVRO-2262: add unit test to test codec behavior on sliced buffers

---

lang/java/pom.xml

m2e lifecycle plugin is used for building maven projects within Eclipse IDE. Since the plugin is in {{pluginManagement}} section and the plugin is never used in {{build/plugins}} or {{profiles/profile/build/plugins}} it is never used by normal Maven builds. It is used exclusively by Eclipse.
All that needed to done was to push the {{pluginManagement}} section into a profile that is triggered only when Eclipse invokes Maven. To get a better view of changes use {{?w=1}} in the URL for this pull request.
This does not have an impact on non-eclipse builds (except getting rid of the warning, of course). For Eclipse builds, this no worse than what we have been always having. I verified that with the latest Eclipse release Photon. There is a different problem (unrelated to m2e). It is related to …

Suppressed warning from m2e maven plugin

---

lang/java/ipc/src/test/java/org/apache/avro/io/Perf.java

Array fields for specific records should be given `List<>` implementations that support the `List.clear` operation.  The class returned by `Arrays.asList` does not support `clear`, so use an `ArrayList` instead.

AVRO-2268 Fix FooBarSpecificRecord case

---

lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/test_schema_validator.rb
share/test/interop/bin/test_rpc_interop.sh

This fixes https://issues.apache.org/jira/browse/AVRO-2239 and re-enables RPC interop tests for Ruby.
The fix is to check that a datum is a Ruby Hash before validating it as a map.
The fix for this was already in https://github.com/apache/avro/pull/230, but I can rebase that PR if this makes it to master first.

AVRO-2239: Fix RPC interop tests for Ruby

---

lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/test_schema_compatibility.rb

This change fixes an error in Schema Compatibility checking in ruby: https://github.com/apache/avro/pull/170
Previously this raised a missing method error because the comparison is invalid.
With this change, the correct result returned that a record schema for a reader is incompatible with a union schema for the writer.
Test coverage is also increased for the cases of:
- a union schema for a reader with an included record schema for the writer (compatible)
- a record schema for a reader with a union schema for the writer (incompatible)
JIRA issue: https://issues.apache.org/jira/browse/AVRO-2256

AVRO-2256 Prevent error checking compatibility of a record reading a union in Ruby

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_schema_validator.rb

This change includes several optimizations of the validation performed during encoding using Ruby. For a use case with a few levels of nesting and unions in several places within the schema we saw a 5x improvement in encoding performance with these changes.
https://issues.apache.org/jira/browse/AVRO-2039
The main changes are:
1. Avoid the exhaustive validation of schemas in a union. Previously a datum was tested against all schemas in a union even though the failures were unused if a compatible schema was found. Now validation stops when the first compatible schema is found, but all failures are still available if there is no compatible type.
2. Avoid the repeated validation of nested schemas. Previously, the datum was recursively validated against the schema prior to encoding. Then …

AVRO-2039: Ruby encoding performance improvements

---

lang/java/avro/src/main/java/org/apache/avro/reflect/AvroDoc.java

License file for org.apache.avro.reflect.AvroDoc was missing a license, breaking the build.  This patch adds the standard lic header.

AVRO-1658 Added license to AvroDoc.java

---

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java

The code snippet in SchemaBuilder is invalid, it has invalid quotes and misses one call in the builder chain.

AVRO-2142: Fix SchemaBuilder javadoc code snippet

---

lang/java/avro/src/main/java/org/apache/avro/io/ResolvingDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/Symbol.java
lang/java/avro/src/test/java/org/apache/avro/io/parsing/SymbolTest.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java
lang/java/tools/src/test/compiler/output/Player.java

Optimize schema-resolution code in cases where subschemas of the reader and writer don't change.  Short story: unchanged enumerations improve by 3%, SpecificRecord with unchanged field-order improve by 8-9%, and unchanged unions improve by 25% (should be a big win for record schemas with lots of nullable fields).  See [AVRO-2274](https://issues.apache.org/jira/browse/AVRO-2274) for details.

AVRO-2274 Improve resolving performance when schemas don't change.

---

.gitignore
lang/java/grpc/pom.xml
lang/java/maven-plugin/pom.xml
lang/java/pom.xml
lang/java/protobuf/pom.xml
lang/java/thrift/pom.xml
lang/java/tools/pom.xml
pom.xml

I also includes fixes for most of the warnings reported via `mvn versions:display-plugin-updates`

AVRO-2279: Fix broken java build on windows

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

Isolated the fix and added an extra test that shows the problem can happen in linux too so we can avoid this in the future.

AVRO-2276: Escape Map keys in GenericData.toString to generate JSON

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/ipc.rb
lang/ruby/lib/avro/protocol.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_logical_types.rb
lang/ruby/test/test_schema.rb

This cleans up all of the warnings with Ruby versions 2.0 through 2.5.
There are still some warnings with Ruby 1.9.3 because it does not recognize the underscore (_) prefix convention for an unused variable.
Tested against:
- 1.9.3-p551
- 2.0.0-p648
- 2.1.10
- 2.2.8
- 2.3.8
- 2.4.5
- 2.5.3
JIRA issue: https://issues.apache.org/jira/browse/AVRO-2277

AVRO-2277: Clean up Ruby warnings

---

lang/py3/avro/io.py
lang/py3/avro/tests/test_io.py

Trouble arises in the python library when deducing the appropriate schema from a list of schemas given a particular datum.
When "null" values are allowed for fields in two separate schemas, there is no way to differentiate which schema should be used given of a list of schemas that are set as the type definition for a record.
This PR checks to ensure all fields defined on a given datum are _also_ defined in the schema being validated to use for that datum.
With this bugfix, datums such as `{"foo": "a"}` will not "cast" to schemas such as `{"name": "bar", "type": ["long", "null"]}`, which is currently the case.

[AVRO-2226] Fixes UnionSchema specificity

---

lang/c++/impl/FileStream.cc

if compiling avro library in unicode mode (for linkage with other unicode libraries) the macro CreateFile will exand to a unicode version that fails to compile. The hardcoded non-unicode CreateFileA fixes this.

fixes unicode compile on windows

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/main/Schema/EnumSchema.cs
lang/csharp/src/apache/main/Schema/FixedSchema.cs
lang/csharp/src/apache/main/Schema/NamedSchema.cs
lang/csharp/src/apache/main/Schema/RecordSchema.cs
lang/csharp/src/apache/test/Schema/SchemaTests.cs

[AVRO-2155](https://issues.apache.org/jira/browse/AVRO-2155)
1. Added `Documentation` property to `NamedSchema`, as well as an argument in the constructor to accept the value for the property
2. Added unit tests for the `Documentation`: `TestEumDoc`, `TestFixedDoc` and `TestRecordDoc`
3. In `CodeGen.cs`, added comments to the generated fixed, enum and record code declarations.
4. Unrelated change: Added missing parameter documentation on `EnumSchema`, `FixedSchema`, `NamedSchema` and `RecordSchema` documentation
I didn't see a good way to unit test the documentation in the generated code. As an alternative, I've added [sample.zip](https://github.com/apache/avro/files/1799659/sample.zip) containing a sample protocol and before/after generated code for comparison.

AVRO-2155: Include documentation for named schemas in generated code

---

doc/src/content/xdocs/site.xml

Fixed Url for CSharp documentation.

AVRO-2144: Fix for CSharp documentation Url

---

lang/csharp/src/apache/codegen/AvroGen.cs
lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs

[AVRO-2156](https://issues.apache.org/jira/browse/AVRO-2156)
Added new optional command line argument, `--namespace <my.avro.ns:my.csharp.ns>`.
Normally, `avrogen.exe` uses the namespaces defined in the schema or protocol as the namespace in the generated C# code. This default behavior has not changed as a part of this pull request. However, if the user wishes to replace the Avro namespace with a C#-friendly namespace in the generated code, they can provide the `--namespace` option. 
For example, if this is our protocol:
```
// sample.avdl
@namespace("org.example.sample")
protocol MySampleProtocol {
fixed MD5(16);
}
```
`avrogen.exe -p sample.avdl output` would produce something like:
```csharp
// MD5.cs
namespace org.example.sample
{
public partial class MD5 : SpecificFixed //...
}
``` …

AVRO-2156: Map Avro namespace to C# namespaces during code generation

---

lang/csharp/src/apache/main/Schema/NamedSchema.cs
lang/csharp/src/apache/main/Schema/Schema.cs
lang/csharp/src/apache/main/Schema/UnionSchema.cs
lang/csharp/src/apache/test/Schema/SchemaTests.cs

Fix the C# parsing of a union schema that contains  duplicate names but in different namespaces. The full name is now used when parsing the schema. This is identical to my previous pull request on this topic, but I've rebased to apache/master and squashed all the commits to a single commit.

AVRO-1363 Fix the C# parsing of a union schema 

---

lang/csharp/src/apache/main/Generic/GenericRecord.cs
lang/csharp/src/apache/test/Generic/GenericTests.cs

Any two arrays / dictionaries would be considered equal

C# - Generic Record - Fix false positive equality

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs

this uses System.IO.Path API when creating output file path.
please review it.

AVRO-1955: fix avrogen.exe output dir path format

---

lang/c/CMakeLists.txt
lang/c/src/CMakeLists.txt

Prior to this commit the `VERSION` and `SOVERSION` properties were not being set correctly for the Avro C shared library. Previously, `VERSION` was unset, and `SOVERSION` was set to the full dotted version string (e.g. "23.0.0"), which resulted in a `SONAME` of "libavro.so.23.0.0", which is incorrect.
This commit sets `SOVERSION` to the library's "current" version number (obtained by invoking `version.sh libcurrent`), and sets `VERSION` to the full dotted version string.
This should result in a proper `libavro.so` → `libavro.so.23` → `libavro.so.23.0.0` symlink chain with a `SONAME` of "libavro.so.23".
See Sune Vuorela's article on "CMake and library properties": http://pusling.com/blog/?p=352.

AVRO-2063. C: VERSION, SOVERSION not set correctly for shared library

---

lang/c/src/errors.c
lang/c/tests/test_avro_errors_are_thread_safe.c

1. change the error module to be thread-safe on Windows as well as on UNIX (depended on defining the macro THREADSAFE).
2. add appropriate test which launch several threads and validate the errors they set/add are thread-safe.

 AVRO-2008: change the error module to be thread-safe on Windows as well as on UNIX

---

lang/c/src/avro/refcount.h

Clang advertizes itself to be compatible with gcc 4.2.1
while that was true several years ago, it now supports
a lot more newer features, the test to just check gcc
version should be supplanted with clang check as well
so atomic support in clang can be asserted as well
Fixes
lang/c/src/avro/refcount.h:301:2: error: "No atomic implementation!"
Signed-off-by: Khem Raj <raj.khem@gmail.com>

avro-c: Fix build with clang compiler

---

pom.xml

some orgs use ivy for builds.
manually constructing ivy.xml files for avro jars is complicated and error-prone.
this utility profile can be used to automatically generate them during build time from pom files

add ivy profile to generate ivy.xml desriptors for java artifacts

---

lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/InduceMojo.java
lang/java/maven-plugin/src/test/java/org/apache/avro/entities/Person.java
lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestInduceMojo.java
lang/java/maven-plugin/src/test/java/org/apache/avro/protocols/Remote.java
lang/java/maven-plugin/src/test/resources/unit/protocol/induce-pom.xml
lang/java/maven-plugin/src/test/resources/unit/schema/induce-pom.xml

[AVRO-1749](https://issues.apache.org/jira/browse/AVRO-1749)
Maven plugin goal to induce Avro schemas and protocol from Java classes.
(this PR was previously #67)

AVRO-1749 Java: Introduce induce Maven plugin goal

---

lang/py3/avro/schema.py
lang/py3/avro/tests/test_schema.py

Fixes undefined variable issue in `RecordSchema._MakeFieldMap`:
```
File ".../avro/schema.py", line 1004, in _MakeFieldMap
'Duplicate field name %r in list %r.' % (field.name, field_desc_list))
NameError: name 'field_desc_list' is not defined
```

Fix undefined variable field_desc_list in RecordSchema._MakeFieldMap

---

lang/c++/CMakeLists.txt
lang/c++/api/Config.hh
lang/c++/impl/ValidSchema.cc
lang/c++/impl/avrogencpp.cc
lang/c++/test/AvrogencppTests.cc

* VS2017 needs `-DNOMINMAX` to avoid having the Windows system header file define `min()` and `max()` as macros.
* There's no builtin `ssize_t`
* `#include <cctype>` is required for some definitions.
Other changes are related to C++11 and aren't VS2017-specific.
* Use scoped enums in generated code, otherwise code that is generated from a schema containing two enums with the same symbol will fail to compile.
* Add an underscore at the end of the generated name of any C++ reserved words to avoid compile issues if the Avro schema uses symbol names like `virtual`

Avro-CPP: build fixes to work with vcpkg and Visual Studio 2017

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java

Suggested fix for AVRO-2286.
The test case only checks for the file handle leaking; inability to delete the file is not reproducible on most unix systems (although the resources may remain blocked, of course), so is not included in the test.

AVRO-2286 fix and regression test

---

lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificLogicalTypes.java
lang/java/integration-test/test-custom-conversions/src/main/java/org.apache.avro.codegentest/CustomDecimal.java
lang/java/trevni/core/src/main/java/org/apache/trevni/OutputBuffer.java

It also fixes a deprecation warning for `RoundingMode` on Java 11 in a backwards compatible way.

AVRO-2288: Trevni’s OutputBuffer signature clashes with new ByteArrayOutputStream#writeBytes method

---

build.sh
lang/ruby/build.sh
share/docker/run-tests.sh

This reverts the changes from https://github.com/apache/avro/pull/422 and fixes the build by installing the latest bundler (1.17.3) that is compatible with the ruby version (2.1.5) from the Docker image.`

AVRO-2297: Re-enable ruby build

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericArray.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java

The fix for AVRO-2050 effectively prevented array elements from ever being reused, thus making the implementation of array element reuse in GenericDatumReader.readArray() by means of GenericArray.peek() useless (GenericArray.peek() would ALWAYS return null).
With this PR, I suggest a means of retaining the behaviour of AVRO-2050 while also allowing GenericData.readArray() to work as it should, by reusing all required existing elements and only pruning the non-used ones to reduce allocation pressure.
A possible extension might even be to disable the pruning via a setting in GenericData/GenericDatumWriter to potentially reduce required allocations even more at the cost of potential zombie elements lurking in unused array cells.
Feedback and suggestions welcome.

AVRO-2291 - Make elements of an array reusable again

---

lang/csharp/README.md
lang/csharp/build.sh
share/docker/Dockerfile

Fixes [AVRO-2303](https://issues.apache.org/jira/browse/AVRO-2303)
Tests against .NET SDK instead of Mono. Still requires Mono for the `./build.sh dist` command.

AVRO-2303 Build and test against .NET SDK instead of Mono

---

lang/py3/avro/datafile.py

This change fixes https://issues.apache.org/jira/browse/AVRO-2306, which is a data corruption bug encountered when using Avro with the snappy codec in Python 3.
CC: @aaltay @chamikaramj @valentyn

AVRO-2306: Fix data corruption issue with snappy in Python 3

---

lang/java/avro/pom.xml
lang/java/compiler/pom.xml
lang/java/ipc/pom.xml
lang/java/mapred/pom.xml
lang/java/pom.xml
lang/java/tools/pom.xml
lang/java/trevni/pom.xml

This also disables the double execution of the tests mentioned in the mailing list for all modules apart of the core module.
I think we could eventually enable parallel tests run for the core module but we need to fix some flaky tests, in the meantime I think this is a worth improvement, in particular now that we need to run the Java 11 tests too.

Update surefire to version 3.0.0-M1 and enable parallel tests for some modules

---

lang/java/avro/src/main/java/org/apache/avro/Conversions.java

```
-- Code currently in master branch
TestFill.fill_master  thrpt   30  72819605.046 ±  283321.097  ops/s
-- Use Arrays.fill for prefix and a basic for-loop to copy the unscaled data
TestFill.fill_fill_loop  thrpt   30  84733757.365 ±  585261.934  ops/s
-- Use Arrays.fill for prefix and a System.arraycopy to copy the unscaled data
TestFill.fill_fill_copy  thrpt   30  92483842.121 ± 1288416.561  ops/s
```
Interestingly, my JMH testing showed that it might be faster too.

AVRO-2309: Conversions.java - Use JDK Array Manipulations

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java

User latest JDK features for array copy and also use the bit-shift instead of multiplication and division.

AVRO-2310: GenericData Array Add Use JDK Copy Facilities

---

.github/autolabeler.yml

As discussed in the mailing list and in [INFRA-17367](https://issues.apache.org/jira/browse/INFRA-17367). This plugin will auto label PRs depending on programming language to ease the triage.

Add probot auto-labeler configuration

---

lang/java/pom.xml

https://jira.apache.org/jira/browse/AVRO-2314
There is an outstanding CVE on 3.4.0+
https://ossindex.sonatype.org/vuln/d47d20ab-eb2a-4cfd-8064-bbf6283649cb

[AVRO-2314] Bump protobuf to 3.6.1

---

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java
lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufDatumReader.java
lang/java/protobuf/src/test/java/org/apache/avro/protobuf/TestProtobuf.java

This change fixes an issue when importing Avro files into BigQuery, when
such files have been generated using `ProtobufData`. The schema
namespace may end in a dollar sign, if using nested classes.
The correction piggybacks on the fix provided for AVRO-2143 (#283). In
it, `SpecificData` will attempt to load a class joining the namespace
and the name with a dot, and if that fails, it tries again with a dollar
sign.
The same behaviour is hereby reused for `ProtobufData`.

AVRO-2302 Fix invalid namespace on BigQuery import

---

lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/test_schema_validator.rb

Ruby schema validation for fixed types should use bytesize in error message.
Minor change based on https://issues.apache.org/jira/browse/AVRO-1989
Create a new PR based on the patch file: https://issues.apache.org/jira/secure/attachment/12849804/AVRO-1989.0.patch

AVRO-1989: Ruby schema validation should  use bytesize in error msg

---

lang/java/pom.xml

https://jira.apache.org/jira/browse/AVRO-2326

[AVRO-2326] Bump netty-codec-http2 from 4.1.30.Final to 4.1.33.Final

---

lang/csharp/src/apache/main/Specific/ObjectCreator.cs

Loading all types from all assemblies in the current domain
could throw an exception for a variety of non-fatal reasons.
Simply catch these exceptions and continue.

AVRO-1981: Catch exceptions loading types from assemblies in C#

---

lang/py3/avro/ipc.py

We have some legacy code which worked fine under HTTP for years and a former developer here wrote a test in Python.  When the API was changed to use HTTPS, we found the test no longer works.  This change makes it work under HTTPS.

Support HTTPS in IPC HTTPTranceiver

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericEnumSymbol.java
lang/java/avro/src/test/java/org/apache/avro/TypeEnum.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericConcreteEnum.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/enum.vm
lang/java/tools/src/test/compiler/output-string/Position.java
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Position.java
lang/java/tools/src/test/compiler/output/Position.java

Generated enum classes will implement GenericEnumSymbol so that they may be written with GenericDatumWriter. This narrows the Comparable scope of GenericEnumSymbol to the class that implements it because java.lang.Enum already implements Comparable. However it seems the broader comparable scope was unused or at least untested.
testGenericWriteAndRead reads into an IndexedRecord because there is no GenericDatumReader support for setting an instance of an Enum into a SpecificRecord (but this seems to make sense and SpecificDatumReader should be used in that instance anyway).
https://issues.apache.org/jira/browse/AVRO-1810

AVRO-1810: Fix GenericDatumWriter w/ enums

---

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java

https://issues.apache.org/jira/browse/AVRO-2345
I'd like to use `getSchema(descriptor)` directly to enable 1) to get schema from protobuf instance doesn't have `getDescriptor()` created from reflection and 2) to pass not protoc-java classes e.g. Scala classes generated by [ScalaPB](https://github.com/scalapb/ScalaPB) has `javaDescriptor()` instread of `getDescriptor()`.

AVRO-2345: Export getSchema() to bypass using reflection

---

lang/java/avro/src/main/java/org/apache/avro/file/CodecFactory.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardLoader.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
lang/java/avro/src/test/java/org/apache/avro/file/TestZstandardCodec.java
lang/java/mapred/pom.xml
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyOutputFormat.java

Adds compression level setting to zstandard codec.  It is very valuable to have this, as ZStandard is extremely flexible in its compression range -- at one end it is faster than snappy (and slightly better compression, around level -2) in the mid levels it is significantly faster than gzip while also being higher compression (levels 1 to 5 or so), and it can go up to near 'xz' compression ratios at the higher levels, but with significantly faster decompression speeds.
Missing out on the compression level flexibility would be a shame.

AVRO-2355 [java] Add level and checksum options to ZStandard compression

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectionUtil.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectData.java

Adds support for generic types in ReflectData for Protocols.
I also took the liberty of cleaning up the iteration over Parameters; the multi-dimensional array style is no longer really necessary with the new methods on Parameter.
https://issues.apache.org/jira/browse/AVRO-2357

AVRO-2357: Allow generic types in reflect protos

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumWriter.java

Current state:
If datum is null and the schema enum does not accept null, then the exception message is "Not an enum: null". This makes it difficult for debugging or failing gracefully with automated solutions if records have multiple schemas using enums.
With this change, the schema will be included in the 'AvroTypeException' with the potential to provide acceptable enum values from the schema's properties.

Provide Schema when 'writeEnum' fails

---

lang/java/build.sh
lang/java/ipc-jetty/pom.xml
lang/java/pom.xml

As explained in #448 Avro's hadoop dependencies are provided/runtime so we can ensure our compatibility just by running tests against Hadoop 3 to ensure no change breaks compatibility with both versions, given that tests pass fully we may not need to release extra artifacts.
Notice that hadoop 3 uses a version of jetty that does not depend on jetty-util so we need to explictly add it to ipc-jetty to avoid runtime issues (ClassNotFoundException) in Avro's tools when using Hadoop 3.
R: @Fokko @dkulp 
CC: @scottcarey

AVRO-2318: Add a new hadoop3 profile and include it in test execution

---

lang/java/avro/pom.xml
lang/java/integration-test/pom.xml
lang/java/ipc-jetty/pom.xml
lang/java/ipc-netty/pom.xml
lang/java/ipc/pom.xml
lang/java/mapred/pom.xml
lang/java/trevni/pom.xml

avro-parent already defines a maven-jar-plugin execution to generate the
test-jar that all others project inherit, so no need to do it again in
every module.

Remove duplicated definitions of maven-jar-plugin

---

lang/java/pom.xml

Test.java in Protobuf test folder is a generated file, and should not be inspected by Spotless.

Exclude generated Protobuf file from spotless check

---

doc/src/content/mddocs/refactoring-resolution.md
lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBlockingIO2.java
lang/java/avro/src/test/java/org/apache/avro/io/TestResolvingIO.java
lang/java/avro/src/test/java/org/apache/avro/io/TestValidatingIO.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestNonStringMapKeys.java

Efforts to improve performance by code-generation and other means have been hampered by the fact that our schema-resolution logic is embedded in resolving-grammar-generation logic (see [AVRO-2275](https://issues.apache.org/jira/browse/AVRO-2275)).  This patch factors the resolution logic out from the grammar-generation logic, so the resolution logic can be more easily reused.  See the design document included in this patch for more information.
This patch consists of the following pieces:
* A design/user-guide document (`refactoring-resolution.md`).
* Core changes: a new file, `Resolver.java`, containing the extracted resolution logic, and a rewrite of `ResolvingGrammarGenerator.java` based on the new `Resolver.java`.
* Changes to resolution-related tests.  These changes do not change the …

AVRO-2275 Refactor schema-resolution code from grammar-generation

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_logical_types.rb

https://issues.apache.org/jira/browse/AVRO-2381
In the Ruby implementation, a logical type associated with a fixed type is incorrectly parsed as a doc attribute (and doc is not supported for a fixed type according to the spec).

[AVRO-2381] Ruby: set logical type for fixed

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificRecordBase.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/integration-test/codegen-test/src/test/java/org/apache/avro/codegentest/TestNestedRecordsWithDifferentNamespaces.java
lang/java/integration-test/codegen-test/src/test/resources/avro/nested_records_different_namespace.avsc
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java
lang/java/tools/src/test/compiler/output/Player.java

The problem was that the generated Java code did not compile for records with nested records in different namespaces. The reason is that these two methods were protected.
The suggested fix is to simply make the methods public, which gets rid of the regression. I realize that this is not good for other reasons (it is after all an internal method), so other suggestions are more than welcome.
This PR also includes a test that reproduced the problem.

AVRO-2386: Make customEncode and customDecode public

---

lang/py3/avro/datafile.py

The corrected code was trying to compare the bytes value returned by GetMeta against a string.
The if was never taken and this was leading to corrupted files when the snappy codes is used.
Here is a minimal test case that demonstrates the issue:
``` python
import avro.schema
from avro.datafile import DataFileReader, DataFileWriter
from avro.io import DatumReader, DatumWriter
schema_text = """
{
"namespace": "example.avro",
"name": "User",
"fields": [
{"name": "name", "type": "string"},
{"name": "favorite_number",  "type": ["int", "null"]},
{"name": "favorite_color", "type": ["string", "null"]}
]
}
"""
schema = avro.schema.Parse(schema_text)
writer = DataFileWriter(open("users.avro", "wb"), DatumWriter(), schema, codec="snappy")
writer.append({"name": "Alyssa", …
```

Fix an incorrect string comparison in avro-python3 leading to corrupted files

---

lang/java/pom.xml

This fixes CVE-2019-12086 on Databind:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9

AVRO-2398 Bump Jackson to 2.9.9

---

lang/py3/MANIFEST.in
lang/py3/setup.cfg
lang/py3/setup.py

The main purpose of this change is to simplify and modernize the setup code without really changing its behavior.
The main change is that I moved most of the setup code into the declarative setup.cfg, where I hope it is somewhat clearer.
I also fleshed out the setup.py commands so that the build.sh and setup.py have parity -- that is, the build.sh is entirely implemented using setup.py.
https://jira.apache.org/jira/browse/AVRO-2391

AVRO-2391 Refactor Py3 Setup

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

Fixing https://issues.apache.org/jira/browse/AVRO-2392
According to the [Avro documentation](https://avro.apache.org/docs/1.8.2/spec.html#Time+%28microsecond+precision%29) `time-micros` and `timestamp-micros` should represent the time instances instead of just Long. 
This PR enables generating expected types for `time-micros` and `timestamp-micros` logicalType fields.

AVRO-2392: enable joda micros logical types supports

---

lang/py/src/avro/io.py
lang/py3/avro/io.py

Switch to using built-in little endian support in the struct
module, instead of explicit bit manipulation.
All tests pass.
(This is a third-party rebase of #132.)
Closes #132

AVRO-1928: Simplify Python float/double encoding

---

lang/py3/avro/schema.py
lang/py3/avro/schemanormalization.py
lang/py3/avro/tests/test_normalization.py

This is a third-party rebase of #258
> An implementation of schema normalization and fingerprinting for Python 3. The code is a fairly literal translation of the Java code and is entirely additional to the existing code, except for one small change in the way `schema.Name` is implemented to improve compatibility with the Java version.
> The new implementation is covered by 138 unit tests which have been automatically generated by a script (not provided) which executed the Java Avro normalization and fingerprinting code to provide expected values for the Python implementation to reproduce.
Closes #258 
https://issues.apache.org/jira/browse/AVRO-2104

AVRO-2104: Schema normalization and fingerprinting for Python 3

---

lang/csharp/src/apache/main/Specific/ObjectCreator.cs
lang/csharp/src/apache/test/File/FileTests.cs
lang/csharp/src/apache/test/Specific/ObjectCreatorTests.cs

I also normalized the style in the `ObjectCreator`.
- https://issues.apache.org/jira/browse/AVRO-2396
- `ObjectCreatorTests.cs`
- 2 tests in `FileTests.cs` that were previously disabled due to performance issues

AVRO-2396: Cache types in ObjectCreator

---

doc/src/content/xdocs/spec.xml
lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityMultiple.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityNameMismatch.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaValidation.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java

Make 1.9.x behavior when parsing qualified names match prior versions.
See https://issues.apache.org/jira/browse/AVRO-2400

AVRO-2400: Make schema resolution behave the same as previous versions

---

lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaValidation.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java

Fix error with resolution with
writer = array<int>
reader = union { null, array<int> }
Resolution works fine in 1.8.2 and got broken with the new Resolver code.
https://issues.apache.org/jira/browse/AVRO-2415

AVRO-2415 - Union resolver regression when dealing with arrays

---

lang/java/avro/src/main/java/org/apache/avro/reflect/AvroAlias.java
lang/java/avro/src/main/java/org/apache/avro/reflect/AvroAliases.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java

[AVRO-2421](https://issues.apache.org/jira/browse/AVRO-2421)
Add all @AvroAlias present on classes and fields to the schema

AVRO-2421 Allow multiple @AvroAliases annotations on classes and fields

---

lang/py/src/avro/__init__.py
lang/py/src/avro/constants.py
lang/py/src/avro/io.py
lang/py/src/avro/schema.py
lang/py/src/avro/timezones.py
lang/py/test/test_io.py
lang/py/test/test_schema.py

This is a third-party rebase of #207.
closes #207

AVRO-1837: Logical Types: date, time & timestamp

---

doc/examples/mr-example/pom.xml
doc/src/content/xdocs/mr.xml

- https://issues.apache.org/jira/browse/AVRO-2428
No additional test since it's mainly a documentation fix. Instead, I walked through the MR document (http://avro.apache.org/docs/current/mr.html) and confirmed all of the commands in that document (`mvn compile` and `mvn exec:java`) worked with the updated pom.xml. Also, I ran `./build.sh dist`
and confirmed that avro-doc-1.10.0-SNAPSHOT was successfully generated.
1. …

AVRO-2428: Update Hadoop version in the MR document

---

share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2436
No additional test, since it's a fix for the test itself. Instead, I ran `./build.sh docker-test` with the revised Dockerfile and confirmed the following message was never shown.
```
[py-test] Snappy not present, will skip testing it.
```
- …

AVRO-2436: Add snappy packages for python2/3 to Dockerfile

---

lang/py3/avro/tests/gen_interop_data.py

- https://issues.apache.org/jira/browse/AVRO-2444
No additional test since it's a fix for an interop test tool itself. I ran the following command and confirmed that the following command succeeded:
```
$ python3 lang/py3/avro/tests/gen_interop_data.py share/test/schemas/interop.avsc /tmp/py3.avro
```
1. Body explains "what" and …

AVRO-2444: Fix gen_interop_data.py to work with interop.avsc

---

lang/py/src/avro/io.py
lang/py3/avro/io.py

Here is a refactor of io.Validate to reduce its complexity and make it more readable.

AVRO-2413: Refactor io.Validate to use a mapping

---

lang/java/avro/src/main/java/org/apache/avro/message/BinaryMessageDecoder.java
lang/java/avro/src/test/java/org/apache/avro/message/TestBinaryMessageEncoding.java

This implements AVRO-2440 by allowing a null value for the readSchema
field in the BinaryMessageDecoder. It is interpreted as "no preference",
and makes the decoder use the write schema of an incoming buffer as its
read schema.
- https://issues.apache.org/jira/browse/AVRO-2440
`org.apache.avro.message.TestBinaryMessageEncoding#testIdenticalReadWithSchemaFromLookup`
- All the public functions and the classes in the PR contain Javadoc that explain what …

AVRO-2440: Decode messages by their write schema

---

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java
lang/java/tools/src/test/compiler/output/Player.java

My PR addressed the following issue: [AVRO-2298](https://issues.apache.org/jira/browse/AVRO-2298) by adding a `org.apache.avro.specific.AvroGenerated` to the Record template. 
Some classes had to be modified so that the unit tests would continue to work as additional annotations had been added these classes are: 
* [lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java](https://github.com/ScottHarwoodTech/avro/blob/22b69578af98d9d81471996f2b909f472bfc308d/lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm)
* [lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java](https://github.com/ScottHarwoodTech/avro/blob/22b69578af98d9d81471996f2b909f472bfc308d/lang/java/tools/src/test/comp …

AVRO-2298: add avro generated annotation to builder class

---

lang/c/docs/CMakeLists.txt

- https://issues.apache.org/jira/browse/AVRO-2425
This change is for the build process, so it's difficult to write unit tests. Instead, I removed the source-highlight package from my OS and ran `./build.sh dist` in the lang/c directory, and confirmed the expected message was shown.
- All …

AVRO-2425: CMake error message for C bindings is misleading

---

lang/py3/avro/tests/test_schema.py

- https://issues.apache.org/jira/browse/AVRO-2439
No additional test since it's a fix for the test itself. I ran `./build.sh test` in the lang/py3 directory and confirmed all of the tests passed.

AVRO-2439: Remove a DeprecationWarning from Py3 test

---

lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java

Lets the test for leaking FileDescriptors pass if the number of open descriptors has gone down.
https://issues.apache.org/jira/browse/AVRO-2448

AVRO-2448: Make test for leaking FileDescriptors more resilient

---

lang/csharp/build.sh

- https://issues.apache.org/jira/browse/AVRO-2442
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x). **n/a**

AVRO-2442: Set LANG variable for C# tests

---

lang/csharp/build.sh

This is the branch-1.9 cherry-pick of #560 .
See: https://issues.apache.org/jira/browse/AVRO-2442

AVRO-2442: Set LANG variable for C# tests - branch 1.9

---

lang/py/src/avro/datafile.py
lang/py/test/test_datafile.py

- https://issues.apache.org/jira/browse/AVRO-2426
I added new codec (zstandard) to CODECS_TO_VALIDATE in test_datafile.py, so if the zstandard python package is installed, read/write are tested in test_round_trip and test_append.
In addition, as an interoperability test, I generated a zstd-compressed Avro file using Java bindings manually and confirmed it can be read from Python2 bindings.
```
$ cd lang/java/tools
$ mvn dependency:copy-dependencies
$ java -cp 'target/avro-tools-1.10.0-SNAPSHOT.jar:target/dependency/*' org.apache.avro.tool.Main fromjson --codec zstandard …
```

AVRO-2426: Add zstd support to Python2 bindings

---

lang/java/avro/src/main/java/org/apache/avro/file/CodecFactory.java

Tested the Codec related unit tests locally. as expected a new log message doesn't impact them.

AVRO-2450 log message about failure to load SnappyCodec

---

lang/php/lib/avro/data_file.php
lang/php/test/DataFileTest.php
lang/php/test/InterOpTest.php
lang/php/test/generate_interop_data.php

- https://issues.apache.org/jira/browse/AVRO-2446
I updated all functions in lang/php/test/DataFileTest.php so that read/write operations are tested for deflated files, not only uncompressed ones. Also, I updated lang/php/test/InterOpTest.php so as to confirm the PHP bindings can read the deflated files that are generated other bindings, such as Java and Ruby.
1. …

AVRO-2446: Add deflate codec support to the PHP bindings

---

lang/java/ipc/src/test/java/org/apache/avro/DataFileInteropTest.java
lang/py/test/test_datafile_interop.py

- https://issues.apache.org/jira/browse/AVRO-2452
No additional test, since it's a fix for the existing test. I ran them manually and ensured that they worked as expected.

AVRO-2452: Interop tests should check the number of records

---

lang/py3/avro/datafile.py
lang/py3/avro/tests/test_datafile.py
share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2460
This PR adds zstd to the codecs to be validated in test_datafile.py. I ran `./build.sh docker-test` and confirmed that all tests passed.

AVRO-2460: Add zstd codec support to the Python3 bindings

---

doc/src/content/xdocs/gettingstartedpython3.xml
doc/src/content/xdocs/site.xml

- https://issues.apache.org/jira/browse/AVRO-2441
No additional test since it's a documentation fix. I ran ant in the doc directory and confirmed that the output was as expected.

AVRO-2441: Add quickstart guide for Python3

---

build.sh
lang/csharp/build.sh
lang/csharp/src/apache/test/Avro.test.csproj
lang/csharp/src/apache/test/Interop/InteropDataConstants.cs
lang/csharp/src/apache/test/Interop/InteropDataGenerator.cs
lang/csharp/src/apache/test/Interop/InteropDataTests.cs

- https://issues.apache.org/jira/browse/AVRO-2459
This PR adds data interop test for the C# bindings. I ran it manually and confirmed it worked as follows:
```
$ cd lang/java/avro
$ mvn -B -P interop-data-generate generate-resources
(snip)
$ cd -
$ ls build/interop/data
java.avro  java_deflate.avro
$ cd lang/csharp
$ ./build.sh interop-data-test
(snip)
Starting test execution, please wait...
Test Run Successful.
Total tests: 1
Passed: 1
Total time: 1.9932 Seconds
$ ./build.sh interop-data-generate
$ cd -
$ ls build/interop/data
csharp.avro  csharp_deflate.avro  java.avro …
```

AVRO-2459: Add data interop test for the C# bindings

---

lang/java/avro/pom.xml
lang/java/ipc/pom.xml
lang/java/pom.xml
lang/py/test/gen_interop_data.py
lang/ruby/interop/test_interop.rb
share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2456
This PR added snappy and zstd interop tests to the Java and Python2 bindings. It also fixed the Ruby bindings to run the interop tests only for null and deflate codecs so that its interop tests pass.
I ran `./build.sh test` locally on the top directory and confirmed that all tests passed.
1. Body wraps at 72 …

AVRO-2456: Add interop test for the snappy and zstd codec

---

build.sh
lang/py3/avro/tests/gen_interop_data.py
lang/py3/avro/tests/test_datafile_interop.py
lang/py3/setup.py

- https://issues.apache.org/jira/browse/AVRO-2469
This PR updates the existing test TestDataFileInterop to read Avro files generated by other language bindings too.

AVRO-2469: Add data interop test to the Python3 bindings

---

lang/ruby/Rakefile

- https://issues.apache.org/jira/browse/AVRO-2475
No additional test, since it's a fix for the test itself. I ran `rake generate_interop` manually and confirmed that output files were generated for all codecs. …

AVRO-2475: rake generate_interop should generate files for all codecs

---

share/test/schemas/reserved.avsc

- https://issues.apache.org/jira/browse/AVRO-2466
No additional test since it's a really obvious and trivial change. I manually executed an one-liner and confirmed the revised schema was successfully parsed.
```
$ python -c 'from avro.schema import parse; parse(open("../../share/test/schemas/reserved.avsc").read())'
$ echo $?
0
``` …

AVRO-2466: Fix a malformed schema in the share/test/schemas directory

---

lang/java/tools/src/main/java/org/apache/avro/tool/Util.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestUtil.java

- https://issues.apache.org/jira/browse/AVRO-2461
testCodecFactoryZstandardCompressionLevel

AVRO-2461: Add compression level support to fromjson and recodec

---

doc/src/content/xdocs/site.xml
doc/src/content/xdocs/tabs.xml

- https://issues.apache.org/jira/browse/AVRO-2483
No additional test, since it's just a documentation fix. I ran `ant` in the `doc` directory and confirmed that those links were fixed in the generated documents. …

AVRO-2483: Fix broken links to wiki pages in the documentation

---

.gitignore
lang/java/avro/src/main/java/org/apache/avro/Schema.java

This method should be removed in the future because it allows to create
invalid schemas (without name) that are not Parseable by Avro.
R: @Fokko

AVRO-2491: Deprecate Schema#createRecord from list of fields method

---

lang/c++/impl/DataFile.cc

While using DataFileReader (C++) through InputStream,
the following error encountered in Ubuntu 14.04, gcc 4.8:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```
The reason is that gcc 4.8 does not allow string(NULL) for initialization.
This fix fixes the issue on gcc 4.8 (Ubuntu 14.04).
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

Fix crash of DataFileReader with gcc 4.8

---

lang/java/avro/src/main/java/org/apache/avro/io/JsonEncoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestEncoders.java

Avoid namespaces to create a Json object without namespaces equal as the original JSON object.
For example:
```
encoder.setIncludeNamespace(false);
```
In case of UNION, instead of creating a a json like:
```
{
"myRecord":  {
"org.apache.avro.MyRecord": {
"name": "testName"
}
}
}
```
It creates something like:
```
{
"myRecord": {
"name": "testName"
}
}
```

Option to remove the namespace from the JSON encoder

---

lang/js/build.sh
lang/js/lib/protocols.js
lang/js/lib/schemas.js
lang/js/lib/utils.js
lang/js/package.json

- https://issues.apache.org/jira/browse/AVRO-2494
This PR adds linting feature to the JavaScript bindings. It also contains fixes for the existing violations.
I ran `./build.sh lint` in the `lang/js` directory and confirmed all violations were fixed.
- All the public functions and the …

AVRO-2494: Introduce JSHint for linting the JavaScript bindings

---

lang/java/grpc/pom.xml

Build log without this fix:
```bash
root@71953052ce65:~/avro/lang/java# ./build.sh lint 
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Avro Java ................................... SUCCESS [  0.360 s]
[INFO] Apache Avro ........................................ SUCCESS [  3.598 s]
[INFO] Apache Avro Compiler ............................... SUCCESS [  0.920 s]
[INFO] Apache Avro Maven Plugin ........................... SUCCESS [  0.923 s]
[INFO] Apache Avro IPC .................................... SUCCESS [  1.170 s]
[INFO] Apache Avro IPC Jetty .............................. SUCCESS [  0.796 s]
[INFO] Apache Avro IPC Netty .............................. SUCCESS [  0.942 s]
[INFO] Trevni Java ........................................ SUCCESS [  0.007 s]
[INFO] Trevni Java Core …
```

AVRO-2510:avro-grpc failed when ./build.sh lint

---

build.sh
lang/c++/build.sh

- https://issues.apache.org/jira/browse/AVRO-2505
No additional test, since it's a fix for the build scripts (with some code cleanup). I locally ran `./build.sh clean` in the lang/c++ directory and `./build.sh veryclean` in the toplevel and confirmed they worked as expected.
- All the …

AVRO-2505: `./build.sh clean` in the c++ directory doesn't remove all temporary files

---

lang/java/tools/src/main/java/org/apache/avro/tool/DataFileWriteTool.java
lang/java/tools/src/main/java/org/apache/avro/tool/RecodecTool.java
lang/java/tools/src/main/java/org/apache/avro/tool/Util.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestCreateRandomFileTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileTools.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestTextFileTools.java

- https://issues.apache.org/jira/browse/AVRO-2465
Added `testDefaultCodec`s to TestCreateRandomFileTool, TestDataFileTools, and TestTextFileTools.

AVRO-2465: Fix wrong defalut values in the avro-tools' usage

---

lang/ruby/Rakefile

- https://issues.apache.org/jira/browse/AVRO-2506
No additional test, since it's a fix for build-related settings. I locally ran `./build.sh dist` in the lang/ruby directory and confirmed it worked as expected. …

AVRO-2506: Fix warnings in creating the Ruby distribution

---

lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java

https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java#L400-L408
We first check if `writerField == null`:
https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java#L400
Then we use it a couple of lines later at 408:
https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java#L408
1. Subject is limited to 50 characters …

AVRO-2512: writerField is always null

---

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java

Enable direct access to utility methods in `ProtobufData` that deal with the message description on a more granular level.
`ProtobufData` presents some great functionality that allows dealing with the Protobuf message descriptors. The intention of this PR is to provide access to the methods that deal with these descriptors on a more granular level. This would make it more flexible for the library clients to deal with their Protobuf message.
In terms of extending the functionality, this would make it possible for clients to adjust some specific moments of the conversion from Protobuf descriptors to Avro schemas.
- https://issues.apache.org/jira/browse/AVRO-2515
- In case you are adding a dependency, check if the license complies with the [ASF …

AVRO-2515: Enable granular access to ProtobufData methods

---

pom.xml

- https://issues.apache.org/jira/browse/AVRO-2530

AVRO-2530: Bump spotless-maven-plugin from 1.21.1 to 1.24.1

---

lang/php/lib/avro/io.php
lang/php/test/StringIOTest.php

- https://issues.apache.org/jira/browse/AVRO-2526
This PR implements test_seek, test_tell, and test_read in lang/php/test/StringIOTest.php.

AVRO-2526: Implement all tests for the PHP bindings

---

lang/java/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2529

AVRO-2529: Bump protobuf-java from 3.6.1 to 3.9.1

---

lang/java/pom.xml

https://jira.apache.org/jira/browse/AVRO-2536

AVRO-2536: Bump netty-codec-http2 from 4.1.33.Final to 4.1.39.Final

---

lang/java/pom.xml

https://jira.apache.org/jira/browse/AVRO-2537

AVRO-2537: Bump zstd-jni from 1.4.0-1 to 1.4.3-1

---

lang/php/README.txt
lang/php/build.sh
lang/php/lib/avro/datum.php
lang/php/test/AllTests.php
lang/php/test/DataFileTest.php
lang/php/test/DatumIOTest.php
lang/php/test/FloatIntEncodingTest.php
lang/php/test/IODatumReaderTest.php
lang/php/test/InterOpTest.php
lang/php/test/LongEncodingTest.php
lang/php/test/NameTest.php
lang/php/test/ProtocolFileTest.php
lang/php/test/SchemaTest.php
lang/php/test/StringIOTest.php
share/docker/Dockerfile

This PR addresses the following incompatibilities between PHP 5.6 and 7.x:
* https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.error-handling.strict
* https://www.php.net/manual/en/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings
* https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
* https://github.com/sebastianbergmann/phpunit/commit/ba2241e6e0a634dc333b6e1d2fd6d0e8c16c2f57
- https://issues.apache.org/jira/browse/AVRO-2527
This PR revises …

AVRO-2527: Upgrade PHP version to 7.x

---

lang/perl/Makefile.PL
lang/perl/build.sh
lang/perl/lib/Avro/Protocol.pm
lang/perl/lib/Avro/Protocol/Message.pm
lang/perl/xt/pod.t
share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2481
This PR adds linting feature to the Perl bindings. It also contains fixes for the existing violations.
I ran `./build.sh lint` in the `lang/perl` directory and confirmed all violations were fixed.
- All the public functions and the classes …

AVRO-2481: Introduce Perl::Critic for linting the Perl bindings

---

lang/py/src/avro/ipc.py
lang/py3/avro/tool.py
share/test/interop/bin/test_rpc_interop.sh

- https://issues.apache.org/jira/browse/AVRO-2507
Fixed share/test/interop/bin/test_rpc_interop.sh to test the RPC interoperability of the Python3 bindings.

AVRO-2507: Add Python3 to the RPC interop test

---

lang/java/avro/pom.xml
lang/java/ipc/pom.xml
lang/java/pom.xml
lang/py/test/test_datafile_interop.py
lang/py3/avro/datafile.py
lang/py3/avro/tests/gen_interop_data.py
lang/py3/avro/tests/test_datafile.py
lang/py3/avro/tests/test_datafile_interop.py

* Add bzip2 and xz support to the Python3 bindings
* Add data interoperability test for these codecs
executed between Java and Python3
* Fix the Python2 data interop test to skip the files
which are compressed with the unsupported codecs
* Add print statements to the Python test codes so that
developers can confirm which files are read and skipped
during the data interop tests
- https://issues.apache.org/jira/browse/AVRO-2546
I added new codecs to the data interoperability test. I ran it locally and confirmed Java and Python3 could read the files compressed by these codecs each …

AVRO-2546: Add bzip2 and xz support to the Python3 bindings

---

lang/java/pom.xml

AVRO-2564:The link address in javadoc-plugin has expired

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/SchemaResolver.java

List<Schema> newSchemas = new ArrayList(types.size());
The generic is declared here, but the initialization is using a non-generic type.

AVRO-2566: Declared generic but did not initialize generic type

---

lang/csharp/src/apache/main/Reflect/ClassCache.cs
lang/csharp/src/apache/main/Reflect/README.md
lang/csharp/src/apache/test/Reflect/TestFromAvroProject.cs
lang/csharp/src/apache/test/Reflect/TestReflect.cs
lang/csharp/src/apache/test/Reflect/TestUnion.cs

AVRO-2499: C# reflect does not cache classes referenced in a union

---

build.sh

- https://issues.apache.org/jira/browse/AVRO-2560
No additional test, since it's a fix for the test itself. I ran `./build.sh test` on the toplevel directory and confirmed it succeeded and took less time (about several minutes, in my environment).
- All the public functions and the classes …

AVRO-2560: Skip unnecessary mvn execution for speeding up tests

---

lang/js/lib/files.js

- https://issues.apache.org/jira/browse/AVRO-2559

AVRO-2559: schema.indexOf(/)is not compatible on windows

---

doc/src/content/xdocs/gettingstartedpython.xml

- https://issues.apache.org/jira/browse/AVRO-2553
No additional test since it's just a documentation fix. I ran `ant` in the `doc` directory and confirmed the fixed document was generated as expected.
- All the public functions and the classes in the PR contain Javadoc that explain what it …

AVRO-2553: Remove unnecessary note from the Python docs

---

doc/src/content/xdocs/spec.xml

Make sure you have checked _all_ steps below. I think it is good practice to add a default value, therefore I'd like to have this on the website as well :-)
- https://issues.apache.org/jira/browse/AVRO-2574

AVRO-2574: Add a default value to the spec

---

pom.xml

AVRO-2586: Bump spotless-maven-plugin from 1.24.1 to 1.25.1

---

lang/java/ipc/src/test/java/org/apache/avro/TestProtocolSpecific.java
lang/java/ipc/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/ipc/src/test/java/org/apache/avro/specific/TestSpecificRecordBuilder.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java

In AbstractAvroMojo developed by maven plugin, @parameter should be set to PRIVATE by default instead of PUBLIC_DEPRECATED.
- https://issues.apache.org/jira/browse/AVRO-2581

AVRO-2581:Generate @Deprecated public attribute in Java

---

lang/py/setup.py
lang/py3/setup.cfg

AVRO-2601: zstandard in extras_require

---

lang/py/test/test_tether_word_count.py

Fixes a bug where when a test fails the cleanup code tries to access a variable that might not have been defined when the error occurred. While I ultimately prefer the changes in #679, that PR has some problem with the Java 11 tether test. This PR is a much smaller changeset and solves the immediate problem, so it may be possible to merge it sooner.

AVRO-2593: Ensure exfile is Always Defined

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_fingerprints.rb

This patch adds support for the [Single Object Encoding Spec](http://avro.apache.org/docs/current/spec.html#single_object_encoding_spec).
I translated the code from Java to Ruby.
I believe this is a performant implementation in Ruby.
I'm not sure this is the right place for this code, but I couldn't think of a better one. Definitely open to suggestions / feedback!
Hope this helps,

Add Single Object Encoding Support to Ruby library

---

lang/py/test/test_tether_word_count.py

This change moves the imports embedded in test functions to the top of the test module. It also standardizes the imports and removes some unnecessary ones.

AVRO-2603: Clean Up Imports

---

lang/py/src/avro/schema.py
lang/py/test/test_schema.py

- making example schema readable
- splitting test_parse into valid vs invalid checks
- Removing dedicated `test_decimal_*` tests and moving their fixtures so they get run by the generic schema.parse tests.

AVRO-2580: Enforce Logical Type and Literal Type Match

---

lang/js/lib/files.js
lang/js/test/test_files.js

- https://issues.apache.org/jira/browse/AVRO-2562
Fixed a flaky test called createFileEncoder in lang/js/test/test_files.js. I also iterated `npm t` 100 times with both node v6.17.1 and v8.10.0 locally and confirmed no failure occurred. …

AVRO-2562: Expose the JavaScript BlockEncoder's piped stream

---

BUILD.md

According to BUILD.md compile and build c error.
Found missing dependencies in BUILD.md: jansson and pkg-config
- https://issues.apache.org/jira/browse/AVRO-2568

AVRO-2568:Add c compile dependency instructions to BUILD.md

---

lang/py/src/avro/datafile.py
lang/py/test/test_datafile.py
lang/py3/avro/datafile.py
lang/py3/avro/tests/test_datafile.py

Fix DataFileReader so it can handle datafiles with zero blocks in them. I refactored David Beswick's patch in the ticket to close out two old TODOs in the DataFileReader iterator implementation.

AVRO-2432: Handle Empty Datafiles

---

lang/java/pom.xml

There has been several point releases in Hadoop since 2.7.3.  
This bumps the version to 2.7.7 to fix a bug when using avro-tools and some recent JDKs.  See https://issues.apache.org/jira/browse/AVRO-2561 for an error which occurs when the java.version reported by the JDK is less than three characters.
Alternatively, we could switch to the -Phadoop3 profile for the default build.
- https://issues.apache.org/jira/browse/AVRO-2561
Testing over all possible providers of all versions of JDK would be prohibitively expensive!
1. Subject is limited to 50 characters (not including Jira …

AVRO-2561: Bump hadoop dependency to 2.7.7.

---

lang/py/src/avro/schema.py
lang/py/test/test_io.py
lang/py/test/test_schema.py

When an unknown or invalid logical type is encountered, it should be ignored by the implementation.  The python2 implementation throws an exception instead.
It appears that just *not* throwing the exception behaves correctly.
- https://issues.apache.org/jira/browse/AVRO-2429 …

AVRO-2429: Ignore unknown logical types in python2.

---

lang/c++/MainPage.dox

- https://issues.apache.org/jira/browse/AVRO-2570

AVRO-2570 - Code line doesn't match the code in Avro C++ Document

---

lang/c++/impl/Node.cc
lang/c++/test/SchemaTests.cc
lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java
lang/java/avro/src/test/java/org/apache/avro/TestLogicalType.java
lang/js/doc/Advanced-usage.md

Currently, when checking the maximum precision for the `decimal` logical type with underlying `fixed` Avro primitive, some implementations use 2<sup>8 × n - 1</sup>  in the formula.
This will overflow a 64 bit floating point number like a Java double at n = 129.
Using the [log power rule](https://en.wikipedia.org/wiki/Logarithm#Product,_quotient,_power,_and_root), we can avoid the overflow by replacing:
**floor(log<sub>10</sub>(2 <sup>8 × n - 1</sup>  - 1))**  
with 
**floor(log<sub>10</sub>(2) × (8 × n - 1))**.
(*N.B.*: There's a missing "minus 1" step in the second formula -- it's OK to omit it because **2<sup>X</sup>-1** and **2<sup>X</sup>** are guaranteed to contain the same number of decimal digits for any X.)
- https://issues.apache.org/jira/browse/AVRO-2620
- In case you are …

AVRO-2620: Calculate max precision for fixed decimal logical type.

---

lang/py3/avro/tests/test_datafile.py
lang/py3/setup.py

AVRO-2615: Fail the Linter when Pycodestyle Fails

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs

- https://issues.apache.org/jira/browse/AVRO-2617
- CodeGen tests still passing 👍 

AVRO-2617: Use consistent line endings in C# CodeGen

---

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java

In this PR, I simply cherry-picked 2b75804d73fa3a8d4d25be2f79aa772f5965bbcd from master.
In [AVRO-2632], I'm trying to determine whether this is the correct approach. The other option I've identified so far is to drop the Jackson version back down to 2.9.9.
[AVRO-2632]: https://issues.apache.org/jira/browse/AVRO-2632

AVRO-2632: Fix Jackson upgrade errors

---

lang/csharp/src/apache/main/File/DataFileReader.cs
lang/csharp/src/apache/main/File/DataFileWriter.cs
lang/csharp/src/apache/test/File/FileTests.cs

This commit allows to support non-seekable Stream as reading input in
avro DataFileReader. This allow not to force the user to fully download
a file from a network storage prior to read it.
When creating an DataFileReader with a non-seekable Stream, features as
Seek(), Sync(), PastSync(), PreviousSync() and Tell() can't be used.
- [X ] My PR adds the following unit tests : TestNonSeekableStream that ensure a standard non-seekable Stream (DeflateStream used to implement the test) can be used as DateFileReader Stream.
- [ X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
1. Subject is separated …

AVRO-2618: DataFileReader supports non-seekable Streams

---

lang/py/src/avro/schema.py
lang/py/test/test_schema.py

Instead of silently ignoring LogicalTypes that happen to be invalid (for any reason), this PR brings in the warning module to print a warning to the output when the schema is encountered.  At runtime, this can be configured to be fatal, or silently ignored.
- https://issues.apache.org/jira/browse/AVRO-2611
- All the public functions …

AVRO-2611: Use warnings for invalid logical types.

---

lang/py/test/test_tether_word_count.py

_Blocked by [AVRO-2624](https://issues.apache.org/jira/browse/AVRO-2603)._
Avoid the need to generate a script in a temporary file by providing the python path in the environment.

AVRO-2603: Provide PYTHONPATH in Environment

---

lang/py/src/avro/datafile.py
lang/py/src/avro/ipc.py
lang/py/src/avro/tether/tether_task.py
lang/py/src/avro/txipc.py
lang/py/test/test_io.py
lang/py/test/test_script.py
lang/py/test/test_tether_task.py
lang/py/test/test_tether_task_runner.py

The name collision between `io` and `avro.io` is resolved in this codebase. It could still be an issue if a user invokes a python module directly on the command line as in `python lang/py/build/src/avro/tool.py …`. This approach causes python to prepend that path to the pythonpath, which enables the collision. Using `python -m avro.tool …` is a safe alternative. In another pr we may want to consider installing `tool.py` via setuptools' `console_script` entrypoint. However, if we do that, we should probably pick a better name than just "tool".
The problem in `avro.tether.tether_task` was resolved by replacing the buffer object each time. This is fine; however, the next problem is the name collision between `io` and `avro.io`.
I think I found the root cause of the discrepancy. I still don't …

AVRO-1880: Futurize Py2 via BytesIO

---

lang/py/src/avro/protocol.py
lang/py/test/test_protocol.py
lang/py/test/test_schema.py

AVRO-748: Protocol Error Schema Implicit String

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/integration-test/codegen-test/pom.xml
lang/java/integration-test/codegen-test/src/test/java/org/apache/avro/codegentest/TestLogicalTypeForStringType.java
lang/java/integration-test/codegen-test/src/test/resources/avro/string_logical_type.avsc

When using 'stringType', logical types whose
Avro type was string would not have that conversion
applied.
- https://issues.apache.org/jira/browse/AVRO-2548
TestLogicalTypeForStringType#shouldUseUUIDAsType

AVRO-2548: Handle logicalTypes with stringType

---

share/docker/Dockerfile

**Note**: I separated the perl modules installed via apt-get to be in the "perl" section and close to the CPAN installation.
I checked that all of the modules were available with `perl -e "use Compress::Zlib"` inside the docker.
- https://issues.apache.org/jira/browse/AVRO-2630 …

AVRO-2630: Use apt-get to install perl modules.

---

.travis/script.sh
build.sh
share/docker/Dockerfile
share/docker/DockerfileLocal
share/precommit/buildtest.sh

It currently takes some manual intervention to create a "local user" docker image based on Java 11.
This PR adds *both* JDK8 (default) and JDK11 to the docker, so the same container can be used to build the two versions.
* Not setting the `JAVA` environment variable will use the java on the path.
* Setting the `JAVA` environment variable will add the JDK to use to the front of the path **inside the main build.sh** script (but only if the JDK is in the expected place).
* The `lang/java/build.sh` always uses the JDK on the path.
*N.B.* The docker image tag that is generated always has the unchanged form `avro-build-rskraba:latest`.
- https://issues.apache.org/jira/browse/AVRO-2594
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …

AVRO-2594: Use JAVA env when building local docker.

---

lang/c/src/avro_generic_internal.h

Currently, the avro C library can not be built for Linux systems based on the [musl standard C library](https://www.musl-libc.org/), which is often used on embedded systems. See the full commit message for more details.
This PR has been tested against the following C libraries, on x86 and arm architectures:
* uClibc
* musl
* glibc
-----
- My PR does not have an associated JIRA issue
- My PR does not add new tests, as it fixes a compilation issue within a particular build environment that is currently not reproducible in Travis
1. Subject uses the imperative mood ("add", not …

Allow avro C to be built on musl based systems.

---

lang/java/tools/src/main/java/org/apache/avro/tool/SpecificCompilerTool.java

Happy to add tests, though would greatly appreciate some guidance as to how. Should I create a new schema directory in `lang/java/tools/src/test/compiler/input`? Should I just test the `sortFiles` function? 
Is there a good place to put this for documentation of the tool itself? In the Usage text? Some other place? 
Thanks!

AVRO-2644: Non-Deterministic avsc Directory Compilation

---

lang/py/.gitignore
lang/py/MANIFEST.in
lang/py/avro/test/test_script.py
lang/py/avro/test/test_tether_task_runner.py
lang/py/build.sh
lang/py/scripts/avro
lang/py/setup.cfg
lang/py/setup.py
lang/py/tox.ini
share/docker/Dockerfile

AVRO-2652: Use Tox to Enable Multi Python Testing

---

lang/java/avro/src/main/java/org/apache/avro/data/RecordBuilderBase.java
lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

AVRO-2654: Use JDK Arrays.copyOf

---

lang/ruby/Gemfile

The CI is broken because of a new release of rdoc, which is being pulled in using a transitive dependency.
Ruby rdoc 6.2.1 has been released which requires Ruby 2.4: https://rubygems.org/gems/rdoc/versions/6.2.1
We would like to contrain this to 6.2.0: https://rubygems.org/gems/rdoc/versions/6.2.0
https://jira.apache.org/jira/browse/AVRO-2664
1. Subject uses the imperative …

AVRO-2664: Pin Ruby rdoc to <=6.2.0

---

lang/ruby/lib/avro.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_schema.rb
lang/ruby/test/test_schema_validator.rb

- https://issues.apache.org/jira/browse/AVRO-2645
* Test that invalid names fail schema parsing
- [] In case of new functionality, my PR adds documentation that describes how to use it.

AVRO-2645: Validate names in schemas in Ruby client

---

lang/py/avro/datafile.py
lang/py/avro/io.py
lang/py/avro/ipc.py
lang/py/avro/protocol.py
lang/py/avro/schema.py
lang/py/avro/test/gen_interop_data.py
lang/py/avro/test/mock_tether_parent.py
lang/py/avro/test/test_datafile.py
lang/py/avro/test/test_datafile_interop.py
lang/py/avro/test/test_io.py
lang/py/avro/test/test_protocol.py
lang/py/avro/test/test_schema.py
lang/py/avro/test/test_script.py
lang/py/avro/test/test_tether_task.py
lang/py/avro/test/test_tether_task_runner.py
lang/py/avro/test/test_tether_word_count.py
lang/py/avro/tether/tether_task.py
lang/py/avro/tether/tether_task_runner.py
lang/py/scripts/avro
lang/py/setup.cfg
lang/py/tox.ini

- closes #133
- closes #234
- closes #251

AVRO-2656: Python3 Support for lang/py

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_schema.rb

- https://issues.apache.org/jira/browse/AVRO-2677
- `test_bytes_decimal_to_include_precision_scale`
- `test_bytes_decimal_to_without_precision_scale`
- `test_bytes_schema`

 AVRO-2677: Ruby parse/serialize bytes decimal logical type

---

lang/java/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2674

AVRO-2674: Bump netty-codec-http2 from 4.1.42.Final to 4.1.44.Final

---

lang/java/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2673

AVRO-2673: Bump protobuf-java from 3.10.0 to 3.11.1

---

pom.xml

- https://issues.apache.org/jira/browse/AVRO-2672

AVRO-2672: Bump spotless-maven-plugin from 1.25.1 to 1.27.0

---

lang/java/ipc/src/test/java/org/apache/avro/TestProtocolSpecific.java

It is better to use the getter instead. This prohibited me from compiling the 1.9 branch locally.
- https://issues.apache.org/jira/browse/AVRO-2669

AVRO-2669: TestProtocolSpecific use getClientProtocol getter

---

doc/src/content/mddocs/refactoring-resolution.md
lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/ResolvingDecoder.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/Parser.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/util/internal/JacksonUtils.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java
lang/java/avro/src/test/resources/schema-location-read.json
lang/java/avro/src/test/resources/schema-location-write.json
lang/java/avro/src/test/resources/schema-location.json
lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java
lang/java/thrift/src/main/java/org/apache/avro/thrift/ThriftData.java

Make sure you have checked _all_ steps below:
```
java.lang.AssertionError: expected null, but was:<-1.539054>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotNull(Assert.java:755)
at org.junit.Assert.assertNull(Assert.java:737)
at org.junit.Assert.assertNull(Assert.java:747)
```
The problem was, using writeschema:
```
{
"name": "table",
"fields": [{
"name": "location",
"type": ["null", {
"type": "map",
"values": ["null", {
"name": "r7",
"fields": [{
"name": "lat",
"type": "float",
"field-id": 1
}, {
"name": "long",
"type": ["null", "float"],
"default": null,
"field-id": 2
}]
}],
"key-id": 6,
"value-id": 7
}],
"default": null,
"field-id": 5
}]
}
```
And reading it with:
```
{
"name": "table",
"fields": [{
"name": …
```

AVRO-2663: Record inside of Union is not resolved properly

---

build.sh

This change fixes the vast majority of problems identified by shellcheck in the build script. The others will take significantly more effort to fix.

AVRO-2679: Fix Shellcheck Warnings in build.sh

---

lang/c++/.gitignore
lang/py/.gitignore
lang/py/build.sh
pom.xml

Some of the recent changes in various languages have added / removed temporary files.  It's simpler for local development if the lists of files excluded by git and rat is kept up to date.
To check, after a complete local build, it should be possible to do a `./build.sh rat` without failure, and a `git status` without new files appearing.
This should have no effect on the CI build.
- https://issues.apache.org/jira/browse/AVRO-2675
1. Subject does not end with …

AVRO-2675: Maintain .gitignore and rat exclusions

---

lang/java/pom.xml

This includes a security fix:
Moderate severity vulnerability that affects org.eclipse.jetty:jetty-server In Eclipse Jetty versions 9.4.21.v20190926, 9.4.22.v20191022, and 9.4.23.v20191118, the generation of default unhandled Error response content (in text/html and text/json Content-Type) does not escape Exception messages in stacktraces included in error output.
Affected versions: = 9.4.21.v20190926
- https://issues.apache.org/jira/browse/AVRO-2686
1. …

AVRO-2686: Bump jetty.version from 9.4.21.v20190926 to 9.4.25.v20191220

---

lang/java/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2684

AVRO-2684: Bump netty-codec-http2 from 4.1.44.Final to 4.1.45.Final

---

lang/java/tools/src/main/java/org/apache/avro/tool/DataFileReadTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileTools.java

- https://issues.apache.org/jira/browse/AVRO-2689
- testReadWithReaderSchema
- testReadWithIncompatibleReaderSchema
- testReadWithReaderSchemaFile

AVRO-2689:  add reader-schema to DataFileReadTool

---

lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericLogicalTypes.java

- https://issues.apache.org/jira/browse/AVRO-2592

AVRO-2592: Avoid consuming ByteBuffer for decimal.

---

lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroRequestMarshaller.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroResponseMarshaller.java
lang/java/pom.xml
pom.xml

Including the JIRAs that have bumped dependencies in 1.10.0-SNAPSHOT.
This builds on #794 and should be merged afterwards.   Commits in this PR start from `AVRO-2537: Bump zstd-jni from 1.4.0-1 to 1.4.3-1 (#630)`
- https://issues.apache.org/jira/browse/AVRO-2721
Only includes cherry-picked commits.
Only includes cherry-picked commits.
Only includes cherry-picked commits.

AVRO-2721: Version bump cherry-picks for 1.9.2

---

lang/java/avro/pom.xml
lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
lang/java/avro/src/main/java/org/apache/avro/io/FastReaderBuilder.java
lang/java/avro/src/main/java/org/apache/avro/io/ReflectionUtils.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

Cannot reopen the original PR (#354), since I've rebased to current master.
I've tried to adress the points that @rstata brought up with my approach. The feature switch between traditional and newly suggested reader mechanism now is done inside `GenericDatumReader`. All tests provided with the avro project run smoothly (I stole @rstata's idea to trigger the tests an additional time with the feature switch enabled). Also fixed defaulting in a way that takes advantage of immutable values and only actually re-reads default objects with a distinct decoder when really required.
If there is any more things that would need testing, please do give me a pointer.
Overall, the newly proposed writer sacrifices time building a `DatumReader`, allowing it to perform the actual reading at a highly …

AVRO-2247 - improved java reading performance with new reader

---

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java

Changed from casting object to String when schema expects String field. Since Avro can represent Strings in Java as either String, CharSequence or org.apache.avro.util.Utf8, the put can fail with a ClassCastException. By changing from cast to toString() the issue is circumvented.
Updated existing unit tests to reflect changes.

AVRO-2641: Fix for SpecificRecord String deserialization

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java

-  [x] My PR  addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-2031) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
- https://issues.apache.org/jira/browse/AVRO-2031 …

AVRO-2031 GenericData.writeEscapedString should be static

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/ipc/src/test/java/org/apache/avro/TestSchema.java

Fixes print-parse consistency for named types with null namespace,
enclosed in named fields with null namespace, which are themselves
enclosed in named fields with non-null namespace.
Currently, if a type specifies the null namespace, this overrides the
enclosing non-null namespace for the purpose of naming that type, but
not for the purposes of determining the closest enclosing namespace for
more deeply nested types. This fixes that by removing special-casing of
null when setting the default namespace for recursively parsed schemas.
For example:
```json
{
"name": "Outer",
"space": "space",
"fields": [
{
"name": "f",
"type": {
"name": "Inner",
"namespace": "",
"fields": [
{
"name": "x",
"type": {
"name": "Deeper",
"fields": [
{
"name": …
```

AVRO-1646: Print/parse consistency for nested null namespace

---

share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2732
Build fix.

AVRO-2732: Fix openjdk changes by using stretch base image

---

lang/java/avro/src/main/java/org/apache/avro/Resolver.java

- https://issues.apache.org/jira/browse/AVRO-2716

AVRO-2716 Removed unused variable in Resolver

---

lang/py/avro/protocol.py
lang/py/avro/test/test_protocol.py

AVRO-2741: Fix Protocol.fullname Crash

---

lang/py3/setup.py

There was a regression / cherry-pick error in the avro-python3 1.9.2 release with this unused import.  There is no issue to fix on master.
The artifact was republished as avro-python3 1.9.2.1 with this change applied manually, and it should definitely be applied to future releases on this branch (if any).
N.B. the avro-python3 1.9.2.1 release is source-identical to the signed 1.9.2 code; just the `setup.py` was fixed to install the module correctly via pip.
- https://issues.apache.org/jira/browse/AVRO-2737
1. Subject is limited to 50 characters (not including Jira issue …

AVRO-2737: Fix pycodestyle regression.

---

lang/java/avro/src/main/java/org/apache/avro/data/RecordBuilderBase.java

- https://issues.apache.org/jira/browse/AVRO-2691

AVRO-2691: Do Not Cache Empty Array in RecordBuilderBase

---

lang/py/build.sh
lang/py/setup.cfg
lang/py/setup.py
lang/py/tox.ini

Having `setup_requires` in setup.cfg causes problems for folks trying to install avro behind a proxy, since `pip` doesn't use the `-i` option for stuff in `setup_requires`. However, we don't really need the `setup_requires` now that we have tox.

AVRO-2747: Remove setup_requires

---

lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java

- https://issues.apache.org/jira/browse/AVRO-2692

AVRO-2692: Do Not Access Map Twice in LogicalTypes

---

share/docker/Dockerfile

These ones are missing in master from the fixes for branch-1.9
R: @RyanSkraba

AVRO-2732: Add missing packages to avoid warnings in the docker image

---

lang/java/tools/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2709

AVRO-2709: Remove Superfluous Dependencies from Avro-Tools Shaded JAR

---

lang/ruby/test/case_finder.rb
lang/ruby/test/test_schema_normalization.rb

- https://issues.apache.org/jira/browse/AVRO-2756
This PR fixes lang/ruby/test/test_schema_normalization.rb to test schema fingerprints in addition to schema normalization.

AVRO-2756: Ruby should test all schema fingerprints defined in share/test/data/schema-tests.txt

---

lang/ruby/test/random_data.rb
lang/ruby/test/test_io.rb

- https://issues.apache.org/jira/browse/AVRO-2755
This PR fixes lang/ruby/test/test_io.rb to test the TimestampMillis logical type in addition to TimestampMicros.

AVRO-2755: Add I/O tests for the TimestampMillis logical type to Ruby

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/main/Util/LogicalTypeFactory.cs
lang/csharp/src/apache/main/Util/Uuid.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs
lang/csharp/src/apache/test/Util/LogicalTypeTests.cs
lang/java/avro/src/main/java/org/apache/avro/data/RecordBuilderBase.java

- https://issues.apache.org/jira/browse/AVRO-2754
- Modified codegen test to add logical type tests. Nullable value types were also broken in the test so that fix sneaked in
- LogicalTypeTests.TestUuid - Verifies translation between serialized string and System.Guid

AVRO-2754: Add support for UUID logical types in C#

---

lang/js/package.json

Backport to 1.9. See #827.
I just updated package.json but not package-lock.json, because the Dockerfile provided by branch-1.9 installs npm 3.x, which does not support package-lock.json ([that support was added in version 5](https://nodejs.dev/the-package-lock-json-file)).
----
- https://issues.apache.org/jira/browse/AVRO-2758
No additional test, since it's a version upgrade for a code coverage tool. I ran `./build.sh test` and `./build.sh dist` in lang/js and confirmed that they succeeded.
1. Subject is limited to 50 characters …

AVRO-2758: Bump istanbul to 0.4.5

---

lang/ruby/test/test_schema_validator.rb

- https://issues.apache.org/jira/browse/AVRO-2759
This PR renames the TestSchema class in lang/ruby/test/test_schema_validator.rb to TestSchemaValidator to avoid a function name conflict.

AVRO-2759: Fix Ruby test not to redefine a function with the same name

---

lang/java/perf/src/main/java/org/apache/avro/perf/test/record/RecordTest.java

- https://issues.apache.org/jira/browse/AVRO-2701

AVRO-2701: Add JMH BlackHole to RecordTest

---

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java
lang/java/protobuf/src/test/java/org/apache/avro/protobuf/TestProtobuf.java

… fields
- https://issues.apache.org/jira/browse/AVRO-2788
- TestProtobuf#testMessageWithEmptyArray
- TestProtobuf#testEmptyArray

AVRO-2788: Default Proto repeated fields to empty arrays

---

lang/ruby/lib/avro/io.rb
lang/ruby/test/test_io.rb

Ruby allows hash keys to be any simple type, but when encoding a hash with non-string keys the error raised is not obvious as to the issue (`The datum nil is not an example of schema "long" (Avro::IO::AvroTypeError)`).
Rather than attempt to provide a more meaningful error, enhancing the encoding to handle keys of all types allows user flexibility.

AVRO-2749: Add ruby support for datum hashes with non-string keys

---

lang/py3/build.sh

- https://issues.apache.org/jira/browse/AVRO-2791
No additional test, since it's a minor fix for a building script. I manually ran it and confirmed that it worked as expected.
```
$ git diff
diff --git a/lang/py3/build.sh b/lang/py3/build.sh
index fc4564f9..4ed60566 100755
--- a/lang/py3/build.sh
+++ b/lang/py3/build.sh
@@ -33,8 +33,8 @@ main() {
clean|dist|isort|test) :;;
*) usage; return 1;;
esac
+    python3 setup.py "$target"
done
-  python3 setup.py "$@"
}
main "$@"
$ ./build.sh docker
(snip)
sekikn@c872b71de646:~/avro$ cd lang/py3
sekikn@c872b71de646:~/avro/lang/py3$ …
```

AVRO-2791: Fix lang/py3/build.sh to process each argument separately

---

lang/py/avro/tool.py
lang/py3/avro/tool.py

AVRO-2765: Py3 Support: Use open(), not file()

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java

- https://issues.apache.org/jira/browse/AVRO-2801

AVRO-2801: Cache Hashcode of UTF8 Strings in all Set Methods

---

share/docker/Dockerfile

No additional test, since it's a fix for Dockerfile. I ran `./build.sh docker` with the new Dockerfile and `cd lang/perl; ./build.sh test` in the newly created container, and confirmed they worked.
- All the public functions and the classes …

AVRO-2816: Remove duplicated Perl library from Dockerfile

---

build.sh
lang/c++/build.sh
lang/c++/impl/Zigzag.cc
share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-2813
No additional test, since this PR is just adding a static code analysis process for Avro C++.
I ran `./build.sh lint` locally and confirmed it worked as expected. …

AVRO-2813: Add cppcheck as a C++ linter

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java

- https://issues.apache.org/jira/browse/AVRO-2790

AVRO-2790:Necessity of using Object as parameter of javaEscape method

---

lang/py/avro/test/av_bench.py
lang/py/avro/test/sample_http_server.py
lang/py/avro/test/test_protocol.py
lang/py/avro/test/test_schema.py
lang/py/avro/tether/tether_task.py
lang/py/avro/tether/tether_task_runner.py
lang/py/avro/tool.py
lang/py/mypy.ini
lang/py/setup.py
lang/py/tox.ini
share/docker/Dockerfile

This PR adds type checking to the tox tests that run locally and in Travis. Mypy is lightly configured, and already uncovered some minor problems that the tests didn't catch. However, at this stage we only have about 58% coverage via typing. (You can see the coverage by running `pip install lxml && mypy --html-report mypyhtml && open mypyhtml/index.html`.)

AVRO-2387: Type Check Python

---

lang/py/avro/test/test_init.py
lang/py3/avro/__init__.py
lang/py3/avro/tests/run_tests.py
lang/py3/avro/tests/test_init.py

- https://issues.apache.org/jira/browse/AVRO-2814
- lang/py/test/test_init.py
- lang/py3/test/test_init.py

AVRO-2814: Add __version__ to __init__.py (PEP396)

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/util/internal/JacksonUtils.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectData.java

No new tests are needed. I just refactor the code base.

AVRO-2723: Refactor ReflectData to allow derived classes to customize default values for fields

---

lang/java/avro/src/main/java/org/apache/avro/util/internal/JacksonUtils.java
lang/java/avro/src/test/java/org/apache/avro/util/internal/TestJacksonUtils.java

this change is relatively small, so I didn't submit a issue in jira.
It allows JacksonUtils.toJsonNode(Object datum) receive type `BigInteger` and `BigDecimal`.
- https://issues.apache.org/jira/browse/AVRO-2819

AVRO-2819:Add BigInteger and BigDecimal support for JacksonUtils

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_schema.rb
lang/ruby/test/test_schema_compatibility.rb

Added Ruby support for enum type defaults introduced in v1.9.0.
Existing non-conforming Ruby behavior is preserved to return
unknown writer's symbols when no enum default is present.
When an enum default is present it is returned instead of an
unknown writer's symbol.
Compatibility checking still strictly enforces the specification.
- [x My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title:
- https://issues.apache.org/jira/browse/AVRO-2535
- test_enum_with_default
- test_unknown_enum_symbol
- test_unknown_enum_symbol_with_enum_default
- test_enum_default_attribute
- test_validate_enum_default
- new test case within test_compatible_reader_writer_pairs
1. Subject is …

AVRO-2535: Add Ruby support for enum defaults

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java

I need a method to reconstruct the original schema string before referenced schemas were resolved and inlined by the Parser.   This is a small enhancement that addresses https://issues.apache.org/jira/browse/AVRO-2822 by exposing a toString() method to pass the referenced schemas.
This also addresses https://github.com/confluentinc/schema-registry/issues/1432

AVRO-2822: Add toString that doesn't inline referenced schemas

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/IDLProtocolMojo.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/ProtocolMojo.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/SchemaMojo.java

- https://issues.apache.org/jira/browse/AVRO-2745

AVRO-2745: Generate optional getters for nullables only

---

lang/php/lib/avro/datum.php

This property is used in `AvroDataIOWriter::__construct()` and therefore it has to be public.
https://jira.apache.org/jira/browse/AVRO-2827

[AVRO-2827] Fixes property visibility.

---

lang/php/lib/avro.php
lang/php/lib/avro/data_file.php
lang/php/lib/avro/datum.php
lang/php/lib/avro/protocol.php
lang/php/test/DataFileTest.php
lang/php/test/FloatIntEncodingTest.php
lang/php/test/InterOpTest.php
lang/php/test/LongEncodingTest.php
lang/php/test/ProtocolFileTest.php
share/docker/Dockerfile

Fixes deprecated warnings and ensures PHP 7.4 compat.

AVRO-2751: Upgrade Compatibility to PHP 7.4

---

lang/py/avro/test/test_datafile_interop.py

- https://issues.apache.org/jira/browse/AVRO-2833

AVRO-2833: Fix python whitespace for lint

---

lang/c++/api/Specific.hh

Avro currently constructs map and vector elements on the stack, decodes in to them, and then *copies* the resulting values in maps and vectors.
This results in a lot of unnecessary memory allocation when decoding.

Use std::move when decoding maps and vectors

---

lang/c++/api/Zigzag.hh

- https://issues.apache.org/jira/browse/AVRO-2766

AVRO-2766: Fix compilation error: 'size_t' does not name a type

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectData.java

- https://issues.apache.org/jira/browse/AVRO-2808

AVRO-2808: provide details while encountering non-static inner classes

---

lang/c/examples/quickstop.c

- https://issues.apache.org/jira/browse/AVRO-2551

AVRO-2551:Changed datum API to value API in examples\quickstop

---

lang/c++/api/LogicalType.hh
lang/c++/impl/Compiler.cc
lang/c++/impl/LogicalType.cc
lang/c++/impl/Node.cc
lang/c++/test/SchemaTests.cc

Add support  for UUID logical type in C++ api as defined in Apache Avro 1.9.0 Specification

Add support for uuid logical type in C++

---

doc/src/content/xdocs/spec.xml

- https://issues.apache.org/jira/browse/AVRO-2427
No additional test since it's a documentation fix. I ran `ant` in the `doc` directory and made sure the fix updated the document as expected.

AVRO-2427: Add undocumented codecs to the specification

---

lang/java/ipc/src/test/java/org/apache/avro/io/Perf.java

- https://issues.apache.org/jira/browse/AVRO-2523
No additional test, since it's a minor fix for the existing test tool. Instead, I ran the following commands locally and confirmed they behaved as expected:
```
~/avro/lang/java/ipc$ mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass=org.apache.avro.io.Perf -Dexec.args="-h"
(snip)
-specific   (executes all specific tests):
-Sf  (FooBarSpecificRecordTest)
(snip)
~/avro/lang/java/ipc$ mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass=org.apache.avro.io.Perf -Dexec.args="-specific"
(snip)
Executing tests: …
```

AVRO-2523: Perf's usage doesn't show the option for specific record test

---

lang/perl/lib/Avro.pm
lang/perl/lib/Avro/DataFile.pm
lang/perl/lib/Avro/DataFileReader.pm
lang/perl/lib/Avro/DataFileWriter.pm
lang/perl/t/04_datafile.t

- https://issues.apache.org/jira/browse/AVRO-2547
I updated lang/perl/t/04_datafile.t to add a test for the bzip2 codec.

AVRO-2547: Add bzip2 support to the Perl bindings

---

lang/ruby/interop/test_interop.rb

- https://issues.apache.org/jira/browse/AVRO-2554
No additional test since it's a fix for the existing test itself.

AVRO-2554: Fix Ruby interop test to read all supported codecs

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/protocol.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

In lang/java/compiler/../SpecificCompiler#javaUnbox(Schema, boolean), 
Utility for template use. Returns the unboxed java type for a Schema including the void type
Used for preventing unnecessary returns for RPC methods without response but with error(s).
This is great.
But in the javaUnbox (Schema) comment added @deprecated, but did not add @Deprecated on the method definition, JDK does not want this, they should exist at the same time, otherwise the compiler will have a warning
- https://issues.apache.org/jira/browse/AVRO-2569
1. …

Avro 2569 @Deprecated annotation usage does not conform to the Java specification

---

lang/java/avro/src/main/java/org/apache/avro/message/BinaryMessageEncoder.java
lang/java/avro/src/main/java/org/apache/avro/message/RawMessageEncoder.java
lang/java/avro/src/main/java/org/apache/avro/package.html
lang/java/avro/src/main/java/org/apache/avro/reflect/MapEntry.java
lang/java/avro/src/main/java/org/apache/avro/specific/package.html
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/SchemaVisitor.java
lang/java/mapred/src/main/java/org/apache/avro/hadoop/io/AvroSequenceFile.java
lang/java/mapred/src/main/java/org/apache/avro/mapred/tether/TetherJob.java

In ./build.sh dist, there are many tags @link: reference not found
@return null and more...
So, I just have a little time to do something for the community.
Thanks.
Best regards.
- https://issues.apache.org/jira/browse/AVRO-2573 …

AVRO-2573:Javadoc Warning in java compilation

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumWriter.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericDatumWriter.java

- https://jira.apache.org/jira/browse/AVRO-2070

AVRO-2070 tolerate any numbers in GenericDatumWriter while writing primitives in java

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java
lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java
lang/java/tools/src/main/java/org/apache/avro/tool/Util.java

I set the initial cache area to some files.
________________________________
- https://issues.apache.org/jira/browse/AVRO-2786

AVRO-2786:Initialize the buffer area for Stringbuilder/List

---

doc/examples/java-example/src/main/java/example/GenericMain.java
doc/examples/java-example/src/main/java/example/SpecificMain.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileCorruption.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileDeflate.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileMeta.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestNonStringMapKeys.java
lang/java/ipc-netty/src/test/java/org/apache/avro/ipc/netty/TestNettyServer.java
lang/java/ipc/src/test/java/org/apache/avro/TestProtocolSpecific.java
lang/java/mapred/src/test/java/org/apache/avro/hadoop/io/TestAvroSequenceFile.java
lang/java/mapred/src/test/java/org/apache/avro/mapred/TestAvroTextOutputFormat.java
lang/java/mapred/src/test/java/org/apache/avro/mapred/tether/TestWordCountTether.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyValueRecordWriter.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestCombineAvroKeyValueFileInputFormat.java
lang/java/tools/src/main/java/org/apache/avro/tool/DataFileGetMetaTool.java
lang/java/tools/src/main/java/org/apache/avro/tool/DataFileGetSchemaTool.java
lang/java/tools/src/main/java/org/apache/avro/tool/RecodecTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileRepairTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestRecodecTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestSpecificCompilerTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestTetherTool.java
lang/java/tools/src/test/java/org/apache/avro/tool/TestTextFileTools.java
lang/java/trevni/avro/src/test/java/org/apache/trevni/avro/TestEvolvedSchema.java
lang/java/trevni/core/src/test/java/org/apache/trevni/TestIOBuffers.java
lang/java/trevni/core/src/test/java/org/apache/trevni/TestInputBytes.java

- https://issues.apache.org/jira/browse/AVRO-2763

AVRO-2763:Resource leak:'<unassigned Closeable value>' is never closed

---

lang/java/avro/src/main/java/org/apache/avro/UnresolvedUnionException.java
lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumWriter.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericDatumWriter.java

Overall idea is to not log a message which can't be understood (like union string,null: 123 where 123 is an index and not something human readable). It is particularly important when schema are generated or encapsulated.

ensure GenericDatumWriter specifies which field triggered an UnresolvedUnionException

---

lang/csharp/src/apache/test/Generic/GenericTests.cs
lang/csharp/src/apache/test/Util/LogicalTypeTests.cs

No additional test, since it's a fix for the existing tests themselves.

AVRO-2792: Fix C# logical type tests to work in other timezones than UTC

---

lang/c/tests/test_interop_data.c

- https://issues.apache.org/jira/browse/AVRO-2845
This PR fixes lang/c/tests/test_interop_data.c and I locally confirmed that it worked as follows:
```
sekikn@0b7a9e1241b5:~/avro/lang/c$ ./build.sh interop-data-test
(snip)
Checking file: ../../build/interop/data/perl_deflate.avro
Checking file: ../../build/interop/data/py_snappy.avro
Checking file: ../../build/interop/data/csharp_deflate.avro
Skipping file: ../../build/interop/data/php_zstandard.avro
Checking file: ../../build/interop/data/java.avro
Skipping file: ../../build/interop/data/py3_xz.avro
Checking file: …
```

AVRO-2845: Fix broken C interop test

---

lang/js/lib/schemas.js

- https://issues.apache.org/jira/browse/AVRO-2844

AVRO-2844:Avro-js can't parse default value {}

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/integration-test/codegen-test/src/test/java/org/apache/avro/codegentest/TestNestedLogicalTypes.java
lang/java/integration-test/codegen-test/src/test/resources/avro/nested_logical_types_union_fixed.avsc
lang/java/integration-test/test-custom-conversions/src/main/java/org/apache/avro/codegentest/CustomDecimal.java
lang/java/integration-test/test-custom-conversions/src/main/java/org/apache/avro/codegentest/CustomDecimalConversion.java

If the logical type is used for a Fixed type (potentially also Enum)
then it should check if there are any conversions used, and
include in the generated java source
Added new test in TestNestedLogicalTypes that fails before this change, but succeeds with it

AVRO-2836 Generated java includes logical type conversions

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java

If readNull not runned, ValidatingDecoder will complain

Always read even if skipped (readNull missing)

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java

- https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2579
- modifies the unit tests to make it more stable

[AVRO-2579]: Fix test by sorting fields for deterministic order

---

share/test/interop/bin/test_rpc_interop.sh

- https://issues.apache.org/jira/browse/AVRO-2733

AVRO-2733: No longer explicitly require rubygems

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/test_io.rb
lang/ruby/test/test_schema.rb
lang/ruby/test/test_schema_compatibility.rb

- https://issues.apache.org/jira/browse/AVRO-2545
- test_aliased
- test_to_avro_includes_aliases
- test_validate_field_aliases
- test_validate_same_alias_multiple_fields
- test_validate_repeated_aliases
- test_validate_record_aliases
- test_validate_enum_aliases
- test_validate_fixed_aliases
- test_aliased_field
- test_crossed_aliases
- test_compatible_reader_writer_pairs (additional test cases)
- test_incompatible_reader_writer_pairs (additional test cases)
- N/A

AVRO-2545: Add Ruby support for aliases

---

lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/test/java/org/apache/avro/TestDecimalConversion.java

Improve the handling to check precision and not error if scale
of value is less
TestDecimalConversion file added with tests of the success and expected error states

AVRO-2837: DecimalConversion handling of scale and precision

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java

Adds a warning to the new toString(...) method.  This is currently the only way to accomplish what the user is looking to do, but we'd like to provide a better solution in the short term (but after the 1.10.0 release).
- https://issues.apache.org/jira/browse/AVRO-2822 …

AVRO-2822: Add warning to an experimental method.

---

lang/java/ipc/src/test/java/org/apache/avro/generic/TestBuilderCopy.java

- https://issues.apache.org/jira/browse/AVRO-2139

AVRO-2139: Add Test for Decimal @java-class Annotated Generated Classes

---

lang/php/lib/Datum/AvroIODatumWriter.php
lang/php/lib/Schema/AvroSchema.php
lang/php/test/IODatumReaderTest.php

Fixed `null` handling on fields.
* added testRecordNullField

AVRO-1669: PHP library can't serialise records with optional (union-null) values

---

lang/java/maven-plugin/src/test/resources/unit/idl/pom.xml
lang/java/maven-plugin/src/test/resources/unit/protocol/pom.xml
lang/java/maven-plugin/src/test/resources/unit/schema/pom.xml

This is the step that needs to be done on test pom resources, not automatically updated when releasing with maven.  To completely close AVRO-2407, there should be a way to verify this in the build or release process.
- https://issues.apache.org/jira/browse/AVRO-2407
- All the public functions and the classes in the PR contain Javadoc …

AVRO-2407: Manually fix test pom.xml releases

---

pom.xml

Add the RAT exclusions for downloaded PHP libraries that are not delivered with Avro.
- https://issues.apache.org/jira/browse/AVRO-1664

AVRO-1664: Fix RAT exclusions for PHP vendor

---

doc/src/content/xdocs/spec.xml

My PR addresses the following [AVRO-2849] (https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2849).  It clarifies that the empty namespace can only be used by itself.
- I built the documentation using ant and forrest and verified layout with links2 browser

AVRO-2849: Update spec to clarify valid namespaces

---

lang/java/maven-plugin/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2865

AVRO-2865: Remove maven 2 support

---

lang/perl/Makefile.PL

Fix Makefile.PL so that PAUSE can identify Avro packages and corresponding files
cc @iemejia @RyanSkraba
- https://issues.apache.org/jira/browse/AVRO-1461
No additional test, since it's a fix for a build script. I ran `./build.sh dist` and uploaded the generated Perl distribution tarball to PAUSE, and confirmed that it was published via CPAN successfully.
1. Body …

AVRO-1461: Distribute Perl API on CPAN

---

lang/ruby/.gitignore
lang/ruby/Manifest
lang/ruby/Rakefile
lang/ruby/lib/avro.rb

This change fixes a long-standing annoyance that the Ruby gem does not contain an accurate version constant. There are many ways this could have been addressed. This was the simplest option that I could come up with given the current build.
- [https://issues.apache.org/jira/browse/AVRO-2382](https://issues.apache.org/jira/browse/AVRO-2382)
No tests added. This replaces the "FIXME" string with a real version value. The library fails to load if we are unable to read this value.
N/A

AVRO-2382: Fix VERSION constant for Ruby gem

---

.travis.yml

Temporarily disable failing tests on Travis.
- https://issues.apache.org/jira/browse/AVRO-2847

AVRO-2847: Deactivate windows OS test on Travis

---

.gitignore

- https://issues.apache.org/jira/browse/AVRO-2909
It just adds to the .gitignore file

AVRO-2909: Add .java-version (jenv) to .gitignore

---

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
lang/java/avro/src/test/java/org/apache/avro/TestSkipEnumSchema.java
lang/java/avro/src/test/java/org/apache/avro/generic/TestSkipEnumSchema.java

- https://issues.apache.org/jira/browse/AVRO-2908
- TestSkipEnumSchema

AVRO-2908: Skip enum using in.readEnum instead of in.readInt

---

lang/py3/avro/__init__.py

AVRO-2676: DeprecationWarning on import avro-python3

---

lang/py/avro/test/test_datafile.py

- Ensure avro.test.test_datafile tests always close resources.
- Use tempfiles to ensure datafile tests can be run in parallel.
This PR…

AVRO-2919 Fix Resource Leaks and Parallelism

---

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java

https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2881
When generating avro files using java's protobuf to avro conversion, double value's default is set to "0" while it should be "0.0".
This will cause import failure on BigQuery.

AVRO-2881 fix double default value

---

lang/py/avro/io.py
lang/py/avro/schema.py

This PR replaces the existing `validate` function in `avro.io` with a new version that uses a traversal-based approach rather than a recursive approach.  It also establishes the concept of a "validator" function that handles validation of various schema types and an "iterator" function, which powers the traversal of specific schema types.
The point of the work is two-fold.  First, by traversing rather than recursing, exceptions raised by validation can be raised immediately where the problem happened, allowing for error messages that are much more localized.  This is an advantage when working with very large schemas.  Second, by using traversal instead of recursion, this approach is more conservative of system resources, especially for deeply nested schemas.
The goal of this pr …

AVRO-2906: Traversal validation

---

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/uuid.avdl
lang/java/compiler/src/test/idl/output/uuid.avpr

- https://issues.apache.org/jira/browse/AVRO-2925
- unit tests to validate compiling idl file with uuid to avpr according to Avro 1.10.0 UUID logical type.

AVRO-2925: add support for UUID in compiler

---

lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_fingerprints.rb

https://issues.apache.org/jira/browse/AVRO-2907
I've compared the output of the [Ruby implementation](https://github.com/apache/avro/blob/release-1.10.0/lang/ruby/lib/avro/schema.rb#L180) (originally implemented in https://github.com/apache/avro/pull/317) to the [Java implementation](https://github.com/apache/avro/blob/release-1.10.0/lang/java/avro/src/main/java/org/apache/avro/SchemaNormalization.java#L64), and it seems like the output of the Ruby implementation of `single_object_schema_fingerprint` is reversed in comparison.
I believe that this is caused by [unnecessarily reversing the array traversal here](https://github.com/apache/avro/blob/release-1.10.0/lang/ruby/lib/avro/schema.rb#L184) during the bit mask + shift operation that constructs the little endian fingerprint for the …

AVRO-2907: Fix Ruby single object encoding fingerprint and header

---

lang/c++/CMakeLists.txt
lang/c++/api/DataFile.hh
lang/c++/impl/DataFile.cc
lang/c++/test/DataFileTests.cc

AVRO-2891: Expose last sync offset written on DataFileWriter
- https://issues.apache.org/jira/browse/AVRO-2891
A new test has been added for all three codec types: DataFileTests::testLastSync

AVRO-2891: Expose last sync offset written on DataFileWriter

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java
lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java

AVRO-2905: Fix Utf8 hash cache

---

lang/java/ipc-netty/src/main/java/org/apache/avro/ipc/netty/NettyTransceiver.java

- https://issues.apache.org/jira/browse/AVRO-2519
AVRO-2519 describes a resource leak in NettyTransceiver that was prevalent before the upgrade from netty 3 to 4. However, during the upgrade, basically the same resource leak occurred. If an …

AVRO-2519: Prevent resource leak in NettyTransceiver

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java

- https://issues.apache.org/jira/browse/AVRO-2817

AVRO-2817: Do not validate schema defaults in file

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java

AVRO-2944: Fix read pointer in java reader to avoid hang on partial read input stream

---

lang/ruby/Gemfile
share/docker/Dockerfile

This is the quickest fix I found, but getting rid of the Ruby 2.3 support seems more and more obvious for the next major release! 

AVRO-2957: Pin ruby 'parallel' dependency for Ruby 2.3 support

---

lang/java/tools/pom.xml

- https://issues.apache.org/jira/browse/AVRO-2875

AVRO-2875: Add logging to avro-tools

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema_validator.rb

This optimizes Ruby datum writing by avoiding an unnecessary hash allocation for constant validation options and avoids an unnecessary array allocation for success datum validation results. These optimizations are on the hot path for writing messages.
This is purely an implementation performance optimization so no new tests or documentation should be required.
/cc @tjwp

AVRO-2984: Optimize memory allocation during Ruby serialization

---

share/docker/Dockerfile

It looks like the build currently fails when the maven update was applied due to a spotless maven plugin bug.
- https://issues.apache.org/jira/browse/AVRO-2994

AVRO-2994: Update maven tool in docker build

---

lang/py/avro/test/test_tether_task_runner.py

Python dropped support for the old 'isAlive' spelling in 3.9.

AVRO-3008: Threading.is_alive Spelling for Py3.9

---

lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/test_schema_validator.rb

AVRO-2749 added support for serializing Ruby hashes with symbol keys but they were still considered invalid. This PR fixes schema validation to also accept hashes with symbol keys.
/cc @tjwp

AVRO-2998: Schema validation for Ruby hashes with symbol keys

---

lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_validator.rb
lang/ruby/test/test_schema_validator.rb

This optimizes several bottlenecks when encoding unions in the Avro Ruby
library:
1) Validation calls repeatedly allocate constant hashes
2) Validation calls repeatedly allocate constant strings
3) Validation calls are expensive and can be avoided when determining
of a datum matches a null union member type (a common pattern for
"optional" fields)
Optimizing these codepaths reduces memory allocations by 78% and
improves throughput 1.9X in our encoding benchmarks.
Note: Encoding unions is still expensive because the code must
determine which member of the union a datum is targeting. Allowing
clients to explicitly specify this would speed up serialization even
further but that requires a larger API change.
/cc @tjwp

AVRO-2999: Optimize Ruby union encoding

---

lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/test_schema_compatibility.rb

Ruby Avro decoding spends a fair amount of time validating that the
reader and writer schemas are compatible. These checks are
unnecessary for the fairly common case of the reader and writer schemas
being the same Avro::Schema instance. This improves the throughput
of our Avro decoding benchmarks by 1.3X.
While I was in here I removed repeated allocations of constant arrays in the `Avro:: SchemaCompatibility` module.
/cc @tjwp

AVRO-3000: Avoid unnecessary schema compatibility checks

---

lang/csharp/src/apache/main/IO/BinaryDecoder.notnetstandard2.0.cs
lang/csharp/src/apache/test/Avro.test.csproj
lang/csharp/src/apache/test/IO/BinaryCodecTests.cs

ArrayPool<T>.Rent(Int32) returns a buffer that is at least
minimumLength in length, but can be more.  The span that is used is
read into until it is empty. When this buffer returned from ArrayPool
is not exactly the same as the requested minimumLength this causes an
Avro.AvroException : End of stream reached
- https://issues.apache.org/jira/browse/AVRO-2983
- Avro.Test.BinaryCodecTests.TestLargeString which generates a 16KB buffer in array pool and then tries to read 16000 string, and this shows how the system currently fails and the patch fixes.  The existing unit tests for string reading didn't catch this because the ArrayPool was in a clean state for each of those reads, this simulates a real world case where the ArrayPool contains buffers …

AVRO-2983: Set Span length of ArrayPool Rent buffer

---

lang/c++/api/DataFile.hh
lang/c++/api/Decoder.hh
lang/c++/api/GenericDatum.hh
lang/c++/api/ValidSchema.hh

1. minumum -> minimum
2. valididated -> validated
Fix 1 typo in lang/c++/api/GenericDatum.hh:
1. appropraite ->  appropriate
Fix 3 typos in lang/c++/api/Decoder.hh:
1. fiedls -> fields
2. arbitray -> arbitrary
3. funtions -> functions
Fix 3 typos in lang/c++/api/DataFile.hh:
1. opportinity -> opportunity
2. entires -> entries
3. desrialize -> deserialize
This PR only fixes typo's in the c++ documentation built from the comments.
1. Subject is limited to 50 characters (not including …

Fix 2 typos in lang/c++/api/ValidSchema.hh:

---

.github/dependabot.yml
lang/java/pom.xml

Bump jetty.version from 9.4.34.v20201102 to 9.4.35.v2020112 in /lang/java

---

lang/c++/impl/avrogencpp.cc

avrogencpp has tabs in CodeGen::generateEnumTraits, which is inconsistent with the rest of the generated code.
This commit replaces all of the tabs in the CodeGen::generateEnumTraits function with 4 spaces to match the formatting of the rest of the file as well as the rest of the generated code.
This PR changes the whitespace in the generated avrogencpp code, which I did not find unit tests for.
1. Subject …

avrogencpp has tabs in CodeGen::generateEnumTraits, which is inconsistent with the rest of the generated code.

---

lang/c/CMakeLists.txt

avro-c fails to build (again) without a C++ compiler because commit 664c2fc7fba19709c1f974055f9cf4c8a799e108 reverted the change made by commit 414a51fdc1856083bb16851f09a4c61a48796132
Fixes:
- http://autobuild.buildroot.org/results/cfa91db53cf5502cbb6f902d1e7ad6397c8d70fd
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

AVRO-2898: Build failure without a C++ compiler (again)

---

doc/src/content/xdocs/spec.xml

I believe that this is an important aspect to clarify as some other
serialization formats omit fields that equal their default for
space-efficiency reasons. I had to run a small experiment as I could not
find this information in the spec.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
- https://issues.apache.org/jira/browse/AVRO-3028
1. Body wraps at 72 …

AVRO-3028: Records encode fields that equal the default

---

lang/java/archetypes/avro-service-archetype/src/main/pom/pom.xml
lang/java/maven-plugin/src/test/resources/unit/idl/pom-injecting-velocity-tools.xml
lang/java/maven-plugin/src/test/resources/unit/idl/pom.xml
lang/java/maven-plugin/src/test/resources/unit/protocol/pom-injecting-velocity-tools.xml
lang/java/maven-plugin/src/test/resources/unit/protocol/pom.xml
lang/java/maven-plugin/src/test/resources/unit/schema/pom-injecting-velocity-tools.xml
lang/java/maven-plugin/src/test/resources/unit/schema/pom.xml

Did a git bisect, and found out that my commit broke master:
```
MacBook-Pro-van-Fokko:avro fokkodriesprong$ git bisect good
5412eca32406e3a5d8579400bc6c3843ff5fb206 is the first bad commit
commit 5412eca32406e3a5d8579400bc6c3843ff5fb206
Author: Fokko Driesprong <fokko@apache.org>
Date:   Wed Jan 13 10:59:05 2021 +0100
AVRO-3024: Bump Jackson to 2.11.4
To consolidate the versions
lang/java/pom.xml | 5 ++---
1 file changed, 2 insertions(+), 3 deletions(-)
```
Turns out that there are still references to the jackson.databind property …

AVRO-3024: Remove references to Jackson databind

---

lang/c++/MainPage.dox

This Pull requests adds anchors to the sections of the avro c++ Documentation for deep linking.
- [ x] In case of new functionality, my PR adds documentation that describes how to use it.

Add anchors to the c++ documentation page

---

.github/workflows/test-lang-ruby.yml
lang/ruby/Gemfile

[AVRO-3023](https://issues.apache.org/jira/browse/AVRO-3023): Test against Ruby 3.0.
Ruby 3.0 was released 12/25/2020: [announcement](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)
`actions/setup-ruby` has not been updated to support Ruby 3.0. Based on this [issue](https://github.com/actions/setup-ruby/issues/80), it looks like [ruby/setup-ruby](https://github.com/ruby/setup-ruby) will be preferred and we should switch to it. That action also has built-in support for dependency caching. We should consider trying that instead of `actions/cache` but I have not done that here in order to keep this change minimal.

AVRO-3023: Test against Ruby 3.0

---

lang/py/avro/tether/tether_task.py

Simple fix for mypy type checking.
- https://issues.apache.org/jira/browse/AVRO-3032
- [X My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
- All the public functions and the classes in …

AVRO-3032: Use best practice for namedtuple

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java

Covers an additional potential issue in the static method for creating a DataFileReader. Let me know if I should create a new JIRA instead of reusing this one. The logic here now more readably follows the same pattern established in the BinaryDecoder's [readRaw](https://github.com/apache/avro/blob/328c539afc77da347ec52be1e112a6a7c371143b/lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java#L846) method, with an unexpected early EOF being properly handled.
In TestDataFileReader:
- testInputStreamEOF
Unrelated to this …

AVRO-2944: Handle unexpected EOF reading magic bytes in DataFileReader

---

lang/c++/CMakeLists.txt
lang/c++/impl/avrogencpp.cc
lang/c++/jsonschemas/cpp_reserved_words
lang/c++/test/AvrogencppTestReservedWords.cc

https://issues.apache.org/jira/browse/AVRO-3031
If avrogencpp encounters a schema with reserved words in it, it will happily generate a header with fields that are reserved words.
The decorate function in avrogencpp was overloaded a reference to an std::string or const avro::Name& to allow this.
The existing decorate function is only called on types, but it should also be called on names as well, which this patch fixes
For example:
```
{
"type" : "record",
"name" : "Words",
"namespace" : "org.apache.avro.example",
"fields" : [ {
"name" : "alignas",
"type" : "string"
}, {
"name" : "alignof",
"type" : "string"
}, {
"name" : "and",
"type" : "string"
}
]
}
Will generate the following header file:
struct Words {
std::string alignas;
std::string alignof;
std::string and;
Words() : …
```

AVRO-3031: Update for avrogencpp to handle C++ reserved words more broadly

---

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java

- https://issues.apache.org/jira/browse/AVRO-3049
testStringMaxArraySize
testNegativeBytesLength
testBytesMaxArraySize
testBytesMaxLengthProperty

AVRO-3049: Add checks to BinaryDecoder for bytes length

---

lang/java/avro/src/main/java/org/apache/avro/file/CodecFactory.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardLoader.java
lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroOutputFormat.java
lang/java/mapred/src/main/java/org/apache/avro/mapreduce/AvroOutputFormatBase.java

[SPARK-34479](https://github.com/apache/spark/pull/31673) added ZSTD support in Avro data source. 
ZSTD is a highly tunable compression codec. This PR aims to support additional ZSTD options.
- avro.mapred.zstd.level
- avro.mapred.zstd.bufferpool
ZSTD JNI bufferpool is a new feature and is supported by [SPARK-34340](https://github.com/apache/spark/pull/31453)/[PARQUET-1973](https://github.com/apache/parquet-mr/pull/865), too.
For the benchmark result of new buffer pool management, please see Apache Spark [ZStandardBenchmark](https://github.com/apache/spark/blob/master/core/benchmarks/ZStandardBenchmark-results.txt) result.
- https://issues.apache.org/jira/browse/AVRO-3060
- In case you are adding a dependency, check if the license complies …

AVRO-3060: Support ZSTD level and BufferPool options

---

lang/java/pom.xml

AVRO-3057: Bump zstd-jni from 1.4.8-6 to 1.4.8-7 in /lang/java

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaWarnings.java

When parsing a schema, we currently log a warning when a `logicalType` property is ignored on a schema if the underlying primitive is not supported.
The `logicalType` annotation is also always ignored on a field, since the annotation only has meaning on a schema.  This is a very common mistake.  This PR logs a warning if there is a `logicalType` property on a field, and missing from the field's schema.
- https://issues.apache.org/jira/browse/AVRO-3014
1. Subject …

AVRO-3014: Log a warning on ignored logicalType

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java
lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java

Instead of collecting the types of primitive datum that appear in a generated class, use the model to find the appropriate Conversion<?> instances that should be used for logical types.

AVRO-2471: Generate specific conversions from LogicalType

---

lang/java/avro/src/main/java/org/apache/avro/file/ZstandardLoader.java
lang/java/pom.xml

ZSTD JNI library recommends to use these *NoFinalizer classes if we don't depend on Java finalizers. Apache Avro doesn't depend on the finalizer behavior because we close explicitly with `try with resource` statement. The following is a benchmark at Apache Spark usage.
- https://github.com/apache/spark/pull/31762 ([SPARK-34647][CORE] Use ZSTD JNI NoFinalizer classes and bump to 1.4.8-7)
- https://issues.apache.org/jira/browse/AVRO-3072
This should pass all the existing test coverage.
1. Subject is limited to 50 characters (not …

AVRO-3072: Use ZSTD NoFinalizer classes and bump to 1.4.9-1

---

lang/py/avro/compatibility.py
lang/py/avro/errors.py
lang/py/avro/test/test_compatibility.py

Keeping in line with the same logic present in the avro java library
that handles type promotions, this aims to be a faithful adaptation of
that code in python.
Most tests were also ported, with the exception of the ones dealing with
enum default, since the python api does not support that yet
See :
- https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java
- https://issues.apache.org/jira/browse/AVRO-1751

AVRO-1751: Add python3 compatibility

---

.github/workflows/test-lang-py.yml

- https://issues.apache.org/jira/browse/AVRO-3080
I ran the revised workflow in my GitHub repository and confirmed Python interop test read snappy and zstd files.

AVRO-3080: Fix Python interop test on CI to check snappy and zstd files

---

lang/php/test/InterOpTest.php

- https://issues.apache.org/jira/browse/AVRO-3085
I ran the "Test PHP" workflow in my GitHub repository and confirmed the warning messages in question were suppressed and the checked/skipped file paths were displayed.
- All the public functions and the classes in the PR contain Javadoc …

AVRO-3085: Fix PHP interop test on CI to suppress unnecessary warnings

---

lang/c++/CMakeLists.txt

- https://issues.apache.org/jira/browse/AVRO-3087
By being able to build is a test
I made commit before creating a JIRA issue
Edit: I changed commit message

[AVRO-3087] fix c++ build if snappy is not found

---

lang/py/setup.cfg
lang/py/tox.ini

This PR removes 3.5 support from build and setup, including classifiers
Closes: AVRO-3004 (https://issues.apache.org/jira/browse/AVRO-3004)
- https://issues.apache.org/jira/browse/AVRO-3004
**NA**

AVRO-3004 Drop support for Python 3.5

---

.github/labeler.yml
DIST_README.txt
build.sh
lang/py/scripts/avro
pom.xml
share/test/interop/bin/test_rpc_interop.sh

With the deprecation notice in place for some time, we can stop maintaining and releasing `avro-python3` package along with other SDKs
Closes: https://issues.apache.org/jira/browse/AVRO-3093
- https://issues.apache.org/jira/browse/AVRO-3093
**NA**
**NA**

AVRO-3093: Stop releasing avro-python3 package

---

share/docker/Dockerfile

This requires installing the JDK8 from another repository, in this case AdoptOpenJDK.
I checked building a distribution with JDK8 and running all tests in the tool on my local machine.
- https://issues.apache.org/jira/browse/AVRO-3092 …

AVRO-3092: Update ubertool image to buster

---

lang/py/avro/tool.py

- https://issues.apache.org/jira/browse/AVRO-3100
With AVRO-3092, this tool is now being used during testing.

AVRO-3100: Fix module typo in avro.tool

---

lang/py/avro/protocol.py
lang/py/avro/schema.py
lang/py/avro/test/test_schema.py

This PR adds support for generating Parsing Canonical Forms of Avro Schemas to the main `avro` package.
The bulk of the work was done by @kojiromike and @forsberg. This PR cleans up code where necessary, adds more test cases, and clarifies on transformations wherever not applicable in Python (ex. Transformation of integers with leading zeros)
Closes: https://issues.apache.org/jira/browse/AVRO-1938
Closes: https://github.com/apache/avro/pull/700/
- https://issues.apache.org/jira/browse/AVRO-1938
Test cases in `test/test_schema.py::CanonicalFormTestCase`
1. Subject uses the imperative …

AVRO-1938: Generate Parsing Canonical Forms of Schema

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java

Avro 1.9+ attempts to access static field MODEL$ on avo-generated classes.
Record classes generated by older Avro (for example 1.7) do not have this field.
This causes modern avro to catch an exception on every record being deserialized
for such classes, which can cause a x3 slow down
(see profiler results in the Jira ticket).
This fix uses ClassValue to cache the SpecificData instance to use per class.
This results in s ~x5 speedup for the happy path (classes that have MODEL$) and
~x50 speedup for classes that do not have MODEL$.
- https://issues.apache.org/jira/browse/AVRO-3094 …

AVRO-3094: improve performance of SpecificData.getForClass(), especially around old generated specific record classes

---

lang/py/avro/constants.py
lang/py/avro/schema.py
lang/py/avro/test/test_io.py
lang/py/avro/test/test_schema.py

This PR introduces the UUID logical type implementation that was missing in the
primary python implementation. A new `UUIDSchema` has been introduced that
validates for valid UUID4 string values.
Closes: https://issues.apache.org/jira/browse/AVRO-3065
- https://issues.apache.org/jira/browse/AVRO-3065
- Test for valid UUID Logical Type in Schema
- Test for valid UUID in values
1. Subject uses the imperative mood ("add", …

AVRO-3065: Introduce UUID logical type to Python implementation

---

.github/workflows/test-lang-ruby.yml
BUILD.md
lang/ruby/Gemfile
lang/ruby/build.sh
share/docker/Dockerfile

Ruby 2.5 is EOL as of March 31, 2021.

AVRO-3108: Drop support for Ruby 2.5

---

.github/workflows/test-lang-java.yml
pom.xml

Some dependencies (jetty) are starting to produce releases with bytecode that targets more recent versions of Java (e.g. Java 11). We should validate that we don't end up accidentally introducing one of those in order to keep supporting the minimum Java version we target (Java 8) correctly.
R: @dkulp or @RyanSkraba

AVRO-3113: Enforce Java 8 bytecode compatibility on Java dependencies

---

.github/workflows/rat.yml
.github/workflows/test-lang-java.yml
pom.xml

It also update other plugin versions to enable the project to build in more recent JDKs.
And reverts the hack we did for the github actions issue that apparently is not needed anymore https://github.com/actions/virtual-environments/issues/3185#issuecomment-824562686
R: @RyanSkraba

AVRO-3113: Update enforcer-plugin to version 3.0.0-M3

---

lang/java/avro/src/main/java/org/apache/avro/Conversions.java
lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java
lang/java/integration-test/pom.xml
lang/java/ipc-netty/src/test/java/org/apache/avro/ipc/netty/TestNettyServerWithCallbacks.java
lang/java/ipc/src/test/java/org/apache/avro/TestSchema.java
lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java
lang/java/perf/src/main/java/org/apache/avro/perf/test/basic/UnchangedUnionTest.java
lang/java/pom.xml
lang/java/tools/src/main/java/org/apache/avro/tool/CatTool.java
pom.xml

More recent javac compilers produce a different exception message so we
should probably not validate based on the text.
R: @RyanSkraba

AVRO-3120: Consider only the exception on TestSchema.testNullPointer

---

lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/test_schema.rb
lang/ruby/test/test_schema_compatibility.rb

In https://github.com/apache/avro/pull/918 it was identified that matching during schema resolution is missing for bytes decimal logical types in the Ruby implementation. (There is no support yet in the Ruby implementation for the fixed decimal.)
Instead of embedding the logic for this specific check in the `SchemaCompatibility` module, I've made a small, initial step in the direction of making this checking more object-oriented. The matching logic needed is added to the `BytesSchema` class.

AVRO-3036: add schema matching for bytes decimal logical type in Ruby

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/avro/src/test/java/org/apache/avro/TestSchema.java

Avro Schema parser fails with NullPointerException when a schema with null Enum symbols are encountered. This behavior is inconsistent with using an empty symbol where a SchemaParseException is thrown. JIRA: https://issues.apache.org/jira/browse/AVRO-3129
- https://issues.apache.org/jira/browse/AVRO-3129
`testEnumSymbolAsNull`
Not applicable.

AVRO-3129: Throw SchemaParseException when enum symbol is null

---

.github/workflows/spotless.yml

Spotless is only configured to run on java right now, so it seems a waste of github actions to run it on anything else. Later, we should discuss running spotless checks for other languages.
This PR…
N/A
My commits…
N/A

AVRO-3139: Only Run Spotless on Java Changesets

---

lang/py/avro/__init__.py
lang/py/avro/compatibility.py
lang/py/avro/test/test_compatibility.py

AVRO-3097: Run Schema Compatibility checks as part of Unittest
Test methods in `test_compatibility.py` were being ignored in unittest runs because they were not connected to `unittest.TestCase`.
This PR encloses the test cases within a class deriving from `unittest.TestCase` and also changes assert statements to be in compliance with unittest. It also exposes `compatibility` as a module in the `avro` package.
- https://issues.apache.org/jira/browse/AVRO-3097
Reuses existing tests but folds them within `unittest` so that they run as part of regular build runs.
1. Subject uses the …

AVRO-3097: Run Schema Compatibility checks as part of Unittest

---

lang/ruby/Gemfile
lang/ruby/lib/avro/logical_types.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/test/test_logical_types.rb
lang/ruby/test/test_schema.rb
lang/ruby/test/test_schema_validator.rb

- https://issues.apache.org/jira/browse/AVRO-3054
- README/CHANGELOG not updated, but the logical type support from AVRO-2677 should have included this encoder/decoder rather than leaving it up to consumers to shove the correct bytes in there. AVRO-2677 is closed, and we are unsure the appropriate measure to take with that. Should we …

AVRO-3054: Fix / support decimal logical type in Ruby

---

.github/workflows/codeql-analysis.yml

AVRO-3145: Enable GitHub CodeQL Scans

---

README.md

Indicate the status of the CodeQL scan in the Readme. It's easier to
determine which checks/tests are passing and failing in the Readme than
it is to click around to figure it out.
N/A

AVRO-3145: Add the CodeQL Badge to the README

---

lang/py/avro/schema.py
lang/py/avro/test/test_schema.py

If you try to test if an arbitrary object is equal to a schema, as in `some_schema == not_a_schema`, avro would crash with an `AttributeError`. This comparison should not crash.It should simply return `False` when the other object is not a schema.
My PR...
N/A

AVRO-3104 Allow Comparing Schemas to non-Schemas

---

lang/py/avro/errors.py
lang/py/avro/io.py
lang/py/avro/test/test_io.py
lang/py/avro/test/test_schema.py

Avro is supposed to check if the scale for a decimal logical schema is large enough for the datum to be written. But Python provides the exponent as negative, so the exponent is always less than the scale.  This change corrects the comparison by ensuring scale and exponent have the same sign.
In testing the above, avro attempts to raise `AvroTypeException` with improper arguments, leading to a secondary exception within the first. This change also fixes `AvroTypeException` so that it is flexible and won't crash when invoked with different arguments.
It also adds a special AvroTypeException subtype to provide useful debugging details when a decimal schema tries to write a datum with an exponent that is too large.
Finally, many test cases in Avro consist of running the same code over …

AVRO-3146: Fix Decimal Scale Exception Handling

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/codeql-java-analysis.yml
.github/workflows/codeql-js-analysis.yml
.github/workflows/codeql-py-analysis.yml
lang/py/setup.py

Reconfigure GitHub Actions so that when CodeQL analysis runs, it only checks the implementations with code changes. This should save energy and time, reserving resources for meaningful checks.
N/A
N/A

AVRO-3152: CodeQL Per Language

---

lang/py/avro/schema.py
lang/py/avro/test/test_bench.py
lang/py/avro/test/test_schema.py

This changeset brings the python implementation in line with [the specification](https://avro.apache.org/docs/current/spec.html#names) insofar as when a namespace is the empty string, it should be treated as if the namespace were null. 
This PR…

AVRO-3118: Treat "" as Null Namespace

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/codeql-java-analysis.yml
.github/workflows/codeql-js-analysis.yml
.github/workflows/codeql-py-analysis.yml

Pull request #1237 seemed to work when I tested it, but continued to scan changesets even for implementations that had not changed.
This seems to be due to the fact that the matrix language list was not specified correctly in each yml file.
N/A
N/A

AVRO-3152: Correction: Specify Languages

---

lang/ruby/.rubocop.yml
lang/ruby/Gemfile
lang/ruby/lib/avro/io.rb
lang/ruby/lib/avro/schema.rb
lang/ruby/lib/avro/schema_compatibility.rb
lang/ruby/test/tool.rb

https://issues.apache.org/jira/browse/AVRO-3147
Rubocop version is set to >= 1.15 but < 2.0.
In addition to using the newer Rubocop version, new Lint cops are enabled, and any offenses corrected or disabled.
The Security group of cops is also enabled.

AVRO-3147: Upgrade to rubocop v1.x

---

lang/java/pom.xml
pom.xml

The maven-maven-plugin upgrade is just to fix a maven issue when building with Java 17, sadly there seems not to be a 3.8.x version to keep them aligned yet.
R: @RyanSkraba

AVRO-3120: Upgrade maven-maven-plugin and spotless to a more recent version

---

lang/py/avro/constants.py
lang/py/avro/name.py
lang/py/avro/schema.py

Refactor name registry into avro.name and add type hints.
N/A

AVRO-2921: Add Type Hints for avro.name

---

lang/py/avro/name.py
lang/py/avro/protocol.py
lang/py/avro/schema.py
lang/py/avro/test/test_protocol.py
lang/py/avro/tether/tether_task.py
lang/py/setup.cfg

Type Hints for avro.protocol, and avro.schema
- The dependency only applies to installations with Python versions earlier than 3.8.
- It is licensed under the [Python Software Foundation License](https://github.com/python/typing/blob/master/LICENSE).
N/A

AVRO-2921: Type Hints for avro.schema and avro.protocol

---

README.md

The original work in AVRO-3152 did not update the README.
N/A

AVRO-3152: Correct CodeQL Links in Readme

---

lang/py/avro/datafile.py
lang/py/avro/test/mock_tether_parent.py
lang/py/avro/test/sample_http_server.py
lang/py/avro/test/test_bench.py
lang/py/avro/test/test_datafile_interop.py
lang/py/avro/test/test_tether_task.py
lang/py/avro/timezones.py
lang/py/avro/utils.py

...and other small modules
- Type hint and refactor `avro.datafile`
- Type hint `avro.test.mock_tether_parent`
- Type hint `avro.timezones`
N/A
[ticket]: https://issues.apache.org/jira/browse/AVRO-2921

AVRO-2921: Type Fixes for avro.datafile

---

lang/c/docs/index.txt

The fix is a very minor typo in the documentation of the C implementation.
I think there is no need of JIRA for it.

Fix a small typo in documentation

---

lang/py/avro/errors.py
lang/py/avro/io.py
lang/py/avro/test/test_bench.py
lang/py/avro/test/test_io.py
lang/py/avro/test/test_schema.py

The exception message now includes the field name on which the type exception
was raised.
Closes: AVRO-2720
- https://issues.apache.org/jira/browse/AVRO-2720
1. Subject is separated from the body by a blank line
NA

AVRO-2720: Enhance AvroTypeException message to include field name

---

lang/js/lib/files.js
lang/js/lib/protocols.js
lang/js/lib/schemas.js
lang/js/lib/utils.js
lang/js/test/test_files.js
lang/js/test/test_protocols.js
lang/js/test/test_schemas.js
lang/js/test/test_utils.js

Use Buffer.alloc(), allocUnsafeSlow() and from() factory methods instead
https://issues.apache.org/jira/browse/AVRO-3174
Several test files are also updated.
Now running `npm run test` no more produces this warning: 
```
(node:1205780) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
No public facing API has been changed. No need of documentation updates.

AVRO-3174 JavaScript: Do not use deprecated constructors of Buffer

---

lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java

Does not change existing functionality. Uses existing unit tests.

AVRO-3183: Do Not Double Buffer Data in DataFileWriter

---

.github/workflows/test-lang-rust-audit.yml
.github/workflows/test-lang-rust-ci.yml
.github/workflows/test-lang-rust-clippy.yml
build.sh
lang/rust/build.sh
lang/rust/src/lib.rs
lang/rust/src/schema_compatibility.rs
lang/rust/src/ser.rs
lang/rust/src/util.rs
lang/rust/tests/io.rs
lang/rust/tests/schema.rs

Fix all linting/clippy errors & warnings.
Add `build.sh` for Rust that currently supports clean, dist, lint and test targets
- https://issues.apache.org/jira/browse/AVRO-3175
Tests' source code has been updated to fix linting/clippy errors and warnings
No public facing API has been modified. No need of documentation changes!

AVRO-3175 Rust: fix lint/clippy errors

---

README.md

The README has not been updated since the adoption of the Rust component. Even though the rust checks aren't passing, having them present will make it clear to people exploring the repo in GitHub that there is a rust implementation, and provides guidance about what needs to be addressed.

AVRO-3193: Add Rust Checks to Readme

---

lang/py/build.sh
lang/py/pyproject.toml

- Modernize the Python build system to the PEP 517 standard.
- Build wheel and tar distributions to ship.
N/A
N/A (Still uses ./build.sh dist)

AVRO-3007: Standardize Building Python Packages

---

lang/csharp/src/apache/main/Schema/PrimitiveSchema.cs
lang/csharp/src/apache/main/Schema/Schema.cs
lang/csharp/src/apache/test/Schema/SchemaTests.cs

- https://issues.apache.org/jira/browse/AVRO-3182

AVRO-3182 fix union schema ToString() has an extra type property

---

lang/csharp/src/apache/main/Schema/SchemaName.cs

FullName property is being called by `ClassCache.GetClass` for each property:
```csharp
public DotnetClass GetClass(RecordSchema schema)
{
DotnetClass result;
if (!this._nameClassMap.TryGetValue(schema.Fullname, ref result))
.
.
```
This allocates TONS of strings on a scenario which calls `Avro.Reflect.ReflectDefaultWriter.WriteRecord` on large amount of entities (millions) + large amount of fields (tens).
1. …

Memory optimization in SchemaName.Fullname

---

.github/workflows/test-lang-java.yml

- https://issues.apache.org/jira/browse/AVRO-3081
I manually ran the "Test Java" workflow in my GitHub repository and confirmed that Java interop test read Avro files generated by Python.

AVRO-3081: Fix Java interop test on CI to read files generated by other languages

---

share/docker/Dockerfile

This only affects manual builds using the ubertool jar.
This should succeed:
```
./build.sh docker
cd lang/python/
./build.sh dist
```
- https://issues.apache.org/jira/browse/AVRO-3198

AVRO-3198: Include venv module in ubertool

---

lang/c++/build.sh

- https://issues.apache.org/jira/browse/AVRO-3201
I locally ran `cd lang/c++ && ./build.sh dist` and made sure that the distribution tarball was successfully created.

AVRO-3201: Remove non-existent directory from lang/c++/build.sh

---

lang/c++/impl/avrogencpp.cc

I have not followed your required steps and have not created a jira issue. This is a drive by fix that I have done while doing microsoft/vcpkg#17335 because it causes the pipeline to fail (see for example [here](https://github.com/microsoft/vcpkg/runs/2714029054)).  
But I think you are maybe interested in this fix and want to integrate it.

Fix c++ windows build. IN and OUT are predefined macros.

---

lang/csharp/src/apache/main/AvroDecimal.cs
lang/csharp/src/apache/test/AvroDecimalTest.cs

The method ToString of class AvroDecimal causes ArgumentOutOfRangeException
when Scale is greater than Unscaled number size.
The method ToString of class AvroDecimal returns a wrong result when Scale
is equal to the Unscaled number size because is missing a "0"
- https://issues.apache.org/jira/browse/AVRO-3134
- AvroDecimalTest.cs

AVRO-3134: Fix ArgumentOutOfRangeException in method ToString of AvroDecimal

---

lang/csharp/src/apache/main/Reflect/ClassCache.cs
lang/csharp/src/apache/test/Reflect/TestRecursive.cs

-https://issues.apache.org/jira/browse/AVRO-3110).
- [ x] TestRecursiveSchema: https://github.com/eaba/AvroSchemaGenerator/blob/nested_schema/AvroSchemaGenerator.Tests/GetSchemaTest.cs

AVRO-3110: Infinite Recursion - CSharp

---

lang/csharp/build.sh
lang/csharp/src/apache/test/Interop/InteropDataTests.cs
lang/perl/xt/interop.t

- https://issues.apache.org/jira/browse/AVRO-3082
I ran the "Test C#" and "Test Perl" workflows in my GitHub repository and confirmed that information about checked/skipped files was displayed.

AVRO-3082: Improve interop test traceability for C# and Perl on CI

---

lang/c++/impl/parsing/JsonCodec.cc

Simple change to make it easier to debug json that doesn't conform to a schema.
I'll put in an issue if that's required to accept a PR.

Enhance json parsing exception text to make it easier to locate problem

---

.github/dependabot.yml
lang/rust/Cargo.toml
lang/rust/src/codec.rs

Update all prod and dev dependencies to their latest versions.
Add an entry for dependabot for Rust.

AVRO-3204 Rust: Update dependencies

---

doc/src/content/xdocs/spec.xml

https://issues.apache.org/jira/browse/AVRO-3212
this is just a text change in the docs

AVRO-3212: fix specification to allow doc in fixed types

---

lang/java/avro/src/main/java/org/apache/avro/file/BZip2Codec.java
lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java
lang/java/avro/src/main/java/org/apache/avro/file/DeflateCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/XZCodec.java
lang/java/avro/src/main/java/org/apache/avro/file/ZstandardCodec.java
lang/java/avro/src/main/java/org/apache/avro/util/NonCopyingByteArrayOutputStream.java

No change in behavior, simply performance/simplicity

AVRO-3167: Simplify Codec Buffer Allocation

---

lang/java/compiler/src/test/java/org/apache/avro/compiler/schema/TestSchemas.java

- AVRO-3211: Refactor PrintingVisitor to improve test design
<hr>
- Decouple test class `PrintingVisitor` from production interface `SchemaVisitor`.
- Remove the redundant test child class `PrintingVisitor`.
<hr>
* Created mocking object to replace test subclass `PrintingVisitor`, decoupled test from production code.
* Created method that return the mocking object for code reuse.
* Make test logic more clear by using method stub instead of method overriding.
* Remove redundant overridden method `get()`.
* Add Mockito dependency.
<hr>

AVRO-3211: Refactor PrintingVisitor to improve testing logic

---

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java
lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java

Related to https://issues.apache.org/jira/browse/BEAM-12628 
It's very common in big data to have a key/value pair where the key is extracted from a record in the value.  This is currently unnecessarily complicated because if the key is a Utf8 datum that does not implement Serializable (although it is serializable inside the record itself).
- https://issues.apache.org/jira/browse/AVRO-3208
1. Body wraps at 72 …

AVRO-3208: Utf8 datum are Serializable

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/compiler/src/test/java/org/apache/avro/specific/TestSpecificData.java
lang/java/compiler/src/test/resources/foo.Bar.avsc

```
SpecificDatumReader.SpecificDatumReader(Schema writer, Schema reader)
-> SpecificData.getForSchema(reader)
// It breaks if system class loader fails to load generated class,
// thus returns an empty SpecificData.
SpecificDatumReader.readField()
-> datum = readWithoutConversion(oldDatum, field.schema(), in);
// conversion is null for union field
-> GenericDatumReader.read(Object old, Schema expected, ResolvingDecoder in)
-> Conversion<?> conversion = getData().getConversionFor(logicalType);
// returns null wrongly
Without this patch, the unit test fails:
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.time.Instant (java.lang.Long and java.time.Instant are in module java.base of loader 'bootstrap')
at foo.Bar.put(Bar.java:113)
at …
```

AVRO-3186: correctly parse union of logical type in specific record

---

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj

Related to https://github.com/apache/avro/pull/1157#pullrequestreview-772364513

AVRO-3095 Handle "classpath" resources only if resourceLoader is not null

---

lang/ruby/avro.gemspec

Add metadata to make the published Ruby gem more secure by requiring a one-time password (OTP) for all privileged operations: https://guides.rubygems.org/mfa-requirement-opt-in/
- https://issues.apache.org/jira/browse/AVRO-3255
Packaging change only for the Ruby gem.

AVRO-3255: Ruby: specify rubygems_mfa_required in gemspec metadata

---

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/simple.avdl
lang/java/compiler/src/test/idl/output/simple.avpr

A field schema can be annotated with the property `avro.java.string`:
{
"name": "fieldName",
"type": {
"type": "string",
"avro.java.string": "String"
}
}
The corresponding IDL is:
@avro.java.`string`("String") string fieldName;
The IDL parser fails on the `. This change fixes that.
- https://issues.apache.org/jira/browse/AVRO-3217
- ~In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).~
Adjusted the `simple.avdl` and `simple.avpr` test
1. Subject uses the imperative mood …

AVRO-3217: Allow any identifier as annotation name

---

doc/src/content/xdocs/idl.xml
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/AnnotationOnTypeReference.avdl
lang/java/compiler/src/test/idl/input/simple.avdl
lang/java/compiler/src/test/idl/output/simple.avpr
lang/java/compiler/src/test/java/org/apache/avro/compiler/idl/TestReferenceAnnotationNotAllowed.java
lang/java/grpc/src/test/avro/TestService.avdl

Previous versions would alter the referenced type when encountering an
annotation on (for example) a field type. This change makes references
read-only.
- https://issues.apache.org/jira/browse/AVRO-3256
- ~In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).~
- {{org.apache.avro.compiler.idl.TestReferenceAnnotationNotAllowed}}
- Updates to {{simple.avdl}} and {{simple.avpr}} (as described in the Jira issue)
- Updates to other test schemata that contained the same bug
1. …

AVRO-3256: IDL type reference with annotation throws error

---

lang/py/setup.cfg

- https://issues.apache.org/jira/browse/AVRO-3258

AVRO-3258: Fix quoting error in python setup.cfg

---

lang/php/lib/Datum/AvroIOBinaryDecoder.php

- https://issues.apache.org/jira/browse/AVRO-3268

AVRO-3268: Fix whitespace error in PHP lint

---

.github/workflows/test-lang-perl.yml

- https://issues.apache.org/jira/browse/AVRO-3269

AVRO-3269: Test Perl workflow does not run the tests

---

lang/perl/lib/Avro/Schema.pm
lang/perl/t/02_bin_encode.t

- Disable warnings in the limited scope of "long" validation that uses pack and unpack. It is unnecessary as warnings don't affect the validation outcome and in some scenarios this validation is expected to fail.
- Add test cases to validate the fix
- https://issues.apache.org/jira/browse/AVRO-3263
- Binary_Encodings.Complex_Types.Unions-record-with-long-field
- Binary_Encodings.Complex_Types.Unions-record-with-long-field-nowarning
1. Subject does not end …

AVRO-3263: Fix warning in Perl encoder when validating a long field

---

lang/py/avro/datafile.py

The `DataFileWriter` class constructor checks for the presence of a `mode` attribute before accessing it, but the `DataFileReader` does not. This means that it is possible to use the `DataFileWriter` to write data to in memory binary streams using `io.BytesIO`, but it is not possible to read from them in the same manner. This commit adds the same check to the `DataFileReader` class.
The following code can trivially reproduce the issue:
```
import io
import avro.schema
from avro.datafile import DataFileReader, DataFileWriter
from avro.io import DatumReader, DatumWriter
schema = """
{
"namespace": "example.avro",
"name": "User",
"fields": [
{"name": "name", "type": "string"},
{"name": "favorite_number",  "type": ["int", "null"]},
{"name": "favorite_color", "type": …
```

AVRO-3252: Add hasattr check for mode attr in DataFileReader

---

lang/py/avro/schema.py
lang/py/avro/test/test_schema.py

AVRO-3218: Fix parsing of logicalType = decimal

---

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/avro/src/main/java/org/apache/avro/util/MapUtil.java
lang/java/grpc/src/main/java/org/apache/avro/grpc/ServiceDescriptor.java

AVRO-3243 Workaround JDK-8161372 - perf issue in ConcurrentHashMap#computeIfAbsent()

---

lang/py/avro/errors.py
lang/py/avro/schema.py
lang/py/avro/test/test_schema.py

Raise an InvalidDefault exception when attempting to parse an enumschema with a default value that isn't one of the enum's symbols.

AVRO-3229: Raise Exception on Invalid Enum Default

---

lang/java/avro/src/main/java/org/apache/avro/Schema.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/IsResolvedSchemaVisitor.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/ResolvingVisitor.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/SchemaResolver.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/Schemas.java
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/simple.avdl
lang/java/compiler/src/test/idl/output/forward_ref.avpr
lang/java/compiler/src/test/idl/output/simple.avpr

If the IDL file defines the schema of a field after the field, record
valued defaults cause a NullPointerException. This PR fixes that.
The fix addresses two situations:
1. The field schema itself is a forward reference
(tested by fixing the missing default value in `forward_ref.avpr`)
2. The field schema contains a forward reference
(tested by the `echo` message in the updated `simple.avdl`)
- https://issues.apache.org/jira/browse/AVRO-2867
- ~In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).~
1. Subject …

AVRO-2867: Fix NullPointerException on record-valued defaults

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/main/CodeGen/CodeGenUtil.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs

Fix for uncompilable code generation in case when the namespace ends with ".Avro".
- [ x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
- [ x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
NOTE: Tests are suppressed for .NET Core environment. I reviewed the changes I've added to tests but unfortunately could not run them on MacOS / .NET 5-6. I did manually tested …

AVRO-3265: Fix avrogen code generation for Avro namespaces

---

lang/java/compiler/src/test/idl/output/uuid.avpr

Minor Java failure caused by merging https://github.com/apache/avro/pull/1377 separately.
- https://issues.apache.org/jira/browse/AVRO-3251

AVRO-3251: Minor testcase fix after merge

---

lang/rust/CHANGELOG.md
lang/rust/Cargo.toml
lang/rust/README.md
lang/rust/README.tpl
lang/rust/src/lib.rs

AVRO-3205 Rust: Update Cargo.toml [package] information

---

.github/workflows/test-lang-rust-ci.yml
lang/rust/Cargo.toml
lang/rust/README.md
lang/rust/src/codec.rs
lang/rust/src/error.rs

Add new codec: zstandard
- https://issues.apache.org/jira/browse/AVRO-3234

AVRO-3234: add new codec to lang/rust: zstandard

---

lang/rust/Cargo.toml
lang/rust/src/codec.rs

AVRO-3245 Rust: Replace crc crate with crc32fast

---

lang/c++/impl/DataFile.cc

This avoids thread-safety issues.
No need of documentation.

AVRO-2722 C++: Move the 'random' variable to be local to the method where it is being used

---

lang/rust/src/schema.rs
lang/rust/tests/io.rs
lang/rust/tests/schema.rs

Only https://github.com/apache/avro/commit/06200ef388a99a92bfe1c419afc74264f6cc971e is part of this PR. The previous commits are from  [AVRO-3197](https://issues.apache.org/jira/browse/AVRO-3197) and they will disappear from this PR once #1340 is merged

AVRO-3216 Reuse records' schema by name

---

lang/rust/src/decode.rs
lang/rust/src/reader.rs

When providing your own schema to `from_avro_datum`,
the deserialization is not backward compatible with messages
containing a previous schema even if the schemas are created
to be backward compatible.
This is due to the `decode_variable` function in `utils` returning
`Error::ReadVariableIntegerBytes` when the reader object is
smaller than expected and thus cannot fill the read_exact buffer.
Reading a message generated with an older schema version than the
one we are statically using, the payload buffer is by essence
smaller than the expected payload from a message serialized with
a newer schema (backward compatible schemas are basically append
only).
The proposed fix takes that into account and just returns empty
Ok() which will be interpreted as null. This is in line with the
fact that …

AVRO-3240: fix deserializer schema backward compatibility

---

.github/workflows/codeql-csharp-analysis.yml
.github/workflows/test-lang-csharp.yml
.travis/before_install.sh
lang/csharp/README.md
lang/csharp/build.sh
lang/csharp/src/apache/codegen/Avro.codegen.csproj
lang/csharp/src/apache/perf/Avro.perf.csproj
lang/csharp/src/apache/test/Avro.test.csproj
lang/csharp/versions.props
share/docker/Dockerfile

- https://issues.apache.org/jira/browse/AVRO-3250

AVRO-3250: Support .NET 6.0

---

.github/workflows/test-lang-java.yml
lang/java/mapred/pom.xml
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyInputFormat.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyOutputFormat.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyRecordReader.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyRecordWriter.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyValueRecordReader.java
lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyValueRecordWriter.java
lang/java/pom.xml
share/docker/Dockerfile

- Disable Spotless' removeUnusedImports
(https://github.com/diffplug/spotless/issues/834). It will be re-enabled
once Avro is updated to JDK 11+. Then we can add .mvn/jvm.config (see
https://github.com/diffplug/spotless/issues/834#issuecomment-817524058)
- Replace Easymock with Mockito.
- 
- [] TODO: Probably I should update the website and/or README

AVRO-3120: Support Next Java LTS (Java 17)

---

lang/java/compiler/pom.xml
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/pom.xml

Also resolve IDE warnings for idl.jj, which was previously impossible.
- https://issues.apache.org/jira/browse/AVRO-3285
Upgrading plugins and libraries does not add functionality; existing tests must pass though …

AVRO-3285: Upgrade JavaCC plugin and library

---

.github/workflows/test-lang-java.yml
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

Ignore compilation warnings that member fields are not Serializable

AVRO-3306: Java: Build failure with JDK 18+

---

lang/java/pom.xml
lang/java/tools/pom.xml

This is an alternative to https://github.com/apache/avro/pull/1458
That PR replaces the logging behind slf4j from log4j 1.x to slf4j-simple, while this PR drops in the reload4j replacement.
Both these solutions are "mitigation" solutions for current CVEs, while downstream projects still bring in log4j 1.x dependencies. 
I've verified that the classes in the generated avro-tools uberjar are the reload4j replacements.
- https://issues.apache.org/jira/browse/AVRO-3304 …

AVRO-3304: Drop-in reload4j to  mitigate log4j 1.x

---

lang/rust/examples/generate_interop_data.rs
lang/rust/src/de.rs
lang/rust/src/decode.rs
lang/rust/src/encode.rs
lang/rust/src/reader.rs
lang/rust/src/schema.rs
lang/rust/src/ser.rs
lang/rust/src/types.rs
lang/rust/src/writer.rs
lang/rust/tests/io.rs

change Value::Union to value it holds and its position in the type list,
this allows us to
- [x ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-3248) issues and references them in the PR title. 
- [ x] My PR adds the following unit tests 
1. schema::tests::test_union_of_records
2. schema::tests::test_nullable_record
- [x ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
1. Subject uses the …

AVRO-3248: Rust: Support named types in UnionSchema

---

lang/rust/src/decode.rs
lang/rust/src/encode.rs
lang/rust/src/error.rs
lang/rust/src/ser.rs
lang/rust/src/types.rs

- https://issues.apache.org/jira/browse/AVRO-3312

AVRO-3312: Use u32 instead of i32 for the Enum/Union's index field

---

lang/js/etc/browser/avro.js
lang/js/lib/schemas.js

- https://issues.apache.org/jira/browse/AVRO-3322
- PR simply adds declarations that do not change the actual code logic

AVRO-3322: Buffer is not defined in browser environment

---

lang/rust/Cargo.toml
lang/rust/README.md
lang/rust/README.tpl
lang/rust/benches/serde.rs
lang/rust/benches/single.rs
lang/rust/build.sh
lang/rust/examples/benchmark.rs
lang/rust/examples/generate_interop_data.rs
lang/rust/examples/test_interop_data.rs
lang/rust/examples/to_value.rs
lang/rust/src/lib.rs
lang/rust/src/rabin.rs
lang/rust/src/reader.rs
lang/rust/tests/io.rs
lang/rust/tests/schema.rs

- https://issues.apache.org/jira/browse/AVRO-3339

AVRO-3339 Rust: Rename crate from avro-rs to apache-avro

---

lang/py/avro/io.py
lang/py/avro/schema.py

Apply style updates from Black 22.1.0, which is the first stable release of Black. This is necessary to get lang/py passing checks again. No ticket should be needed for this.

Update Styles to Stable Black 22.1.0

---

lang/csharp/src/apache/main/CodeGen/CodeGenUtil.cs

- https://issues.apache.org/jira/browse/AVRO-3342

AVRO-3342 Updated CodeGenUtil to standard documentation styling 

---

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
lang/csharp/src/apache/test/CodGen/CodeGenTest.cs

Additionally updated naming since it does not need to preserve Java like naming.
- https://issues.apache.org/jira/browse/AVRO-3335

AVRO-3335 Evaluate input of GenerateNames

---

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/enum.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/fixed.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/protocol.vm
lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java

- https://issues.apache.org/jira/browse/AVRO-3305
Existing SpecificCompiler.testMangle* tests were updated to cover more cases.

AVRO-3305: Only mangle type identifier keywords when used as types 

---

lang/csharp/src/apache/main/File/DataFileConstants.cs

- https://issues.apache.org/jira/browse/AVRO-3345

AVRO-3345: Made Magic readonly in DataFileConstants

---

lang/csharp/src/apache/main/Schema/EnumSchema.cs
lang/csharp/src/apache/test/Schema/SchemaTests.cs

Current implementation could return a KeyNotFoundException
- https://issues.apache.org/jira/browse/AVRO-3350

AVRO-3350 Validate default enum value exists before returning.

---

lang/csharp/src/apache/main/File/Codec.cs

- https://issues.apache.org/jira/browse/AVRO-3355

AVRO-3355 Fix order of access modifier

---

lang/java/avro/src/main/java/org/apache/avro/Resolver.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java
lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java
lang/java/avro/src/test/java/org/apache/avro/io/parsing/TestResolvingGrammarGenerator.java

Hello! This inconsistency between the schema compatibility checks and the resolver has tripped me up a few times, so I'd like to put in a fix for it. I didn't get any comments on my original issue and never got around to bumping it, so hopefully I've not misinterpreted this as a bug - it does seem to me to be an inconsistency with the specification.
(It looks like neither unqualified nor qualified name is used for resolving records, and [this comment](https://github.com/apache/avro/blob/98ee7b0c1fa815271a3da4e033bd4781748b0409/lang/java/avro/src/main/java/org/apache/avro/Resolver.java#L507) explains that it breaks some regression tests. Changing it to compare unqualified name (in line with the specification) would be a breaking change, and so I believe it to be out of the scope of this …

AVRO-3133: Fix enum resolution to be consistent with Apache Avro specification and the schema compatibility checks

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/idl/DocCommentHelper.java
lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
lang/java/compiler/src/test/idl/input/comments.avdl
lang/java/compiler/src/test/idl/output/comments.avpr
lang/java/compiler/src/test/java/org/apache/avro/compiler/idl/TestIdl.java

Use the previously introduced method `DocCommentHandler#clearDoc()` to
generate warnings for misplaced documentation. Also add documentation to
describe the tricky bits when using this method.
The brittleness of the solution proves that doc comments as special
tokens are a hack. However, making regular tokens out of them may break
existing `.avdl` files.
- https://issues.apache.org/jira/browse/AVRO-3294
-  `org.apache.avro.compiler.idl.TestIdl#testDocCommentsAndWarnings`
-  `input/comments.avdl` & `output/comments.avpr`
1. Subject …

AVRO-3294: Improve IDL doc comment handling

---

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java

this is to be able to load resources by absolute path on windows
…
- https://issues.apache.org/jira/browse/AVRO-3371
fixes 3 existing unit tests to pass on windows:
TestIDLProtocolMojo.testSetCompilerVelocityAdditionalTools
TestProtocolMojo.testSetCompilerVelocityAdditionalTools
TestSchemaMojo.testSetCompilerVelocityAdditionalTools …

AVRO-3371 - add empty string as 3rd velocity root in SpecificCompiler

---

lang/csharp/src/apache/main/File/Codec.cs
lang/csharp/src/apache/main/File/DataFileReader.cs
lang/csharp/src/apache/test/File/FileTests.cs

- https://issues.apache.org/jira/browse/AVRO-3259

AVRO-3259: Throw exception if unknown codec

---

lang/py/avro/errors.py
lang/py/avro/io.py
lang/py/avro/test/test_io.py

- https://issues.apache.org/jira/browse/AVRO-3380
* lang/py/avro/test/test_io.py::TestIncompatibleSchemaReading

AVRO-3380: Raise an exception if invalid number of bytes read
