apache/avro

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java
=> AVRO-2189: Fix typo in SchemaBuilder example

lang/c++/Doxyfile, lang/c++/impl/Compiler.cc, lang/c++/impl/json/JsonDom.hh, lang/c++/test/SchemaTests.cc
See https://issues.apache.org/jira/browse/AVRO-2209
=> Allow "integer" defaults for double and float

lang/java/ipc/src/test/java/org/apache/avro/io/Perf.java
I've been experimenting with a number of performance improvements.  This patch (AVRO-2251) modifies `Perf.java` to generate output that's more easily consumed by scripts (vs. humans).  The changes in this patch are 100% backward compatible.
=> Make Perf.java more friendly to automation scripts

doc/src/content/xdocs/gettingstartedjava.xml, doc/src/content/xdocs/spec.xml
See also: https://issues.apache.org/jira/browse/AVRO-1843
=> Clarify importance of writer's schema in documentation (master)

lang/java/tools/src/main/java/org/apache/avro/tool/SpecificCompilerTool.java
maven-avro-plugin allows to specify custom template directory (https://issues.apache.org/jira/browse/AVRO-983), same applies to
gradle-avro-plugin (https://github.com/commercehub-oss/gradle-avro-plugin#templatedirectory).
It would be useful to support that in Arvo CLI tools as well. Use case: generating Java classes during CI or for any scripting needs when using maven or gradle plugins is too much
=> Allow to set template dir for avro-tools compile

pom.xml
So we're up to date with the latest greatest
=> AVRO-2261 Bump Rat version

lang/java/avro/pom.xml, lang/java/avro/src/test/java/org/apache/avro/message/TestBinaryMessageEncoding.java, lang/java/mapred/pom.xml, lang/java/pom.xml
Get rid of Guava: https://github.com/apache/avro/pull/373
Ticket: https://issues.apache.org/jira/browse/AVRO-2265
=> AVRO-2265 Remove Guava as a test dependency

lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificLogicalTypes.java
Ticket: https://issues.apache.org/jira/browse/AVRO-2244
=> Test and fix for AVRO-2244

lang/java/tools/src/main/java/org/apache/avro/tool/DataFileReadTool.java, lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileTools.java
Let me know if this pull request should be pointed to a different branch.
=> AVRO-1858 add tojson head mode

lang/ruby/lib/avro/io.rb
This makes some performance improvements around unpacking strings and freezing some strings that cause a lot of unnecessary allocations in some cases. We can also take advantage of `unpack1` when running in a version of ruby that supports it.
=> AVRO-2281: Optimize ruby binary encoder/decoder

lang/java/avro/src/main/java/org/apache/avro/io/JsonDecoder.java, lang/java/avro/src/main/java/org/apache/avro/io/parsing/JsonGrammarGenerator.java, lang/java/avro/src/main/java/org/apache/avro/io/parsing/Symbol.java, lang/java/avro/src/test/java/org/apache/avro/TestReadingWritingDataInEvolvedSchemas.java
JsonDecoder doesn't honor aliases
=> AVRO-2184: Unable to decode JSON data file if a property is renamed in reader schema

lang/js/package.json
root@95b4c18065bf:/home/avro# tree dist
dist
├── avro-src-1.8.2.tar.gz
└── js
└── avro-js-1.8.2.tgz
1 directory, 2 files
=> AVRO-2025 Bump version in JS

lang/c++/api/DataFile.hh, lang/c++/impl/DataFile.cc, lang/c++/test/AvrogencppTests.cc, lang/c++/test/unittest.cc
Tested with macOS Xcode, gcc and docker.
=> Fix for move constructor errors and warnings

lang/java/compiler/pom.xml, lang/java/ipc/pom.xml, lang/java/mapred/src/test/java/org/apache/avro/mapreduce/TestAvroKeyOutputFormat.java, lang/java/pom.xml, lang/java/thrift/pom.xml, lang/java/trevni/avro/pom.xml, lang/java/trevni/core/pom.xml, lang/java/trevni/pom.xml
=> Upgrade avro dependencies to the latest versions

share/docker/Dockerfile
Now that #427 is merged this should be easy.
R: @Fokko 
CC: @blachniet
=> AVRO-2303: C#: Update docker image to use .net sdk 2.2

lang/java/pom.xml
=> AVRO-2315: Update zstd-jni to version 1.3.8-3

lang/java/avro/pom.xml, lang/java/pom.xml, pom.xml
=> AVRO-2317 Update hamcrest-library to version 2.1 and remove hamcrest-all

lang/java/pom.xml
=> AVRO-2316: Update ant to version 1.10.5

lang/py/src/avro/protocol.py, lang/py/src/avro/schema.py
Mainly, it hides errors. For specific details, please read Hynek Schlawack's [excellent blog post](https://hynek.me/articles/hasattr/).
=> AVRO-2321 Avoid hasattr in Python 2

lang/java/pom.xml
https://jira.apache.org/jira/browse/AVRO-2323
=> [AVRO-2323] Bump maven-jar-plugin to 3.1.1

lang/java/pom.xml
https://jira.apache.org/jira/browse/AVRO-2325
=> [AVRO-2325] Bump commons-codec from 1.11 to 1.12

pom.xml
https://jira.apache.org/jira/browse/AVRO-2324
=> [AVRO-2324] Update Apache parent POM to version 21

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java, lang/java/avro/src/main/java/org/apache/avro/io/BinaryData.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java
I shuffled around the code a bit so that simple native types are grouped together.
=> AVRO-2340: Use JDK compareTo and hashcode Methods

lang/java/pom.xml, pom.xml
This should fix it, PTAL 
R: @nandorKollar
=> AVRO-2362: Enable calling mvn spotless:apply to auto format code

lang/ruby/lib/avro/schema_validator.rb, lang/ruby/test/test_schema_validator.rb
See https://issues.apache.org/jira/browse/AVRO-2200
Currently, when passing a datum into the schema validator, the datum will pass even if the datum has more fields than the schema does. This can be dangerous because the client code is assuming that the schema has these values, but they are actually being silently swallowed when they are encoded.
This PR provides an option to make the validator fail on any extra fields.
=> AVRO-2200: Option to fail when extra fields are in the payload

lang/java/maven-plugin/src/test/resources/unit/idl/pom-joda.xml, lang/java/maven-plugin/src/test/resources/unit/idl/pom-jsr310.xml, lang/java/maven-plugin/src/test/resources/unit/protocol/pom-joda.xml, lang/java/maven-plugin/src/test/resources/unit/protocol/pom-jsr310.xml, lang/java/maven-plugin/src/test/resources/unit/schema/pom-joda.xml, lang/java/maven-plugin/src/test/resources/unit/schema/pom-jsr310.xml
https://jira.apache.org/jira/browse/AVRO-2374
=> [AVRO-2374] Remove hardcoded Jackson versions

lang/java/avro/src/main/java/org/apache/avro/reflect/AvroMeta.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
https://issues.apache.org/jira/browse/AVRO-2375
=> AVRO-2375: Allow repeating AvroMeta use

lang/java/avro/src/main/java/org/apache/avro/Protocol.java, lang/java/avro/src/main/java/org/apache/avro/Schema.java
https://jira.apache.org/jira/browse/AVRO-2377
=> AVRO-2377: Remove Reserved Words Initialization Blocks

share/githooks/commit-msg
See [AVRO-2394](https://issues.apache.org/jira/browse/AVRO-2394)
=> AVRO-2394: Remove CHANGES.txt check from commit-msg hook

build.sh, share/docker/Dockerfile, share/docker/DockerfileLocal
This MUST wait for AVRO-2405 to be completed !!!
=> AVRO-2408: Local docker based dev env with Forrest

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java, lang/java/compiler/src/test/resources/templates_with_custom_tools/record.vm, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/IDLProtocolMojo.java, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/ProtocolMojo.java, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/SchemaMojo.java, lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestIDLProtocolMojo.java, lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestProtocolMojo.java, lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestSchemaMojo.java, lang/java/maven-plugin/src/test/resources/templates/enum.vm, lang/java/maven-plugin/src/test/resources/templates/protocol.vm, lang/java/maven-plugin/src/test/resources/templates/record.vm, lang/java/maven-plugin/src/test/resources/unit/idl/pom-injecting-velocity-tools.xml, lang/java/maven-plugin/src/test/resources/unit/protocol/pom-injecting-velocity-tools.xml, lang/java/maven-plugin/src/test/resources/unit/schema/pom-injecting-velocity-tools.xml
Refer to [Avro-1762](https://issues.apache.org/jira/browse/AVRO-1762?focusedCommentId=16846039&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16846039) for more information.  
Avro 1762 pull request rebased on master and with some tests improvements.
This PR is a rebased version of #71
=> AVRO-1762: Velocity custom objects

lang/java/pom.xml
- https://issues.apache.org/jira/browse/AVRO-2430
=> AVRO-2430: Bump zstd 1.3.8-6 to 1.4.0-1

BUILD.md
- https://issues.apache.org/jira/browse/AVRO-2433
No additional test since it's a documentation fix.
=> AVRO-2433: Update the dependencies for Perl binding in BUILD.md

lang/java/avro/src/main/java/org/apache/avro/message/BinaryMessageDecoder.java, lang/java/avro/src/test/java/org/apache/avro/message/TestBinaryMessageEncoding.java
Cherry picked + squashed https://github.com/apache/avro/pull/557 onto branch-1.9
=> Avro 2440 branch 1.9

.travis.yml, .travis/before_install.sh, .travis/script.sh
There have been a few recent "close calls" on changes that would have broken the C# bindings on Windows. To help avoid this, I'd like to start running the C# tests on a Travis Windows agent.
To make this work, the contents of the `before_install` and `script` Travis CI steps were moved to
`./.travis/before_install.sh` and `./.travis/script.sh`. Within each of those scripts, the build
performs different actions based on the OS.
The matrix in the `.travis.yml` Specifies the two previous environments, `JAVA=8` and `JAVA=11`.
Additionally, it specifies a third environment that requires a Windows build agent.
The two original build environments do exactly the same thing. The are simply executed from the
build scripts rather than directly from the `.travis.yml`. The Windows environment only …
=> AVRO-2467: Run C# tests on Windows in Travis

lang/java/avro/src/main/java/org/apache/avro/Schema.java
=> Fix typo, it's fixed

lang/csharp/src/apache/main/Schema/UnnamedSchema.cs, lang/csharp/src/apache/test/Schema/SchemaTests.cs
- https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2500
=> AVRO-2500: Fixing serializing int type in some cultures

lang/csharp/src/apache/test/Interop/InteropDataConstants.cs, lang/csharp/src/apache/test/Interop/InteropDataGenerator.cs, lang/csharp/src/apache/test/Interop/InteropDataTests.cs, lang/py/setup.cfg
Fix insecure urls.
- https://issues.apache.org/jira/browse/AVRO-2404
=> AVRO-2404: Fix insecure urls.

lang/java/maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Permit building on configuration but not on incremental.
=> AVRO-2479: Add m2e lifecycle mapping file for maven

pom.xml
- https://issues.apache.org/jira/browse/AVRO-2497
No additional test, since it's a fix for the build process. Instead, I ran some commands manually and confirmed the fix worked as expected.
Reproducing the problem without the fix:
```
sekikn@f71991757016:~/avro$ cd lang/java/maven-plugin
sekikn@f71991757016:~/avro/lang/java/maven-plugin$ mvn install
(snip)
[WARNING] 
Goal prefix is specified as: 'spotless'. Maven currently expects it to be 'avro'.
(snip)
[INFO] Installing /home/sekikn/avro/lang/java/maven-plugin/target/avro-maven-plugin-1.10.0-SNAPSHOT-tests.jar to …
```
=> AVRO-2497: Avro-grpc failed when spotless:check alone

lang/java/pom.xml
R: @Fokko or @dkulp 
https://issues.apache.org/jira/browse/AVRO-2531
=> AVRO-2531: Update commons-compress to version 1.19

lang/java/pom.xml
https://jira.apache.org/jira/browse/AVRO-2533
=> AVRO-2533: Bump jetty.version from 9.4.18.v20190429 to 9.4.20.v20190813

lang/java/pom.xml
https://en.wikipedia.org/wiki/Java_servlet
Supports HTTP/2 :-)
=> AVRO-2534: Bump javax.servlet-api from 3.1.0 to 4.0.1

lang/java/pom.xml
- https://issues.apache.org/jira/browse/AVRO-2541
=> AVRO-2541: Bump velocity-engine-core from 2.0 to 2.1

lang/java/checkstyle.xml, lang/java/pom.xml, pom.xml
- https://issues.apache.org/jira/browse/AVRO-2542
=> AVRO-2542: Bump various Maven plugins

lang/java/pom.xml
- https://issues.apache.org/jira/browse/AVRO-2540
=> AVRO-2540: Bump commons-lang3 from 3.8.1 to 3.9.0

doc/examples/java-example/src/main/java/example/GenericMain.java
- https://issues.apache.org/jira/browse/AVRO-2557
=> AVRO-2557: user.avsc file address error

lang/java/pom.xml
=> AVRO-2583: Bump grpc.version from 1.23.0 to 1.24.0

lang/java/pom.xml
=> AVRO-2582: Bump protobuf-java from 3.9.1 to 3.10.0

lang/java/pom.xml
=> AVRO-2585: Bump jetty.version from 9.4.20.v20190813 to 9.4.21.v20190926

share/docker/Dockerfile
This PR refactors the Dockerfile so it's easier to isolate failures from individual sources. Then it fixes the problem with the outdated Microsoft .Net install instructions.
=> AVRO-2590: Dockerfile Fails to Fetch Microsoft Dist

lang/py/test/set_avro_test_path.py
=> AVRO-2605: Remove Use of Filter Function

lang/py/test/test_tether_word_count.py
Use the Python `with` block better to ensure file descriptors and other resources get closed.
=> AVRO-2603: Context Managers to Manage Resources

build.sh, share/docker/Dockerfile
=> AVRO-2609 Send Minimal Build Context to Docker

doc/src/content/xdocs/spec.xml
=> AVRO-2030: Link to Google Books Chapter

lang/py/test/test_tether_word_count.py
=> AVRO-2603: Check Exit Status of Tether Tool Command

lang/py/test/test_tether_word_count.py
=> AVRO-2603: Simplify and Clean Up Assertions

lang/py/scripts/avro, lang/py/test/test_script.py
=> AVRO-2614: Remove Trailing Spaces in Pretty Print

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
https://issues.apache.org/jira/browse/AVRO-2600
=> AVRO-2600: Swap to new properties in Velocity Engine

lang/py/test/test_tether_word_count.py
=> AVRO-2603: Setup and Teardown

lang/py3/setup.cfg
=> AVRO-2631: Install the Right Snappy

.gitignore
Trivial change that ignores some stuff that makes it easier to do local python work.
=> Ignore Python Local Development Files

lang/py/src/avro/tool.py, share/test/interop/bin/test_rpc_interop.sh
=> AVRO-2635: Use Tools via python -m

lang/py/src/avro/schema.py, lang/py/test/test_schema.py
=> AVRO-621: Stricter Name Validation

lang/java/avro/src/main/java/org/apache/avro/Protocol.java, lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/Pair.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/tether/TetherJob.java
=> AVRO-2629: Use Java Collections and Arrays Utilities

lang/js/package-lock.json, lang/js/package.json
This PR fixes 1 low, 6 moderate, 3 high, 1 critical issues.
=> AVRO-2634 - Fix critical CVE in Javascript component

lang/java/pom.xml
=> AVRO-2646: Update Jetty to version 9.4.24.v20191120

lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroMultipleInputs.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/DelegatingInputFormat.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/tether/TetheredProcess.java
- https://issues.apache.org/jira/browse/AVRO-2625
=> AVRO-2625:System.out.print should not be used a log record

lang/js/package-lock.json, lang/js/package.json
Cherry pick of #722 into branch-1.9
R: @RyanSkraba 
CC: @coheigea
=> AVRO-2634: Fix critical CVE in Javascript component

share/test/interop/bin/test_rpc_interop.sh
=> AVRO-2661: Fixup Test RPC Interop

lang/py/tox.ini, share/docker/Dockerfile
=> AVRO-2662: Report Coverage in Python Tests

share/docker/Dockerfile
=> AVRO-2678: Update node.js version (used for js tests) to current LTS (10.x.x)

pom.xml
The Maven parent project, provided by the ASF
- https://issues.apache.org/jira/browse/AVRO-2685
=> AVRO-2685: Bump apache from 21 to 22

lang/java/pom.xml
- https://issues.apache.org/jira/browse/AVRO-2680
=> AVRO-2680: Bump grpc.version from 1.24.1 to 1.26.0

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader12.java, lang/java/avro/src/test/java/org/apache/avro/TestProtocol.java, lang/java/avro/src/test/java/org/apache/avro/TestSchema.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaValidation.java, lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/compiler/src/test/java/org/apache/avro/compiler/idl/TestIdl.java, lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java, lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroGrpcClient.java, lang/java/grpc/src/main/java/org/apache/avro/grpc/ServiceDescriptor.java, lang/java/ipc-netty/src/main/java/org/apache/avro/ipc/netty/NettyServer.java, lang/java/ipc-netty/src/main/java/org/apache/avro/ipc/netty/NettyTransceiver.java, lang/java/ipc/src/main/java/org/apache/avro/ipc/SaslSocketTransceiver.java, lang/java/ipc/src/main/java/org/apache/avro/ipc/stats/StatsServlet.java, lang/java/ipc/src/test/java/org/apache/avro/ipc/TestSaslAnonymous.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroMultipleOutputs.java, lang/java/mapred/src/test/java/org/apache/avro/hadoop/file/TestSortedKeyValueFile.java, lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java, lang/java/tools/src/main/java/org/apache/avro/tool/TetherTool.java
- https://issues.apache.org/jira/browse/AVRO-2708
=> AVRO-2708: Remove Unused Code

build.sh, doc/src/content/xdocs/site.xml, doc/src/content/xdocs/tabs.xml, lang/java/avro/src/main/java/org/apache/avro/Protocol.java, lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm, lang/java/integration-test/codegen-test/pom.xml, lang/java/integration-test/codegen-test/src/test/java/org/apache/avro/codegentest/TestLogicalTypeForStringType.java, lang/java/integration-test/codegen-test/src/test/resources/avro/string_logical_type.avsc, lang/java/pom.xml, lang/java/tools/src/main/java/org/apache/avro/tool/DataFileReadTool.java, lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java, lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java, lang/java/tools/src/test/compiler/output/Player.java, lang/java/tools/src/test/java/org/apache/avro/tool/TestDataFileTools.java, lang/perl/build.sh, lang/perl/lib/Avro/Schema.pm, lang/perl/share/interop-data-generate, lang/perl/xt/interop.t, lang/perl/xt/schema.t, lang/py/setup.cfg, lang/py/src/avro/schema.py, lang/py/test/test_io.py, lang/py/test/test_schema.py, lang/py3/setup.cfg, lang/ruby/Gemfile, share/githooks/commit-msg, share/test/schemas/reserved.avsc
Going through the JIRA resolved and commits in 1.10.0, this PR cherry picks:
* PRs that are marked as fixed in JIRA but don't see to be fixed yet in branch-1.9 (unless I'm mistaken),
* Some simple documentation and bug fixes that I think should be included in 1.9.2.
(Based on #777, containing the cherry-picks related to python, should be merged after.)
- https://issues.apache.org/jira/browse/AVRO-2719
1. Body …
=> AVRO-2719: Additional cherry-picks for 1.9.2

lang/csharp/src/apache/codegen/AvroGen.cs
- https://issues.apache.org/jira/browse/AVRO-2695
=> AVRO-2695: avrogen: Non-zero exit code if failure and write error messages to stderr

lang/java/maven-plugin/pom.xml, lang/java/pom.xml, pom.xml
- https://issues.apache.org/jira/browse/AVRO-2710
=> AVRO-2710: Upgrade Avro Maven Plugin to 3.X

lang/java/avro/src/main/java/org/apache/avro/file/ZstandardLoader.java, lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java, lang/java/pom.xml
=> AVRO-2726: Upgrade Jackson to version 2.10.2

lang/java/pom.xml
=> AVRO-2727: Update hadoop3 to version 3.2.1

lang/java/avro/src/main/java/org/apache/avro/file/ZstandardLoader.java, lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java, lang/java/pom.xml
Cherry pick of 
AVRO-2727: Update hadoop3 to version 3.2.1
AVRO-2726: Upgrade Jackson to version 2.10.2
R: @RyanSkraba
=> [branch-1.9] Cherry pick AVRO-2727 #799 and AVRO-2726 #800

doc/src/content/mddocs/refactoring-resolution.md, lang/java/avro/src/main/java/org/apache/avro/Resolver.java, lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java
* [AVRO-2663] Bug with nested record
* Compare the names as well
* Apply stylecheck
* Fix some docs
* Make spotless happy
* Remove unused statement
* Fix Spotless error
- All the public functions and the classes in the PR contain Javadoc …
=> AVRO-2663: Record inside of Union is not resolved properly (#752)

lang/java/pom.xml
=> AVRO-2729: Upgrade Velocity to version 2.2

.travis/before_install.sh, lang/csharp/build.sh, lang/csharp/src/apache/codegen/Avro.codegen.csproj, lang/csharp/src/apache/perf/Avro.perf.csproj, lang/csharp/src/apache/test/Avro.test.csproj, lang/csharp/src/apache/test/CodGen/CodeGenTest.cs, lang/csharp/src/apache/test/Specific/SpecificTests.cs, share/docker/Dockerfile
=> AVRO-2693: Upgrade to netcoreapp3.1

lang/py/avro/schema.py
=> AVRO-2740: Remove Duplicate LogicalType

lang/java/pom.xml
=> AVRO-2744: Update commons-compress to version 1.20

lang/java/pom.xml
=> AVRO-2743: Update zstd-jni to version 1.4.4-7

lang/java/ipc-netty/src/main/java/org/apache/avro/ipc/netty/NettyTransceiver.java, lang/java/mapred/src/main/java/org/apache/avro/hadoop/file/SortedKeyValueFile.java, lang/java/mapred/src/main/java/org/apache/avro/hadoop/io/AvroSequenceFile.java
- https://issues.apache.org/jira/browse/AVRO-2711
=> AVRO-2711: Use SLF4J Parameterized Logging for Debug Statements

lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java
=> AVRO-2761: Prevent NPE when creating SpecificDatumReader/Writer

lang/js/package-lock.json, lang/js/package.json
- https://issues.apache.org/jira/browse/AVRO-2758
No additional test, since it's a version upgrade for a code coverage tool. I ran `./build.sh test` in `lang/js` and confirmed that no vulnerabilities found, as follows:
```
sekikn@0327d61710c0:~/avro/lang/js$ grep istanbul package.json 
"cover": "istanbul cover _mocha -- -f interop -i",
"istanbul": "^0.4.5",
sekikn@0327d61710c0:~/avro/lang/js$ ./build.sh test
audited 356 packages in 1.506s
4 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
> avro-js@1.9.0 cover /home/sekikn/avro/lang/js
> istanbul …
```
=> AVRO-2758: Bump istanbul to 0.4.5

lang/perl/MANIFEST, lang/perl/Makefile.PL, lang/perl/build.sh, lang/perl/lib/Avro/BinaryDecoder.pm, lang/perl/lib/Avro/BinaryEncoder.pm, lang/perl/lib/Avro/DataFile.pm, lang/perl/lib/Avro/DataFileReader.pm, lang/perl/lib/Avro/DataFileWriter.pm, lang/perl/lib/Avro/Protocol.pm, lang/perl/lib/Avro/Protocol/Message.pm, lang/perl/lib/Avro/Schema.pm
- https://issues.apache.org/jira/browse/AVRO-1461
No additional test, since it's mainly a fix for the build scripts.
=> AVRO-1461: Distribute Perl API on CPAN

lang/java/avro/src/main/java/org/apache/avro/Resolver.java
- https://issues.apache.org/jira/browse/AVRO-2694
=> AVRO-2694: Simplify Comparison Check in Resolver

lang/java/avro/src/main/java/org/apache/avro/io/BinaryData.java
- https://issues.apache.org/jira/browse/AVRO-2696
=> AVRO-2696: Improve Avro Double and Float Encode Performance

lang/java/avro/src/main/java/org/apache/avro/io/BinaryData.java, lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryData.java
- https://issues.apache.org/jira/browse/AVRO-2698
=> AVRO-2698: Improve and Add Test for skipLong Method

lang/java/avro/src/main/java/org/apache/avro/Protocol.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
- [C] In case of new functionality, my PR adds documentation that describes how to use it.
=> AVRO-2700: Change Java Collection Usage

lang/java/avro/src/main/java/org/apache/avro/util/Utf8.java, lang/java/avro/src/test/java/org/apache/avro/util/TestUtf8.java
- https://issues.apache.org/jira/browse/AVRO-2704
=> AVRO-2704: Cache Hashcode of UTF8 Strings

lang/ruby/Gemfile
- https://issues.apache.org/jira/browse/AVRO-2807
No additional test, since it's a fix for the Docker image. I ran `./build.sh docker` locally and confirmed it succeeded.
=> AVRO-2807: Pin RuboCop to <=0.81

lang/java/pom.xml
This PR does not involve scenario use cases, just associate grpc ticket.
Eg: 
https://github.com/grpc/grpc-java/issues/6601
- https://issues.apache.org/jira/browse/AVRO-2811
=> AVRO-2811:Upgrade grpc 1.26 to 1.28

lang/py/avro/io.py, lang/py/avro/schema.py
Leverage each schema type's internal knowledge of its matching logic to
simplify schema matching code. This object-oriented refactor is intended
to make it easier to approach tickets like AVRO-2748. It doesn't
actually resolve the issue, but makes it possible to reason about in
better isolation.
=> AVRO-2748: Refactor Schema Matching

lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroInputFormat.java
- https://issues.apache.org/jira/browse/AVRO-2802
=> AVRO-2802: Pre-Size List in AvroInputFormat Avro File Lookup

.asf.yaml, .yamllint.yml
ML thread for more details
https://lists.apache.org/thread.html/rada5d1b3dbee3469940d89d5c43042d008dcec026967c099fba04ade%40%3Cdev.avro.apache.org%3E
R: @RyanSkraba @Fokko
=> AVRO-2826: Add .asf.yaml file to configure github notifications

lang/php/lib/avro.php
Added missing AvroNotImplementedException implementation.
=> AVRO-2828: Add AvroNotImplementedException

lang/c/tests/test_interop_data.c
This PR is a fix for test_interop_data.c.
=> AVRO-2453: Implement interop test for the C bindings

lang/c/src/codec.c
- My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issue: https://issues.apache.org/jira/browse/AVRO-2718
=> [avro-c] Fixed building with Snappy enabled in Windows

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
- https://issues.apache.org/jira/browse/AVRO-2762
=> AVRO-2762:Unkown resource closed

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
Replace <> with `&lt;` and `&gt;`
[AVRO-2770](https://issues.apache.org/jira/browse/AVRO-2770)
=> Fix Optional Javadoc

doc/examples/java-example/pom.xml, doc/examples/mr-example/pom.xml
- https://issues.apache.org/jira/browse/AVRO-2558
=> AVRO-2558: Updatejava/mr-example pom to load into m2e

lang/php/lib/avro/data_file.php, lang/php/test/InterOpTest.php, share/docker/Dockerfile
Added bzip2 codec like the one seen in the java implementation.
=> AVRO-2841: PHP - Add Bzip2 codec

lang/csharp/src/apache/main/Generic/GenericDatumReader.cs, lang/csharp/src/apache/main/Generic/GenericDatumWriter.cs, lang/csharp/src/apache/main/Generic/GenericReader.cs, lang/csharp/src/apache/main/Generic/GenericRecord.cs, lang/csharp/src/apache/main/Generic/GenericWriter.cs, lang/csharp/src/apache/test/Generic/GenericTests.cs
Jira: https://issues.apache.org/jira/browse/AVRO-2782
Changed GenericRecord to have indexed access to field values, also changed writers and reader to use the indexed access. This improves performance (as there is no calculations of has codes).
No new tests as the change is already covered by existing tests
=> AVRO-2782:Add indexed access to C# GenericRecord

lang/java/tools/src/main/java/org/apache/avro/tool/Main.java, lang/java/tools/src/main/java/org/apache/avro/tool/RecordCountTool.java, lang/java/tools/src/test/java/org/apache/avro/tool/TestRecordCountTool.java
- https://issues.apache.org/jira/browse/AVRO-1720
org.apache.avro.tool.TestRecordCountTool
=> AVRO-1720: Add tool to count records in avro files

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java
- https://issues.apache.org/jira/browse/AVRO-2703
=> AVRO-2703: Use KMP Algorithm For Sync Marker Search

doc/src/content/xdocs/spec.xml
Adding a bit of documentation, no Jira ticket.
Documentation update
Improves existing documentation
=> Add example schema for date logical type field to spec docs

lang/java/avro/src/main/java/org/apache/avro/Schema.java
- https://issues.apache.org/jira/browse/AVRO-2068
=> AVRO-2068: Improved static class constructor performance

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
Simply ran `mvn spotless:apply`
=> Fix spotless format

lang/java/build.sh, lang/java/pom.xml
=> AVRO-2850: Configure Hadoop 2 tests execution for backwards compatibility

lang/java/pom.xml
=> AVRO-2811: Fix incorrect repeated grpc version of 1.28.0

lang/java/pom.xml
=> AVRO-2852: Update Thrift to version 0.13.0

doc/src/content/xdocs/sasl.xml, lang/java/pom.xml, lang/py/avro/test/mock_tether_parent.py, lang/py/avro/tether/tether_task_runner.py
=> AVRO-2853: Upgrade jackson to version 2.11.0

lang/java/pom.xml
=> AVRO-2854: Upgrade hamcrest to version 2.2

lang/java/pom.xml, pom.xml
=> Update some maven plugins: antrun (3.0.0) spotless (1.31.1)

lang/java/protobuf/src/main/java/org/apache/avro/protobuf/ProtobufData.java, lang/java/thrift/src/main/java/org/apache/avro/thrift/ThriftData.java
=> AVRO-2780: ProtobufData and ThriftData Can Get Into Endless Loop

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java, lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
- https://issues.apache.org/jira/browse/AVRO-2757
=> AVRO-2757: Avoid dollar signs when reflecting Java

lang/py/avro/test/test_tether_task_runner.py, lang/py/avro/tether/tether_task_runner.py
=> AVRO-2889: Fix Flaky Test Race Condition

lang/py/avro/codecs.py, lang/py/avro/datafile.py, lang/py/avro/errors.py, lang/py/avro/io.py, lang/py/avro/ipc.py, lang/py/avro/protocol.py, lang/py/avro/schema.py, lang/py/avro/test/mock_tether_parent.py, lang/py/avro/test/sample_http_client.py, lang/py/avro/test/test_datafile.py, lang/py/avro/test/test_io.py, lang/py/avro/test/test_protocol.py, lang/py/avro/test/test_schema.py, lang/py/avro/test/txsample_http_client.py, lang/py/avro/tether/tether_task.py, lang/py/avro/tether/tether_task_runner.py, lang/py/scripts/avro
=> AVRO-2893: Isolate Errors to Simplify Import Graph

doc/examples/java-example/pom.xml, doc/examples/mr-example/pom.xml, lang/js/package.json, pom.xml, share/docker/Dockerfile
=> Various missing fixes and improvements after the 1.10.0 release

doc/src/content/xdocs/spec.xml
Current has an error in the map example. Using the following schema
```
{
"name": "Demo",
"namespace": "demo",
"fields": [
{
"name": "someMap",
"type": {
"type": "map",
"items": "long"
}
}
]
}
```
and trying to generate Java files results in an error:
```
$ java -jar avro-tools-1.10.0.jar compile schema demo.avsc output
Input files to compile:
demo.avsc
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.apache.avro.SchemaParseException: Map has no values type: {"type":"map","items":"long"}
at org.apache.avro.Schema.parse(Schema.java:1711)
at …
```
=> Fixed map example

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
Optimization to GenericData.addLogicalTypeConversion to about double map lookup.
=> AVRO-2936: Optimize GenericData.addLogicalTypeConversion

composer.json
- https://issues.apache.org/jira/browse/AVRO-2949
=> AVRO-2949: Bump composer-monorepo-plugin for Composer 2

lang/perl/README, lang/perl/lib/Avro.pm
- https://issues.apache.org/jira/browse/AVRO-2945
Documentation only
=> AVRO-2945: Add CPAN trademark clarification.

lang/java/pom.xml, pom.xml
I added all of this in a single PR so we run the full checks with all. However I let at your discretion if squashing them or not to ease cherry picking.
R: @RyanSkraba
=> AVRO-2964-2973: Multiple version updates for Java

build.sh, lang/php/build.sh, lang/php/lib/AvroDebug.php, lang/php/lib/AvroIO.php, lang/php/lib/DataFile/AvroDataIO.php, lang/php/lib/IO/AvroFile.php, lang/php/lib/Schema/AvroField.php, lang/php/lib/Schema/AvroName.php, lang/php/lib/Schema/AvroSchema.php, pom.xml
- https://issues.apache.org/jira/browse/AVRO-2975
No additional unit test, since this PR fixes the test itself. I ran `./build.sh clean test` in the Docker container locally and confirmed it succeeded.
- All the public functions and the classes in the PR contain Javadoc that explain what …
=> AVRO-2975: Enable PHP linting and fix its errors

composer.json, lang/java/avro/src/main/java/org/apache/avro/io/parsing/ResolvingGrammarGenerator.java, lang/java/avro/src/test/java/org/apache/avro/io/parsing/TestResolvingGrammarGenerator2.java, share/docker/Dockerfile
This PR adds a commit for unit testing the fix from https://github.com/apache/avro/pull/980
This shouldn't be squashed, credit to @bellemare 
This is also built on top of the PHP fix from https://github.com/apache/avro/pull/986
- https://issues.apache.org/jira/browse/AVRO-2702 …
=> AVRO-2702: Fix and test UNION equivalents.

.github/dependabot.yml
This has to be enabled by INFRA too.
=> AVRO-9262: Configure dependency updates via dependabot

README.md
Just updates the base README with appropriate status badges and links for Github actions.
=> AVRO-3009: Update Status Badges in Readme

lang/java/pom.xml
=> AVRO-3024: Bump Jackson to 2.11.4

lang/java/avro/src/test/java/org/apache/avro/TestDataFileReader.java
Retry the test for leaked file descriptors in case there was a change due to a running background process.
=> AVRO-3033: Fix flaky file descriptor test

lang/c++/api/Zigzag.hh, lang/c++/impl/Zigzag.cc
=> Modernizing Zigzag

lang/java/perf/pom.xml
=> Bump jmh.version from 1.27 to 1.28 in /lang/java

lang/java/pom.xml
=> Bump commons-lang3 from 3.11 to 3.12.0 in /lang/java

lang/java/pom.xml
=> Bump jackson.version from 2.12.1 to 2.12.2 in /lang/java

lang/js/package-lock.json, lang/js/package.json
I am not 100% clear about how the lock file works but it seems to be the way to override the unwanted deps.
R: @RyanSkraba
=> AVRO-3062: Upgrade javascript mocha and handlebars transitive dependencies

lang/c++/.gitignore, lang/c++/build.sh, lang/perl/README, pom.xml
- https://issues.apache.org/jira/browse/AVRO-3069
Build fix.
=> AVRO-3069: Ignore modified files after build

share/docker/DockerfileLocal
- https://issues.apache.org/jira/browse/AVRO-3079
I locally ran `./build.sh docker` and made sure that it succeeded.
=> AVRO-3079: Fix Forrest download URL in Dockerfile

lang/c++/impl/json/JsonIO.hh
- https://issues.apache.org/jira/browse/AVRO-3070
=> Fixed the error that caused C++ lint to fail

lang/c++/impl/NodeImpl.cc, lang/c++/impl/ValidSchema.cc, lang/c++/impl/json/JsonIO.hh, lang/c++/test/DataFileTests.cc
- https://issues.apache.org/jira/browse/AVRO-3089
=> Avro 3089 fix cpp warnings

lang/c++/impl/Compiler.cc, lang/c++/impl/json/JsonDom.cc, lang/c++/impl/json/JsonDom.hh, lang/c++/impl/json/JsonIO.cc, lang/c++/impl/json/JsonIO.hh, lang/c++/impl/parsing/JsonCodec.cc, lang/c++/test/JsonTests.cc
- https://issues.apache.org/jira/browse/AVRO-3051
=> AVRO-3051: Modernized JSON module

lang/c++/test/AvrogencppTestReservedWords.cc, lang/c++/test/AvrogencppTests.cc, lang/c++/test/CodecTests.cc, lang/c++/test/CompilerTests.cc, lang/c++/test/DataFileTests.cc, lang/c++/test/LargeSchemaTests.cc, lang/c++/test/SchemaTests.cc, lang/c++/test/SpecificTests.cc, lang/c++/test/StreamTests.cc, lang/c++/test/buffertest.cc, lang/c++/test/testparser.cc, lang/c++/test/unittest.cc
- https://issues.apache.org/jira/browse/AVRO-3051
=> AVRO-3051: Modernized unit tests

doc/examples/java-example/pom.xml, doc/examples/mr-example/pom.xml, lang/java/pom.xml
=> AVRO-3111: Update Hadoop versions to prevent false-positive security reports

.github/workflows/test-lang-js.yml
=> AVRO-3009: Run Avro JS tests only for LTS versions of node

.github/workflows/test-lang-c++.yml, .github/workflows/test-lang-c.yml, .github/workflows/test-lang-csharp.yml, .github/workflows/test-lang-java.yml, .github/workflows/test-lang-js.yml, .github/workflows/test-lang-perl.yml, .github/workflows/test-lang-php.yml, .github/workflows/test-lang-py.yml, .github/workflows/test-lang-ruby.yml
=> AVRO-3009: Trigger CI tests when specific github actions are modified

.github/workflows/test-lang-java.yml
This is a temporal fix until github rolls out their fix https://github.com/actions/virtual-environments/issues/3185
R: @RyanSkraba
=>  AVRO-3009: Fix IP address in GitHub Actions container

lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java, lang/java/compiler/src/test/java/org/apache/avro/compiler/specific/TestSpecificCompiler.java, lang/java/compiler/src/test/resources/simple_record_for_scape.avsc
- https://issues.apache.org/jira/browse/AVRO-3116
=> AVRO-3116: Mangle Java16 keywords appropriately.

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java, lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java
- [ x ] My PR addresses the following [AVRO-3124](https://issues.apache.org/jira/browse/AVRO-3124) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
- https://issues.apache.org/jira/browse/AVRO-3124
- [ x ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
* TestGenericData.java
- [ x ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
1. Subject is separated …
=> AVRO-3124: Produce valid string for Temporal JSON serialization

lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/main/java/org/apache/avro/reflect/CustomEncoding.java, lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java, lang/java/avro/src/test/java/org/apache/avro/FooBarSpecificRecord.java, lang/java/avro/src/test/java/org/apache/avro/TypeEnum.java, lang/java/eclipse-java-formatter.xml, lang/java/grpc/src/main/java/org/apache/avro/grpc/AvroGrpcClient.java, lang/java/ipc/src/main/java/org/apache/avro/ipc/Requestor.java, lang/java/ipc/src/main/java/org/apache/avro/ipc/stats/Histogram.java, lang/java/mapred/src/main/java/org/apache/avro/hadoop/io/AvroDatumConverter.java, lang/java/mapred/src/main/java/org/apache/avro/mapred/AvroMultipleOutputs.java, lang/java/mapred/src/main/java/org/apache/avro/mapreduce/AvroKeyValueOutputFormat.java, lang/java/mapred/src/test/java/org/apache/avro/mapreduce/AvroFiles.java, lang/java/pom.xml, lang/java/trevni/avro/src/main/java/org/apache/trevni/avro/mapreduce/AvroTrevniKeyOutputFormat.java, lang/java/trevni/avro/src/main/java/org/apache/trevni/avro/mapreduce/AvroTrevniKeyValueInputFormat.java, lang/java/trevni/avro/src/main/java/org/apache/trevni/avro/mapreduce/AvroTrevniKeyValueOutputFormat.java, lang/java/trevni/avro/src/main/java/org/apache/trevni/avro/mapreduce/AvroTrevniRecordReaderBase.java, lang/java/trevni/avro/src/main/java/org/apache/trevni/avro/mapreduce/AvroTrevniRecordWriterBase.java, lang/java/trevni/core/src/main/java/org/apache/trevni/ValueType.java, pom.xml
=> Bump maven-spotless-plugin from 1.31.1 to 2.10.3

.github/workflows/spotless.yml
So we can fail builds eagerly in case of formatting issues
R: @RyanSkraba
=> Add spotless github action

.github/workflows/test-lang-js.yml, share/docker/Dockerfile
=> AVRO-3131: Drop support for Node.js 10

lang/py/avro/tether/util.py
=> AVRO-2921: Typefix avro.tether.util

lang/py/avro/compatibility.py, lang/py/avro/schema.py
Add type hints to avro.schema while ensuring no breaking changes.
N/A
=> AVRO-2921: Incremental Type Hints for avro.schema

lang/py/avro/codecs.py, lang/py/avro/datafile.py, lang/py/avro/test/gen_interop_data.py, lang/py/avro/test/test_bench.py, lang/py/avro/test/test_datafile.py, lang/py/avro/test/test_init.py, lang/py/avro/test/test_io.py, lang/py/avro/test/test_ipc.py, lang/py/avro/test/test_protocol.py, lang/py/avro/test/test_schema.py, lang/py/avro/test/test_script.py, lang/py/avro/test/test_tether_task.py, lang/py/avro/test/test_tether_task_runner.py, lang/py/avro/test/test_tether_word_count.py, lang/py/avro/tether/tether_task_runner.py
=> AVRO-2921: Type Fixes for avro.codecs

pom.xml, share/docker/Dockerfile
=> AVRO-3113: Align maven versions

lang/java/ipc-netty/src/main/java/org/apache/avro/ipc/netty/NettyTransceiver.java
Otherwise it leaks the workerGroup for every connection, as it is never closed on server side.
- https://issues.apache.org/jira/browse/AVRO-3165
N / A
=> AVRO-3165: Do not create workerGroup if NettyTransceiver created via internal Constructor

lang/java/avro/src/main/java/org/apache/avro/SchemaBuilder.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java
- https://issues.apache.org/jira/browse/AVRO-3144
=> AVRO-3144 Support for enabling and disabling default value validation through SchemaBuilder

lang/java/pom.xml
A bunch of vulnerabilities have been disclosed recently for the version 1.20:
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316638
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316640
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316641
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316639
1. Body wraps …
=> Update apache/commons-compress to 1.21

lang/ruby/lib/avro/ipc.rb
https://issues.apache.org/jira/browse/AVRO-3180
=> AVRO-3180: Interop tests fail on force_encoding

lang/py/avro/test/test_bench.py
- https://issues.apache.org/jira/browse/AVRO-3067
=> AVRO-3067: Bump validation times for PyPy

lang/java/integration-test/codegen-test/src/test/java/org/apache/avro/codegentest/TestCustomConversion.java, lang/java/integration-test/codegen-test/src/test/resources/avro/custom_conversion_idl.avdl, pom.xml
- https://issues.apache.org/jira/browse/AVRO-3191
=> AVRO-3191: logical type idl example

share/docker/Dockerfile
- https://issues.apache.org/jira/browse/AVRO-3195
=> AVRO-3195: Include rust in the docker build image

lang/rust/benches/serde.rs, lang/rust/examples/benchmark.rs, lang/rust/src/de.rs, lang/rust/src/encode.rs, lang/rust/src/reader.rs, lang/rust/src/schema.rs, lang/rust/src/writer.rs, lang/rust/tests/schema.rs
=> AVRO-3200 Fix some new lint errors

.github/workflows/test-lang-rust-audit.yml
=> AVRO-3199 Try to run Rust audit checks

lang/js/test/test_files.js
=> AVRO-3171 Since there is no read on the Readable there is no 'end' event

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java
Performance, no change in functionality.
=> AVRO-3184: Cache Datum Type Strings in Resolve Union

lang/java/avro/src/test/java/org/apache/avro/TestDataFileCorruption.java, lang/java/compiler/pom.xml, lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj, lang/java/compiler/src/test/idl/putOnClassPath/folder/relativePath.avdl, lang/java/compiler/src/test/java/org/apache/avro/compiler/idl/TestIdl.java
=> AVRO-3095: Handle relative imports in resources

.github/workflows/test-lang-py.yml, BUILD.md, lang/py/avro/__main__.py, lang/py/avro/datafile.py, lang/py/avro/io.py, lang/py/setup.cfg, lang/py/tox.ini, share/docker/Dockerfile
=> AVRO-3721 Support Python 3.10; Fix Annotations

.gitignore, lang/c++/test/CodecTests.cc, lang/csharp/build.sh
No need of JIRA. Just spelling fixes and .gitignore
=> Minor non functional changes

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj, lang/java/compiler/src/test/idl/input/reservedwords.avdl, lang/java/compiler/src/test/idl/input/uuid.avdl, lang/java/compiler/src/test/idl/output/import.avpr, lang/java/compiler/src/test/idl/output/nestedimport.avpr, lang/java/compiler/src/test/idl/output/reservedwords.avpr, lang/java/compiler/src/test/idl/output/uuid.avpr
=> AVRO-3251 AVDL files containing fields called "uuid" no longer compile.

.github/workflows/java-publish-snapshot.yml
=> AVRO-3241 [Java] Publish SNAPSHOT artifacts

lang/rust/src/types.rs
Just a typo PR. Close as desired.
=> [Rust] Duplicate doc line remove

lang/rust/Cargo.toml, lang/rust/README.md, lang/rust/src/codec.rs, lang/rust/src/lib.rs
=> AVRO-3246 Rust: Add new codec: bzip2

.github/workflows/test-lang-rust-miri.yml, lang/rust/src/lib.rs, lang/rust/src/schema.rs
=> AVRO-3247 Rust: Run MIRI checks

.github/workflows/test-lang-ruby.yml
- https://issues.apache.org/jira/browse/AVRO-3277
=> AVRO-3277: Test against Ruby 3.1

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm
- https://issues.apache.org/jira/browse/AVRO-3043
=> AVRO-3043: Remove redundant casts

.travis.yml
=> AVRO-3242 Add config for TravisCI on Linux ARM64

lang/rust/src/de.rs
the deserialize_any method is used when using `from_value::<T>`
to deserialize a record which has fields that are not present
in `<T>`
the deserialize_any was missing some matches on certain
Value variants which caused errors like:
Error: DeserializeValue("Unsupported union")
Error: DeserializeValue("incorrect value of type: String")
this patch adds the missing matches and enhances the error
message to help in understanding which type could be missing in
the future
the test case added showcases the problem while validating that
union deserialization is actually working as well
=> AVRO-3232: add matches to deserialize_any union+string/map

lang/rust/Cargo.toml, lang/rust/src/rabin.rs
=> AVRO-3284: Update Rabin fingerprint implementation to digest to 0.10+

lang/rust/src/decode.rs, lang/rust/src/schema.rs, lang/rust/src/schema_compatibility.rs, lang/rust/src/types.rs, lang/rust/src/writer.rs, lang/rust/tests/schema.rs
Do I need to update some documentation ?
=> AVRO-3214 Rust: Support 'doc' attribute for FixedSchema

pom.xml
=> AVRO-3293: Update spotless-maven-plugin to 2.19.1 (latest available)

lang/rust/Cargo.toml, lang/rust/README.md, lang/rust/src/codec.rs
=> AVRO-3303: Rust: Add support for Xz codec

lang/rust/src/schema.rs
- https://issues.apache.org/jira/browse/AVRO-3315
-
=> AVRO-3315: Rust: Add support to back/cycle reference an alias

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3314
- Documentation updated in code
=> AVRO-3314: Updated exception thrown by IConvertable.ToType

lang/c++/impl/avrogencpp.cc, lang/csharp/src/apache/codegen/AvroGen.cs
- https://issues.apache.org/jira/browse/AVRO-3330
=> AVRO-3330: Avrogen returns success if help requested

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3328
=> AVRO-3328 Updated XML documentation for CodeGen Class

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3327
=> AVRO-3327 Implemented pattern matching on Equals check

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3326
=> AVRO-3326 Updated brace location on constructors

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3325
=> AVRO-3325 Removed suppression of CA2225

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3324
=> AVRO-3324 Styling - Added braces for if statements

lang/csharp/src/apache/main/AvroDecimal.cs
- https://issues.apache.org/jira/browse/AVRO-3323
=> AVRO-3323 Updated documentation and removed suppression of CS1591

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
Additionally addressed SA1131 - moved literal value of comparison to the right side.
- https://issues.apache.org/jira/browse/AVRO-3329
=> AVRO-3329 Added omitted braces to CodeGen class

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3333
=> AVRO-3333 Updated to correct spacing styling issues

lang/csharp/src/apache/ipc/Avro.ipc.csproj
- https://issues.apache.org/jira/browse/AVRO-3337
=> AVRO-3337 C#: Bump Log4net to a newer version

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3336
=> AVRO-3336 deprecate namespaceLookup field.

lang/csharp/src/apache/main/File/DataFileReader.cs
- https://issues.apache.org/jira/browse/AVRO-3346
=> AVRO-3346 Update DataFileReader to documentation standards

lang/csharp/src/apache/main/File/Codec.cs
- https://issues.apache.org/jira/browse/AVRO-3343
=> AVRO-3343 Updated Codec to styling standards

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3347
=> AVRO-3347 Update addNamespace to AddNamespace

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3348
=> AVRO-3348 Updated ProcessSchemas to meet styling guidelines

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3349
=> AVRO-3349 Updated ProcessProtocols to meet style guidelines.

lang/csharp/src/apache/main/Avro.main.csproj, lang/csharp/src/apache/test/Avro.test.csproj, lang/csharp/src/apache/test/Schema/AliasTest.cs, lang/csharp/versions.props
- https://issues.apache.org/jira/browse/AVRO-3352
=> AVRO-3352: Only Newtonsoft uses minimum version as of now

lang/rust/src/decimal.rs
Add more docs and simple unit tests
- https://issues.apache.org/jira/browse/AVRO-3331
=> AVRO-3331: Add TryFrom owned Decimal

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3353
=> AVRO-3353 simplified naming in CodeGen

lang/csharp/src/apache/main/CodeGen/CodeGen.cs
- https://issues.apache.org/jira/browse/AVRO-3354
=> AVRO-3354 Simplified if statements

lang/csharp/src/apache/main/File/DataFileReader.cs
- https://issues.apache.org/jira/browse/AVRO-3356
=> AVRO-3356 simplify naming in DataFileReader

lang/csharp/src/apache/main/File/DataFileReader.cs
- https://issues.apache.org/jira/browse/AVRO-3357
=> AVRO-3357 marked properties readonly

lang/csharp/src/apache/main/File/DataFileWriter.cs
- https://issues.apache.org/jira/browse/AVRO-3358
=> AVRO-3358 Updated XML documentation

lang/csharp/src/apache/main/File/Header.cs
- https://issues.apache.org/jira/browse/AVRO-3360
=> AVRO-3360 Updated XML documentation

lang/csharp/src/apache/main/File/Header.cs, lang/csharp/src/apache/main/Generic/GenericEnum.cs
Added some additional formatting around spacing and string concatenation.
- https://issues.apache.org/jira/browse/AVRO-3366
=> AVRO-3366 Updated naming of variables.

lang/csharp/src/apache/main/File/DeflateCodec.cs
- https://issues.apache.org/jira/browse/AVRO-3359
=> AVRO-3359 update formatting of DeflateCodec

lang/csharp/src/apache/main/File/Header.cs, lang/csharp/src/apache/main/File/NullCodec.cs
- https://issues.apache.org/jira/browse/AVRO-3361
=> AVRO-3361 simplify if statement

lang/csharp/src/apache/main/File/Header.cs, lang/csharp/src/apache/main/Generic/GenericEnum.cs
- https://issues.apache.org/jira/browse/AVRO-3367
=> AVRO-3367 Remove unnecessary suppression of CA1307

lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumReader.java, lang/java/avro/src/main/java/org/apache/avro/generic/GenericDatumWriter.java, lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumReader.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectDatumWriter.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectionUtil.java, lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectDatumWithAnonymousEnum.java, lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflectDatumWithAnonymousInstances.java
Only bug fixes and typos in javadoc. No new functionality.
=> AVRO-1851: Better handling for anonymous classes

lang/csharp/src/apache/test/Interop/InteropDataGenerator.cs, lang/csharp/src/apache/test/Interop/InteropDataTests.cs, lang/java/avro/src/main/java/org/apache/avro/util/RandomData.java, lang/java/ipc/src/test/java/org/apache/avro/DataFileInteropTest.java, lang/perl/share/interop-data-generate, lang/perl/xt/interop.t, lang/py/avro/test/gen_interop_data.py, lang/py/avro/test/test_datafile_interop.py, lang/rust/examples/generate_interop_data.rs, lang/rust/examples/test_interop_data.rs
- https://issues.apache.org/jira/browse/AVRO-3407
- No need of new docs
=> AVRO-3407: Test for user metadata in the interop tests

composer.json
- https://issues.apache.org/jira/browse/AVRO-3413
=> AVRO-3413: Add allow-plugins to PHP build

lang/csharp/common.props
=> AVRO-3417: Fix logo.png location and name

build.sh, doc/README.md, doc/package.json
It should be a priority for contributors to build and test the new website locally.  This PR updates the build script and provides some local development instructions.
- https://issues.apache.org/jira/browse/AVRO-2175
=> AVRO-2175: Fix build scripts and instructions

lang/rust/src/schema.rs
Support references to types named after Avro complex types (record, enum
& fixed)
- https://issues.apache.org/jira/browse/AVRO-3370
-
=> AVRO-3370: [Spec] Inconsistent behaviour on types as invalid names.

doc/content/en/docs/next/IDL Language/_index.md
It looks like there were a few changes to the IDL reference since the migration.
I migrated the text changes, and fixed a few links between this document and the spec.
- https://issues.apache.org/jira/browse/AVRO-3420
=> AVRO-3420: Ensure IDL reference is identical

lang/rust/avro/Cargo.toml
- https://issues.apache.org/jira/browse/AVRO-3437
=> AVRO-3437: Rust: Update dependencies

doc/content/en/docs/next/Specification/_index.md
- https://issues.apache.org/jira/browse/AVRO-3370
=> AVRO-3370: Clarify spec with regards to permitted names

pom.xml
- https://issues.apache.org/jira/browse/AVRO-3442
=> AVRO-3442: Add codec build to RAT excludes

lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs
The same style of fixes needed in the encoding, decoding, and schema parsing flows done in #1602 also needed to happen for resolution. I also refactored the code style to fit those other flows and removed unneeded clones where possible. 
- no new functionality
=> AVRO-3461: Resolve flow namespace resolution work

lang/rust/avro/src/schema.rs, lang/rust/avro/tests/schema.rs
- https://issues.apache.org/jira/browse/AVRO-3452
=> AVRO-3452: Implement custom deserialization for Name that employs the special parsing of name and namespace

lang/rust/avro/src/schema.rs
=> [AVRO-3466] Serialize enum and fixed with namespace

doc/content/en/docs/next/IDL Language/_index.md
- https://issues.apache.org/jira/browse/AVRO-3450
=> AVRO-3450: Document editor support for IDL

.github/workflows/test-lang-csharp.yml, lang/csharp/common.props, lang/csharp/versions.props
=> AVRO-3469: Add .NET 7.0 prerelease support

lang/js/package-lock.json, lang/js/package.json
- https://issues.apache.org/jira/browse/AVRO-3489
=> AVRO-3489: [JavaScript] Replace istanbul with nyc for code coverage

lang/rust/avro_derive/src/lib.rs, lang/rust/avro_derive/tests/derive.rs
- https://issues.apache.org/jira/browse/AVRO-3492
=> AVRO-3492: Add logic to derive the aliases for Schema::Enum

.github/workflows/test-lang-rust-ci.yml
- https://issues.apache.org/jira/browse/AVRO-3501
=> AVRO-3501: Rust: Cache ~/.cargo and target folder for faster builds

lang/csharp/src/apache/main/Specific/ObjectCreator.cs
- https://issues.apache.org/jira/browse/AVRO-3498
=> AVRO-3498 Deprecate NameCtorKey

.travis.yml
=> Updated the checksum for PHP composer download

.travis.yml
Read the hash on the fly
- https://issues.apache.org/jira/browse/AVRO-3510
=> AVRO-3510: Do not hardcode the PHP Composer installer Sha384 in TravisCI

lang/rust/avro/examples/test_interop_single_object_encoding.rs, lang/rust/avro/src/lib.rs, lang/rust/avro/src/writer.rs
Not sure what happened to the commit on the previous PR
=> [AVRO-3506] followup: Specific rename

lang/rust/avro/src/schema.rs
To prevent regressions in the future
=> AVRO-3130: Rust: Add a unit test demonstrating that the schema could be parsed successfully

lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs, lang/rust/avro/tests/io.rs
Fixes TODOs from https://github.com/flavray/avro-rs/issues/96
=> AVRO-3526: RUST: Improve schema resolution related to byte types

.github/workflows/test-lang-rust-audit.yml
=> AVRO-3530: Rust: Use dependency-review-action for Rust

doc/content/en/docs/next/Specification/_index.md
- https://issues.apache.org/jira/browse/AVRO-3159
=> AVRO-3159: Small clarification

lang/java/ipc-netty/src/test/java/org/apache/avro/ipc/netty/TestNettyTransceiverWhenFailsToConnect.java
My PR addresses the following [Avro AVRO-3537](https://issues.apache.org/jira/browse/AVRO/AVRO-3537) issues.
It modify only a unit test on netty.
=> AVRO-3537: fix netty unit test

lang/py/tox.ini
=> AVRO-3525: whitelist_externals is now deprecated

lang/rust/avro/Cargo.toml, lang/rust/avro_derive/Cargo.toml, lang/rust/avro_test_helper/Cargo.toml
=> AVRO-3552: Rust: sort the contents in Cargo.toml files with cargo-tomlfmt

doc/config.toml, doc/content/en/blog/news/avro-joins-apache.md, doc/content/en/blog/releases/_index.md, doc/content/en/blog/releases/avro-joins-apache.md, doc/content/en/docs/next/Getting started (Java)/_index.md, doc/content/en/project/License/_index.md, doc/content/en/project/Privacy policy/_index.md, doc/content/en/project/Security/_index.md, doc/content/en/project/Thanks/_index.md, doc/layouts/partials/footer.html
Some text fixes for the website before the first release
=> AVRO-3545: Some text fixes on website

doc/layouts/partials/favicons.html
Adds the favicons to the website
=> AVRO-3546: Add favicons to the website

build.sh, doc/content/en/docs/++version++/api-c++.md, doc/content/en/docs/++version++/api-c.md, doc/content/en/docs/++version++/api-csharp.md, doc/content/en/docs/++version++/api-java.md
- [C] My PR does not need testing for this extremely good reason: Manual testing with the website build
=> AVRO-3556: Use absolute links for api documentation

doc/content/en/blog/news/new-committer-zoltan-csizmadia.md
https://lists.apache.org/thread/0c4s279gyxcl8lxg69q33grznn8kksjd
=> Add a blog entry for Zoltan Csizmadia as a new committer

lang/rust/avro/src/encode.rs
=> AVRO-3585: Add support for encoding Value::String as Schema::Uuid

.github/workflows/test-lang-java.yml, lang/java/pom.xml, lang/java/trevni/core/src/main/java/org/apache/trevni/InputBuffer.java, pom.xml
I also needed to update some plugins and as a side effect one class. Please look at the JIRA AVRO-3586 for the motivation.
R: @RyanSkraba 
CC: @martin-g
=> AVRO-3586: Pin output timestamp to make the Java build reproducible

.github/dependabot.yml, .github/workflows/codeql-csharp-analysis.yml, .github/workflows/codeql-java-analysis.yml, .github/workflows/codeql-js-analysis.yml, .github/workflows/codeql-py-analysis.yml, .github/workflows/java-publish-snapshot.yml, .github/workflows/labeler.yml, .github/workflows/rat.yml, .github/workflows/spotless.yml, .github/workflows/test-lang-c++.yml, .github/workflows/test-lang-c.yml, .github/workflows/test-lang-csharp.yml, .github/workflows/test-lang-java.yml, .github/workflows/test-lang-js.yml, .github/workflows/test-lang-perl.yml, .github/workflows/test-lang-php.yml, .github/workflows/test-lang-py.yml, .github/workflows/test-lang-ruby.yml, .github/workflows/test-lang-rust-audit.yml, .github/workflows/test-lang-rust-ci.yml, .github/workflows/test-lang-rust-clippy.yml
=> AVRO-3589: Update github actions versions

doc/content/en/project/Credits/_index.md
=> Add myself to the list of committers

doc/content/en/blog/releases/avro-1.11.1-released.md
=> AVRO-3595: [Website] Add release notes for 1.11.1

doc/config.toml
=> AVRO-3598: Disable offline search on the site

lang/rust/avro/src/decode.rs, lang/rust/avro/src/schema.rs, lang/rust/avro/src/schema_compatibility.rs, lang/rust/avro/src/types.rs, lang/rust/avro/src/writer.rs, lang/rust/avro/tests/schema.rs, lang/rust/avro_derive/src/lib.rs
=> AVRO-3609: [Rust] Add support for custom attributes

lang/csharp/src/apache/main/Generic/GenericWriter.cs, lang/csharp/src/apache/main/Generic/PreresolvingDatumWriter.cs, lang/csharp/src/apache/main/IO/Encoder.cs, lang/csharp/src/apache/main/IO/JsonDecoder.cs, lang/csharp/src/apache/main/IO/JsonEncoder.cs, lang/csharp/src/apache/main/IO/Parsing/JsonGrammarGenerator.cs, lang/csharp/src/apache/main/IO/Parsing/Parser.cs, lang/csharp/src/apache/main/IO/Parsing/SkipParser.cs, lang/csharp/src/apache/main/IO/Parsing/Symbol.cs, lang/csharp/src/apache/main/IO/Parsing/ValidatingGrammarGenerator.cs, lang/csharp/src/apache/main/IO/ParsingDecoder.cs, lang/csharp/src/apache/main/IO/ParsingEncoder.cs, lang/csharp/src/apache/main/Schema/LogicalSchema.cs, lang/csharp/src/apache/test/IO/JsonCodecTests.cs, lang/csharp/src/apache/test/Schema/SchemaNormalizationTests.cs
Add JSON encoder/decoder for C#.
This PR is a straightforward port of the corresponding classes from Java.  The tests for the JSON encoder/decoder have also been ported from Java to C#.
Also some fixes for logical types have been included.
- https://issues.apache.org/jira/browse/AVRO-3001
- https://issues.apache.org/jira/browse/AVRO-3274
- https://issues.apache.org/jira/browse/AVRO-3568
- https://issues.apache.org/jira/browse/AVRO-3613 …
=> AVRO-3001 AVRO-3274 AVRO-3568 AVRO-3613: Add JSON encoder/decoder for C#

lang/rust/Cargo.lock, lang/rust/avro/Cargo.toml, lang/rust/avro/src/schema.rs
=> AVRO-3625: [Rust] UnionSchema is nullable if any of its variants is Null

lang/rust/avro/src/de.rs
Allow to deserialize enum with unit type, e.g.,
```
enum MyEnum {
Variant(()),
}
```
- new unit test that deserialize an enum with unit type
=> AVRO-3645: [RUST] Fix deserialization of enum with unit type

doc/content/en/blog/news/new-pmc-martin-grigorov.md
Update the news section of the blog to invite Martin G
This change is a trivial website change without any test coverage.
- If yes, how is the feature documented? no
=> Update blog to invite Martin Grigorov

doc/content/en/docs/++version++/Specification/_index.md
I was reading through the specification docs for `logicalType` and found minor inconsistencies.
While editing the README on Github, I saw some weird JSON rendering in Markdown, so I tried fixing that too.
This is how it looked.
vs.
now,
Hope this helps.
- If yes, how is the feature documented? Not applicable
=> Improve formatting of Avro types and JSON code

lang/csharp/src/apache/test/Generic/GenericRecordTests.cs, lang/csharp/src/apache/test/Schema/SchemaTests.cs
* This PR is a part of [AVRO-3532](https://issues.apache.org/jira/browse/AVRO-3532) about naming rules for CSharp. It adds 2 unit test that proves the avro current version in csharp accepts more field names that describe in [documentation](https://avro.apache.org/docs/1.11.1/specification/#names).
The aims of the [JIRA](https://issues.apache.org/jira/browse/AVRO-3532) is to update naming rule in documentation and adapt it to C# & Java implementation and update code for other languages (PRs for C & rust already exists).
This change added tests (GenericRecordTests.cs -> TestFieldNames & SchemaTests.cs -> TestRecordFieldNames) and can be verified by running it 
=> AVRO-3532: Test field names in C#

lang/rust/avro_derive/src/lib.rs
This makes it easier to read and reason about the code No functional changes!
* Minor non-functional changes
* This change is a trivial rework / code cleanup without any test coverage.
=> Use fully qualified names for darling::FromAttributes and syn::Error

lang/py/MANIFEST.in, pom.xml
* This pull request adds a py.typed marker file so the package will advertise itself as supporting type checking according to PEP561.
This change is already covered by existing tests. There is no new functionality.
I manually verified that `./build.sh dist` creates an sdist that contains the new `py.typed` file.
=> AVRO-3669: [python] Add py.typed marker file (PEP561 compliance)

lang/js/README.md, lang/py/avro/compatibility.py
This pull request updates the JS-Lang Readme to add guidance on the usage of recursive schemata in JS, which is currently not sufficiently documented. 
=> Add README example for usage of recursive schemata in JS

doc/content/en/docs/++version++/Getting started (Python)/_index.md
Simple fix to "Getting Started (Python)" documentation, which was using *print* without parentheses in snippets.
=> docs: use python 3 print syntax

lang/java/avro/src/main/java/org/apache/avro/util/RandomData.java
* [AVRO-3611](https://issues.apache.org/jira/browse/AVRO-3611) about record generator in Java and LogicalType. Some logical type should constrain value generation to keep it valid.
This change is already covered by existing tests, as it is used by unit test to generates record to test.
=> AVRO-3611: fix generator

lang/java/pom.xml, pom.xml
I forgot to move this to the Java scope while merging #2046
=> AVRO-3700: Move CycloneDX configuration to Java specific project

lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj, lang/java/compiler/src/test/idl/work space/level1.avdl, lang/java/compiler/src/test/idl/work space/level2.avdl, lang/java/compiler/src/test/idl/work space/root.avdl, lang/java/compiler/src/test/idl/work space/root.avpr, lang/java/compiler/src/test/java/org/apache/avro/compiler/idl/TestIdl.java
[AVRO-3706](https://issues.apache.org/jira/browse/AVRO-3706) : Make IDL accept space in folder name.
This change added unit tests on compiler module and can be verified by running it.
- Does this pull request introduce a new feature?  no
=> AVRO-3706: accept space in folder name

lang/rust/avro/src/de.rs
These improvements were identified while working on AVRO-3646 but they are not related to the changes related to this ticket.
This commit was part of https://github.com/apache/avro/pull/1921
Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
Adds small improvements to the JSON deserialization logic and improves the error messages.
Old and new tests should pass.
=> AVRO-3646: [Rust] Add missing pattern match branches

doc/content/en/docs/++version++/IDL Language/_index.md
=> AVRO-3711: [Docs] Add uuid logical type to IDL

.github/workflows/test-lang-java.yml, pom.xml
The build never passes anymore in Github.
https://issues.apache.org/jira/browse/AVRO-3715
=> [AVRO-3715]: Make build work again

lang/c++/api/buffer/Buffer.hh
This pull request fixes a compiler warning caused by assigning an unsigned `size_type` result from `pimpl_->wroteTo` to a signed `int`. This also fixes a CAT I finding in projects using Fortify to scan code that includes this header.
=> [C++] Fix compiler warning

lang/py/avro/io.py, lang/py/avro/test/test_compatibility.py, lang/py/avro/test/test_datafile_interop.py, lang/py/avro/test/test_io.py, lang/py/avro/test/test_schema.py, lang/py/avro/tether/tether_task.py
Fix python formatting problems.
=> AVRO-3715 Make the build work again.

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java, lang/java/avro/src/main/java/org/apache/avro/util/springframework/Assert.java, lang/java/avro/src/main/java/org/apache/avro/util/springframework/ConcurrentReferenceHashMap.java, lang/java/avro/src/main/java/org/apache/avro/util/springframework/ObjectUtils.java, lang/java/avro/src/test/java/org/apache/avro/util/springframework/ComparableComparator.java, lang/java/avro/src/test/java/org/apache/avro/util/springframework/NullSafeComparator.java, lang/java/avro/src/test/java/org/apache/avro/util/springframework/StopWatch.java, lang/java/avro/src/test/java/org/apache/avro/util/springframework/TestConcurrentReferenceHashMap.java
*Fix synchronization regression*
https://issues.apache.org/jira/browse/AVRO-3713
All tests pass.
I'm in doubt about dropping the "weak keys".
=> AVRO-3713: [Java] Fix Map synchronization regression

lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
implementation of a test case for appending into an existing file with outputstream.
=> AVRO-3684: [Java] testAppendStream test

lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
Caused by flaky Github Actions and me not paying enough attention this slipped through.
=> AVRO-3690: [Java] Fix testMultipleFieldAliases test

lang/java/avro/src/main/java/org/apache/avro/JsonProperties.java, lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java, lang/java/avro/src/main/java/org/apache/avro/reflect/ReflectData.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/schema/Schemas.java, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java
[AVRO-3721](https://issues.apache.org/jira/browse/AVRO-3721) : Improve performance usage of JsonProperties by adding simple function that allow to avoid usage of "JsonProperties.getObjectProps()" (that make a copy of Map)
existing unit test and an added unit test on a method.
=> AVRO-3721: add method to JsonProperties

lang/rust/avro/src/reader.rs, lang/rust/avro/src/schema.rs
=> AVRO-3725: fix documentation of functions and variables

lang/csharp/src/apache/main/Specific/SpecificDatumWriter.cs, lang/csharp/src/apache/test/IO/JsonCodecTests.cs
https://issues.apache.org/jira/browse/AVRO-3724
Fix C# JsonEncoder for nested array of records.
The SpecificDatumWriter is missing a call to `encoder.StartItem()`.  The GenericDatumWriter has this call.
Added test with nested array of records that fails without the fix and passes with the fix.
N/A
=> AVRO-3724 Fix C# JsonEncoder for nested array of records

lang/rust/avro/src/schema.rs
AVRO-3735
Add the code snippets from the JIRA issue as a test case
Run the tests. All should pass!
=> AVRO-3735: Add a unit test for parsing enum with enclosing namespace

BUILD.md
The requirement version of Rust is not noted in `BUILD.md`.
It's better to note like other languages to make it clear for developers.
According to the `rust-version` in `Cargo.toml`, it's `1.60.0` for now.
no
=> AVRO-3741: [doc] Add note about the version requirement of Rust in BUILD.md.

lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs
Associated issue: https://issues.apache.org/jira/browse/AVRO-3767
=> Avro-3767 [Rust] fix complex Ref resolving in Union

lang/csharp/src/apache/main/CodeGen/CodeGen.cs, lang/csharp/src/apache/test/CodGen/CodeGenTest.cs
This PR adds the ability to write types directly back to the user, instead of forcing writing to disk. This is critical for use in scenarios where the code generation is done in a CI job, where disk permissions might not be flexible.
This change can be verified as follows:
- Manually verified the change by building and using the new methods locally in C# Source Generators (see https://github.com/alexrosenfeld10/avro-sourcegen-csharp/pull/4)
Note - I did not add unit tests for this change nor refactor any code style, as it is a very congruent method to other methods in the `CodeGen` class. It may make sense to refactor the class to be a bit DRY-er, and at that point, add tests. If that should happen, it should happen in a separate PR.
- …
=> AVRO-3756: [csharp] Add a method to return types instead of writing them to disk

lang/java/avro/src/test/java/org/apache/avro/TestSchema.java
* Fix tests that use JUnit 4 syntax for expected exception.
- Does this pull request introduce a new feature?  no
=> AVRO-2560: Convert tests to JUnit 5

lang/py/avro/schema.py, lang/py/avro/test/test_io.py
Fix validation of nullable UUID fields, fixing AVRO-3761. This was previously broken due to the UUID validator not being resilient to being passed any kind of object.
I've added test cases to the existing matrix. The UUID case with `None` fails without applying the fix.
=> AVRO-3761: [python] Fix broken validation of nullable UUID field

lang/rust/avro/src/decimal.rs
Adds From<Decimal> impl for BigInt
=> AVRO-3784 [Rust] Add underlying bigint extraction from decimal

lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs, lang/rust/avro/tests/schema.rs
AVRO-3785
* Fix the resolving of union schemata with inherited namespace
* A new IT test has been added (from the JIRA issue)
=> AVRO-3785: [Rust] Make use of the enclosing namespace when resolving union schemata

lang/java/avro/src/main/java/org/apache/avro/generic/GenericData.java, lang/java/avro/src/test/java/org/apache/avro/generic/TestGenericData.java
Fix map comparison in GenericData (AVRO-3789).
See the new tests. These all failed before I changed the implementation.
n/a
=> AVRO-3789: [java] fix map comparison in GenericData

lang/py/avro/datafile.py, lang/py/avro/io.py, lang/py/avro/ipc.py, lang/py/avro/schema.py, lang/py/avro/test/test_protocol.py, lang/py/avro/test/test_schema.py, lang/py/avro/test/test_tether_task.py, lang/py/avro/test/test_tether_task_runner.py, lang/py/avro/tether/__init__.py, lang/py/avro/tether/tether_task.py, lang/py/avro/tether/tether_task_runner.py, lang/py/avro/utils.py, lang/py/pyproject.toml, lang/py/setup.cfg, lang/py/setup.py, lang/py/tox.ini
This is a cleanup change to remove unused imports and variable assignments.
No features or need for additional documentation.
=> AVRO-3807 Cleanup Unused Imports and Variable Assignments

lang/py/build.sh
This PR fixes a bug in the Python doc build.
This change does not affect any of the implementation runtimes. It just affects build.
=> AVRO-312: Fix Bug in Py Doc Build

lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/test/java/org/apache/avro/TestUnionError.java
[AVRO-2764](https://issues.apache.org/jira/browse/AVRO-2764) show the lack of information for AvroTypeException when it concerns union type.
`org.apache.avro.AvroTypeException: Found TUPLE_1, expecting union`
The idea is to change Schema.getName() method for union type, to include inner union name.
New unit test  TestUnionError
=> AVRO-2764: [Java] explain union for clearer error message.

lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/SchemaMojo.java, lang/java/maven-plugin/src/test/avro/extends/Custom.avsc, lang/java/maven-plugin/src/test/java/org/apache/avro/custom/CustomRecordBase.java, lang/java/maven-plugin/src/test/java/org/apache/avro/mojo/TestSchemaMojo.java, lang/java/maven-plugin/src/test/resources/unit/schema/pom-customExtends.xml
[AVRO-2712](https://issues.apache.org/jira/browse/AVRO-2712) : Allow the user to set a custom base class for generated records.
new unit test on maven-plugin module.
- Does this pull request introduce a new feature? (improvement)
- If yes, how is the feature documented? (not documented)
=> AVRO-2712: [Java] maven-plugin allow extends custom class

lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/test/java/org/apache/avro/TestSchema.java, lang/java/compiler/src/main/javacc/org/apache/avro/compiler/idl/idl.jj
[AVRO-3801](https://issues.apache.org/jira/browse/AVRO-3801) : simplify Parse addTypes signature.
Unit test added
=> AVRO-3801: [java] change method signature

lang/java/avro/src/test/java/org/apache/avro/TestDataFileConcat.java, lang/java/avro/src/test/java/org/apache/avro/TestReadingWritingDataInEvolvedSchemas.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityFixedSizeMismatch.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityMissingEnumSymbols.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityMissingUnionBranch.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityNameMismatch.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityReaderFieldMissingDefaultValue.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityTypeMismatch.java, lang/java/avro/src/test/java/org/apache/avro/file/TestAllCodecs.java, lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java, lang/java/avro/src/test/java/org/apache/avro/io/TestBlockingIO.java, lang/java/avro/src/test/java/org/apache/avro/io/TestBlockingIO2.java, lang/java/avro/src/test/java/org/apache/avro/io/TestResolvingIO.java, lang/java/avro/src/test/java/org/apache/avro/io/TestResolvingIOResolving.java, lang/java/avro/src/test/java/org/apache/avro/io/TestValidatingIO.java, lang/java/avro/src/test/java/org/apache/avro/io/parsing/TestResolvingGrammarGenerator.java, lang/java/avro/src/test/java/org/apache/avro/specific/TestSpecificRecordWithUnion.java, lang/java/tools/src/test/java/org/apache/avro/tool/TestRpcProtocolTool.java, lang/java/trevni/core/src/test/java/org/apache/trevni/TestAllCodecs.java, lang/java/trevni/core/src/test/java/org/apache/trevni/TestColumnFile.java
[AVRO-3829](https://issues.apache.org/jira/browse/AVRO-3829) : Finalise conversion from JUnit4 to JUnit5.
The only tests that stay in JUnit4 are for Mojo as the harness maven plugin still use JUnit4.
Same unit test should be OK
=> AVRO-3829: [Java] Junit5

lang/java/avro/src/main/java/org/apache/avro/util/WeakIdentityHashMap.java, lang/java/avro/src/test/java/org/apache/avro/util/WeakIdentityHashMapTest.java
[AVRO-3751](https://issues.apache.org/jira/browse/AVRO-3751) : use ConcurrentHashMap on WeakIdentityHashMap to be robust in multi-thread env.
new unit test WeakIdentityHashMapTest; that fail sometimes with current main code and never with new code.
- If yes, how is the feature documented? (not)
=> AVRO-3751: weak identity hash map thread safe

lang/java/avro/src/main/java/org/apache/avro/SchemaCompatibility.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibilityTypeMismatch.java
[AVRO-3612](https://issues.apache.org/jira/browse/AVRO-3612) : report location on incompability issue when writer is an union type and not reader.
Current unit test + one specific added unionWriterSimpleReaderIncompatibility
=> AVRO-3612: [Java] explain incompability for union.

lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/test/java/org/apache/avro/TestSchema.java, lang/java/avro/src/test/resources/multipleFile/ApplicationEvent.avsc, lang/java/avro/src/test/resources/multipleFile/DocumentInfo.avsc, lang/java/avro/src/test/resources/multipleFile/MyResponse.avsc, lang/java/avro/src/test/resources/multipleFile/README.md, lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java, lang/java/ipc/src/test/java/org/apache/avro/TestSchema.java, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java, lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/SchemaMojo.java, lang/java/maven-plugin/src/test/avro/multipleSchemas/ApplicationEvent.avsc, lang/java/maven-plugin/src/test/avro/multipleSchemas/DocumentInfo.avsc, lang/java/maven-plugin/src/test/avro/multipleSchemas/MyResponse.avsc, lang/java/maven-plugin/src/test/avro/multipleSchemas/README.md, lang/java/maven-plugin/src/test/resources/unit/schema/pom-multiple-schema.xml
[AVRO-3805](https://issues.apache.org/jira/browse/AVRO-3805) : Schema parser can compile several file at a time, allowing one file to use a type define in another file without worring about order of parsing.
This capabilities is used by maven plugin.
New unit test on schema parser and on maven-plugin.
=> AVRO-3805: Parse multiple schema

.github/workflows/test-lang-java.yml, lang/java/archetypes/avro-service-archetype/src/main/pom/pom.xml, lang/java/pom.xml
=> AVRO-3852: Support Java 21

lang/java/avro/src/main/java/org/apache/avro/Protocol.java, lang/java/avro/src/main/java/org/apache/avro/Schema.java, lang/java/avro/src/test/java/org/apache/avro/TestProtocol.java, lang/java/avro/src/test/java/org/apache/avro/reflect/TestReflect.java
[AVRO-530](https://issues.apache.org/jira/browse/AVRO-530) : Types in protocol can be defined each other
=> AVRO-530: Allow recursive types in protocol

doc/content/en/blog/news/new-committer-christophe-le-saec.md, doc/content/en/blog/news/new-committer-oscar-westra-van-holthe-kind.md, doc/content/en/blog/news/new-pmc-michael-a-smith.md
Welcome new committers and PMC to the community! 
=> [docs] Announce new committers

lang/rust/Cargo.toml, lang/rust/avro/Cargo.toml, lang/rust/avro_derive/Cargo.toml, lang/rust/avro_test_helper/Cargo.toml
AVRO-3875
* Fix the landing pages at crates.io
* The change cannot be easily verified. The only way I know of is to publish a new release and see whether it is correct
=> AVRO-3875: [Rust]: Set "readme" metadata for each package separately

doc/content/en/docs/++version++/Getting started (Java)/_index.md, doc/examples/java-example/pom.xml
Fix the documentation and help newbies.
=> AVRO-3877: [doc] fix wrong configuration for avro-maven-plugin in java example

lang/java/avro/src/main/java/org/apache/avro/io/JsonEncoder.java, lang/java/avro/src/main/java/org/apache/avro/util/internal/JacksonUtils.java, lang/java/avro/src/test/java/org/apache/avro/TestSchemaBuilder.java, lang/java/avro/src/test/java/org/apache/avro/io/TestBinaryDecoder.java, lang/java/avro/src/test/java/org/apache/avro/io/TestJsonDecoder.java, lang/java/avro/src/test/java/org/apache/avro/util/internal/TestJacksonUtils.java
[AVRO-3876](https://issues.apache.org/jira/browse/AVRO-3876): Current JacksonUtils is not symmetric, means that
```java
Object object = JacksonUtils.toObject(node);
JsonNode node1 = JacksonUtils.toJsonNode(object);
Assertions.assertEquals(node, node1);
```
is not true for float with high precision and array of byte.
Precision must also be fixed for Json encoder.
- Test added on JacksonUtils class and on Encoder test.
=> Avro 3876 jackson util

doc/content/en/docs/++version++/Specification/_index.md
Fix miss documentation about [AVRO-3779](https://issues.apache.org/jira/browse/AVRO-3779); it missed that the new feature is available for Rust to
not applicable,, just doc
=> AVRO-3779: add mention for rust

lang/py/build.sh
This pull request fixes `./build.sh clean` for the Python binding to remove the auto-generated documents so that we can run `./build.sh dist` multiple times without the RAT error.
=> AVRO-3879: [Build][Python] Fix `./build.sh clean` to remove the generated Python documents

lang/java/avro/src/main/java/org/apache/avro/io/BinaryDecoder.java
=> AVRO-3887: [Java] Remove redundant casts in BinaryDecoder

lang/rust/avro/src/schema_compatibility.rs
AVRO-3898
* According to the spec (https://avro.apache.org/docs/1.11.1/specification/#schema-resolution) named schemas must check only the unqualified names:
```
both schemas are records with the same (unqualified) name
```
* New unit tests are added
=> AVRO-3898: [Rust] Schema compatibility should not check namespace

lang/rust/avro/src/error.rs, lang/rust/avro/src/schema.rs
For now, our process for logical types is:
1. parse the schema 
2. check whether the schema is supported internally:
- if yes, returun the internal schema (e.g. Decimal)
- if no, return a error(this what [logical_verify_type](https://github.com/apache/avro/blob/f0fd236f27a378a4fbd8b3334d04a41bd32e8169/lang/rust/avro/src/schema.rs#L1285) do) or return the schema directly(this what [try_logical_type](https://github.com/apache/avro/blob/f0fd236f27a378a4fbd8b3334d04a41bd32e8169/lang/rust/avro/src/schema.rs#L1331) do)
Returning a error prevents user to custom the logical type, so this PR:
1. unify the process of all logical type: return the schema directly if the schema isn't supported internally. 
2. Refine the process logical. (Hopefully it looks more clear. I'm glad to revert it if it …
=> AVRO-3896: support to custom more logical type

doc/content/en/docs/++version++/Specification/_index.md, lang/rust/Cargo.lock, lang/rust/avro/Cargo.toml, lang/rust/avro/src/decimal.rs, lang/rust/avro/src/decode.rs, lang/rust/avro/src/encode.rs, lang/rust/avro/src/error.rs, lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs
[AVRO-3779](https://issues.apache.org/jira/browse/AVRO-3779) Add big decimal for rust in branch 1.11 
by unit test
- If yes, how is the feature documented? (docs)
=> AVRO-3779: bigdecimal rust 1 11

doc/config.toml
Instead of directly to the email adres. Within Ponymail people can subscribe to the devlist, and that is what we encougage people to do.
*(or)*
*(or)*
*(example:)*
- Does this …
=> AVRO-3885: Link to Ponymail

lang/rust/Cargo.lock, lang/rust/avro/Cargo.toml, lang/rust/avro_derive/Cargo.toml, lang/rust/avro_test_helper/Cargo.toml, lang/rust/wasm-demo/Cargo.toml
* Update the dependencies. For some reason dependabot does not send PRs for Rust since some time. 
* The build and tests must pass
=> [Rust] Update dependencies

README.md
Add the Apache Avro airplane logo to the REAMD, with attribution.
This change is a visual change only, but please review the new footer.
- If yes, how is the feature documented? (**not applicable** / ~docs~ / ~JavaDocs~ / ~not documented~)
=> AVRO-3908: Add logo to README.md

doc/content/en/docs/++version++/Specification/_index.md
With an example as we have with the other types as well.
Add a small example on the UUID type.
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature? …
=> AVRO-3919: [Spec] Clarify UUID type

doc/content/en/blog/releases/avro-1.11.3-released.md
I noticed that this one is missing, and took the liberty of adding it 👍 
*(or)*
*(or)*
*(example:)*
- If yes, how …
=> AVRO-3923: [Docs] Add 1.11.3 release blog

lang/rust/avro/src/schema.rs
AVRO-3925
Fix decimal schema serialization format in rust.
- If yes, how is the feature documented? not documented
=> AVRO-3925: [Rust] Fix decimal serialization format

lang/java/mapred/src/main/java/org/apache/avro/hadoop/file/HadoopCodecFactory.java
This PR fixes Java doc typo in HadoopCodecFactory.java
=> Fix Java doc typo in HadoopCodecFactory.java

.github/workflows/test-lang-c.yml, lang/c/CMakeLists.txt
AVRO-3932
**@ZLIB_PKG@** can't be replaced as expected since we upgrade cmake from 2.4 to 3.1 in this commit: 664c2fc7fba19709c1f974055f9cf4c8a799e108.
You can find more details here: https://cmake.org/cmake/help/latest/policy/CMP0053.html.
So we should change **@ZLIB_PKG@** to **${ZLIB_PKG}** or add **cmake_policy(SET CMP0053 OLD)**
*(or)*
*(or)*
*(example:)*
- *Extended interop tests to verify consistent valid schema names between …
=> AVRO-3932: [C] fix variable reference in CMakeLists.txt

doc/content/en/docs/++version++/Specification/_index.md
=> AVRO-3918: Add support for UUID encoded as `fixed[16]`

lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs
AVRO-3927
For deserializing list && map with custom attribute, it will ignore the custom attributes. And this case also miss in test. This PR fixes them:
1. fix the deserialized behavior
2. fix the test 
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new …
=> AVRO-3927: [Rust] fix array/map deserilaize with custom attribute

lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm, lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/FieldTest.java, lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/NullSafeAnnotationsFieldsTest.java, lang/java/tools/src/test/compiler/output-string/avro/examples/baseball/Player.java, lang/java/tools/src/test/compiler/output/AddExtraOptionalGettersTest.java, lang/java/tools/src/test/compiler/output/NoSettersTest.java, lang/java/tools/src/test/compiler/output/OptionalGettersAllFieldsTest.java, lang/java/tools/src/test/compiler/output/OptionalGettersNullableFieldsTest.java, lang/java/tools/src/test/compiler/output/Player.java
`org.apache.avro.generic.GenericArray` is not used anywhere in this file
*(or)*
*(or)*
*(example:)*
- If yes, how …
=> remove unnecessary import from generated Java classes

lang/rust/avro/src/de.rs
This pull request allow to decode an avro enumeration from a previously encoded one.
Below, the example case to reproduce it.
```rust
#[derive(PartialEq, Eq, Serialize, Deserialize, Debug)]
pub struct StringEnum {
pub source: String,
}
#[test]
fn avro_xxxx_decode_enum() {
let schema_content = r#"
{
"name": "AccessLog",
"namespace": "com.clevercloud.accesslogs.common.avro",
"fields": [
{
"name": "source",
"type": {
"name": "SourceType",
"items": "string",
"symbols": ["SOZU", "HAPROXY", "HAPROXY_TCP"]
}
}
]
}
"#;
let schema = crate::Schema::parse_str(schema_content).unwrap();
let data = StringEnum { source: "SOZU".to_string() };
// encode into avro
let value = crate::to_value(&data).unwrap();
let mut buf = std::io::Cursor::new(crate::to_avro_datum(&schema, …
```
=> AVRO-3955: [Rust] allow deserializer to decode enum string

doc/content/en/docs/++version++/IDL Language/_index.md
Cherry pick change from afa8ea6dac14e271136bd1d2b2ab17bc28297c67
=> Add local_timestamp_ms logical type to IDL doc

lang/c++/impl/json/JsonIO.cc, lang/c++/impl/json/JsonIO.hh, lang/c++/test/JsonTests.cc
*Fix for handling Unicode values above 0xffff in JSON. Jira issue AVRO-3860*
- *New tests to handle the extended range of Unicode code points*
- Does this pull request introduce a new feature? *no*
=> AVRO-3860: Fix for wrong encoding of Unicode values above 0xffff

lang/rust/avro/src/schema_compatibility.rs
AVRO-3974
* Add support for Schema compatibility for Schema::Ref
* New unit tests are added
=> AVRO-3974: [Rust] Support schema compatibility for Schema::Ref

.asf.yaml
Add `jbonofre` to the Avro collaborator in `.asf.yml`.
This is a infra change, not related to source.
- If yes, how is the feature documented? N/A
=> Add jbonofre as collaborator in .asf.yml

lang/java/avro/src/main/java/org/apache/avro/io/BinaryEncoder.java
=> AVRO-3982: Use String.isEmpty() instead

lang/java/avro/src/main/java/org/apache/avro/file/DataFileWriter.java, lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
=> AVRO-3983: Allow setting a custom encoder in DataFileWriter

doc/examples/example.py
title says it all
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / …
=> update example to python3 print syntax

.github/workflows/avro-compatibility.yml, .github/workflows/ci.yml, .github/workflows/gradle-compatibility.yml, .github/workflows/java-compatibility.yml, .github/workflows/os-compatibility.yml
- Updates workflow files to start fixing builds after integrating software donation of gradle avro plugin
This change is already covered by existing tests, such as:
- Avro Compatibility Tests
- Gradle Compatibility Tests
- Java Compatibility Tests
- OS Compatibility Tests
- CI Build Test
=> AVRO-3731:[gradl- avro-plugin] Integrates software donation of gradle avro plugin

lang/java/pom.xml
Backport. 1.16.1 seem to be revoked:
https://mvnrepository.com/artifact/io.grpc/grpc-core
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature? (yes / …
=> Bump gRPC to 1.16.2

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java, lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java, lang/java/avro/src/test/java/org/apache/avro/TestDataFile.java
1.11 backport
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / …
=> AVRO-4006: Fix block finish while reading data files

lang/java/avro/src/main/java/org/apache/avro/file/DataFileReader.java, lang/java/avro/src/main/java/org/apache/avro/file/SeekableByteArrayInput.java, lang/java/avro/src/test/java/org/apache/avro/file/TestSeekableByteArrayInput.java, lang/java/avro/src/test/java/org/apache/avro/file/TestSeekableInputStream.java
Fix for AVRO-3748: two of the implementations of SeekableInput.skip had a bug. The `skip` method was implemented as `seek` (i.e. using an absolute input position instead of a relative one).
This change adds a test to `TestSeekableByteArrayInput`, and adds a test class `TestSeekableInputStream`.
=> AVRO-3748: [Java] Fix SeekableInput.skip

lang/java/pom.xml, pom.xml
This PR provides several minor updates, good to have for 1.11.x next release.
=> Some minor updates for 1.11.x next release cycle

share/docker/Dockerfile
`build.sh docker` fails while adding the PHP init extra modules with:
```
49.74 /bin/sh: 1: cannot create /etc/php/7.4/cli/conf.d/10-zstd.ini: Directory nonexistent
```
=> Fix PHP modules installation path

share/docker/Dockerfile
Base docker image now 22.04 (`branch-1.11` is using 20.04) which use PHP 8.1 now by default.
=> Update to PHP8, new default version

share/docker/Dockerfile
`./build.sh docker` is failing with:
```
15.65 ERROR:  Error installing bundler:                                                                                                                                                                                                              
15.65   The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
15.65   bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.0.0.
```
=> Define bundler specific version working with default ruby version installed

lang/php/lib/DataFile/AvroDataIOWriter.php, lang/php/lib/Protocol/AvroProtocol.php, lang/php/lib/Protocol/AvroProtocolMessage.php, lang/php/test/DataFileTest.php
This Pull Request solves deprecations that were introduced in PHP 8, that will eventually cause errors in future versions of PHP.
=> AVRO-4013: [php] Fix PHP 8 deprecations

lang/rust/avro/.cargo/config.toml.disabled, lang/rust/avro/tests/test.rs
A couple of files are missing ASF headers, and so rat is complaining.
=> Add missing ASF headers in rust files

lang/c++/build.sh
`parser` doesn't exist in `lang/c++` and so `build.sh dist` fails to copy it.
=> Remove parser copy on c++ build

lang/c++/build.sh
`parser` is not present anymore on the `lang/c++` folder, so the `build.sh dist` fails when it tries to copy.
=> Remove parser copy from c++ parser

lang/c++/test/CodecTests.cc
New unit tests attempting to reproduce the issue AVRO-3675
The change is to add more tests
- Does this pull request introduce a new feature? *no*
=> AVRO-3675: Added more tests for resolving decoder

build.sh, share/docker/Dockerfile
This way we automatically build for x64 and arm based images.
*(or)*
*(or)*
*(example:)*
- If yes, how is the …
=> AVRO-4021: Pass in BUILDPLATFORM explicitly

build.sh
Currently, `BUILDPLATFORM` (used to build Docker image) is "evaluated" based on Docker daemon. We can allow user to "force" the platform (for cross arch Docker image).
=> Allow user to define BUILDPLATFORM to build Docker image

lang/java/idl/src/main/java/org/apache/avro/idl/IdlSchemaFormatter.java, lang/java/idl/src/main/java/org/apache/avro/idl/IdlUtils.java, lang/java/idl/src/test/java/org/apache/avro/idl/IdlUtilsTest.java
Noticed this when building the distributions.
I think it makes sense to move it just into the `idl` namspace.
This package hasn't been released before, so we don't break any existing APIs.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.8.0:jar (module-javadocs) on project avro-idl: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 2
[ERROR] error: No source files for package org.apache.avro.util
[ERROR] 1 error
[ERROR] Command line was: /usr/lib/jvm/java-21-openjdk-arm64/bin/javadoc -J-Duser.language= -J-Duser.country= -Xdoclint:none @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/home/fokko.driesprong/avro/lang/java/idl/target/apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full …
```
=> AVRO-4023: Move `IdlUtils` into `org.apache.avro.idl`

BUILD.md
=> Minor: Fix versions in `BUILD.md`

pom.xml
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.8.0:jar (module-javadocs) on project avro-idl: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 2
[ERROR] error: No source files for package org.apache.avro.util
[ERROR] 1 error
[ERROR] Command line was: /usr/lib/jvm/java-21-openjdk-arm64/bin/javadoc -J-Duser.language= -J-Duser.country= -Xdoclint:none @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/fokko.driesprong/avro/lang/java/idl/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors …
```
=> Minor: Remove `doc` from the path

DIST_README.txt
=> Minor: Add rust to REAMDE

build.sh
=> Minor: Update docs path

lang/c++/build.sh
```
+ ./build.sh dist
-- Version: 10.2.1
-- Build type: Release
Enabled snappy codec
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fokko.driesprong/avro/lang/c++/build
-- Version: 10.2.1
-- Build type: Release
Enabled snappy codec
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fokko.driesprong/avro/lang/c++/build
cp: cannot stat 'api': No such file or directory
```
*(or)*
*(or)*
This change added tests and can be …
=> Minor: Remove `api` directory from cpp dist

build.sh
I noticed this after bumping the version number from `1.12.0-SNAPSHOT` to `1.12.0` that it could not resolve the artifacts.
*(or)*
*(or)*
*(example:)*
- Does this pull request …
=> Minor: Make sure that the artifacts are published

BUILD.md
See:
https://github.com/apache/avro/blob/61f2ecdc2faf7a5df759ace1acd24d5a5bac3739/lang/rust/Cargo.toml#L37
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new …
=> Minor: Update Rust version

lang/rust/avro/README.md, lang/rust/avro/src/lib.rs, lang/rust/avro/src/rabin.rs, lang/rust/avro/src/schema.rs, lang/rust/avro/src/types.rs
fix doc link
Previous links cannot jump to the sections any more.
e.g.,
old: https://avro.apache.org/docs/current/spec.html#single_object_encoding
new: https://avro.apache.org/docs/current/specification/#single-object-encoding
=> [No Jira] [Rust] fix links to spec

.asf.yaml
Looking at
https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#publish
It looks like it is missing
*(or)*
*(or)*
*(example:)*
- Does this pull request …
=> [NO-JIRA] Add publish section

.github/workflows/deploy-docs.yml
... and copy over only the newly generated .html files
Also create a simple .asf.yaml file with `publish`
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new …
=> [NO-JIRA][Website] Wipe out the old contents of asf-site branch

doc/content/en/project/Contributors onboarding guide/_index.md
Tested locally using `hugo serve`
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not …
=> [NO-JIRA] Add alias for contributions page

.github/workflows/deploy-docs.yml
=> AVRO-4041: [website] Checkout the old docs from subversion

lang/java/perf/pom.xml
* Make it easier to launch the Avro Perf tests
=> AVRO-4047: Build perf tests into Uber JAR

lang/java/avro/src/test/java/org/apache/avro/TestCompare.java, lang/java/ipc/src/test/java/org/apache/avro/TestCompare.java
* This pull request improves quality of live by moving relevant unit tests into correct package, fixing AVRO-4064.
=> AVRO-4064: Move relavent unit tests from ipc package to avro package

README.md
=> punctuation correction

lang/c++/impl/Compiler.cc
AVRO-4083
This pull request remove compilation warnings, related to AVRO-4083.
This change is a trivial rework / code cleanup already covered by existing tests.
=> [AVRO-4083][C++] Remove unused variable

lang/c++/test/CommonsSchemasTests.cc
AVRO-4084
This pull request fixes windows compilation test error on `std::filesystem::path` fixing AVRO-4084.
This change is already covered by existing test `\lang\c++\test\CommonsSchemasTests.cc`.
=> [AVRO-4084][C++] Fix bad filesystem::path conversion type on windows

lang/py/setup.cfg, lang/py/tox.ini
Python 3.7 has been EOL since June 2023: https://devguide.python.org/versions/
It now also breaks the CI because third-party packages dropped 3.7.
*(or)*
*(or)*
*(example:)*
- …
=> AVRO-4104: Drop support for Python 3.7

lang/ruby/lib/avro/schema_validator.rb
This pull request improves the `validate_simple` method performance. fixing [AVRO-4114](https://issues.apache.org/jira/browse/AVRO-4114)
Ruby raise/rescue is slow. the method code is rewritten without raise/rescue
Example performance benchmark
`Benchmark.measure { 50000.times{ errors=[];begin;raise "aa" ; rescue ;errors<< "error"; end }}` => 2 seconds
`Benchmark.measure { 50000.times{ errors=[];begin; errors<< "error"; end }}` => 0.003 seconds
600x times faster
The `validate_simple` method is in use for validation, and, more importantly, it is called in a loop multiple times for union type encoding. That makes the changes really important for performance
This change is a trivial rework. The code is covered with existing tests.
- Does this pull request introduce a new feature? ( no )
- If …
=> AVRO-4114: [Ruby] Improve validate_simple method performance

share/docker/Dockerfile
Follow up to https://github.com/apache/avro/pull/3057 to fix the docker build for making releases [as requested here](https://github.com/apache/avro/pull/3057#issuecomment-2642788366). 
I saw the comment about `composer.lock`. This is PHP's way to pin dependencies, and this is done in the individual projects that pull in the dependencies, so I've left this unchanged. 
I'm not super-familiar with this project's build system, but I replicated with `./build.sh docker-test` and fixed that command locally. If there's any other tests you'd like me to run, let me know.
- ~If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)~
=> AVRO-2843: [PHP] Add ext-curl to PHP setup in Dockerfile

lang/php/lib/Datum/AvroIODatumWriter.php
This pull request improves write performance, by avoiding re-validating data that has already been validated, fixing AVRO-4040.
=> AVRO-4090: [php] Avoid repeating data validation

doc/content/en/docs/++version++/Editor Support/_index.md
Fix for pressing "merge" too soon on PR #3366.
=> AVRO-3951: Document IDE support (2)

.github/workflows/test-docker.yml, lang/py/avro/io.py
And also run the Docker tests on pull-requests
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? …
=> Fix mypy test

lang/java/tools/pom.xml, share/docker/Dockerfile
AVRO-4154: Fix python tests running in Docker
Some dependencies use multi-release jars. This change ensures they are
included fully, by making the tools jar also a multi-release jar.
If the change is good, the docker pipeline will succeed.
=> AVRO-4154: Make tools jar multi-release

doc/content/en/project/Security/_index.md
Describe when using Avro is secure. This is necessary documentation, given the world-wide shift to extend product liability to "digital elements" (this includes software). Users of the Avro library will want to know how using Avro affects the security of their product.
See AVRO-4145.
This change only adds documentation. No code has been changed.
=> AVRO-4145: Add Avro security model

lang/c++/CMakeLists.txt
Fixes the install locations for the C++ build in the following situations:
1. The Windows DLL will now be installed to the bin directory, which is expected for projects built by CMake.
2. The standard CMake variables are now used for the install locations, which both makes it configurable and respects system-specific locations, such as some Linux distros using lib64.
Does not introduce a new feature.
=> AVRO-4167: [C++] Fix install locations

lang/c++/CMakeLists.txt
This fixes the install locations under Unix (in particular: Debian Multiarch) by using CMake's [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module.
- If yes, how is the feature documented? **not applicable**
=> AVRO-4179: [C++] Use GNUInstallDirs to install to the correct folders
